<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Argon" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Argon&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Argon&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Argon&quot; Atom feed" href="/index.php?title=Argon&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Argon","wgTitle":"Argon","wgCurRevisionId":14346,"wgRevisionId":0,"wgArticleId":9,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Argon","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Argon skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Argon"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Argon" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Argon" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Argon" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=14337" title="Argon">prev</a>)</span><input type="radio" value="14346" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14346" checked="checked" name="diff" id="mw-diff-14346" /> <a href="/index.php?title=Argon&amp;oldid=14346" title="Argon" class="mw-changeslist-date">05:12, 19 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">Talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,828 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,828 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Ships" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=14337&amp;undo=14346" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=14337" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=14337&amp;oldid=14335" title="Argon">prev</a>)</span><input type="radio" value="14337" checked="checked" name="oldid" id="mw-oldid-14337" /><input type="radio" value="14337" name="diff" id="mw-diff-14337" /> <a href="/index.php?title=Argon&amp;oldid=14337" title="Argon" class="mw-changeslist-date">11:38, 17 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">Talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,801 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,801 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=14335&amp;undo=14337" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=14335" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=14335&amp;oldid=13815" title="Argon">prev</a>)</span><input type="radio" value="14335" name="oldid" id="mw-oldid-14335" /><input type="radio" value="14335" name="diff" id="mw-diff-14335" /> <a href="/index.php?title=Argon&amp;oldid=14335" title="Argon" class="mw-changeslist-date">11:36, 17 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">Talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,771 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,771 bytes after change">(+604)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=13815&amp;undo=14335" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=13815" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=13815&amp;oldid=13615" title="Argon">prev</a>)</span><input type="radio" value="13815" name="oldid" id="mw-oldid-13815" /><input type="radio" value="13815" name="diff" id="mw-diff-13815" /> <a href="/index.php?title=Argon&amp;oldid=13815" title="Argon" class="mw-changeslist-date">18:19, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,167 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,167 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=13615&amp;undo=13815" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=13615" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=13615&amp;oldid=11278" title="Argon">prev</a>)</span><input type="radio" value="13615" name="oldid" id="mw-oldid-13615" /><input type="radio" value="13615" name="diff" id="mw-diff-13615" /> <a href="/index.php?title=Argon&amp;oldid=13615" title="Argon" class="mw-changeslist-date">10:19, 23 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,157 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,157 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Adding Argon Navbox (will roll out to other pages later, unless someone beats me to it))</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=11278&amp;undo=13615" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=11278" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=11278&amp;oldid=9513" title="Argon">prev</a>)</span><input type="radio" value="11278" name="oldid" id="mw-oldid-11278" /><input type="radio" value="11278" name="diff" id="mw-diff-11278" /> <a href="/index.php?title=Argon&amp;oldid=11278" title="Argon" class="mw-changeslist-date">17:05, 10 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,139 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,139 bytes after change">(+625)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Ships" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=9513&amp;undo=11278" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=9513" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=9513&amp;oldid=8706" title="Argon">prev</a>)</span><input type="radio" value="9513" name="oldid" id="mw-oldid-9513" /><input type="radio" value="9513" name="diff" id="mw-diff-9513" /> <a href="/index.php?title=Argon&amp;oldid=9513" title="Argon" class="mw-changeslist-date">13:33, 25 July 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,514 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,514 bytes after change">(-132)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#List_of_Stations" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">List of Stations: </span> removed dead links, doesn&#039;t look like anyone&#039;s interested in making em.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=8706&amp;undo=9513" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=8706" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=8706&amp;oldid=8435" title="Argon">prev</a>)</span><input type="radio" value="8706" name="oldid" id="mw-oldid-8706" /><input type="radio" value="8706" name="diff" id="mw-diff-8706" /> <a href="/index.php?title=Argon&amp;oldid=8706" title="Argon" class="mw-changeslist-date">17:02, 22 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,646 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,646 bytes after change">(-127)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Ships" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> WHOOT it works. deleted unimplemented links. replaced with composite page inclusion. neat!</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=8435&amp;undo=8706" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=8435" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=8435&amp;oldid=8314" title="Argon">prev</a>)</span><input type="radio" value="8435" name="oldid" id="mw-oldid-8435" /><input type="radio" value="8435" name="diff" id="mw-diff-8435" /> <a href="/index.php?title=Argon&amp;oldid=8435" title="Argon" class="mw-changeslist-date">20:17, 4 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Therefromhere&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Therefromhere (page does not exist)">Therefromhere</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Therefromhere&amp;action=edit&amp;redlink=1" class="new" title="User talk:Therefromhere (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Therefromhere" title="Special:Contributions/Therefromhere">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,773 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="6,773 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Fixed link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=8314&amp;undo=8435" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=8314" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=8314&amp;oldid=6447" title="Argon">prev</a>)</span><input type="radio" value="8314" name="oldid" id="mw-oldid-8314" /><input type="radio" value="8314" name="diff" id="mw-diff-8314" /> <a href="/index.php?title=Argon&amp;oldid=8314" title="Argon" class="mw-changeslist-date">18:53, 16 January 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/108.35.157.210" title="Special:Contributions/108.35.157.210" class="mw-userlink">108.35.157.210</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:108.35.157.210&amp;action=edit&amp;redlink=1" class="new" title="User talk:108.35.157.210 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,773 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,773 bytes after change">(+20)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Core_Worlds" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Core Worlds</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=6447&amp;undo=8314" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=6447" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=6447&amp;oldid=5871" title="Argon">prev</a>)</span><input type="radio" value="6447" name="oldid" id="mw-oldid-6447" /><input type="radio" value="6447" name="diff" id="mw-diff-6447" /> <a href="/index.php?title=Argon&amp;oldid=6447" title="Argon" class="mw-changeslist-date">22:35, 26 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/41.132.51.82" title="Special:Contributions/41.132.51.82" class="mw-userlink">41.132.51.82</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:41.132.51.82&amp;action=edit&amp;redlink=1" class="new" title="User talk:41.132.51.82 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,753 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="6,753 bytes after change">(-514)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Ships" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=5871&amp;undo=6447" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=5871" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=5871&amp;oldid=5646" title="Argon">prev</a>)</span><input type="radio" value="5871" name="oldid" id="mw-oldid-5871" /><input type="radio" value="5871" name="diff" id="mw-diff-5871" /> <a href="/index.php?title=Argon&amp;oldid=5871" title="Argon" class="mw-changeslist-date">08:05, 29 March 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/99.40.57.188" title="Special:Contributions/99.40.57.188" class="mw-userlink">99.40.57.188</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:99.40.57.188&amp;action=edit&amp;redlink=1" class="new" title="User talk:99.40.57.188 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,267 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,267 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Shipyards" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Shipyards</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=5646&amp;undo=5871" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=5646" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=5646&amp;oldid=5464" title="Argon">prev</a>)</span><input type="radio" value="5646" name="oldid" id="mw-oldid-5646" /><input type="radio" value="5646" name="diff" id="mw-diff-5646" /> <a href="/index.php?title=Argon&amp;oldid=5646" title="Argon" class="mw-changeslist-date">15:33, 7 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,267 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,267 bytes after change">(+106)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Shipyards" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Shipyards: </span> link to argon federal shipyard</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=5464&amp;undo=5646" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=5464" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=5464&amp;oldid=2691" title="Argon">prev</a>)</span><input type="radio" value="5464" name="oldid" id="mw-oldid-5464" /><input type="radio" value="5464" name="diff" id="mw-diff-5464" /> <a href="/index.php?title=Argon&amp;oldid=5464" title="Argon" class="mw-changeslist-date">06:46, 16 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,161 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,161 bytes after change">(+68)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=2691&amp;undo=5464" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=2691" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=2691&amp;oldid=1470" title="Argon">prev</a>)</span><input type="radio" value="2691" name="oldid" id="mw-oldid-2691" /><input type="radio" value="2691" name="diff" id="mw-diff-2691" /> <a href="/index.php?title=Argon&amp;oldid=2691" title="Argon" class="mw-changeslist-date">14:02, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,093 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,093 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Territories" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Territories: </span> formatted core-borderworlds</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=1470&amp;undo=2691" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=1470" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=1470&amp;oldid=1327" title="Argon">prev</a>)</span><input type="radio" value="1470" name="oldid" id="mw-oldid-1470" /><input type="radio" value="1470" name="diff" id="mw-diff-1470" /> <a href="/index.php?title=Argon&amp;oldid=1470" title="Argon" class="mw-changeslist-date">14:10, 24 September 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,050 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,050 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=1327&amp;undo=1470" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=1327" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=1327&amp;oldid=1100" title="Argon">prev</a>)</span><input type="radio" value="1327" name="oldid" id="mw-oldid-1327" /><input type="radio" value="1327" name="diff" id="mw-diff-1327" /> <a href="/index.php?title=Argon&amp;oldid=1327" title="Argon" class="mw-changeslist-date">14:51, 22 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,033 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,033 bytes after change">(+184)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Stations" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> shipyards</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=1100&amp;undo=1327" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=1100" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=1100&amp;oldid=1097" title="Argon">prev</a>)</span><input type="radio" value="1100" name="oldid" id="mw-oldid-1100" /><input type="radio" value="1100" name="diff" id="mw-diff-1100" /> <a href="/index.php?title=Argon&amp;oldid=1100" title="Argon" class="mw-changeslist-date">16:03, 20 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,849 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,849 bytes after change">(+2,834)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Reverted edits by <a href="/index.php/Special:Contributions/95.79.91.90" title="Special:Contributions/95.79.91.90">95.79.91.90</a> (<a href="/index.php?title=User_talk:95.79.91.90&amp;action=edit&amp;redlink=1" class="new" title="User talk:95.79.91.90 (page does not exist)">talk</a>) to last revision by <a href="/index.php/User:Madned" title="User:Madned">Madned</a>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=1097&amp;undo=1100" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=1097" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=1097&amp;oldid=930" title="Argon">prev</a>)</span><input type="radio" value="1097" name="oldid" id="mw-oldid-1097" /><input type="radio" value="1097" name="diff" id="mw-diff-1097" /> <a href="/index.php?title=Argon&amp;oldid=1097" title="Argon" class="mw-changeslist-date">20:34, 17 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/95.79.91.90" title="Special:Contributions/95.79.91.90" class="mw-userlink">95.79.91.90</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:95.79.91.90&amp;action=edit&amp;redlink=1" class="new" title="User talk:95.79.91.90 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,015 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="4,015 bytes after change">(-2,834)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(WPvu65 hi all ?heey ? http://avtozastivxux.sweb.cz)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=930&amp;undo=1097" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=930" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=930&amp;oldid=929" title="Argon">prev</a>)</span><input type="radio" value="930" name="oldid" id="mw-oldid-930" /><input type="radio" value="930" name="diff" id="mw-diff-930" /> <a href="/index.php?title=Argon&amp;oldid=930" title="Argon" class="mw-changeslist-date">16:53, 1 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,849 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,849 bytes after change">(+1,229)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#Science_and_Technology" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">Science and Technology: </span> ship pedia transcript.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=929&amp;undo=930" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=929" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=929&amp;oldid=637" title="Argon">prev</a>)</span><input type="radio" value="929" name="oldid" id="mw-oldid-929" /><input type="radio" value="929" name="diff" id="mw-diff-929" /> <a href="/index.php?title=Argon&amp;oldid=929" title="Argon" class="mw-changeslist-date">16:42, 1 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,620 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,620 bytes after change">(+937)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Argon#General" title="Argon">→</a>‎<span dir="auto"><span class="autocomment">General: </span> fill from pedia entry description.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=637&amp;undo=929" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=637" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=637&amp;oldid=624" title="Argon">prev</a>)</span><input type="radio" value="637" name="oldid" id="mw-oldid-637" /><input type="radio" value="637" name="diff" id="mw-diff-637" /> <a href="/index.php?title=Argon&amp;oldid=637" title="Argon" class="mw-changeslist-date">18:54, 30 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,683 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,683 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(redid the rank list as a descending numbered list. may make some availability discussions a little easier.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=624&amp;undo=637" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=624" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=624&amp;oldid=503" title="Argon">prev</a>)</span><input type="radio" value="624" name="oldid" id="mw-oldid-624" /><input type="radio" value="624" name="diff" id="mw-diff-624" /> <a href="/index.php?title=Argon&amp;oldid=624" title="Argon" class="mw-changeslist-date">16:39, 29 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,687 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,687 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fix rank list bullet)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=503&amp;undo=624" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=503" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=503&amp;oldid=159" title="Argon">prev</a>)</span><input type="radio" value="503" name="oldid" id="mw-oldid-503" /><input type="radio" value="503" name="diff" id="mw-diff-503" /> <a href="/index.php?title=Argon&amp;oldid=503" title="Argon" class="mw-changeslist-date">19:33, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,670 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,670 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(missed government in infobox fixed.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=159&amp;undo=503" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=159" title="Argon">cur</a> | <a href="/index.php?title=Argon&amp;diff=159&amp;oldid=40" title="Argon">prev</a>)</span><input type="radio" value="159" name="oldid" id="mw-oldid-159" /><input type="radio" value="159" name="diff" id="mw-diff-159" /> <a href="/index.php?title=Argon&amp;oldid=159" title="Argon" class="mw-changeslist-date">18:37, 22 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,661 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,661 bytes after change">(+4,613)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(copy with formatting from cache)</span> (<span class="mw-history-undo"><a href="/index.php?title=Argon&amp;action=edit&amp;undoafter=40&amp;undo=159" title="Argon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Argon&amp;diff=14346&amp;oldid=40" title="Argon">cur</a> | prev)</span><input type="radio" value="40" name="oldid" id="mw-oldid-40" /><input type="radio" value="40" name="diff" id="mw-diff-40" /> <a href="/index.php?title=Argon&amp;oldid=40" title="Argon" class="mw-changeslist-date">11:26, 29 April 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(48 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="48 bytes after change">(+48)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &#039;Argon is one of the <a href="/index.php/Races" title="Races">races</a> in the X universe.&#039;)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Argon">http://x3wiki.com/index.php/Argon</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Argon" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Argon" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Argon&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Argon&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Argon&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Argon&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Argon" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Argon" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Argon&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Argon&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.300 secs. --></body></html>