<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Hub Plot Walkthrough" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Hub Plot Walkthrough&quot; Atom feed" href="/index.php?title=Hub_Plot_Walkthrough&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Hub_Plot_Walkthrough","wgTitle":"Hub Plot Walkthrough","wgCurRevisionId":15426,"wgRevisionId":0,"wgArticleId":1430,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Hub_Plot_Walkthrough","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Hub_Plot_Walkthrough skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Hub Plot Walkthrough"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Hub+Plot+Walkthrough" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Hub_Plot_Walkthrough" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Hub_Plot_Walkthrough" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15425" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15426" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="15426" checked="checked" name="diff" id="mw-diff-15426" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15426" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:58, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,762 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,762 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_3" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 3</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15425&amp;undo=15426" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15425" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15425&amp;oldid=15424" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15425" checked="checked" name="oldid" id="mw-oldid-15425" /><input type="radio" value="15425" name="diff" id="mw-diff-15425" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15425" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:57, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,762 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,762 bytes after change">(+113)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Rebuilding_the_Hub_v3.2" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Rebuilding the Hub v3.2</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15424&amp;undo=15425" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15424" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15424&amp;oldid=15423" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15424" name="oldid" id="mw-oldid-15424" /><input type="radio" value="15424" name="diff" id="mw-diff-15424" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15424" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:56, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,649 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,649 bytes after change">(+53)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_3" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 3</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15423&amp;undo=15424" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15423" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15423&amp;oldid=15422" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15423" name="oldid" id="mw-oldid-15423" /><input type="radio" value="15423" name="diff" id="mw-diff-15423" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15423" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:55, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,596 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,596 bytes after change">(+53)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_2" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 2</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15422&amp;undo=15423" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15422" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15422&amp;oldid=15421" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15422" name="oldid" id="mw-oldid-15422" /><input type="radio" value="15422" name="diff" id="mw-diff-15422" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15422" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:55, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,543 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,543 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_1" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 1</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15421&amp;undo=15422" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15421" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15421&amp;oldid=15420" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15421" name="oldid" id="mw-oldid-15421" /><input type="radio" value="15421" name="diff" id="mw-diff-15421" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15421" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:54, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,543 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,543 bytes after change">(+49)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Realignment" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Realignment</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=15420&amp;undo=15421" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=15420" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15420&amp;oldid=9261" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="15420" name="oldid" id="mw-oldid-15420" /><input type="radio" value="15420" name="diff" id="mw-diff-15420" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=15420" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:53, 2 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.176.216.83" title="Special:Contributions/70.176.216.83" class="mw-userlink">70.176.216.83</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.176.216.83&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.176.216.83 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,494 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,494 bytes after change">(+53)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_1" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 1</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9261&amp;undo=15420" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9261" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9261&amp;oldid=9260" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9261" name="oldid" id="mw-oldid-9261" /><input type="radio" value="9261" name="diff" id="mw-diff-9261" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9261" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:46, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,441 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,441 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9260&amp;undo=9261" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9260" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9260&amp;oldid=9259" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9260" name="oldid" id="mw-oldid-9260" /><input type="radio" value="9260" name="diff" id="mw-diff-9260" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9260" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:45, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,445 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,445 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Rebuilding_the_Hub" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Rebuilding the Hub</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9259&amp;undo=9260" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9259" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9259&amp;oldid=9258" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9259" name="oldid" id="mw-oldid-9259" /><input type="radio" value="9259" name="diff" id="mw-diff-9259" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9259" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:43, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,441 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,441 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Rebuilding_the_Hub" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Rebuilding the Hub</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9258&amp;undo=9259" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9258" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9258&amp;oldid=9257" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9258" name="oldid" id="mw-oldid-9258" /><input type="radio" value="9258" name="diff" id="mw-diff-9258" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9258" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:42, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,435 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,435 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Rebuilding_the_Hub" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Rebuilding the Hub</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9257&amp;undo=9258" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9257" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9257&amp;oldid=9256" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9257" name="oldid" id="mw-oldid-9257" /><input type="radio" value="9257" name="diff" id="mw-diff-9257" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9257" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:41, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,430 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,430 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_3" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 3</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9256&amp;undo=9257" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9256" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9256&amp;oldid=9231" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9256" name="oldid" id="mw-oldid-9256" /><input type="radio" value="9256" name="diff" id="mw-diff-9256" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9256" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:40, 22 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.137.201" title="Special:Contributions/87.64.137.201" class="mw-userlink">87.64.137.201</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.137.201&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.137.201 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,431 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,431 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_2" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 2</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9231&amp;undo=9256" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9231" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9231&amp;oldid=9224" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9231" name="oldid" id="mw-oldid-9231" /><input type="radio" value="9231" name="diff" id="mw-diff-9231" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9231" title="Hub Plot Walkthrough" class="mw-changeslist-date">15:04, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/68.80.32.45" title="Special:Contributions/68.80.32.45" class="mw-userlink">68.80.32.45</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:68.80.32.45&amp;action=edit&amp;redlink=1" class="new" title="User talk:68.80.32.45 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,431 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,431 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_3" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 3</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9224&amp;undo=9231" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9224" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9224&amp;oldid=9176" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9224" name="oldid" id="mw-oldid-9224" /><input type="radio" value="9224" name="diff" id="mw-diff-9224" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9224" title="Hub Plot Walkthrough" class="mw-changeslist-date">12:48, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/68.80.32.45" title="Special:Contributions/68.80.32.45" class="mw-userlink">68.80.32.45</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:68.80.32.45&amp;action=edit&amp;redlink=1" class="new" title="User talk:68.80.32.45 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,430 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,430 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_2" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 2</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=9176&amp;undo=9224" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=9176" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=9176&amp;oldid=8731" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="9176" name="oldid" id="mw-oldid-9176" /><input type="radio" value="9176" name="diff" id="mw-diff-9176" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=9176" title="Hub Plot Walkthrough" class="mw-changeslist-date">12:44, 15 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.64.158.75" title="Special:Contributions/87.64.158.75" class="mw-userlink">87.64.158.75</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.64.158.75&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.64.158.75 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,430 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,430 bytes after change">(-29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_1" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 1</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=8731&amp;undo=9176" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=8731" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=8731&amp;oldid=7088" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="8731" name="oldid" id="mw-oldid-8731" /><input type="radio" value="8731" name="diff" id="mw-diff-8731" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=8731" title="Hub Plot Walkthrough" class="mw-changeslist-date">14:28, 25 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Kazehito&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Kazehito (page does not exist)">Kazehito</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Kazehito&amp;action=edit&amp;redlink=1" class="new" title="User talk:Kazehito (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Kazehito" title="Special:Contributions/Kazehito">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,459 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,459 bytes after change">(+307)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=7088&amp;undo=8731" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=7088" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=7088&amp;oldid=6446" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="7088" name="oldid" id="mw-oldid-7088" /><input type="radio" value="7088" name="diff" id="mw-diff-7088" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=7088" title="Hub Plot Walkthrough" class="mw-changeslist-date">11:29, 24 August 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/69.143.12.176" title="Special:Contributions/69.143.12.176" class="mw-userlink">69.143.12.176</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:69.143.12.176&amp;action=edit&amp;redlink=1" class="new" title="User talk:69.143.12.176 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,152 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,152 bytes after change">(+143)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_2" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 2: </span> Split the realignment ability to its own stage, rather than calling it part of Gate2, since it is a distinct achievement.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=6446&amp;undo=7088" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=6446" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=6446&amp;oldid=5774" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="6446" name="oldid" id="mw-oldid-6446" /><input type="radio" value="6446" name="diff" id="mw-diff-6446" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=6446" title="Hub Plot Walkthrough" class="mw-changeslist-date">12:55, 26 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/89.196.33.44" title="Special:Contributions/89.196.33.44" class="mw-userlink">89.196.33.44</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:89.196.33.44&amp;action=edit&amp;redlink=1" class="new" title="User talk:89.196.33.44 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,009 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,009 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hub_Plot_Walkthrough#Gate_Pair_3" title="Hub Plot Walkthrough">→</a>‎<span dir="auto"><span class="autocomment">Gate Pair 3</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=5774&amp;undo=6446" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=5774" title="Hub Plot Walkthrough">cur</a> | <a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=5774&amp;oldid=5476" title="Hub Plot Walkthrough">prev</a>)</span><input type="radio" value="5774" name="oldid" id="mw-oldid-5774" /><input type="radio" value="5774" name="diff" id="mw-diff-5774" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=5774" title="Hub Plot Walkthrough" class="mw-changeslist-date">21:59, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,006 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,006 bytes after change">(+119)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added links, corrected punctuation; hope no one minds)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit&amp;undoafter=5476&amp;undo=5774" title="Hub Plot Walkthrough">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hub_Plot_Walkthrough&amp;diff=15426&amp;oldid=5476" title="Hub Plot Walkthrough">cur</a> | prev)</span><input type="radio" value="5476" name="oldid" id="mw-oldid-5476" /><input type="radio" value="5476" name="diff" id="mw-diff-5476" /> <a href="/index.php?title=Hub_Plot_Walkthrough&amp;oldid=5476" title="Hub Plot Walkthrough" class="mw-changeslist-date">18:01, 16 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,887 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,887 bytes after change">(+4,887)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &quot;[http://forum.egosoft.com/viewtopic.php?p=3466606#3466606 Check here for the Hub Plot Walkthrough on the Egosoft forums.]   This plot is regarded by most players as the most time...&quot;)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://www.x3wiki.com/index.php/Hub_Plot_Walkthrough">http://www.x3wiki.com/index.php/Hub_Plot_Walkthrough</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Hub_Plot_Walkthrough" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Hub_Plot_Walkthrough&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Hub+Plot+Walkthrough&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Hub+Plot+Walkthrough&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Hub_Plot_Walkthrough" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Hub_Plot_Walkthrough" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Hub_Plot_Walkthrough&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.266 secs. --></body></html>