<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "M5" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"M5","wgTitle":"M5","wgCurRevisionId":16411,"wgRevisionId":0,"wgArticleId":119,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"M5","wgRelevantArticleId":119,"wgRequestId":"WfUV-FkfZokAABwa1lAAAAAH","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=M5&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=M5&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;M5&quot; Atom feed" href="/index.php?title=M5&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-M5 rootpage-M5 skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "M5"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=M5" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="M5" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="M5" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=M5&amp;diff=16411&amp;oldid=16316" title="M5">prev</a>)</span><input type="radio" value="16411" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16411" checked="checked" name="diff" id="mw-diff-16411" /> <a href="/index.php?title=M5&amp;oldid=16411" title="M5" class="mw-changeslist-date">20:42, 20 August 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.49.172.50" title="Special:Contributions/78.49.172.50" class="mw-userlink mw-anonuserlink">78.49.172.50</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.49.172.50&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.49.172.50 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,834 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,834 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=16316&amp;undo=16411" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=16316" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=16316&amp;oldid=14040" title="M5">prev</a>)</span><input type="radio" value="16316" checked="checked" name="oldid" id="mw-oldid-16316" /><input type="radio" value="16316" name="diff" id="mw-diff-16316" /> <a href="/index.php?title=M5&amp;oldid=16316" title="M5" class="mw-changeslist-date">10:07, 10 July 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/88.156.226.87" title="Special:Contributions/88.156.226.87" class="mw-userlink mw-anonuserlink">88.156.226.87</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:88.156.226.87&amp;action=edit&amp;redlink=1" class="new" title="User talk:88.156.226.87 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,829 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,829 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=14040&amp;undo=16316" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=14040" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=14040&amp;oldid=13386" title="M5">prev</a>)</span><input type="radio" value="14040" name="oldid" id="mw-oldid-14040" /><input type="radio" value="14040" name="diff" id="mw-diff-14040" /> <a href="/index.php?title=M5&amp;oldid=14040" title="M5" class="mw-changeslist-date">00:57, 13 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,829 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,829 bytes after change">(+255)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List: </span> Make Shields column correctly sortable with &quot;data-sort-value&quot; key</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=13386&amp;undo=14040" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=13386" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=13386&amp;oldid=13385" title="M5">prev</a>)</span><input type="radio" value="13386" name="oldid" id="mw-oldid-13386" /><input type="radio" value="13386" name="diff" id="mw-diff-13386" /> <a href="/index.php?title=M5&amp;oldid=13386" title="M5" class="mw-changeslist-date">21:02, 6 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,574 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,574 bytes after change">(+212)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Weapons)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=13385&amp;undo=13386" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=13385" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=13385&amp;oldid=13015" title="M5">prev</a>)</span><input type="radio" value="13385" name="oldid" id="mw-oldid-13385" /><input type="radio" value="13385" name="diff" id="mw-diff-13385" /> <a href="/index.php?title=M5&amp;oldid=13385" title="M5" class="mw-changeslist-date">06:49, 4 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Ei8htx" class="mw-redirect mw-userlink" title="User:Ei8htx">Ei8htx</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Ei8htx" title="User talk:Ei8htx">talk</a> | <a href="/index.php/Special:Contributions/Ei8htx" title="Special:Contributions/Ei8htx">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,362 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,362 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated/fixed valkyrie stats)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=13015&amp;undo=13385" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=13015" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=13015&amp;oldid=12808" title="M5">prev</a>)</span><input type="radio" value="13015" name="oldid" id="mw-oldid-13015" /><input type="radio" value="13015" name="diff" id="mw-diff-13015" /> <a href="/index.php?title=M5&amp;oldid=13015" title="M5" class="mw-changeslist-date">23:04, 2 July 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,364 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,364 bytes after change">(-24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12808&amp;undo=13015" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12808" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12808&amp;oldid=12548" title="M5">prev</a>)</span><input type="radio" value="12808" name="oldid" id="mw-oldid-12808" /><input type="radio" value="12808" name="diff" id="mw-diff-12808" /> <a href="/index.php?title=M5&amp;oldid=12808" title="M5" class="mw-changeslist-date">14:49, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,388 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,388 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(consistent header)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12548&amp;undo=12808" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12548" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12548&amp;oldid=12544" title="M5">prev</a>)</span><input type="radio" value="12548" name="oldid" id="mw-oldid-12548" /><input type="radio" value="12548" name="diff" id="mw-diff-12548" /> <a href="/index.php?title=M5&amp;oldid=12548" title="M5" class="mw-changeslist-date">10:37, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,387 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,387 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(see also header)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12544&amp;undo=12548" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12544" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12544&amp;oldid=12542" title="M5">prev</a>)</span><input type="radio" value="12544" name="oldid" id="mw-oldid-12544" /><input type="radio" value="12544" name="diff" id="mw-diff-12544" /> <a href="/index.php?title=M5&amp;oldid=12544" title="M5" class="mw-changeslist-date">10:34, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,371 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,371 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(filling in missing info)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12542&amp;undo=12544" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12542" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12542&amp;oldid=12537" title="M5">prev</a>)</span><input type="radio" value="12542" name="oldid" id="mw-oldid-12542" /><input type="radio" value="12542" name="diff" id="mw-diff-12542" /> <a href="/index.php?title=M5&amp;oldid=12542" title="M5" class="mw-changeslist-date">10:31, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,356 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,356 bytes after change">(+314)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(adding Arrow and Starburst to M5 list)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12537&amp;undo=12542" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12537" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12537&amp;oldid=12161" title="M5">prev</a>)</span><input type="radio" value="12537" name="oldid" id="mw-oldid-12537" /><input type="radio" value="12537" name="diff" id="mw-diff-12537" /> <a href="/index.php?title=M5&amp;oldid=12537" title="M5" class="mw-changeslist-date">10:11, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,042 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,042 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(move nav further down so it wont interfere with main article)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12161&amp;undo=12537" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12161" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12161&amp;oldid=12160" title="M5">prev</a>)</span><input type="radio" value="12161" name="oldid" id="mw-oldid-12161" /><input type="radio" value="12161" name="diff" id="mw-diff-12161" /> <a href="/index.php?title=M5&amp;oldid=12161" title="M5" class="mw-changeslist-date">14:58, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,043 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,043 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List: </span> added wikitable look</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=12160&amp;undo=12161" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=12160" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=12160&amp;oldid=10518" title="M5">prev</a>)</span><input type="radio" value="12160" name="oldid" id="mw-oldid-12160" /><input type="radio" value="12160" name="diff" id="mw-diff-12160" /> <a href="/index.php?title=M5&amp;oldid=12160" title="M5" class="mw-changeslist-date">05:09, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Red_Asphalt&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Red Asphalt (page does not exist)">Red Asphalt</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Red_Asphalt&amp;action=edit&amp;redlink=1" class="new" title="User talk:Red Asphalt (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Red_Asphalt" title="Special:Contributions/Red Asphalt">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,033 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,033 bytes after change">(+286)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_list" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable list: </span> Changed sort options to support commas in numbers</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=10518&amp;undo=12160" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=10518" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=10518&amp;oldid=10516" title="M5">prev</a>)</span><input type="radio" value="10518" name="oldid" id="mw-oldid-10518" /><input type="radio" value="10518" name="diff" id="mw-diff-10518" /> <a href="/index.php?title=M5&amp;oldid=10518" title="M5" class="mw-changeslist-date">20:29, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,747 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="2,747 bytes after change">(-2,622)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(using M5 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=10516&amp;undo=10518" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=10516" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=10516&amp;oldid=10515" title="M5">prev</a>)</span><input type="radio" value="10516" name="oldid" id="mw-oldid-10516" /><input type="radio" value="10516" name="diff" id="mw-diff-10516" /> <a href="/index.php?title=M5&amp;oldid=10516" title="M5" class="mw-changeslist-date">20:18, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,369 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,369 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=10515&amp;undo=10516" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=10515" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=10515&amp;oldid=10439" title="M5">prev</a>)</span><input type="radio" value="10515" name="oldid" id="mw-oldid-10515" /><input type="radio" value="10515" name="diff" id="mw-diff-10515" /> <a href="/index.php?title=M5&amp;oldid=10515" title="M5" class="mw-changeslist-date">20:18, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,368 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,368 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=10439&amp;undo=10515" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=10439" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=10439&amp;oldid=9523" title="M5">prev</a>)</span><input type="radio" value="10439" name="oldid" id="mw-oldid-10439" /><input type="radio" value="10439" name="diff" id="mw-diff-10439" /> <a href="/index.php?title=M5&amp;oldid=10439" title="M5" class="mw-changeslist-date">07:22, 11 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,367 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,367 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Kestrel data)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9523&amp;undo=10439" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9523" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9523&amp;oldid=9521" title="M5">prev</a>)</span><input type="radio" value="9523" name="oldid" id="mw-oldid-9523" /><input type="radio" value="9523" name="diff" id="mw-diff-9523" /> <a href="/index.php?title=M5&amp;oldid=9523" title="M5" class="mw-changeslist-date">02:22, 2 August 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,361 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,361 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(aliasing deca fade. note the <a href="/index.php/Deca.fade" title="Deca.fade">#deca.fade</a> notation.)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9521&amp;undo=9523" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9521" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9521&amp;oldid=9520" title="M5">prev</a>)</span><input type="radio" value="9521" name="oldid" id="mw-oldid-9521" /><input type="radio" value="9521" name="diff" id="mw-diff-9521" /> <a href="/index.php?title=M5&amp;oldid=9521" title="M5" class="mw-changeslist-date">20:04, 1 August 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tdeith&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tdeith (page does not exist)">Tdeith</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tdeith&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tdeith (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tdeith" title="Special:Contributions/Tdeith">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,350 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,350 bytes after change">(-8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">((after experimenting with some possible replacements) removed the # character from deca.fade, as the link automatically interpreted the # as an anchor-link.)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9520&amp;undo=9521" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9520" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9520&amp;oldid=9519" title="M5">prev</a>)</span><input type="radio" value="9520" name="oldid" id="mw-oldid-9520" /><input type="radio" value="9520" name="diff" id="mw-diff-9520" /> <a href="/index.php?title=M5&amp;oldid=9520" title="M5" class="mw-changeslist-date">20:02, 1 August 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tdeith&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tdeith (page does not exist)">Tdeith</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tdeith&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tdeith (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tdeith" title="Special:Contributions/Tdeith">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,358 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,358 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9519&amp;undo=9520" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9519" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9519&amp;oldid=9245" title="M5">prev</a>)</span><input type="radio" value="9519" name="oldid" id="mw-oldid-9519" /><input type="radio" value="9519" name="diff" id="mw-diff-9519" /> <a href="/index.php?title=M5&amp;oldid=9519" title="M5" class="mw-changeslist-date">19:59, 1 August 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tdeith&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tdeith (page does not exist)">Tdeith</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tdeith&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tdeith (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tdeith" title="Special:Contributions/Tdeith">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,355 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,355 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9245&amp;undo=9519" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9245" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9245&amp;oldid=9244" title="M5">prev</a>)</span><input type="radio" value="9245" name="oldid" id="mw-oldid-9245" /><input type="radio" value="9245" name="diff" id="mw-diff-9245" /> <a href="/index.php?title=M5&amp;oldid=9245" title="M5" class="mw-changeslist-date">00:17, 21 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,351 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,351 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9244&amp;undo=9245" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9244" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9244&amp;oldid=9243" title="M5">prev</a>)</span><input type="radio" value="9244" name="oldid" id="mw-oldid-9244" /><input type="radio" value="9244" name="diff" id="mw-diff-9244" /> <a href="/index.php?title=M5&amp;oldid=9244" title="M5" class="mw-changeslist-date">00:17, 21 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,352 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,352 bytes after change">(+1,684)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M5#Sortable_List" title="M5">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=9243&amp;undo=9244" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=9243" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=9243&amp;oldid=7494" title="M5">prev</a>)</span><input type="radio" value="9243" name="oldid" id="mw-oldid-9243" /><input type="radio" value="9243" name="diff" id="mw-diff-9243" /> <a href="/index.php?title=M5&amp;oldid=9243" title="M5" class="mw-changeslist-date">23:46, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,668 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,668 bytes after change">(+428)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=7494&amp;undo=9243" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=7494" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=7494&amp;oldid=6783" title="M5">prev</a>)</span><input type="radio" value="7494" name="oldid" id="mw-oldid-7494" /><input type="radio" value="7494" name="diff" id="mw-diff-7494" /> <a href="/index.php?title=M5&amp;oldid=7494" title="M5" class="mw-changeslist-date">16:02, 26 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/113.146.229.171" title="Special:Contributions/113.146.229.171" class="mw-userlink mw-anonuserlink">113.146.229.171</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:113.146.229.171&amp;action=edit&amp;redlink=1" class="new" title="User talk:113.146.229.171 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,240 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,240 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Fixed link to #deca.fade)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6783&amp;undo=7494" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6783" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6783&amp;oldid=6759" title="M5">prev</a>)</span><input type="radio" value="6783" name="oldid" id="mw-oldid-6783" /><input type="radio" value="6783" name="diff" id="mw-diff-6783" /> <a href="/index.php?title=M5&amp;oldid=6783" title="M5" class="mw-changeslist-date">22:23, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,230 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,230 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6759&amp;undo=6783" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6759" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6759&amp;oldid=6744" title="M5">prev</a>)</span><input type="radio" value="6759" name="oldid" id="mw-oldid-6759" /><input type="radio" value="6759" name="diff" id="mw-diff-6759" /> <a href="/index.php?title=M5&amp;oldid=6759" title="M5" class="mw-changeslist-date">20:38, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,230 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,230 bytes after change">(-38)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6744&amp;undo=6759" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6744" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6744&amp;oldid=6743" title="M5">prev</a>)</span><input type="radio" value="6744" name="oldid" id="mw-oldid-6744" /><input type="radio" value="6744" name="diff" id="mw-diff-6744" /> <a href="/index.php?title=M5&amp;oldid=6744" title="M5" class="mw-changeslist-date">10:46, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,268 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,268 bytes after change">(-33)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6743&amp;undo=6744" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6743" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6743&amp;oldid=6742" title="M5">prev</a>)</span><input type="radio" value="6743" name="oldid" id="mw-oldid-6743" /><input type="radio" value="6743" name="diff" id="mw-diff-6743" /> <a href="/index.php?title=M5&amp;oldid=6743" title="M5" class="mw-changeslist-date">10:44, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,301 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,301 bytes after change">(-58)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6742&amp;undo=6743" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6742" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6742&amp;oldid=6741" title="M5">prev</a>)</span><input type="radio" value="6742" name="oldid" id="mw-oldid-6742" /><input type="radio" value="6742" name="diff" id="mw-diff-6742" /> <a href="/index.php?title=M5&amp;oldid=6742" title="M5" class="mw-changeslist-date">10:38, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,359 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,359 bytes after change">(+255)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6741&amp;undo=6742" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6741" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6741&amp;oldid=6740" title="M5">prev</a>)</span><input type="radio" value="6741" name="oldid" id="mw-oldid-6741" /><input type="radio" value="6741" name="diff" id="mw-diff-6741" /> <a href="/index.php?title=M5&amp;oldid=6741" title="M5" class="mw-changeslist-date">10:32, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,104 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,104 bytes after change">(-9)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6740&amp;undo=6741" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6740" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6740&amp;oldid=6739" title="M5">prev</a>)</span><input type="radio" value="6740" name="oldid" id="mw-oldid-6740" /><input type="radio" value="6740" name="diff" id="mw-diff-6740" /> <a href="/index.php?title=M5&amp;oldid=6740" title="M5" class="mw-changeslist-date">10:31, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,113 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,113 bytes after change">(+261)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6739&amp;undo=6740" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6739" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6739&amp;oldid=6738" title="M5">prev</a>)</span><input type="radio" value="6739" name="oldid" id="mw-oldid-6739" /><input type="radio" value="6739" name="diff" id="mw-diff-6739" /> <a href="/index.php?title=M5&amp;oldid=6739" title="M5" class="mw-changeslist-date">10:24, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,852 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,852 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6738&amp;undo=6739" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6738" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6738&amp;oldid=6737" title="M5">prev</a>)</span><input type="radio" value="6738" name="oldid" id="mw-oldid-6738" /><input type="radio" value="6738" name="diff" id="mw-diff-6738" /> <a href="/index.php?title=M5&amp;oldid=6738" title="M5" class="mw-changeslist-date">10:23, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,852 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,852 bytes after change">(+811)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=6737&amp;undo=6738" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=6737" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=6737&amp;oldid=4450" title="M5">prev</a>)</span><input type="radio" value="6737" name="oldid" id="mw-oldid-6737" /><input type="radio" value="6737" name="diff" id="mw-diff-6737" /> <a href="/index.php?title=M5&amp;oldid=6737" title="M5" class="mw-changeslist-date">10:12, 5 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:JoshyMW&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:JoshyMW (page does not exist)">JoshyMW</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:JoshyMW&amp;action=edit&amp;redlink=1" class="new" title="User talk:JoshyMW (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/JoshyMW" title="Special:Contributions/JoshyMW">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,041 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,041 bytes after change">(+1,168)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=4450&amp;undo=6737" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=4450" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=4450&amp;oldid=3018" title="M5">prev</a>)</span><input type="radio" value="4450" name="oldid" id="mw-oldid-4450" /><input type="radio" value="4450" name="diff" id="mw-diff-4450" /> <a href="/index.php?title=M5&amp;oldid=4450" title="M5" class="mw-changeslist-date">18:58, 28 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(873 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="873 bytes after change">(+20)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Assorted edits)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=3018&amp;undo=4450" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=3018" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=3018&amp;oldid=2126" title="M5">prev</a>)</span><input type="radio" value="3018" name="oldid" id="mw-oldid-3018" /><input type="radio" value="3018" name="diff" id="mw-diff-3018" /> <a href="/index.php?title=M5&amp;oldid=3018" title="M5" class="mw-changeslist-date">22:47, 16 October 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(853 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="853 bytes after change">(+152)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=2126&amp;undo=3018" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=2126" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=2126&amp;oldid=1972" title="M5">prev</a>)</span><input type="radio" value="2126" name="oldid" id="mw-oldid-2126" /><input type="radio" value="2126" name="diff" id="mw-diff-2126" /> <a href="/index.php?title=M5&amp;oldid=2126" title="M5" class="mw-changeslist-date">12:59, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(701 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="701 bytes after change">(+153)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=1972&amp;undo=2126" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=1972" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=1972&amp;oldid=701" title="M5">prev</a>)</span><input type="radio" value="1972" name="oldid" id="mw-oldid-1972" /><input type="radio" value="1972" name="diff" id="mw-diff-1972" /> <a href="/index.php?title=M5&amp;oldid=1972" title="M5" class="mw-changeslist-date">20:27, 4 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(548 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="548 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fighter category sortkey)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=701&amp;undo=1972" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=701" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=701&amp;oldid=694" title="M5">prev</a>)</span><input type="radio" value="701" name="oldid" id="mw-oldid-701" /><input type="radio" value="701" name="diff" id="mw-diff-701" /> <a href="/index.php?title=M5&amp;oldid=701" title="M5" class="mw-changeslist-date">23:48, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(514 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="514 bytes after change">(+156)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restored some commentary from cache description)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=694&amp;undo=701" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=694" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=694&amp;oldid=507" title="M5">prev</a>)</span><input type="radio" value="694" name="oldid" id="mw-oldid-694" /><input type="radio" value="694" name="diff" id="mw-diff-694" /> <a href="/index.php?title=M5&amp;oldid=694" title="M5" class="mw-changeslist-date">23:20, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(358 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="358 bytes after change">(+233)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore ship list from cache description)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=507&amp;undo=694" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=507" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=507&amp;oldid=346" title="M5">prev</a>)</span><input type="radio" value="507" name="oldid" id="mw-oldid-507" /><input type="radio" value="507" name="diff" id="mw-diff-507" /> <a href="/index.php?title=M5&amp;oldid=507" title="M5" class="mw-changeslist-date">02:41, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(125 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="125 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added discoverer)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=346&amp;undo=507" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=346" title="M5">cur</a> | <a href="/index.php?title=M5&amp;diff=346&amp;oldid=317" title="M5">prev</a>)</span><input type="radio" value="346" name="oldid" id="mw-oldid-346" /><input type="radio" value="346" name="diff" id="mw-diff-346" /> <a href="/index.php?title=M5&amp;oldid=346" title="M5" class="mw-changeslist-date">19:53, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(111 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="111 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(category)</span> (<span class="mw-history-undo"><a href="/index.php?title=M5&amp;action=edit&amp;undoafter=317&amp;undo=346" title="M5">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M5&amp;diff=16411&amp;oldid=317" title="M5">cur</a> | prev)</span><input type="radio" value="317" name="oldid" id="mw-oldid-317" /><input type="radio" value="317" name="diff" id="mw-diff-317" /> <a href="/index.php?title=M5&amp;oldid=317" title="M5" class="mw-changeslist-date">01:41, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(95 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="95 bytes after change">(+95)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(stub no anchors even)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/M5">http://x3wiki.com/index.php/M5</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/M5" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:M5" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=M5&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=M5&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=M5&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=M5&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/M5" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/M5" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=M5&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=M5&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":114});});</script></body></html>
