<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Asteroids" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Asteroids","wgTitle":"Asteroids","wgCurRevisionId":16330,"wgRevisionId":0,"wgArticleId":12,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Asteroids","wgRelevantArticleId":12,"wgRequestId":"WXRI3lkfZokAABC-CxIAAAAV","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Asteroids&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Asteroids&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Asteroids&quot; Atom feed" href="/index.php?title=Asteroids&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Asteroids rootpage-Asteroids skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Asteroids"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Asteroids" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Asteroids" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Asteroids" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=14137" title="Asteroids">prev</a>)</span><input type="radio" value="16330" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16330" checked="checked" name="diff" id="mw-diff-16330" /> <a href="/index.php?title=Asteroids&amp;oldid=16330" title="Asteroids" class="mw-changeslist-date">05:22, 18 July 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/99.127.67.41" title="Special:Contributions/99.127.67.41" class="mw-userlink mw-anonuserlink">99.127.67.41</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:99.127.67.41&amp;action=edit&amp;redlink=1" class="new" title="User talk:99.127.67.41 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,590 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,590 bytes after change">(-5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Asteroids#Yield" title="Asteroids">→</a>‎<span dir="auto"><span class="autocomment">Yield</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=14137&amp;undo=16330" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=14137" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=14137&amp;oldid=13134" title="Asteroids">prev</a>)</span><input type="radio" value="14137" checked="checked" name="oldid" id="mw-oldid-14137" /><input type="radio" value="14137" name="diff" id="mw-diff-14137" /> <a href="/index.php?title=Asteroids&amp;oldid=14137" title="Asteroids" class="mw-changeslist-date">21:48, 3 January 2014</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,595 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,595 bytes after change">(+515)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Linkifying the page, and tidying it up to be worthy of being linked to from the sidebar.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=13134&amp;undo=14137" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=13134" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=13134&amp;oldid=12135" title="Asteroids">prev</a>)</span><input type="radio" value="13134" name="oldid" id="mw-oldid-13134" /><input type="radio" value="13134" name="diff" id="mw-diff-13134" /> <a href="/index.php?title=Asteroids&amp;oldid=13134" title="Asteroids" class="mw-changeslist-date">13:57, 17 July 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,080 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,080 bytes after change">(-138)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Pretty table.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=12135&amp;undo=13134" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=12135" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=12135&amp;oldid=8709" title="Asteroids">prev</a>)</span><input type="radio" value="12135" name="oldid" id="mw-oldid-12135" /><input type="radio" value="12135" name="diff" id="mw-diff-12135" /> <a href="/index.php?title=Asteroids&amp;oldid=12135" title="Asteroids" class="mw-changeslist-date">23:22, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,218 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,218 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=8709&amp;undo=12135" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=8709" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=8709&amp;oldid=8460" title="Asteroids">prev</a>)</span><input type="radio" value="8709" name="oldid" id="mw-oldid-8709" /><input type="radio" value="8709" name="diff" id="mw-diff-8709" /> <a href="/index.php?title=Asteroids&amp;oldid=8709" title="Asteroids" class="mw-changeslist-date">00:32, 23 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,191 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,191 bytes after change">(+87)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(moved mineral scanner here from mobile mining.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=8460&amp;undo=8709" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=8460" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=8460&amp;oldid=8457" title="Asteroids">prev</a>)</span><input type="radio" value="8460" name="oldid" id="mw-oldid-8460" /><input type="radio" value="8460" name="diff" id="mw-diff-8460" /> <a href="/index.php?title=Asteroids&amp;oldid=8460" title="Asteroids" class="mw-changeslist-date">01:18, 10 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,104 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,104 bytes after change">(+63)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(what can i say, i like tables. :P)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=8457&amp;undo=8460" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=8457" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=8457&amp;oldid=8456" title="Asteroids">prev</a>)</span><input type="radio" value="8457" name="oldid" id="mw-oldid-8457" /><input type="radio" value="8457" name="diff" id="mw-diff-8457" /> <a href="/index.php?title=Asteroids&amp;oldid=8457" title="Asteroids" class="mw-changeslist-date">11:57, 9 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,041 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,041 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=8456&amp;undo=8457" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=8456" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=8456&amp;oldid=4844" title="Asteroids">prev</a>)</span><input type="radio" value="8456" name="oldid" id="mw-oldid-8456" /><input type="radio" value="8456" name="diff" id="mw-diff-8456" /> <a href="/index.php?title=Asteroids&amp;oldid=8456" title="Asteroids" class="mw-changeslist-date">11:56, 9 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,039 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,039 bytes after change">(+297)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=4844&amp;undo=8456" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=4844" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=4844&amp;oldid=1943" title="Asteroids">prev</a>)</span><input type="radio" value="4844" name="oldid" id="mw-oldid-4844" /><input type="radio" value="4844" name="diff" id="mw-diff-4844" /> <a href="/index.php?title=Asteroids&amp;oldid=4844" title="Asteroids" class="mw-changeslist-date">00:32, 20 January 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(742 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="742 bytes after change">(+391)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(expanded text)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1943&amp;undo=4844" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1943" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1943&amp;oldid=1942" title="Asteroids">prev</a>)</span><input type="radio" value="1943" name="oldid" id="mw-oldid-1943" /><input type="radio" value="1943" name="diff" id="mw-diff-1943" /> <a href="/index.php?title=Asteroids&amp;oldid=1943" title="Asteroids" class="mw-changeslist-date">23:35, 3 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(351 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="351 bytes after change">(-11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(testing new spam protection)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1942&amp;undo=1943" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1942" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1942&amp;oldid=1941" title="Asteroids">prev</a>)</span><input type="radio" value="1942" name="oldid" id="mw-oldid-1942" /><input type="radio" value="1942" name="diff" id="mw-diff-1942" /> <a href="/index.php?title=Asteroids&amp;oldid=1942" title="Asteroids" class="mw-changeslist-date">23:35, 3 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(362 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="362 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1941&amp;undo=1942" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1941" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1941&amp;oldid=1940" title="Asteroids">prev</a>)</span><input type="radio" value="1941" name="oldid" id="mw-oldid-1941" /><input type="radio" value="1941" name="diff" id="mw-diff-1941" /> <a href="/index.php?title=Asteroids&amp;oldid=1941" title="Asteroids" class="mw-changeslist-date">23:33, 3 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(351 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="351 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1940&amp;undo=1941" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1940" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1940&amp;oldid=1592" title="Asteroids">prev</a>)</span><input type="radio" value="1940" name="oldid" id="mw-oldid-1940" /><input type="radio" value="1940" name="diff" id="mw-diff-1940" /> <a href="/index.php?title=Asteroids&amp;oldid=1940" title="Asteroids" class="mw-changeslist-date">23:33, 3 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(353 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="353 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1592&amp;undo=1940" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1592" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1592&amp;oldid=1028" title="Asteroids">prev</a>)</span><input type="radio" value="1592" name="oldid" id="mw-oldid-1592" /><input type="radio" value="1592" name="diff" id="mw-diff-1592" /> <a href="/index.php?title=Asteroids&amp;oldid=1592" title="Asteroids" class="mw-changeslist-date">14:38, 26 September 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Lord Hayden (page does not exist)">Lord Hayden</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new" title="User talk:Lord Hayden (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Lord_Hayden" title="Special:Contributions/Lord Hayden">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(351 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="351 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=1028&amp;undo=1592" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=1028" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=1028&amp;oldid=562" title="Asteroids">prev</a>)</span><input type="radio" value="1028" name="oldid" id="mw-oldid-1028" /><input type="radio" value="1028" name="diff" id="mw-diff-1028" /> <a href="/index.php?title=Asteroids&amp;oldid=1028" title="Asteroids" class="mw-changeslist-date">01:46, 12 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(348 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="348 bytes after change">(+147)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(additional color text)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=562&amp;undo=1028" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=562" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=562&amp;oldid=561" title="Asteroids">prev</a>)</span><input type="radio" value="562" name="oldid" id="mw-oldid-562" /><input type="radio" value="562" name="diff" id="mw-diff-562" /> <a href="/index.php?title=Asteroids&amp;oldid=562" title="Asteroids" class="mw-changeslist-date">23:57, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(201 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="201 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(capitalized i in ice.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=561&amp;undo=562" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=561" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=561&amp;oldid=560" title="Asteroids">prev</a>)</span><input type="radio" value="561" name="oldid" id="mw-oldid-561" /><input type="radio" value="561" name="diff" id="mw-diff-561" /> <a href="/index.php?title=Asteroids&amp;oldid=561" title="Asteroids" class="mw-changeslist-date">23:56, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(201 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="201 bytes after change">(+12)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(changed list to unnumbered and linked minerals)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=560&amp;undo=561" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=560" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=560&amp;oldid=78" title="Asteroids">prev</a>)</span><input type="radio" value="560" name="oldid" id="mw-oldid-560" /><input type="radio" value="560" name="diff" id="mw-diff-560" /> <a href="/index.php?title=Asteroids&amp;oldid=560" title="Asteroids" class="mw-changeslist-date">23:55, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(189 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="189 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(link nividium)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=78&amp;undo=560" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=78" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=78&amp;oldid=69" title="Asteroids">prev</a>)</span><input type="radio" value="78" name="oldid" id="mw-oldid-78" /><input type="radio" value="78" name="diff" id="mw-diff-78" /> <a href="/index.php?title=Asteroids&amp;oldid=78" title="Asteroids" class="mw-changeslist-date">22:17, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(185 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="185 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=69&amp;undo=78" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=69" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=69&amp;oldid=66" title="Asteroids">prev</a>)</span><input type="radio" value="69" name="oldid" id="mw-oldid-69" /><input type="radio" value="69" name="diff" id="mw-diff-69" /> <a href="/index.php?title=Asteroids&amp;oldid=69" title="Asteroids" class="mw-changeslist-date">22:12, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(183 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="183 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=66&amp;undo=69" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=66" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=66&amp;oldid=62" title="Asteroids">prev</a>)</span><input type="radio" value="66" name="oldid" id="mw-oldid-66" /><input type="radio" value="66" name="diff" id="mw-diff-66" /> <a href="/index.php?title=Asteroids&amp;oldid=66" title="Asteroids" class="mw-changeslist-date">22:11, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(146 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="146 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(moved <a href="/index.php/Astroids" class="mw-redirect" title="Astroids">Astroids</a> to <a href="/index.php/Asteroids" title="Asteroids">Asteroids</a>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=62&amp;undo=66" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=62" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=62&amp;oldid=61" title="Asteroids">prev</a>)</span><input type="radio" value="62" name="oldid" id="mw-oldid-62" /><input type="radio" value="62" name="diff" id="mw-diff-62" /> <a href="/index.php?title=Asteroids&amp;oldid=62" title="Asteroids" class="mw-changeslist-date">22:07, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(146 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="146 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=61&amp;undo=62" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=61" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=61&amp;oldid=60" title="Asteroids">prev</a>)</span><input type="radio" value="61" name="oldid" id="mw-oldid-61" /><input type="radio" value="61" name="diff" id="mw-diff-61" /> <a href="/index.php?title=Asteroids&amp;oldid=61" title="Asteroids" class="mw-changeslist-date">22:07, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(143 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="143 bytes after change">(-16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Asteroids#Astroids" title="Asteroids">→</a>‎<span dir="auto"><span class="autocomment">Astroids</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=60&amp;undo=61" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=60" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=60&amp;oldid=59" title="Asteroids">prev</a>)</span><input type="radio" value="60" name="oldid" id="mw-oldid-60" /><input type="radio" value="60" name="diff" id="mw-diff-60" /> <a href="/index.php?title=Asteroids&amp;oldid=60" title="Asteroids" class="mw-changeslist-date">22:07, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(159 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="159 bytes after change">(-191,795)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Replaced content with &#039; == Astroids ==  There are 3 types of astroids in the X universe.  # Ore (<a href="/index.php?title=Ore_astroid_list&amp;action=edit&amp;redlink=1" class="new" title="Ore astroid list (page does not exist)">Ore astroid list</a>) # Silicon(<a href="/index.php?title=Silicon_astroid_list&amp;action=edit&amp;redlink=1" class="new" title="Silicon astroid list (page does not exist)">Silicon astroid list</a>) # Ice(<a href="/index.php?title=Ice_astroid_list&amp;action=edit&amp;redlink=1" class="new" title="Ice astroid list (page does not exist)">ice astroid list</a>)&#039;)</span> (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=59&amp;undo=60" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=59" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=59&amp;oldid=58" title="Asteroids">prev</a>)</span><input type="radio" value="59" name="oldid" id="mw-oldid-59" /><input type="radio" value="59" name="diff" id="mw-diff-59" /> <a href="/index.php?title=Asteroids&amp;oldid=59" title="Asteroids" class="mw-changeslist-date">22:04, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(191,954 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="191,954 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=58&amp;undo=59" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=58" title="Asteroids">cur</a> | <a href="/index.php?title=Asteroids&amp;diff=58&amp;oldid=57" title="Asteroids">prev</a>)</span><input type="radio" value="58" name="oldid" id="mw-oldid-58" /><input type="radio" value="58" name="diff" id="mw-diff-58" /> <a href="/index.php?title=Asteroids&amp;oldid=58" title="Asteroids" class="mw-changeslist-date">22:02, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(191,951 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="191,951 bytes after change">(-262)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Asteroids&amp;action=edit&amp;undoafter=57&amp;undo=58" title="Asteroids">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Asteroids&amp;diff=16330&amp;oldid=57" title="Asteroids">cur</a> | prev)</span><input type="radio" value="57" name="oldid" id="mw-oldid-57" /><input type="radio" value="57" name="diff" id="mw-diff-57" /> <a href="/index.php?title=Asteroids&amp;oldid=57" title="Asteroids" class="mw-changeslist-date">22:01, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(192,213 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="192,213 bytes after change">(+192,213)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &#039;all astroids  {| {{table}} | align=&quot;center&quot; style=&quot;background:#f0f0f0;&quot;|&#039;&#039;&#039;Race&#039;&#039;&#039; | align=&quot;center&quot; style=&quot;background:#f0f0f0;&quot;|&#039;&#039;&#039;Sector&#039;&#039;&#039; | align=&quot;center&quot; style=&quot;background:#f…&#039;)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Asteroids">http://x3wiki.com/index.php/Asteroids</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Asteroids" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Asteroids" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Asteroids&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Asteroids&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Asteroids&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Asteroids&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Asteroids" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Asteroids" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Asteroids&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Asteroids&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":77});});</script></body></html>
