<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Cerberus" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Cerberus&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Cerberus&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Cerberus&quot; Atom feed" href="/index.php?title=Cerberus&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Cerberus","wgTitle":"Cerberus","wgCurRevisionId":16447,"wgRevisionId":0,"wgArticleId":235,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Cerberus","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Cerberus skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Cerberus"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Cerberus" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Cerberus" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Cerberus" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=13651" title="Cerberus">prev</a>)</span><input type="radio" value="16447" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16447" checked="checked" name="diff" id="mw-diff-16447" /> <a href="/index.php?title=Cerberus&amp;oldid=16447" title="Cerberus" class="mw-changeslist-date">22:07, 27 August 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,608 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,608 bytes after change">(+112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Suggested_Roles" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=13651&amp;undo=16447" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=13651" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=13651&amp;oldid=13516" title="Cerberus">prev</a>)</span><input type="radio" value="13651" checked="checked" name="oldid" id="mw-oldid-13651" /><input type="radio" value="13651" name="diff" id="mw-diff-13651" /> <a href="/index.php?title=Cerberus&amp;oldid=13651" title="Cerberus" class="mw-changeslist-date">08:37, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,496 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,496 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=13516&amp;undo=13651" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=13516" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=13516&amp;oldid=12771" title="Cerberus">prev</a>)</span><input type="radio" value="13516" name="oldid" id="mw-oldid-13516" /><input type="radio" value="13516" name="diff" id="mw-diff-13516" /> <a href="/index.php?title=Cerberus&amp;oldid=13516" title="Cerberus" class="mw-changeslist-date">05:59, 14 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,479 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,479 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Category:Carrier" title="Category:Carrier">Category: Carrier</a>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=12771&amp;undo=13516" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=12771" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=12771&amp;oldid=12653" title="Cerberus">prev</a>)</span><input type="radio" value="12771" name="oldid" id="mw-oldid-12771" /><input type="radio" value="12771" name="diff" id="mw-diff-12771" /> <a href="/index.php?title=Cerberus&amp;oldid=12771" title="Cerberus" class="mw-changeslist-date">06:59, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,457 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,457 bytes after change">(+57)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(reintroduce related reference)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=12653&amp;undo=12771" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=12653" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=12653&amp;oldid=11559" title="Cerberus">prev</a>)</span><input type="radio" value="12653" name="oldid" id="mw-oldid-12653" /><input type="radio" value="12653" name="diff" id="mw-diff-12653" /> <a href="/index.php?title=Cerberus&amp;oldid=12653" title="Cerberus" class="mw-changeslist-date">05:44, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,400 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,400 bytes after change">(-45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#See_Also" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> no need for special mention; all m7m in template</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=11559&amp;undo=12653" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=11559" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=11559&amp;oldid=11101" title="Cerberus">prev</a>)</span><input type="radio" value="11559" name="oldid" id="mw-oldid-11559" /><input type="radio" value="11559" name="diff" id="mw-diff-11559" /> <a href="/index.php?title=Cerberus&amp;oldid=11559" title="Cerberus" class="mw-changeslist-date">17:01, 6 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,445 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,445 bytes after change">(-50)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Okay, you people need to fix the retarded link filter. It was linking to egosoft for fuck&#039;s sake, I shouldn&#039;t be prohibited from fixing errors in the article because the stupid filter seems to think EVERY link is evil. Put the link back later.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=11101&amp;undo=11559" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=11101" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=11101&amp;oldid=11035" title="Cerberus">prev</a>)</span><input type="radio" value="11101" name="oldid" id="mw-oldid-11101" /><input type="radio" value="11101" name="diff" id="mw-diff-11101" /> <a href="/index.php?title=Cerberus&amp;oldid=11101" title="Cerberus" class="mw-changeslist-date">23:54, 28 November 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,495 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,495 bytes after change">(+3,036)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added data and text)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=11035&amp;undo=11101" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=11035" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=11035&amp;oldid=10777" title="Cerberus">prev</a>)</span><input type="radio" value="11035" name="oldid" id="mw-oldid-11035" /><input type="radio" value="11035" name="diff" id="mw-diff-11035" /> <a href="/index.php?title=Cerberus&amp;oldid=11035" title="Cerberus" class="mw-changeslist-date">21:33, 16 November 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,459 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,459 bytes after change">(+330)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added in-game description)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=10777&amp;undo=11035" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=10777" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=10777&amp;oldid=9283" title="Cerberus">prev</a>)</span><input type="radio" value="10777" name="oldid" id="mw-oldid-10777" /><input type="radio" value="10777" name="diff" id="mw-diff-10777" /> <a href="/index.php?title=Cerberus&amp;oldid=10777" title="Cerberus" class="mw-changeslist-date">16:33, 16 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,129 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,129 bytes after change">(-340)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M7 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=9283&amp;undo=10777" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=9283" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=9283&amp;oldid=9142" title="Cerberus">prev</a>)</span><input type="radio" value="9283" name="oldid" id="mw-oldid-9283" /><input type="radio" value="9283" name="diff" id="mw-diff-9283" /> <a href="/index.php?title=Cerberus&amp;oldid=9283" title="Cerberus" class="mw-changeslist-date">10:39, 8 June 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Troyminator&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Troyminator (page does not exist)">Troyminator</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Troyminator&amp;action=edit&amp;redlink=1" class="new" title="User talk:Troyminator (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Troyminator" title="Special:Contributions/Troyminator">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,469 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,469 bytes after change">(+559)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=9142&amp;undo=9283" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=9142" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=9142&amp;oldid=8810" title="Cerberus">prev</a>)</span><input type="radio" value="9142" name="oldid" id="mw-oldid-9142" /><input type="radio" value="9142" name="diff" id="mw-diff-9142" /> <a href="/index.php?title=Cerberus&amp;oldid=9142" title="Cerberus" class="mw-changeslist-date">22:24, 8 May 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.228.104.113" title="Special:Contributions/71.228.104.113" class="mw-userlink">71.228.104.113</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.228.104.113&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.228.104.113 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,910 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,910 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Suggested_Roles" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=8810&amp;undo=9142" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=8810" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=8810&amp;oldid=8671" title="Cerberus">prev</a>)</span><input type="radio" value="8810" name="oldid" id="mw-oldid-8810" /><input type="radio" value="8810" name="diff" id="mw-diff-8810" /> <a href="/index.php?title=Cerberus&amp;oldid=8810" title="Cerberus" class="mw-changeslist-date">23:18, 28 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/24.218.243.149" title="Special:Contributions/24.218.243.149" class="mw-userlink">24.218.243.149</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:24.218.243.149&amp;action=edit&amp;redlink=1" class="new" title="User talk:24.218.243.149 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,909 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,909 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Combat" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=8671&amp;undo=8810" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=8671" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=8671&amp;oldid=8426" title="Cerberus">prev</a>)</span><input type="radio" value="8671" name="oldid" id="mw-oldid-8671" /><input type="radio" value="8671" name="diff" id="mw-diff-8671" /> <a href="/index.php?title=Cerberus&amp;oldid=8671" title="Cerberus" class="mw-changeslist-date">14:39, 18 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,898 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,898 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Updated Cerberus specs.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=8426&amp;undo=8671" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=8426" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=8426&amp;oldid=8236" title="Cerberus">prev</a>)</span><input type="radio" value="8426" name="oldid" id="mw-oldid-8426" /><input type="radio" value="8426" name="diff" id="mw-diff-8426" /> <a href="/index.php?title=Cerberus&amp;oldid=8426" title="Cerberus" class="mw-changeslist-date">18:53, 3 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/62.107.32.49" title="Special:Contributions/62.107.32.49" class="mw-userlink">62.107.32.49</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:62.107.32.49&amp;action=edit&amp;redlink=1" class="new" title="User talk:62.107.32.49 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,900 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,900 bytes after change">(+495)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Suggested_Roles" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=8236&amp;undo=8426" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=8236" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=8236&amp;oldid=7077" title="Cerberus">prev</a>)</span><input type="radio" value="8236" name="oldid" id="mw-oldid-8236" /><input type="radio" value="8236" name="diff" id="mw-diff-8236" /> <a href="/index.php?title=Cerberus&amp;oldid=8236" title="Cerberus" class="mw-changeslist-date">03:08, 3 January 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.193.145.233" title="Special:Contributions/71.193.145.233" class="mw-userlink">71.193.145.233</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.193.145.233&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.193.145.233 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,405 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,405 bytes after change">(-42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Combat" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span>  Better grammar.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=7077&amp;undo=8236" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=7077" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=7077&amp;oldid=6367" title="Cerberus">prev</a>)</span><input type="radio" value="7077" name="oldid" id="mw-oldid-7077" /><input type="radio" value="7077" name="diff" id="mw-diff-7077" /> <a href="/index.php?title=Cerberus&amp;oldid=7077" title="Cerberus" class="mw-changeslist-date">17:21, 20 August 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.57.70.242" title="Special:Contributions/87.57.70.242" class="mw-userlink">87.57.70.242</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.57.70.242&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.57.70.242 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,447 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,447 bytes after change">(+164)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Combat" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=6367&amp;undo=7077" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=6367" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=6367&amp;oldid=6366" title="Cerberus">prev</a>)</span><input type="radio" value="6367" name="oldid" id="mw-oldid-6367" /><input type="radio" value="6367" name="diff" id="mw-diff-6367" /> <a href="/index.php?title=Cerberus&amp;oldid=6367" title="Cerberus" class="mw-changeslist-date">02:16, 26 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/216.171.23.100" title="Special:Contributions/216.171.23.100" class="mw-userlink">216.171.23.100</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:216.171.23.100&amp;action=edit&amp;redlink=1" class="new" title="User talk:216.171.23.100 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,283 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,283 bytes after change">(-12)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Availability" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=6366&amp;undo=6367" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=6366" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=6366&amp;oldid=4387" title="Cerberus">prev</a>)</span><input type="radio" value="6366" name="oldid" id="mw-oldid-6366" /><input type="radio" value="6366" name="diff" id="mw-diff-6366" /> <a href="/index.php?title=Cerberus&amp;oldid=6366" title="Cerberus" class="mw-changeslist-date">09:01, 25 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.121.193.253" title="Special:Contributions/212.121.193.253" class="mw-userlink">212.121.193.253</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.121.193.253&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.121.193.253 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,295 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,295 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Availability" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=4387&amp;undo=6366" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=4387" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=4387&amp;oldid=4384" title="Cerberus">prev</a>)</span><input type="radio" value="4387" name="oldid" id="mw-oldid-4387" /><input type="radio" value="4387" name="diff" id="mw-diff-4387" /> <a href="/index.php?title=Cerberus&amp;oldid=4387" title="Cerberus" class="mw-changeslist-date">07:52, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,251 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,251 bytes after change">(+46)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#See_Also" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=4384&amp;undo=4387" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=4384" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=4384&amp;oldid=4383" title="Cerberus">prev</a>)</span><input type="radio" value="4384" name="oldid" id="mw-oldid-4384" /><input type="radio" value="4384" name="diff" id="mw-diff-4384" /> <a href="/index.php?title=Cerberus&amp;oldid=4384" title="Cerberus" class="mw-changeslist-date">07:37, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,205 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,205 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#See_Also" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=4383&amp;undo=4384" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=4383" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=4383&amp;oldid=3225" title="Cerberus">prev</a>)</span><input type="radio" value="4383" name="oldid" id="mw-oldid-4383" /><input type="radio" value="4383" name="diff" id="mw-diff-4383" /> <a href="/index.php?title=Cerberus&amp;oldid=4383" title="Cerberus" class="mw-changeslist-date">07:37, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,179 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,179 bytes after change">(+101)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Suggested_Roles" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=3225&amp;undo=4383" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=3225" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=3225&amp;oldid=3223" title="Cerberus">prev</a>)</span><input type="radio" value="3225" name="oldid" id="mw-oldid-3225" /><input type="radio" value="3225" name="diff" id="mw-diff-3225" /> <a href="/index.php?title=Cerberus&amp;oldid=3225" title="Cerberus" class="mw-changeslist-date">10:23, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,078 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,078 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#See_Also" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=3223&amp;undo=3225" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=3223" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=3223&amp;oldid=3222" title="Cerberus">prev</a>)</span><input type="radio" value="3223" name="oldid" id="mw-oldid-3223" /><input type="radio" value="3223" name="diff" id="mw-diff-3223" /> <a href="/index.php?title=Cerberus&amp;oldid=3223" title="Cerberus" class="mw-changeslist-date">10:14, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,051 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,051 bytes after change">(+256)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#See_Also" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=3222&amp;undo=3223" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=3222" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=3222&amp;oldid=3221" title="Cerberus">prev</a>)</span><input type="radio" value="3222" name="oldid" id="mw-oldid-3222" /><input type="radio" value="3222" name="diff" id="mw-diff-3222" /> <a href="/index.php?title=Cerberus&amp;oldid=3222" title="Cerberus" class="mw-changeslist-date">10:13, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,795 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,795 bytes after change">(+95)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Combat" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=3221&amp;undo=3222" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=3221" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=3221&amp;oldid=3215" title="Cerberus">prev</a>)</span><input type="radio" value="3221" name="oldid" id="mw-oldid-3221" /><input type="radio" value="3221" name="diff" id="mw-diff-3221" /> <a href="/index.php?title=Cerberus&amp;oldid=3221" title="Cerberus" class="mw-changeslist-date">10:13, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,700 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,700 bytes after change">(+116)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Physical_Characteristics" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=3215&amp;undo=3221" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=3215" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=3215&amp;oldid=2759" title="Cerberus">prev</a>)</span><input type="radio" value="3215" name="oldid" id="mw-oldid-3215" /><input type="radio" value="3215" name="diff" id="mw-diff-3215" /> <a href="/index.php?title=Cerberus&amp;oldid=3215" title="Cerberus" class="mw-changeslist-date">10:05, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,584 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,584 bytes after change">(+266)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Cerberus#Overview" title="Cerberus">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=2759&amp;undo=3215" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=2759" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=2759&amp;oldid=2682" title="Cerberus">prev</a>)</span><input type="radio" value="2759" name="oldid" id="mw-oldid-2759" /><input type="radio" value="2759" name="diff" id="mw-diff-2759" /> <a href="/index.php?title=Cerberus&amp;oldid=2759" title="Cerberus" class="mw-changeslist-date">18:18, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,318 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,318 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(rejigged Argonshipcategory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=2682&amp;undo=2759" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=2682" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=2682&amp;oldid=764" title="Cerberus">prev</a>)</span><input type="radio" value="2682" name="oldid" id="mw-oldid-2682" /><input type="radio" value="2682" name="diff" id="mw-diff-2682" /> <a href="/index.php?title=Cerberus&amp;oldid=2682" title="Cerberus" class="mw-changeslist-date">09:55, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,314 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,314 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=764&amp;undo=2682" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=764" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=764&amp;oldid=673" title="Cerberus">prev</a>)</span><input type="radio" value="764" name="oldid" id="mw-oldid-764" /><input type="radio" value="764" name="diff" id="mw-diff-764" /> <a href="/index.php?title=Cerberus&amp;oldid=764" title="Cerberus" class="mw-changeslist-date">14:22, 13 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,296 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,296 bytes after change">(+341)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(data fill, gunslots)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=673&amp;undo=764" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=673" title="Cerberus">cur</a> | <a href="/index.php?title=Cerberus&amp;diff=673&amp;oldid=668" title="Cerberus">prev</a>)</span><input type="radio" value="673" name="oldid" id="mw-oldid-673" /><input type="radio" value="673" name="diff" id="mw-diff-673" /> <a href="/index.php?title=Cerberus&amp;oldid=673" title="Cerberus" class="mw-changeslist-date">13:18, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,955 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,955 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(dockbay)</span> (<span class="mw-history-undo"><a href="/index.php?title=Cerberus&amp;action=edit&amp;undoafter=668&amp;undo=673" title="Cerberus">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Cerberus&amp;diff=16447&amp;oldid=668" title="Cerberus">cur</a> | prev)</span><input type="radio" value="668" name="oldid" id="mw-oldid-668" /><input type="radio" value="668" name="diff" id="mw-diff-668" /> <a href="/index.php?title=Cerberus&amp;oldid=668" title="Cerberus" class="mw-changeslist-date">13:10, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,927 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,927 bytes after change">(+1,927)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(created from argon ship list data)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Cerberus">http://x3wiki.com/index.php/Cerberus</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Cerberus" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Cerberus&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Cerberus&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Cerberus&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Cerberus&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Cerberus&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Cerberus" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Cerberus" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Cerberus&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Cerberus&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.327 secs. --></body></html>