<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Skiron" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Skiron","wgTitle":"Skiron","wgCurRevisionId":16530,"wgRevisionId":0,"wgArticleId":609,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Skiron","wgRelevantArticleId":609,"wgRequestId":"Wllo4lkfZokAACHQh8IAAAAF","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Skiron&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Skiron&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Skiron&quot; Atom feed" href="/index.php?title=Skiron&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Skiron rootpage-Skiron skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Skiron"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Skiron" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Skiron" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Skiron" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=16294" title="Skiron">prev</a>)</span><input type="radio" value="16530" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16530" checked="checked" name="diff" id="mw-diff-16530" /> <a href="/index.php?title=Skiron&amp;oldid=16530" title="Skiron" class="mw-changeslist-date">21:29, 4 November 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Heyjustarooni (page does not exist)">Heyjustarooni</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new" title="User talk:Heyjustarooni (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Heyjustarooni" title="Special:Contributions/Heyjustarooni">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,618 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,618 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Updated hull per AP stats.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=16294&amp;undo=16530" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=16294" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=16294&amp;oldid=16293" title="Skiron">prev</a>)</span><input type="radio" value="16294" checked="checked" name="oldid" id="mw-oldid-16294" /><input type="radio" value="16294" name="diff" id="mw-diff-16294" /> <a href="/index.php?title=Skiron&amp;oldid=16294" title="Skiron" class="mw-changeslist-date">17:53, 22 June 2014</a>‎ <span class='history-user'><a href="/index.php/User:Kerberizer" title="User:Kerberizer" class="mw-userlink">Kerberizer</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Kerberizer&amp;action=edit&amp;redlink=1" class="new" title="User talk:Kerberizer (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Kerberizer" title="Special:Contributions/Kerberizer">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,603 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,603 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Combat" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span> PBE --&gt; PRG</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=16293&amp;undo=16294" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=16293" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=16293&amp;oldid=16196" title="Skiron">prev</a>)</span><input type="radio" value="16293" name="oldid" id="mw-oldid-16293" /><input type="radio" value="16293" name="diff" id="mw-diff-16293" /> <a href="/index.php?title=Skiron&amp;oldid=16293" title="Skiron" class="mw-changeslist-date">17:46, 22 June 2014</a>‎ <span class='history-user'><a href="/index.php/User:Kerberizer" title="User:Kerberizer" class="mw-userlink">Kerberizer</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Kerberizer&amp;action=edit&amp;redlink=1" class="new" title="User talk:Kerberizer (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Kerberizer" title="Special:Contributions/Kerberizer">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,603 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,603 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fill in missing Shieldslots)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=16196&amp;undo=16293" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=16196" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=16196&amp;oldid=15380" title="Skiron">prev</a>)</span><input type="radio" value="16196" name="oldid" id="mw-oldid-16196" /><input type="radio" value="16196" name="diff" id="mw-diff-16196" /> <a href="/index.php?title=Skiron&amp;oldid=16196" title="Skiron" class="mw-changeslist-date">07:23, 10 April 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Kalil&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Kalil (page does not exist)">Kalil</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Kalil&amp;action=edit&amp;redlink=1" class="new" title="User talk:Kalil (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Kalil" title="Special:Contributions/Kalil">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,602 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,602 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added rep requirement)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=15380&amp;undo=16196" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=15380" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=15380&amp;oldid=13617" title="Skiron">prev</a>)</span><input type="radio" value="15380" name="oldid" id="mw-oldid-15380" /><input type="radio" value="15380" name="diff" id="mw-diff-15380" /> <a href="/index.php?title=Skiron&amp;oldid=15380" title="Skiron" class="mw-changeslist-date">03:25, 1 March 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/69.132.145.168" title="Special:Contributions/69.132.145.168" class="mw-userlink mw-anonuserlink">69.132.145.168</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:69.132.145.168&amp;action=edit&amp;redlink=1" class="new" title="User talk:69.132.145.168 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,578 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,578 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=13617&amp;undo=15380" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=13617" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=13617&amp;oldid=11783" title="Skiron">prev</a>)</span><input type="radio" value="13617" name="oldid" id="mw-oldid-13617" /><input type="radio" value="13617" name="diff" id="mw-diff-13617" /> <a href="/index.php?title=Skiron&amp;oldid=13617" title="Skiron" class="mw-changeslist-date">03:56, 24 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,579 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,579 bytes after change">(+12)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(AP Laser Recharge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=11783&amp;undo=13617" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=11783" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=11783&amp;oldid=11782" title="Skiron">prev</a>)</span><input type="radio" value="11783" name="oldid" id="mw-oldid-11783" /><input type="radio" value="11783" name="diff" id="mw-diff-11783" /> <a href="/index.php?title=Skiron&amp;oldid=11783" title="Skiron" class="mw-changeslist-date">16:16, 23 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,567 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,567 bytes after change">(+75)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Overview" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=11782&amp;undo=11783" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=11782" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=11782&amp;oldid=11259" title="Skiron">prev</a>)</span><input type="radio" value="11782" name="oldid" id="mw-oldid-11782" /><input type="radio" value="11782" name="diff" id="mw-diff-11782" /> <a href="/index.php?title=Skiron&amp;oldid=11782" title="Skiron" class="mw-changeslist-date">16:15, 23 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,492 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,492 bytes after change">(+79)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Combat" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=11259&amp;undo=11782" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=11259" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=11259&amp;oldid=10703" title="Skiron">prev</a>)</span><input type="radio" value="11259" name="oldid" id="mw-oldid-11259" /><input type="radio" value="11259" name="diff" id="mw-diff-11259" /> <a href="/index.php?title=Skiron&amp;oldid=11259" title="Skiron" class="mw-changeslist-date">19:56, 10 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,413 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,413 bytes after change">(+473)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=10703&amp;undo=11259" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=10703" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=10703&amp;oldid=10506" title="Skiron">prev</a>)</span><input type="radio" value="10703" name="oldid" id="mw-oldid-10703" /><input type="radio" value="10703" name="diff" id="mw-diff-10703" /> <a href="/index.php?title=Skiron&amp;oldid=10703" title="Skiron" class="mw-changeslist-date">17:30, 16 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,940 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,940 bytes after change">(-288)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M6+ template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=10506&amp;undo=10703" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=10506" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=10506&amp;oldid=9619" title="Skiron">prev</a>)</span><input type="radio" value="10506" name="oldid" id="mw-oldid-10506" /><input type="radio" value="10506" name="diff" id="mw-diff-10506" /> <a href="/index.php?title=Skiron&amp;oldid=10506" title="Skiron" class="mw-changeslist-date">06:36, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,228 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,228 bytes after change">(+571)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=9619&amp;undo=10506" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=9619" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=9619&amp;oldid=9367" title="Skiron">prev</a>)</span><input type="radio" value="9619" name="oldid" id="mw-oldid-9619" /><input type="radio" value="9619" name="diff" id="mw-diff-9619" /> <a href="/index.php?title=Skiron&amp;oldid=9619" title="Skiron" class="mw-changeslist-date">08:35, 4 October 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Bad_Debt&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Bad Debt (page does not exist)">Bad Debt</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bad_Debt&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bad Debt (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bad_Debt" title="Special:Contributions/Bad Debt">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,657 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,657 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Physical_Characteristics" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics: </span> Oberleutnant Grammatik</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=9367&amp;undo=9619" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=9367" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=9367&amp;oldid=9017" title="Skiron">prev</a>)</span><input type="radio" value="9367" name="oldid" id="mw-oldid-9367" /><input type="radio" value="9367" name="diff" id="mw-diff-9367" /> <a href="/index.php?title=Skiron&amp;oldid=9367" title="Skiron" class="mw-changeslist-date">09:02, 3 July 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/193.105.85.4" title="Special:Contributions/193.105.85.4" class="mw-userlink mw-anonuserlink">193.105.85.4</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:193.105.85.4&amp;action=edit&amp;redlink=1" class="new" title="User talk:193.105.85.4 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,658 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,658 bytes after change">(-7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Combat" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span> grammar/syntax/spelling fixes</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=9017&amp;undo=9367" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=9017" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=9017&amp;oldid=8352" title="Skiron">prev</a>)</span><input type="radio" value="9017" name="oldid" id="mw-oldid-9017" /><input type="radio" value="9017" name="diff" id="mw-diff-9017" /> <a href="/index.php?title=Skiron&amp;oldid=9017" title="Skiron" class="mw-changeslist-date">05:40, 15 April 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/76.171.148.108" title="Special:Contributions/76.171.148.108" class="mw-userlink mw-anonuserlink">76.171.148.108</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:76.171.148.108&amp;action=edit&amp;redlink=1" class="new" title="User talk:76.171.148.108 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,665 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,665 bytes after change">(-21)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Turret names - consistency with other M6+ pages)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=8352&amp;undo=9017" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=8352" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=8352&amp;oldid=6885" title="Skiron">prev</a>)</span><input type="radio" value="8352" name="oldid" id="mw-oldid-8352" /><input type="radio" value="8352" name="diff" id="mw-diff-8352" /> <a href="/index.php?title=Skiron&amp;oldid=8352" title="Skiron" class="mw-changeslist-date">05:22, 22 January 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/174.60.54.189" title="Special:Contributions/174.60.54.189" class="mw-userlink mw-anonuserlink">174.60.54.189</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:174.60.54.189&amp;action=edit&amp;redlink=1" class="new" title="User talk:174.60.54.189 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,686 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,686 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Background" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Background</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6885&amp;undo=8352" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6885" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6885&amp;oldid=6460" title="Skiron">prev</a>)</span><input type="radio" value="6885" name="oldid" id="mw-oldid-6885" /><input type="radio" value="6885" name="diff" id="mw-diff-6885" /> <a href="/index.php?title=Skiron&amp;oldid=6885" title="Skiron" class="mw-changeslist-date">16:16, 11 August 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/75.86.195.123" title="Special:Contributions/75.86.195.123" class="mw-userlink mw-anonuserlink">75.86.195.123</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:75.86.195.123&amp;action=edit&amp;redlink=1" class="new" title="User talk:75.86.195.123 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,686 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,686 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Suggested_Roles" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6460&amp;undo=6885" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6460" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6460&amp;oldid=6459" title="Skiron">prev</a>)</span><input type="radio" value="6460" name="oldid" id="mw-oldid-6460" /><input type="radio" value="6460" name="diff" id="mw-diff-6460" /> <a href="/index.php?title=Skiron&amp;oldid=6460" title="Skiron" class="mw-changeslist-date">08:53, 30 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.137.235.207" title="Special:Contributions/71.137.235.207" class="mw-userlink mw-anonuserlink">71.137.235.207</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.137.235.207&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.137.235.207 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,681 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,681 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Suggested_Roles" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6459&amp;undo=6460" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6459" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6459&amp;oldid=6458" title="Skiron">prev</a>)</span><input type="radio" value="6459" name="oldid" id="mw-oldid-6459" /><input type="radio" value="6459" name="diff" id="mw-diff-6459" /> <a href="/index.php?title=Skiron&amp;oldid=6459" title="Skiron" class="mw-changeslist-date">08:52, 30 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.137.235.207" title="Special:Contributions/71.137.235.207" class="mw-userlink mw-anonuserlink">71.137.235.207</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.137.235.207&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.137.235.207 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,677 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,677 bytes after change">(-29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Suggested_Roles" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6458&amp;undo=6459" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6458" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6458&amp;oldid=6457" title="Skiron">prev</a>)</span><input type="radio" value="6458" name="oldid" id="mw-oldid-6458" /><input type="radio" value="6458" name="diff" id="mw-diff-6458" /> <a href="/index.php?title=Skiron&amp;oldid=6458" title="Skiron" class="mw-changeslist-date">08:52, 30 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.137.235.207" title="Special:Contributions/71.137.235.207" class="mw-userlink mw-anonuserlink">71.137.235.207</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.137.235.207&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.137.235.207 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,706 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,706 bytes after change">(+49)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Suggested_Roles" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6457&amp;undo=6458" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6457" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6457&amp;oldid=6456" title="Skiron">prev</a>)</span><input type="radio" value="6457" name="oldid" id="mw-oldid-6457" /><input type="radio" value="6457" name="diff" id="mw-diff-6457" /> <a href="/index.php?title=Skiron&amp;oldid=6457" title="Skiron" class="mw-changeslist-date">08:51, 30 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.137.235.207" title="Special:Contributions/71.137.235.207" class="mw-userlink mw-anonuserlink">71.137.235.207</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.137.235.207&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.137.235.207 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,657 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,657 bytes after change">(+111)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6456&amp;undo=6457" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6456" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6456&amp;oldid=6444" title="Skiron">prev</a>)</span><input type="radio" value="6456" name="oldid" id="mw-oldid-6456" /><input type="radio" value="6456" name="diff" id="mw-diff-6456" /> <a href="/index.php?title=Skiron&amp;oldid=6456" title="Skiron" class="mw-changeslist-date">08:48, 30 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.137.235.207" title="Special:Contributions/71.137.235.207" class="mw-userlink mw-anonuserlink">71.137.235.207</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.137.235.207&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.137.235.207 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,546 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,546 bytes after change">(+1,308)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=6444&amp;undo=6456" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=6444" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=6444&amp;oldid=4707" title="Skiron">prev</a>)</span><input type="radio" value="6444" name="oldid" id="mw-oldid-6444" /><input type="radio" value="6444" name="diff" id="mw-diff-6444" /> <a href="/index.php?title=Skiron&amp;oldid=6444" title="Skiron" class="mw-changeslist-date">16:17, 25 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/90.200.27.196" title="Special:Contributions/90.200.27.196" class="mw-userlink mw-anonuserlink">90.200.27.196</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:90.200.27.196&amp;action=edit&amp;redlink=1" class="new" title="User talk:90.200.27.196 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,238 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,238 bytes after change">(+273)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Physical_Characteristics" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=4707&amp;undo=6444" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=4707" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=4707&amp;oldid=4703" title="Skiron">prev</a>)</span><input type="radio" value="4707" name="oldid" id="mw-oldid-4707" /><input type="radio" value="4707" name="diff" id="mw-diff-4707" /> <a href="/index.php?title=Skiron&amp;oldid=4707" title="Skiron" class="mw-changeslist-date">19:00, 30 December 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,965 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,965 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(gunslots)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=4703&amp;undo=4707" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=4703" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=4703&amp;oldid=4420" title="Skiron">prev</a>)</span><input type="radio" value="4703" name="oldid" id="mw-oldid-4703" /><input type="radio" value="4703" name="diff" id="mw-diff-4703" /> <a href="/index.php?title=Skiron&amp;oldid=4703" title="Skiron" class="mw-changeslist-date">13:05, 30 December 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/173.48.245.158" title="Special:Contributions/173.48.245.158" class="mw-userlink mw-anonuserlink">173.48.245.158</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:173.48.245.158&amp;action=edit&amp;redlink=1" class="new" title="User talk:173.48.245.158 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,960 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,960 bytes after change">(+57)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=4420&amp;undo=4703" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=4420" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=4420&amp;oldid=4419" title="Skiron">prev</a>)</span><input type="radio" value="4420" name="oldid" id="mw-oldid-4420" /><input type="radio" value="4420" name="diff" id="mw-diff-4420" /> <a href="/index.php?title=Skiron&amp;oldid=4420" title="Skiron" class="mw-changeslist-date">15:26, 28 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,903 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,903 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#See_Also" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=4419&amp;undo=4420" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=4419" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=4419&amp;oldid=3559" title="Skiron">prev</a>)</span><input type="radio" value="4419" name="oldid" id="mw-oldid-4419" /><input type="radio" value="4419" name="diff" id="mw-diff-4419" /> <a href="/index.php?title=Skiron&amp;oldid=4419" title="Skiron" class="mw-changeslist-date">15:25, 28 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,876 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,876 bytes after change">(-6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Combat" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=3559&amp;undo=4419" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=3559" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=3559&amp;oldid=3558" title="Skiron">prev</a>)</span><input type="radio" value="3559" name="oldid" id="mw-oldid-3559" /><input type="radio" value="3559" name="diff" id="mw-diff-3559" /> <a href="/index.php?title=Skiron&amp;oldid=3559" title="Skiron" class="mw-changeslist-date">00:37, 22 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,882 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,882 bytes after change">(+254)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#See_Also" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=3558&amp;undo=3559" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=3558" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=3558&amp;oldid=3557" title="Skiron">prev</a>)</span><input type="radio" value="3558" name="oldid" id="mw-oldid-3558" /><input type="radio" value="3558" name="diff" id="mw-diff-3558" /> <a href="/index.php?title=Skiron&amp;oldid=3558" title="Skiron" class="mw-changeslist-date">00:37, 22 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,628 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,628 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Availability" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=3557&amp;undo=3558" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=3557" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=3557&amp;oldid=3555" title="Skiron">prev</a>)</span><input type="radio" value="3557" name="oldid" id="mw-oldid-3557" /><input type="radio" value="3557" name="diff" id="mw-diff-3557" /> <a href="/index.php?title=Skiron&amp;oldid=3557" title="Skiron" class="mw-changeslist-date">00:36, 22 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,621 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,621 bytes after change">(+170)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Availability" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=3555&amp;undo=3557" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=3555" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=3555&amp;oldid=3553" title="Skiron">prev</a>)</span><input type="radio" value="3555" name="oldid" id="mw-oldid-3555" /><input type="radio" value="3555" name="diff" id="mw-diff-3555" /> <a href="/index.php?title=Skiron&amp;oldid=3555" title="Skiron" class="mw-changeslist-date">00:35, 22 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,451 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,451 bytes after change">(+582)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Combat" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=3553&amp;undo=3555" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=3553" title="Skiron">cur</a> | <a href="/index.php?title=Skiron&amp;diff=3553&amp;oldid=2081" title="Skiron">prev</a>)</span><input type="radio" value="3553" name="oldid" id="mw-oldid-3553" /><input type="radio" value="3553" name="diff" id="mw-diff-3553" /> <a href="/index.php?title=Skiron&amp;oldid=3553" title="Skiron" class="mw-changeslist-date">00:31, 22 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,869 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,869 bytes after change">(+244)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Skiron#Overview" title="Skiron">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Skiron&amp;action=edit&amp;undoafter=2081&amp;undo=3553" title="Skiron">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Skiron&amp;diff=16530&amp;oldid=2081" title="Skiron">cur</a> | prev)</span><input type="radio" value="2081" name="oldid" id="mw-oldid-2081" /><input type="radio" value="2081" name="diff" id="mw-diff-2081" /> <a href="/index.php?title=Skiron&amp;oldid=2081" title="Skiron" class="mw-changeslist-date">19:55, 5 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,625 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,625 bytes after change">(+1,625)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(start)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Skiron">http://www.x3wiki.com/index.php/Skiron</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Skiron" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Skiron&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Skiron&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Skiron&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Skiron&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Skiron&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Skiron" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Skiron" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Skiron&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Skiron&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":123});});</script></body></html>
