<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Legend's Home" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Legend's_Home","wgTitle":"Legend's Home","wgCurRevisionId":16086,"wgRevisionId":0,"wgArticleId":222,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Legend's_Home","wgRelevantArticleId":222,"wgRequestId":"WUYaqVkfZokAAAmrC8UAAAAQ","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Legend%27s_Home&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Legend%27s_Home&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Legend's Home&quot; Atom feed" href="/index.php?title=Legend%27s_Home&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Legend_s_Home rootpage-Legend_s_Home skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Legend's Home"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Legend%27s+Home" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Legend's_Home" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Legend's_Home" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=16085" title="Legend's Home">prev</a>)</span><input type="radio" value="16086" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16086" checked="checked" name="diff" id="mw-diff-16086" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=16086" title="Legend's Home" class="mw-changeslist-date">00:12, 17 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,406 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,406 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=16085&amp;undo=16086" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=16085" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=16085&amp;oldid=16072" title="Legend's Home">prev</a>)</span><input type="radio" value="16085" checked="checked" name="oldid" id="mw-oldid-16085" /><input type="radio" value="16085" name="diff" id="mw-diff-16085" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=16085" title="Legend's Home" class="mw-changeslist-date">00:12, 17 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,400 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,400 bytes after change">(+107)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability: </span> add description</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=16072&amp;undo=16085" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=16072" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=16072&amp;oldid=15841" title="Legend's Home">prev</a>)</span><input type="radio" value="16072" name="oldid" id="mw-oldid-16072" /><input type="radio" value="16072" name="diff" id="mw-diff-16072" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=16072" title="Legend's Home" class="mw-changeslist-date">11:30, 16 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,293 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,293 bytes after change">(-268)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability: </span> fix tables</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=15841&amp;undo=16072" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=15841" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=15841&amp;oldid=15655" title="Legend's Home">prev</a>)</span><input type="radio" value="15841" name="oldid" id="mw-oldid-15841" /><input type="radio" value="15841" name="diff" id="mw-diff-15841" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=15841" title="Legend's Home" class="mw-changeslist-date">18:59, 6 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,561 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,561 bytes after change">(+349)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability: </span> add available notes</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=15655&amp;undo=15841" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=15655" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=15655&amp;oldid=15251" title="Legend's Home">prev</a>)</span><input type="radio" value="15655" name="oldid" id="mw-oldid-15655" /><input type="radio" value="15655" name="diff" id="mw-diff-15655" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=15655" title="Legend's Home" class="mw-changeslist-date">16:04, 5 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,212 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,212 bytes after change">(+400)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability: </span> use new shipyard templates</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=15251&amp;undo=15655" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=15251" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=15251&amp;oldid=15218" title="Legend's Home">prev</a>)</span><input type="radio" value="15251" name="oldid" id="mw-oldid-15251" /><input type="radio" value="15251" name="diff" id="mw-diff-15251" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=15251" title="Legend's Home" class="mw-changeslist-date">12:45, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,812 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,812 bytes after change">(-50)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 15218 by <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">Knighster35</a> (<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=15218&amp;undo=15251" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=15218" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=15218&amp;oldid=14831" title="Legend's Home">prev</a>)</span><input type="radio" value="15218" name="oldid" id="mw-oldid-15218" /><input type="radio" value="15218" name="diff" id="mw-diff-15218" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=15218" title="Legend's Home" class="mw-changeslist-date">12:12, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,862 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,862 bytes after change">(+50)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Gateblock2 update)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=14831&amp;undo=15218" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=14831" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=14831&amp;oldid=14761" title="Legend's Home">prev</a>)</span><input type="radio" value="14831" name="oldid" id="mw-oldid-14831" /><input type="radio" value="14831" name="diff" id="mw-diff-14831" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=14831" title="Legend's Home" class="mw-changeslist-date">16:17, 26 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,812 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,812 bytes after change">(-15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Asteroids" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Asteroids: </span> remove coma</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=14761&amp;undo=14831" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=14761" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=14761&amp;oldid=14511" title="Legend's Home">prev</a>)</span><input type="radio" value="14761" name="oldid" id="mw-oldid-14761" /><input type="radio" value="14761" name="diff" id="mw-diff-14761" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=14761" title="Legend's Home" class="mw-changeslist-date">12:25, 26 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,827 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,827 bytes after change">(-170)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Asteroids" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Asteroids: </span> reformat table with asteroid table templates</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=14511&amp;undo=14761" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=14511" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=14511&amp;oldid=13642" title="Legend's Home">prev</a>)</span><input type="radio" value="14511" name="oldid" id="mw-oldid-14511" /><input type="radio" value="14511" name="diff" id="mw-diff-14511" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=14511" title="Legend's Home" class="mw-changeslist-date">15:32, 24 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,997 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,997 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(setup column title)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=13642&amp;undo=14511" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=13642" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=13642&amp;oldid=12492" title="Legend's Home">prev</a>)</span><input type="radio" value="13642" name="oldid" id="mw-oldid-13642" /><input type="radio" value="13642" name="diff" id="mw-diff-13642" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=13642" title="Legend's Home" class="mw-changeslist-date">15:34, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,972 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,972 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=12492&amp;undo=13642" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=12492" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=12492&amp;oldid=12466" title="Legend's Home">prev</a>)</span><input type="radio" value="12492" name="oldid" id="mw-oldid-12492" /><input type="radio" value="12492" name="diff" id="mw-diff-12492" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=12492" title="Legend's Home" class="mw-changeslist-date">01:45, 3 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,954 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="5,954 bytes after change">(-2,342)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=12466&amp;undo=12492" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=12466" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=12466&amp;oldid=12461" title="Legend's Home">prev</a>)</span><input type="radio" value="12466" name="oldid" id="mw-oldid-12466" /><input type="radio" value="12466" name="diff" id="mw-diff-12466" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=12466" title="Legend's Home" class="mw-changeslist-date">23:52, 2 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,296 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="8,296 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Legend%27s_Home#Shipyard_Availability" title="Legend's Home">→</a>‎<span dir="auto"><span class="autocomment">Shipyard Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=12461&amp;undo=12466" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=12461" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=12461&amp;oldid=11413" title="Legend's Home">prev</a>)</span><input type="radio" value="12461" name="oldid" id="mw-oldid-12461" /><input type="radio" value="12461" name="diff" id="mw-diff-12461" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=12461" title="Legend's Home" class="mw-changeslist-date">23:50, 2 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,298 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="8,298 bytes after change">(+6,638)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added Shipyard Availability list (:D) + OTAS Shipyard)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=11413&amp;undo=12461" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=11413" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=11413&amp;oldid=9173" title="Legend's Home">prev</a>)</span><input type="radio" value="11413" name="oldid" id="mw-oldid-11413" /><input type="radio" value="11413" name="diff" id="mw-diff-11413" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=11413" title="Legend's Home" class="mw-changeslist-date">09:00, 15 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,660 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,660 bytes after change">(+515)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added asteroids and gate destination for AP)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9173&amp;undo=11413" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9173" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9173&amp;oldid=9172" title="Legend's Home">prev</a>)</span><input type="radio" value="9173" name="oldid" id="mw-oldid-9173" /><input type="radio" value="9173" name="diff" id="mw-diff-9173" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9173" title="Legend's Home" class="mw-changeslist-date">05:38, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,145 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,145 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9172&amp;undo=9173" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9172" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9172&amp;oldid=9171" title="Legend's Home">prev</a>)</span><input type="radio" value="9172" name="oldid" id="mw-oldid-9172" /><input type="radio" value="9172" name="diff" id="mw-diff-9172" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9172" title="Legend's Home" class="mw-changeslist-date">05:36, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,141 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,141 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9171&amp;undo=9172" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9171" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9171&amp;oldid=9170" title="Legend's Home">prev</a>)</span><input type="radio" value="9171" name="oldid" id="mw-oldid-9171" /><input type="radio" value="9171" name="diff" id="mw-diff-9171" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9171" title="Legend's Home" class="mw-changeslist-date">05:35, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,127 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,127 bytes after change">(-16)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9170&amp;undo=9171" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9170" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9170&amp;oldid=9169" title="Legend's Home">prev</a>)</span><input type="radio" value="9170" name="oldid" id="mw-oldid-9170" /><input type="radio" value="9170" name="diff" id="mw-diff-9170" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9170" title="Legend's Home" class="mw-changeslist-date">05:33, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,143 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,143 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9169&amp;undo=9170" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9169" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9169&amp;oldid=9168" title="Legend's Home">prev</a>)</span><input type="radio" value="9169" name="oldid" id="mw-oldid-9169" /><input type="radio" value="9169" name="diff" id="mw-diff-9169" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9169" title="Legend's Home" class="mw-changeslist-date">05:32, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,138 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,138 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Updated and corrected table information.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=9168&amp;undo=9169" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=9168" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=9168&amp;oldid=2853" title="Legend's Home">prev</a>)</span><input type="radio" value="9168" name="oldid" id="mw-oldid-9168" /><input type="radio" value="9168" name="diff" id="mw-diff-9168" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=9168" title="Legend's Home" class="mw-changeslist-date">05:28, 14 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Tommo_455&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Tommo 455 (page does not exist)">Tommo 455</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Tommo_455&amp;action=edit&amp;redlink=1" class="new" title="User talk:Tommo 455 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Tommo_455" title="Special:Contributions/Tommo 455">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,140 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,140 bytes after change">(+382)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added a description to Legends Home)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=2853&amp;undo=9168" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=2853" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=2853&amp;oldid=716" title="Legend's Home">prev</a>)</span><input type="radio" value="2853" name="oldid" id="mw-oldid-2853" /><input type="radio" value="2853" name="diff" id="mw-diff-2853" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=2853" title="Legend's Home" class="mw-changeslist-date">00:48, 14 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(758 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="758 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated gateblock)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=716&amp;undo=2853" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=716" title="Legend's Home">cur</a> | <a href="/index.php?title=Legend%27s_Home&amp;diff=716&amp;oldid=649" title="Legend's Home">prev</a>)</span><input type="radio" value="716" name="oldid" id="mw-oldid-716" /><input type="radio" value="716" name="diff" id="mw-diff-716" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=716" title="Legend's Home" class="mw-changeslist-date">20:58, 7 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(717 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="717 bytes after change">(+193)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(gates)</span> (<span class="mw-history-undo"><a href="/index.php?title=Legend%27s_Home&amp;action=edit&amp;undoafter=649&amp;undo=716" title="Legend's Home">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Legend%27s_Home&amp;diff=16086&amp;oldid=649" title="Legend's Home">cur</a> | prev)</span><input type="radio" value="649" name="oldid" id="mw-oldid-649" /><input type="radio" value="649" name="diff" id="mw-diff-649" /> <a href="/index.php?title=Legend%27s_Home&amp;oldid=649" title="Legend's Home" class="mw-changeslist-date">23:29, 1 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(524 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="524 bytes after change">(+524)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore from cache)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Legend%27s_Home">http://www.x3wiki.com/index.php/Legend%27s_Home</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Legend%27s_Home" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Legend%27s_Home&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Legend%27s_Home&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Legend%27s_Home&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Legend%27s+Home&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Legend%27s+Home&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Legend%27s_Home" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Legend%27s_Home" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Legend%27s_Home&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Legend%27s_Home&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":65});});</script></body></html>
