<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Energy Cells" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Energy_Cells&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Energy_Cells&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Energy Cells&quot; Atom feed" href="/index.php?title=Energy_Cells&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Energy_Cells","wgTitle":"Energy Cells","wgCurRevisionId":13244,"wgRevisionId":0,"wgArticleId":549,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Energy_Cells","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Energy_Cells skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Energy Cells"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Energy+Cells" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Energy_Cells" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=Energy_Cells&amp;dir=prev&amp;action=history" title="Energy Cells" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Energy_Cells&amp;offset=20121007040629&amp;action=history" title="Energy Cells" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=20&amp;action=history" title="Energy Cells" class="mw-numlink">20</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=50&amp;action=history" title="Energy Cells" class="mw-numlink">50</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=100&amp;action=history" title="Energy Cells" class="mw-numlink">100</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=250&amp;action=history" title="Energy Cells" class="mw-numlink">250</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=500&amp;action=history" title="Energy Cells" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Energy_Cells" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=12920" title="Energy Cells">prev</a>)</span><input type="radio" value="13244" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="13244" checked="checked" name="diff" id="mw-diff-13244" /> <a href="/index.php?title=Energy_Cells&amp;oldid=13244" title="Energy Cells" class="mw-changeslist-date">04:02, 25 July 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,955 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,955 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Energy Production Base XL)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=12920&amp;undo=13244" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=12920" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=12920&amp;oldid=11485" title="Energy Cells">prev</a>)</span><input type="radio" value="12920" checked="checked" name="oldid" id="mw-oldid-12920" /><input type="radio" value="12920" name="diff" id="mw-diff-12920" /> <a href="/index.php?title=Energy_Cells&amp;oldid=12920" title="Energy Cells" class="mw-changeslist-date">13:47, 29 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,924 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,924 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(sector travel template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=11485&amp;undo=12920" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=11485" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=11485&amp;oldid=11443" title="Energy Cells">prev</a>)</span><input type="radio" value="11485" name="oldid" id="mw-oldid-11485" /><input type="radio" value="11485" name="diff" id="mw-diff-11485" /> <a href="/index.php?title=Energy_Cells&amp;oldid=11485" title="Energy Cells" class="mw-changeslist-date">18:27, 1 January 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Buu&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Buu (page does not exist)">Buu</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Buu&amp;action=edit&amp;redlink=1" class="new" title="User talk:Buu (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Buu" title="Special:Contributions/Buu">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,890 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,890 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=11443&amp;undo=11485" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=11443" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=11443&amp;oldid=10895" title="Energy Cells">prev</a>)</span><input type="radio" value="11443" name="oldid" id="mw-oldid-11443" /><input type="radio" value="11443" name="diff" id="mw-diff-11443" /> <a href="/index.php?title=Energy_Cells&amp;oldid=11443" title="Energy Cells" class="mw-changeslist-date">13:46, 23 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,891 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,891 bytes after change">(+195)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Energy_Cells#Commentary" title="Energy Cells">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10895&amp;undo=11443" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10895" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10895&amp;oldid=10399" title="Energy Cells">prev</a>)</span><input type="radio" value="10895" name="oldid" id="mw-oldid-10895" /><input type="radio" value="10895" name="diff" id="mw-diff-10895" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10895" title="Energy Cells" class="mw-changeslist-date">14:32, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,696 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,696 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Waretable template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10399&amp;undo=10895" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10399" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10399&amp;oldid=10391" title="Energy Cells">prev</a>)</span><input type="radio" value="10399" name="oldid" id="mw-oldid-10399" /><input type="radio" value="10399" name="diff" id="mw-diff-10399" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10399" title="Energy Cells" class="mw-changeslist-date">00:34, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,682 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,682 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Wraith Missile Production Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10391&amp;undo=10399" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10391" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10391&amp;oldid=10384" title="Energy Cells">prev</a>)</span><input type="radio" value="10391" name="oldid" id="mw-oldid-10391" /><input type="radio" value="10391" name="diff" id="mw-diff-10391" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10391" title="Energy Cells" class="mw-changeslist-date">00:28, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,645 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,645 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Spectre Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10384&amp;undo=10391" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10384" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10384&amp;oldid=10377" title="Energy Cells">prev</a>)</span><input type="radio" value="10384" name="oldid" id="mw-oldid-10384" /><input type="radio" value="10384" name="diff" id="mw-diff-10384" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10384" title="Energy Cells" class="mw-changeslist-date">00:24, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,604 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,604 bytes after change">(+45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Poltergeist Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10377&amp;undo=10384" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10377" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10377&amp;oldid=10368" title="Energy Cells">prev</a>)</span><input type="radio" value="10377" name="oldid" id="mw-oldid-10377" /><input type="radio" value="10377" name="diff" id="mw-diff-10377" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10377" title="Energy Cells" class="mw-changeslist-date">00:19, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,559 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,559 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phantom Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10368&amp;undo=10377" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10368" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10368&amp;oldid=10360" title="Energy Cells">prev</a>)</span><input type="radio" value="10368" name="oldid" id="mw-oldid-10368" /><input type="radio" value="10368" name="diff" id="mw-diff-10368" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10368" title="Energy Cells" class="mw-changeslist-date">00:05, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,518 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,518 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-Matter Mine Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10360&amp;undo=10368" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10360" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10360&amp;oldid=10352" title="Energy Cells">prev</a>)</span><input type="radio" value="10360" name="oldid" id="mw-oldid-10360" /><input type="radio" value="10360" name="diff" id="mw-diff-10360" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10360" title="Energy Cells" class="mw-changeslist-date">23:51, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,485 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,485 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Keris Drone Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10352&amp;undo=10360" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10352" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10352&amp;oldid=10345" title="Energy Cells">prev</a>)</span><input type="radio" value="10352" name="oldid" id="mw-oldid-10352" /><input type="radio" value="10352" name="diff" id="mw-diff-10352" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10352" title="Energy Cells" class="mw-changeslist-date">20:09, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,460 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,460 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ghoul Missile Manufacturing Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10345&amp;undo=10352" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10345" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10345&amp;oldid=10334" title="Energy Cells">prev</a>)</span><input type="radio" value="10345" name="oldid" id="mw-oldid-10345" /><input type="radio" value="10345" name="diff" id="mw-diff-10345" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10345" title="Energy Cells" class="mw-changeslist-date">20:00, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,421 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,421 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; EMP Rifle Assembly Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10334&amp;undo=10345" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10334" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10334&amp;oldid=10326" title="Energy Cells">prev</a>)</span><input type="radio" value="10334" name="oldid" id="mw-oldid-10334" /><input type="radio" value="10334" name="diff" id="mw-diff-10334" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10334" title="Energy Cells" class="mw-changeslist-date">19:47, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,388 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,388 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Disintegrator Rifles Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10326&amp;undo=10334" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10326" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10326&amp;oldid=10316" title="Energy Cells">prev</a>)</span><input type="radio" value="10326" name="oldid" id="mw-oldid-10326" /><input type="radio" value="10326" name="diff" id="mw-diff-10326" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10326" title="Energy Cells" class="mw-changeslist-date">19:42, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,358 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,358 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Rehabilitation Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10316&amp;undo=10326" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10316" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10316&amp;oldid=10304" title="Energy Cells">prev</a>)</span><input type="radio" value="10316" name="oldid" id="mw-oldid-10316" /><input type="radio" value="10316" name="diff" id="mw-diff-10316" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10316" title="Energy Cells" class="mw-changeslist-date">19:03, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,329 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,329 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mobile Drilling System Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10304&amp;undo=10316" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10304" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10304&amp;oldid=10295" title="Energy Cells">prev</a>)</span><input type="radio" value="10304" name="oldid" id="mw-oldid-10304" /><input type="radio" value="10304" name="diff" id="mw-diff-10304" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10304" title="Energy Cells" class="mw-changeslist-date">18:44, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,293 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,293 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Drone Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10295&amp;undo=10304" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10295" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10295&amp;oldid=10282" title="Energy Cells">prev</a>)</span><input type="radio" value="10295" name="oldid" id="mw-oldid-10295" /><input type="radio" value="10295" name="diff" id="mw-diff-10295" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10295" title="Energy Cells" class="mw-changeslist-date">18:37, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,262 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,262 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Cluster Flak Array Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10282&amp;undo=10295" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10282" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10282&amp;oldid=10272" title="Energy Cells">prev</a>)</span><input type="radio" value="10282" name="oldid" id="mw-oldid-10282" /><input type="radio" value="10282" name="diff" id="mw-diff-10282" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10282" title="Energy Cells" class="mw-changeslist-date">12:33, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,232 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,232 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tracker Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10272&amp;undo=10282" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10272" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10272&amp;oldid=10260" title="Energy Cells">prev</a>)</span><input type="radio" value="10272" name="oldid" id="mw-oldid-10272" /><input type="radio" value="10272" name="diff" id="mw-diff-10272" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10272" title="Energy Cells" class="mw-changeslist-date">12:27, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,206 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,206 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tomahawk Missile Manufacturing Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10260&amp;undo=10272" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10260" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10260&amp;oldid=10252" title="Energy Cells">prev</a>)</span><input type="radio" value="10260" name="oldid" id="mw-oldid-10260" /><input type="radio" value="10260" name="diff" id="mw-diff-10260" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10260" title="Energy Cells" class="mw-changeslist-date">12:21, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,164 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,164 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Swarm Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10252&amp;undo=10260" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10252" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10252&amp;oldid=10242" title="Energy Cells">prev</a>)</span><input type="radio" value="10252" name="oldid" id="mw-oldid-10252" /><input type="radio" value="10252" name="diff" id="mw-diff-10252" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10252" title="Energy Cells" class="mw-changeslist-date">12:07, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,126 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,126 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; SQUASH Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10242&amp;undo=10252" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10242" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10242&amp;oldid=10237" title="Energy Cells">prev</a>)</span><input type="radio" value="10242" name="oldid" id="mw-oldid-10242" /><input type="radio" value="10242" name="diff" id="mw-diff-10242" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10242" title="Energy Cells" class="mw-changeslist-date">12:02, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,101 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,101 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Seeker Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10237&amp;undo=10242" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10237" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10237&amp;oldid=10226" title="Energy Cells">prev</a>)</span><input type="radio" value="10237" name="oldid" id="mw-oldid-10237" /><input type="radio" value="10237" name="diff" id="mw-diff-10237" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10237" title="Energy Cells" class="mw-changeslist-date">11:53, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,062 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,062 bytes after change">(+47)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-Matter Warhead Production Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10226&amp;undo=10237" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10226" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10226&amp;oldid=10216" title="Energy Cells">prev</a>)</span><input type="radio" value="10226" name="oldid" id="mw-oldid-10226" /><input type="radio" value="10226" name="diff" id="mw-diff-10226" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10226" title="Energy Cells" class="mw-changeslist-date">11:46, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,015 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,015 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Image Recognition Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10216&amp;undo=10226" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10216" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10216&amp;oldid=10215" title="Energy Cells">prev</a>)</span><input type="radio" value="10216" name="oldid" id="mw-oldid-10216" /><input type="radio" value="10216" name="diff" id="mw-diff-10216" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10216" title="Energy Cells" class="mw-changeslist-date">11:36, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,973 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,973 bytes after change">(+150)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; High Yield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10215&amp;undo=10216" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10215" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10215&amp;oldid=10214" title="Energy Cells">prev</a>)</span><input type="radio" value="10215" name="oldid" id="mw-oldid-10215" /><input type="radio" value="10215" name="diff" id="mw-diff-10215" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10215" title="Energy Cells" class="mw-changeslist-date">11:35, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,823 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,823 bytes after change">(+1,327)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 10187 by <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">Skald359</a> (<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10214&amp;undo=10215" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10214" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10214&amp;oldid=10213" title="Energy Cells">prev</a>)</span><input type="radio" value="10214" name="oldid" id="mw-oldid-10214" /><input type="radio" value="10214" name="diff" id="mw-diff-10214" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10214" title="Energy Cells" class="mw-changeslist-date">11:35, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,496 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,496 bytes after change">(-35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 10196 by <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">Skald359</a> (<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10213&amp;undo=10214" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10213" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10213&amp;oldid=10201" title="Energy Cells">prev</a>)</span><input type="radio" value="10213" name="oldid" id="mw-oldid-10213" /><input type="radio" value="10213" name="diff" id="mw-diff-10213" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10213" title="Energy Cells" class="mw-changeslist-date">11:35, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,531 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,531 bytes after change">(-41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 10201 by <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">Skald359</a> (<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10201&amp;undo=10213" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10201" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10201&amp;oldid=10196" title="Energy Cells">prev</a>)</span><input type="radio" value="10201" name="oldid" id="mw-oldid-10201" /><input type="radio" value="10201" name="diff" id="mw-diff-10201" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10201" title="Energy Cells" class="mw-changeslist-date">11:28, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,572 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,572 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Hammer Torpedo Fabrication Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10196&amp;undo=10201" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10196" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10196&amp;oldid=10187" title="Energy Cells">prev</a>)</span><input type="radio" value="10196" name="oldid" id="mw-oldid-10196" /><input type="radio" value="10196" name="diff" id="mw-diff-10196" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10196" title="Energy Cells" class="mw-changeslist-date">11:12, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,531 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,531 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Gauss Cannon Ammunition Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10187&amp;undo=10196" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10187" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10187&amp;oldid=10179" title="Energy Cells">prev</a>)</span><input type="radio" value="10187" name="oldid" id="mw-oldid-10187" /><input type="radio" value="10187" name="diff" id="mw-diff-10187" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10187" title="Energy Cells" class="mw-changeslist-date">11:07, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,496 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="1,496 bytes after change">(-1,327)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Flail Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10179&amp;undo=10187" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10179" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10179&amp;oldid=10170" title="Energy Cells">prev</a>)</span><input type="radio" value="10179" name="oldid" id="mw-oldid-10179" /><input type="radio" value="10179" name="diff" id="mw-diff-10179" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10179" title="Energy Cells" class="mw-changeslist-date">11:01, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,823 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,823 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Energy Bolt Chaingun Ammunition Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10170&amp;undo=10179" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10170" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10170&amp;oldid=10163" title="Energy Cells">prev</a>)</span><input type="radio" value="10170" name="oldid" id="mw-oldid-10170" /><input type="radio" value="10170" name="diff" id="mw-diff-10170" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10170" title="Energy Cells" class="mw-changeslist-date">10:57, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,780 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,780 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Dumbfire Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10163&amp;undo=10170" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10163" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10163&amp;oldid=10158" title="Energy Cells">prev</a>)</span><input type="radio" value="10163" name="oldid" id="mw-oldid-10163" /><input type="radio" value="10163" name="diff" id="mw-diff-10163" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10163" title="Energy Cells" class="mw-changeslist-date">01:45, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,739 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,739 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Cyclone Missile Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10158&amp;undo=10163" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10158" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10158&amp;oldid=10153" title="Energy Cells">prev</a>)</span><input type="radio" value="10158" name="oldid" id="mw-oldid-10158" /><input type="radio" value="10158" name="diff" id="mw-diff-10158" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10158" title="Energy Cells" class="mw-changeslist-date">01:26, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,710 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,710 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ammunition Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10153&amp;undo=10158" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10153" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10153&amp;oldid=10147" title="Energy Cells">prev</a>)</span><input type="radio" value="10153" name="oldid" id="mw-oldid-10153" /><input type="radio" value="10153" name="diff" id="mw-diff-10153" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10153" title="Energy Cells" class="mw-changeslist-date">01:23, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,686 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,686 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tractor Beam Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10147&amp;undo=10153" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10147" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10147&amp;oldid=10139" title="Energy Cells">prev</a>)</span><input type="radio" value="10147" name="oldid" id="mw-oldid-10147" /><input type="radio" value="10147" name="diff" id="mw-diff-10147" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10147" title="Energy Cells" class="mw-changeslist-date">01:20, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,660 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,660 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Starburst Shockwave Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10139&amp;undo=10147" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10139" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10139&amp;oldid=10130" title="Energy Cells">prev</a>)</span><input type="radio" value="10139" name="oldid" id="mw-oldid-10139" /><input type="radio" value="10139" name="diff" id="mw-diff-10139" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10139" title="Energy Cells" class="mw-changeslist-date">01:11, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,622 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,622 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Shield Production Facility 1MJ)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10130&amp;undo=10139" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10130" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10130&amp;oldid=10124" title="Energy Cells">prev</a>)</span><input type="radio" value="10130" name="oldid" id="mw-oldid-10130" /><input type="radio" value="10130" name="diff" id="mw-diff-10130" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10130" title="Energy Cells" class="mw-changeslist-date">00:37, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,586 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,586 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Satellite Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10124&amp;undo=10130" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10124" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10124&amp;oldid=10118" title="Energy Cells">prev</a>)</span><input type="radio" value="10124" name="oldid" id="mw-oldid-10124" /><input type="radio" value="10124" name="diff" id="mw-diff-10124" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10124" title="Energy Cells" class="mw-changeslist-date">00:06, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,563 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,563 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Point Singularity Projector Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10118&amp;undo=10124" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10118" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10118&amp;oldid=10110" title="Energy Cells">prev</a>)</span><input type="radio" value="10118" name="oldid" id="mw-oldid-10118" /><input type="radio" value="10118" name="diff" id="mw-diff-10118" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10118" title="Energy Cells" class="mw-changeslist-date">00:03, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,524 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,524 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Plasma Burst Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10110&amp;undo=10118" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10110" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10110&amp;oldid=10105" title="Energy Cells">prev</a>)</span><input type="radio" value="10110" name="oldid" id="mw-oldid-10110" /><input type="radio" value="10110" name="diff" id="mw-diff-10110" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10110" title="Energy Cells" class="mw-changeslist-date">23:55, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,490 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,490 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Photon Pulse Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10105&amp;undo=10110" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10105" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10105&amp;oldid=10097" title="Energy Cells">prev</a>)</span><input type="radio" value="10105" name="oldid" id="mw-oldid-10105" /><input type="radio" value="10105" name="diff" id="mw-diff-10105" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10105" title="Energy Cells" class="mw-changeslist-date">23:50, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,459 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,459 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phased Shockwave Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10097&amp;undo=10105" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10097" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10097&amp;oldid=10089" title="Energy Cells">prev</a>)</span><input type="radio" value="10097" name="oldid" id="mw-oldid-10097" /><input type="radio" value="10097" name="diff" id="mw-diff-10097" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10097" title="Energy Cells" class="mw-changeslist-date">23:46, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,421 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,421 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phased Repeater Gun Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10089&amp;undo=10097" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10089" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10089&amp;oldid=10078" title="Energy Cells">prev</a>)</span><input type="radio" value="10089" name="oldid" id="mw-oldid-10089" /><input type="radio" value="10089" name="diff" id="mw-diff-10089" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10089" title="Energy Cells" class="mw-changeslist-date">23:41, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,390 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,390 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Particle Accelerator Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10078&amp;undo=10089" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10078" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10078&amp;oldid=10070" title="Energy Cells">prev</a>)</span><input type="radio" value="10078" name="oldid" id="mw-oldid-10078" /><input type="radio" value="10078" name="diff" id="mw-diff-10078" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10078" title="Energy Cells" class="mw-changeslist-date">23:32, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,351 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,351 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10070&amp;undo=10078" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10070" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10070&amp;oldid=10064" title="Energy Cells">prev</a>)</span><input type="radio" value="10070" name="oldid" id="mw-oldid-10070" /><input type="radio" value="10070" name="diff" id="mw-diff-10070" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10070" title="Energy Cells" class="mw-changeslist-date">23:25, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,323 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,323 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10064&amp;undo=10070" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10064" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10064&amp;oldid=10058" title="Energy Cells">prev</a>)</span><input type="radio" value="10064" name="oldid" id="mw-oldid-10064" /><input type="radio" value="10064" name="diff" id="mw-diff-10064" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10064" title="Energy Cells" class="mw-changeslist-date">23:16, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,285 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,285 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-matter Launcher Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10058&amp;undo=10064" title="Energy Cells">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Energy_Cells&amp;diff=13244&amp;oldid=10058" title="Energy Cells">cur</a> | <a href="/index.php?title=Energy_Cells&amp;diff=10058&amp;oldid=10052" title="Energy Cells">prev</a>)</span><input type="radio" value="10058" name="oldid" id="mw-oldid-10058" /><input type="radio" value="10058" name="diff" id="mw-diff-10058" /> <a href="/index.php?title=Energy_Cells&amp;oldid=10058" title="Energy Cells" class="mw-changeslist-date">23:06, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,246 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,246 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mass Driver Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Energy_Cells&amp;action=edit&amp;undoafter=10052&amp;undo=10058" title="Energy Cells">undo</a></span>)</li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form>(newest | <a href="/index.php?title=Energy_Cells&amp;dir=prev&amp;action=history" title="Energy Cells" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Energy_Cells&amp;offset=20121007040629&amp;action=history" title="Energy Cells" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=20&amp;action=history" title="Energy Cells" class="mw-numlink">20</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=50&amp;action=history" title="Energy Cells" class="mw-numlink">50</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=100&amp;action=history" title="Energy Cells" class="mw-numlink">100</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=250&amp;action=history" title="Energy Cells" class="mw-numlink">250</a> | <a href="/index.php?title=Energy_Cells&amp;offset=&amp;limit=500&amp;action=history" title="Energy Cells" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a href="http://www.x3wiki.com/index.php/Energy_Cells">http://www.x3wiki.com/index.php/Energy_Cells</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Energy_Cells" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Energy_Cells&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Energy_Cells&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Energy_Cells&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Energy+Cells&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Energy+Cells&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Energy_Cells" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Energy_Cells" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Energy_Cells&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Energy_Cells&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.483 secs. --></body></html>