<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Sectors" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Sectors","wgTitle":"Sectors","wgCurRevisionId":15840,"wgRevisionId":0,"wgArticleId":21,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Sectors","wgRelevantArticleId":21,"wgRequestId":"Wcc8BVkfZokAAEQ1Y10AAAAJ","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Sectors&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Sectors&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Sectors&quot; Atom feed" href="/index.php?title=Sectors&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Sectors rootpage-Sectors skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Sectors"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Sectors" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Sectors" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Sectors" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=15275" title="Sectors">prev</a>)</span><input type="radio" value="15840" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="15840" checked="checked" name="diff" id="mw-diff-15840" /> <a href="/index.php?title=Sectors&amp;oldid=15840" title="Sectors" class="mw-changeslist-date">18:00, 6 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,728 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,728 bytes after change">(+32)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Unknown Sector (8,16))</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=15275&amp;undo=15840" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=15275" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=15275&amp;oldid=13323" title="Sectors">prev</a>)</span><input type="radio" value="15275" checked="checked" name="oldid" id="mw-oldid-15275" /><input type="radio" value="15275" name="diff" id="mw-diff-15275" /> <a href="/index.php?title=Sectors&amp;oldid=15275" title="Sectors" class="mw-changeslist-date">13:00, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,696 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,696 bytes after change">(+70)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(add AP sector I know)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=13323&amp;undo=15275" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=13323" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=13323&amp;oldid=13142" title="Sectors">prev</a>)</span><input type="radio" value="13323" name="oldid" id="mw-oldid-13323" /><input type="radio" value="13323" name="diff" id="mw-diff-13323" /> <a href="/index.php?title=Sectors&amp;oldid=13323" title="Sectors" class="mw-changeslist-date">13:39, 1 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,626 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,626 bytes after change">(+20)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Sectors#See_Also" title="Sectors">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=13142&amp;undo=13323" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=13142" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=13142&amp;oldid=12936" title="Sectors">prev</a>)</span><input type="radio" value="13142" name="oldid" id="mw-oldid-13142" /><input type="radio" value="13142" name="diff" id="mw-diff-13142" /> <a href="/index.php?title=Sectors&amp;oldid=13142" title="Sectors" class="mw-changeslist-date">14:11, 17 July 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,606 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,606 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(See also - universe map.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=12936&amp;undo=13142" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=12936" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=12936&amp;oldid=12930" title="Sectors">prev</a>)</span><input type="radio" value="12936" name="oldid" id="mw-oldid-12936" /><input type="radio" value="12936" name="diff" id="mw-diff-12936" /> <a href="/index.php?title=Sectors&amp;oldid=12936" title="Sectors" class="mw-changeslist-date">21:31, 29 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,578 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,578 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(void of opportunity sector link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=12930&amp;undo=12936" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=12930" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=12930&amp;oldid=12915" title="Sectors">prev</a>)</span><input type="radio" value="12930" name="oldid" id="mw-oldid-12930" /><input type="radio" value="12930" name="diff" id="mw-diff-12930" /> <a href="/index.php?title=Sectors&amp;oldid=12930" title="Sectors" class="mw-changeslist-date">21:24, 29 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,553 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,553 bytes after change">(+85)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(link to player sector)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=12915&amp;undo=12930" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=12915" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=12915&amp;oldid=12202" title="Sectors">prev</a>)</span><input type="radio" value="12915" name="oldid" id="mw-oldid-12915" /><input type="radio" value="12915" name="diff" id="mw-diff-12915" /> <a href="/index.php?title=Sectors&amp;oldid=12915" title="Sectors" class="mw-changeslist-date">20:44, 29 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,468 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,468 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(sector travel template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=12202&amp;undo=12915" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=12202" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=12202&amp;oldid=8471" title="Sectors">prev</a>)</span><input type="radio" value="12202" name="oldid" id="mw-oldid-12202" /><input type="radio" value="12202" name="diff" id="mw-diff-12202" /> <a href="/index.php?title=Sectors&amp;oldid=12202" title="Sectors" class="mw-changeslist-date">17:33, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,434 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,434 bytes after change">(+71)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added X3:AP Sectors)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=8471&amp;undo=12202" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=8471" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=8471&amp;oldid=7330" title="Sectors">prev</a>)</span><input type="radio" value="8471" name="oldid" id="mw-oldid-8471" /><input type="radio" value="8471" name="diff" id="mw-diff-8471" /> <a href="/index.php?title=Sectors&amp;oldid=8471" title="Sectors" class="mw-changeslist-date">05:28, 11 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,363 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,363 bytes after change">(-80)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(reworded universe map link rohrbeka&#039;s site no longer operational. thanks rohrbecka!)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=7330&amp;undo=8471" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=7330" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=7330&amp;oldid=5093" title="Sectors">prev</a>)</span><input type="radio" value="7330" name="oldid" id="mw-oldid-7330" /><input type="radio" value="7330" name="diff" id="mw-diff-7330" /> <a href="/index.php?title=Sectors&amp;oldid=7330" title="Sectors" class="mw-changeslist-date">20:35, 17 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,443 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,443 bytes after change">(+40)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(made improvements)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=5093&amp;undo=7330" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=5093" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=5093&amp;oldid=5092" title="Sectors">prev</a>)</span><input type="radio" value="5093" name="oldid" id="mw-oldid-5093" /><input type="radio" value="5093" name="diff" id="mw-diff-5093" /> <a href="/index.php?title=Sectors&amp;oldid=5093" title="Sectors" class="mw-changeslist-date">10:41, 5 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,403 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="6,403 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(rephrased gate position list intro)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=5092&amp;undo=5093" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=5092" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=5092&amp;oldid=4858" title="Sectors">prev</a>)</span><input type="radio" value="5092" name="oldid" id="mw-oldid-5092" /><input type="radio" value="5092" name="diff" id="mw-diff-5092" /> <a href="/index.php?title=Sectors&amp;oldid=5092" title="Sectors" class="mw-changeslist-date">10:38, 5 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,403 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="6,403 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected terrans link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=4858&amp;undo=5092" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=4858" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=4858&amp;oldid=4846" title="Sectors">prev</a>)</span><input type="radio" value="4858" name="oldid" id="mw-oldid-4858" /><input type="radio" value="4858" name="diff" id="mw-diff-4858" /> <a href="/index.php?title=Sectors&amp;oldid=4858" title="Sectors" class="mw-changeslist-date">19:46, 20 January 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,403 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,403 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected my laziness on jumpdrive and jumpgate links)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=4846&amp;undo=4858" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=4846" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=4846&amp;oldid=3181" title="Sectors">prev</a>)</span><input type="radio" value="4846" name="oldid" id="mw-oldid-4846" /><input type="radio" value="4846" name="diff" id="mw-diff-4846" /> <a href="/index.php?title=Sectors&amp;oldid=4846" title="Sectors" class="mw-changeslist-date">01:01, 20 January 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,401 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,401 bytes after change">(+1,412)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(divvied up sector list by first letter. added intro.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=3181&amp;undo=4846" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=3181" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=3181&amp;oldid=2690" title="Sectors">prev</a>)</span><input type="radio" value="3181" name="oldid" id="mw-oldid-3181" /><input type="radio" value="3181" name="diff" id="mw-diff-3181" /> <a href="/index.php?title=Sectors&amp;oldid=3181" title="Sectors" class="mw-changeslist-date">21:12, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,989 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,989 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected reservoir of tranquility link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=2690&amp;undo=3181" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=2690" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=2690&amp;oldid=1602" title="Sectors">prev</a>)</span><input type="radio" value="2690" name="oldid" id="mw-oldid-2690" /><input type="radio" value="2690" name="diff" id="mw-diff-2690" /> <a href="/index.php?title=Sectors&amp;oldid=2690" title="Sectors" class="mw-changeslist-date">21:01, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,989 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,989 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(altered unknown 18.10 to 18,10)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=1602&amp;undo=2690" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=1602" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=1602&amp;oldid=1563" title="Sectors">prev</a>)</span><input type="radio" value="1602" name="oldid" id="mw-oldid-1602" /><input type="radio" value="1602" name="diff" id="mw-diff-1602" /> <a href="/index.php?title=Sectors&amp;oldid=1602" title="Sectors" class="mw-changeslist-date">10:06, 27 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,989 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,989 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(link titan to titan (sector))</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=1563&amp;undo=1602" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=1563" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=1563&amp;oldid=1562" title="Sectors">prev</a>)</span><input type="radio" value="1563" name="oldid" id="mw-oldid-1563" /><input type="radio" value="1563" name="diff" id="mw-diff-1563" /> <a href="/index.php?title=Sectors&amp;oldid=1563" title="Sectors" class="mw-changeslist-date">07:12, 25 September 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Lord Hayden (page does not exist)">Lord Hayden</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new" title="User talk:Lord Hayden (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Lord_Hayden" title="Special:Contributions/Lord Hayden">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,980 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,980 bytes after change">(+83)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=1562&amp;undo=1563" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=1562" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=1562&amp;oldid=721" title="Sectors">prev</a>)</span><input type="radio" value="1562" name="oldid" id="mw-oldid-1562" /><input type="radio" value="1562" name="diff" id="mw-diff-1562" /> <a href="/index.php?title=Sectors&amp;oldid=1562" title="Sectors" class="mw-changeslist-date">07:10, 25 September 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Lord Hayden (page does not exist)">Lord Hayden</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Lord_Hayden&amp;action=edit&amp;redlink=1" class="new" title="User talk:Lord Hayden (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Lord_Hayden" title="Special:Contributions/Lord Hayden">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,897 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,897 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=721&amp;undo=1562" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=721" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=721&amp;oldid=720" title="Sectors">prev</a>)</span><input type="radio" value="721" name="oldid" id="mw-oldid-721" /><input type="radio" value="721" name="diff" id="mw-diff-721" /> <a href="/index.php?title=Sectors&amp;oldid=721" title="Sectors" class="mw-changeslist-date">21:08, 7 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,875 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,875 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(no really i fixed the link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=720&amp;undo=721" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=720" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=720&amp;oldid=698" title="Sectors">prev</a>)</span><input type="radio" value="720" name="oldid" id="mw-oldid-720" /><input type="radio" value="720" name="diff" id="mw-diff-720" /> <a href="/index.php?title=Sectors&amp;oldid=720" title="Sectors" class="mw-changeslist-date">21:07, 7 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,875 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,875 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fix link to table of gate coords)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=698&amp;undo=720" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=698" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=698&amp;oldid=630" title="Sectors">prev</a>)</span><input type="radio" value="698" name="oldid" id="mw-oldid-698" /><input type="radio" value="698" name="diff" id="mw-diff-698" /> <a href="/index.php?title=Sectors&amp;oldid=698" title="Sectors" class="mw-changeslist-date">23:38, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,876 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,876 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected mercury link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=630&amp;undo=698" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=630" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=630&amp;oldid=110" title="Sectors">prev</a>)</span><input type="radio" value="630" name="oldid" id="mw-oldid-630" /><input type="radio" value="630" name="diff" id="mw-diff-630" /> <a href="/index.php?title=Sectors&amp;oldid=630" title="Sectors" class="mw-changeslist-date">20:30, 30 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,867 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,867 bytes after change">(+4,807)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore may 24 cache entry.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=110&amp;undo=630" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=110" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=110&amp;oldid=108" title="Sectors">prev</a>)</span><input type="radio" value="110" name="oldid" id="mw-oldid-110" /><input type="radio" value="110" name="diff" id="mw-diff-110" /> <a href="/index.php?title=Sectors&amp;oldid=110" title="Sectors" class="mw-changeslist-date">16:26, 3 May 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.130.113.35" title="Special:Contributions/212.130.113.35" class="mw-userlink mw-anonuserlink">212.130.113.35</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.130.113.35&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.130.113.35 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(60 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="60 bytes after change">(-19,789)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Replaced content with &#039;<a href="/index.php/Universe_map" title="Universe map">Universe map</a> &lt;br /&gt; <a href="/index.php/All_sectors_withs_gate_positions" class="mw-redirect" title="All sectors withs gate positions">All sectors withs gate positions</a>&#039;)</span> (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=108&amp;undo=110" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=108" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=108&amp;oldid=107" title="Sectors">prev</a>)</span><input type="radio" value="108" name="oldid" id="mw-oldid-108" /><input type="radio" value="108" name="diff" id="mw-diff-108" /> <a href="/index.php?title=Sectors&amp;oldid=108" title="Sectors" class="mw-changeslist-date">16:25, 3 May 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.130.113.35" title="Special:Contributions/212.130.113.35" class="mw-userlink mw-anonuserlink">212.130.113.35</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.130.113.35&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.130.113.35 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(19,849 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="19,849 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=107&amp;undo=108" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=107" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=107&amp;oldid=105" title="Sectors">prev</a>)</span><input type="radio" value="107" name="oldid" id="mw-oldid-107" /><input type="radio" value="107" name="diff" id="mw-diff-107" /> <a href="/index.php?title=Sectors&amp;oldid=107" title="Sectors" class="mw-changeslist-date">16:24, 3 May 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.130.113.35" title="Special:Contributions/212.130.113.35" class="mw-userlink mw-anonuserlink">212.130.113.35</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.130.113.35&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.130.113.35 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(19,842 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="19,842 bytes after change">(+55)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=105&amp;undo=107" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=105" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=105&amp;oldid=104" title="Sectors">prev</a>)</span><input type="radio" value="105" name="oldid" id="mw-oldid-105" /><input type="radio" value="105" name="diff" id="mw-diff-105" /> <a href="/index.php?title=Sectors&amp;oldid=105" title="Sectors" class="mw-changeslist-date">16:13, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(19,787 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="19,787 bytes after change">(-53)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=104&amp;undo=105" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=104" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=104&amp;oldid=98" title="Sectors">prev</a>)</span><input type="radio" value="104" name="oldid" id="mw-oldid-104" /><input type="radio" value="104" name="diff" id="mw-diff-104" /> <a href="/index.php?title=Sectors&amp;oldid=104" title="Sectors" class="mw-changeslist-date">16:12, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(19,840 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="19,840 bytes after change">(+53)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=98&amp;undo=104" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=98" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=98&amp;oldid=97" title="Sectors">prev</a>)</span><input type="radio" value="98" name="oldid" id="mw-oldid-98" /><input type="radio" value="98" name="diff" id="mw-diff-98" /> <a href="/index.php?title=Sectors&amp;oldid=98" title="Sectors" class="mw-changeslist-date">15:59, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(19,787 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="19,787 bytes after change">(-3,663)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=97&amp;undo=98" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=97" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=97&amp;oldid=96" title="Sectors">prev</a>)</span><input type="radio" value="97" name="oldid" id="mw-oldid-97" /><input type="radio" value="97" name="diff" id="mw-diff-97" /> <a href="/index.php?title=Sectors&amp;oldid=97" title="Sectors" class="mw-changeslist-date">15:43, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(23,450 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="23,450 bytes after change">(-6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=96&amp;undo=97" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=96" title="Sectors">cur</a> | <a href="/index.php?title=Sectors&amp;diff=96&amp;oldid=95" title="Sectors">prev</a>)</span><input type="radio" value="96" name="oldid" id="mw-oldid-96" /><input type="radio" value="96" name="diff" id="mw-diff-96" /> <a href="/index.php?title=Sectors&amp;oldid=96" title="Sectors" class="mw-changeslist-date">15:40, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(23,456 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="23,456 bytes after change">(-76)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Sectors&amp;action=edit&amp;undoafter=95&amp;undo=96" title="Sectors">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Sectors&amp;diff=15840&amp;oldid=95" title="Sectors">cur</a> | prev)</span><input type="radio" value="95" name="oldid" id="mw-oldid-95" /><input type="radio" value="95" name="diff" id="mw-diff-95" /> <a href="/index.php?title=Sectors&amp;oldid=95" title="Sectors" class="mw-changeslist-date">15:38, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(23,532 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="23,532 bytes after change">(+23,532)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &#039;{| {{table}} | align=&quot;center&quot; style=&quot;background:#f0f0f0;&quot;|&#039;&#039;&#039;Name&#039;&#039;&#039; | align=&quot;center&quot; style=&quot;background:#f0f0f0;&quot;|&#039;&#039;&#039;&#039;&#039;&#039; | align=&quot;center&quot; style=&quot;background:#f0f0f0;&quot;|&#039;&#039;&#039;&#039;&#039;&#039; | ali…&#039;)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Sectors">http://x3wiki.com/index.php/Sectors</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Sectors" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Sectors" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Sectors&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Sectors&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Sectors&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Sectors&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Sectors" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Sectors" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Sectors&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Sectors&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":89});});</script></body></html>
