<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Meatsteak Cahoonas" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Meatsteak Cahoonas&quot; Atom feed" href="/index.php?title=Meatsteak_Cahoonas&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Meatsteak_Cahoonas","wgTitle":"Meatsteak Cahoonas","wgCurRevisionId":13675,"wgRevisionId":0,"wgArticleId":1047,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Meatsteak_Cahoonas","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Meatsteak_Cahoonas skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Meatsteak Cahoonas"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Meatsteak+Cahoonas" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Meatsteak_Cahoonas" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Meatsteak_Cahoonas" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10901" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="13675" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="13675" checked="checked" name="diff" id="mw-diff-13675" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=13675" title="Meatsteak Cahoonas" class="mw-changeslist-date">08:42, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,515 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,515 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10901&amp;undo=13675" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10901" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10901&amp;oldid=10319" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10901" checked="checked" name="oldid" id="mw-oldid-10901" /><input type="radio" value="10901" name="diff" id="mw-diff-10901" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10901" title="Meatsteak Cahoonas" class="mw-changeslist-date">14:34, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,498 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,498 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Waretable template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10319&amp;undo=10901" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10319" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10319&amp;oldid=10309" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10319" name="oldid" id="mw-oldid-10319" /><input type="radio" value="10319" name="diff" id="mw-diff-10319" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10319" title="Meatsteak Cahoonas" class="mw-changeslist-date">19:34, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,484 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,484 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mobile Drilling System Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10309&amp;undo=10319" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10309" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10309&amp;oldid=10284" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10309" name="oldid" id="mw-oldid-10309" /><input type="radio" value="10309" name="diff" id="mw-diff-10309" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10309" title="Meatsteak Cahoonas" class="mw-changeslist-date">18:46, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,448 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,448 bytes after change">(-31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(removed Drone Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10284&amp;undo=10309" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10284" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10284&amp;oldid=10263" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10284" name="oldid" id="mw-oldid-10284" /><input type="radio" value="10284" name="diff" id="mw-diff-10284" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10284" title="Meatsteak Cahoonas" class="mw-changeslist-date">12:34, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,479 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,479 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tracker Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10263&amp;undo=10284" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10263" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10263&amp;oldid=10245" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10263" name="oldid" id="mw-oldid-10263" /><input type="radio" value="10263" name="diff" id="mw-diff-10263" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10263" title="Meatsteak Cahoonas" class="mw-changeslist-date">12:22, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,453 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,453 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Swarm Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10245&amp;undo=10263" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10245" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10245&amp;oldid=10229" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10245" name="oldid" id="mw-oldid-10245" /><input type="radio" value="10245" name="diff" id="mw-diff-10245" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10245" title="Meatsteak Cahoonas" class="mw-changeslist-date">12:03, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,415 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,415 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Seeker Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10229&amp;undo=10245" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10229" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10229&amp;oldid=10219" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10229" name="oldid" id="mw-oldid-10229" /><input type="radio" value="10229" name="diff" id="mw-diff-10229" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10229" title="Meatsteak Cahoonas" class="mw-changeslist-date">11:48, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,376 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,376 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Image Recognition Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10219&amp;undo=10229" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10219" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10219&amp;oldid=10173" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10219" name="oldid" id="mw-oldid-10219" /><input type="radio" value="10219" name="diff" id="mw-diff-10219" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10219" title="Meatsteak Cahoonas" class="mw-changeslist-date">11:37, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,334 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,334 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; High Yield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10173&amp;undo=10219" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10173" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10173&amp;oldid=10080" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10173" name="oldid" id="mw-oldid-10173" /><input type="radio" value="10173" name="diff" id="mw-diff-10173" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10173" title="Meatsteak Cahoonas" class="mw-changeslist-date">10:58, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,299 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,299 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Dumbfire Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10080&amp;undo=10173" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10080" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10080&amp;oldid=10072" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10080" name="oldid" id="mw-oldid-10080" /><input type="radio" value="10080" name="diff" id="mw-diff-10080" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10080" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:33, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,258 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,258 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10072&amp;undo=10080" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10072" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10072&amp;oldid=10060" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10072" name="oldid" id="mw-oldid-10072" /><input type="radio" value="10072" name="diff" id="mw-diff-10072" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10072" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:26, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,230 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,230 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10060&amp;undo=10072" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10060" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10060&amp;oldid=10053" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10060" name="oldid" id="mw-oldid-10060" /><input type="radio" value="10060" name="diff" id="mw-diff-10060" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10060" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:07, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,192 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,192 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mass Driver Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10053&amp;undo=10060" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10053" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10053&amp;oldid=10045" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10053" name="oldid" id="mw-oldid-10053" /><input type="radio" value="10053" name="diff" id="mw-diff-10053" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10053" title="Meatsteak Cahoonas" class="mw-changeslist-date">21:47, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,169 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,169 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Marine Training Barracks)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10045&amp;undo=10053" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10045" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10045&amp;oldid=10040" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10045" name="oldid" id="mw-oldid-10045" /><input type="radio" value="10045" name="diff" id="mw-diff-10045" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10045" title="Meatsteak Cahoonas" class="mw-changeslist-date">21:41, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,139 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,139 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Light Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=10040&amp;undo=10045" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=10040" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=10040&amp;oldid=9942" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="10040" name="oldid" id="mw-oldid-10040" /><input type="radio" value="10040" name="diff" id="mw-diff-10040" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=10040" title="Meatsteak Cahoonas" class="mw-changeslist-date">21:28, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,112 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,112 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Light Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=9942&amp;undo=10040" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=9942" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=9942&amp;oldid=9933" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="9942" name="oldid" id="mw-oldid-9942" /><input type="radio" value="9942" name="diff" id="mw-diff-9942" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=9942" title="Meatsteak Cahoonas" class="mw-changeslist-date">13:05, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,075 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,075 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Heavy Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=9933&amp;undo=9942" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=9933" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=9933&amp;oldid=9774" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="9933" name="oldid" id="mw-oldid-9933" /><input type="radio" value="9933" name="diff" id="mw-diff-9933" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=9933" title="Meatsteak Cahoonas" class="mw-changeslist-date">12:57, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,048 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,048 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Heavy Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=9774&amp;undo=9933" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=9774" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=9774&amp;oldid=4262" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="9774" name="oldid" id="mw-oldid-9774" /><input type="radio" value="9774" name="diff" id="mw-diff-9774" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=9774" title="Meatsteak Cahoonas" class="mw-changeslist-date">17:30, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,011 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,011 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(changed &#039;Sold by&#039; to &#039;Produced by&#039;)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4262&amp;undo=9774" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4262" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=4262&amp;oldid=4261" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="4262" name="oldid" id="mw-oldid-4262" /><input type="radio" value="4262" name="diff" id="mw-diff-4262" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4262" title="Meatsteak Cahoonas" class="mw-changeslist-date">14:18, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,007 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,007 bytes after change">(+156)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(rotate trading information table.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4261&amp;undo=4262" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4261" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=4261&amp;oldid=4253" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="4261" name="oldid" id="mw-oldid-4261" /><input type="radio" value="4261" name="diff" id="mw-diff-4261" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4261" title="Meatsteak Cahoonas" class="mw-changeslist-date">14:11, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,851 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,851 bytes after change">(+1,187)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(testdrive spychotic&#039;s trading information table)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4253&amp;undo=4261" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4253" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=4253&amp;oldid=4177" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="4253" name="oldid" id="mw-oldid-4253" /><input type="radio" value="4253" name="diff" id="mw-diff-4253" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4253" title="Meatsteak Cahoonas" class="mw-changeslist-date">14:32, 17 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Jared1990&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Jared1990 (page does not exist)">Jared1990</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Jared1990&amp;action=edit&amp;redlink=1" class="new" title="User talk:Jared1990 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Jared1990" title="Special:Contributions/Jared1990">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(664 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="664 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4177&amp;undo=4253" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4177" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=4177&amp;oldid=4173" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="4177" name="oldid" id="mw-oldid-4177" /><input type="radio" value="4177" name="diff" id="mw-diff-4177" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4177" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:41, 11 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Jared1990&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Jared1990 (page does not exist)">Jared1990</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Jared1990&amp;action=edit&amp;redlink=1" class="new" title="User talk:Jared1990 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Jared1990" title="Special:Contributions/Jared1990">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(626 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="626 bytes after change">(-17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Meatsteak_Cahoonas#In-game_encyclopedia_entry" title="Meatsteak Cahoonas">→</a>‎<span dir="auto"><span class="autocomment">In-game encyclopedia entry</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4173&amp;undo=4177" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4173" title="Meatsteak Cahoonas">cur</a> | <a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=4173&amp;oldid=4171" title="Meatsteak Cahoonas">prev</a>)</span><input type="radio" value="4173" name="oldid" id="mw-oldid-4173" /><input type="radio" value="4173" name="diff" id="mw-diff-4173" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4173" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:10, 11 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Jared1990&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Jared1990 (page does not exist)">Jared1990</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Jared1990&amp;action=edit&amp;redlink=1" class="new" title="User talk:Jared1990 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Jared1990" title="Special:Contributions/Jared1990">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(643 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="643 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit&amp;undoafter=4171&amp;undo=4173" title="Meatsteak Cahoonas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Meatsteak_Cahoonas&amp;diff=13675&amp;oldid=4171" title="Meatsteak Cahoonas">cur</a> | prev)</span><input type="radio" value="4171" name="oldid" id="mw-oldid-4171" /><input type="radio" value="4171" name="diff" id="mw-diff-4171" /> <a href="/index.php?title=Meatsteak_Cahoonas&amp;oldid=4171" title="Meatsteak Cahoonas" class="mw-changeslist-date">23:01, 11 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Jared1990&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Jared1990 (page does not exist)">Jared1990</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Jared1990&amp;action=edit&amp;redlink=1" class="new" title="User talk:Jared1990 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Jared1990" title="Special:Contributions/Jared1990">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(635 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="635 bytes after change">(+635)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &quot;{{Infobox open}} {{Infobox ware |ware= Meatsteak Cahoonas |cargoclass=M |volume=5 |minprice=34 |aveprice=72 |maxprice=110 }} {{Infobox close}}  == In-game encyclopedia entry ==  ...&quot;)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Meatsteak_Cahoonas">http://x3wiki.com/index.php/Meatsteak_Cahoonas</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Meatsteak_Cahoonas" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Meatsteak_Cahoonas&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Meatsteak+Cahoonas&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Meatsteak+Cahoonas&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Meatsteak_Cahoonas" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Meatsteak_Cahoonas" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Meatsteak_Cahoonas&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Meatsteak_Cahoonas&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.287 secs. --></body></html>