<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Boreas" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Boreas","wgTitle":"Boreas","wgCurRevisionId":16227,"wgRevisionId":0,"wgArticleId":230,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Boreas","wgRelevantArticleId":230,"wgRequestId":"WfQDn1kfZokAABa-ps8AAAAC","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Boreas&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Boreas&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Boreas&quot; Atom feed" href="/index.php?title=Boreas&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Boreas rootpage-Boreas skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Boreas"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Boreas" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Boreas" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Boreas" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=11581" title="Boreas">prev</a>)</span><input type="radio" value="16227" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16227" checked="checked" name="diff" id="mw-diff-16227" /> <a href="/index.php?title=Boreas&amp;oldid=16227" title="Boreas" class="mw-changeslist-date">14:40, 30 April 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,908 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,908 bytes after change">(+12)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Overview" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=11581&amp;undo=16227" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=11581" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=11581&amp;oldid=10790" title="Boreas">prev</a>)</span><input type="radio" value="11581" checked="checked" name="oldid" id="mw-oldid-11581" /><input type="radio" value="11581" name="diff" id="mw-diff-11581" /> <a href="/index.php?title=Boreas&amp;oldid=11581" title="Boreas" class="mw-changeslist-date">09:21, 7 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,896 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,896 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=10790&amp;undo=11581" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=10790" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=10790&amp;oldid=10789" title="Boreas">prev</a>)</span><input type="radio" value="10790" name="oldid" id="mw-oldid-10790" /><input type="radio" value="10790" name="diff" id="mw-diff-10790" /> <a href="/index.php?title=Boreas&amp;oldid=10790" title="Boreas" class="mw-changeslist-date">02:41, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,900 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,900 bytes after change">(-6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=10789&amp;undo=10790" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=10789" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=10789&amp;oldid=9503" title="Boreas">prev</a>)</span><input type="radio" value="10789" name="oldid" id="mw-oldid-10789" /><input type="radio" value="10789" name="diff" id="mw-diff-10789" /> <a href="/index.php?title=Boreas&amp;oldid=10789" title="Boreas" class="mw-changeslist-date">02:41, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,906 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,906 bytes after change">(-305)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M2 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=9503&amp;undo=10789" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=9503" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=9503&amp;oldid=8628" title="Boreas">prev</a>)</span><input type="radio" value="9503" name="oldid" id="mw-oldid-9503" /><input type="radio" value="9503" name="diff" id="mw-diff-9503" /> <a href="/index.php?title=Boreas&amp;oldid=9503" title="Boreas" class="mw-changeslist-date">20:17, 24 July 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Heyjustarooni (page does not exist)">Heyjustarooni</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new" title="User talk:Heyjustarooni (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Heyjustarooni" title="Special:Contributions/Heyjustarooni">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,211 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,211 bytes after change">(+2,087)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added X3AP 2.1 variant of Boreas with stats from info panel)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8628&amp;undo=9503" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8628" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8628&amp;oldid=8445" title="Boreas">prev</a>)</span><input type="radio" value="8628" name="oldid" id="mw-oldid-8628" /><input type="radio" value="8628" name="diff" id="mw-diff-8628" /> <a href="/index.php?title=Boreas&amp;oldid=8628" title="Boreas" class="mw-changeslist-date">00:23, 17 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,124 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,124 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(m2category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8445&amp;undo=8628" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8445" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8445&amp;oldid=8431" title="Boreas">prev</a>)</span><input type="radio" value="8445" name="oldid" id="mw-oldid-8445" /><input type="radio" value="8445" name="diff" id="mw-diff-8445" /> <a href="/index.php?title=Boreas&amp;oldid=8445" title="Boreas" class="mw-changeslist-date">01:50, 7 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,108 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,108 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Albion_Prelude" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Albion Prelude</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8431&amp;undo=8445" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8431" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8431&amp;oldid=8428" title="Boreas">prev</a>)</span><input type="radio" value="8431" name="oldid" id="mw-oldid-8431" /><input type="radio" value="8431" name="diff" id="mw-diff-8431" /> <a href="/index.php?title=Boreas&amp;oldid=8431" title="Boreas" class="mw-changeslist-date">22:16, 4 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,109 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,109 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(It did not have &quot;it is&quot; shields scaled down ;p)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8428&amp;undo=8431" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8428" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8428&amp;oldid=8403" title="Boreas">prev</a>)</span><input type="radio" value="8428" name="oldid" id="mw-oldid-8428" /><input type="radio" value="8428" name="diff" id="mw-diff-8428" /> <a href="/index.php?title=Boreas&amp;oldid=8428" title="Boreas" class="mw-changeslist-date">08:23, 4 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/62.107.32.49" title="Special:Contributions/62.107.32.49" class="mw-userlink mw-anonuserlink">62.107.32.49</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:62.107.32.49&amp;action=edit&amp;redlink=1" class="new" title="User talk:62.107.32.49 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,110 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,110 bytes after change">(+237)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Combat" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8403&amp;undo=8428" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8403" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8403&amp;oldid=8368" title="Boreas">prev</a>)</span><input type="radio" value="8403" name="oldid" id="mw-oldid-8403" /><input type="radio" value="8403" name="diff" id="mw-diff-8403" /> <a href="/index.php?title=Boreas&amp;oldid=8403" title="Boreas" class="mw-changeslist-date">13:04, 30 January 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/90.192.113.232" title="Special:Contributions/90.192.113.232" class="mw-userlink mw-anonuserlink">90.192.113.232</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:90.192.113.232&amp;action=edit&amp;redlink=1" class="new" title="User talk:90.192.113.232 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,873 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,873 bytes after change">(+167)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8368&amp;undo=8403" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8368" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8368&amp;oldid=8290" title="Boreas">prev</a>)</span><input type="radio" value="8368" name="oldid" id="mw-oldid-8368" /><input type="radio" value="8368" name="diff" id="mw-diff-8368" /> <a href="/index.php?title=Boreas&amp;oldid=8368" title="Boreas" class="mw-changeslist-date">07:22, 23 January 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Skybon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Skybon (page does not exist)">Skybon</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skybon&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skybon (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skybon" title="Special:Contributions/Skybon">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,706 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,706 bytes after change">(-16)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8290&amp;undo=8368" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8290" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8290&amp;oldid=8138" title="Boreas">prev</a>)</span><input type="radio" value="8290" name="oldid" id="mw-oldid-8290" /><input type="radio" value="8290" name="diff" id="mw-diff-8290" /> <a href="/index.php?title=Boreas&amp;oldid=8290" title="Boreas" class="mw-changeslist-date">19:06, 10 January 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Xiphias&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Xiphias (page does not exist)">Xiphias</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Xiphias&amp;action=edit&amp;redlink=1" class="new" title="User talk:Xiphias (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Xiphias" title="Special:Contributions/Xiphias">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,722 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,722 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=8138&amp;undo=8290" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=8138" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=8138&amp;oldid=7659" title="Boreas">prev</a>)</span><input type="radio" value="8138" name="oldid" id="mw-oldid-8138" /><input type="radio" value="8138" name="diff" id="mw-diff-8138" /> <a href="/index.php?title=Boreas&amp;oldid=8138" title="Boreas" class="mw-changeslist-date">14:42, 19 December 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Grithok&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Grithok (page does not exist)">Grithok</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Grithok&amp;action=edit&amp;redlink=1" class="new" title="User talk:Grithok (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Grithok" title="Special:Contributions/Grithok">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,720 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,720 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7659&amp;undo=8138" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7659" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7659&amp;oldid=7618" title="Boreas">prev</a>)</span><input type="radio" value="7659" name="oldid" id="mw-oldid-7659" /><input type="radio" value="7659" name="diff" id="mw-diff-7659" /> <a href="/index.php?title=Boreas&amp;oldid=7659" title="Boreas" class="mw-changeslist-date">23:05, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,689 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,689 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Suggested_Roles" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7618&amp;undo=7659" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7618" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7618&amp;oldid=7617" title="Boreas">prev</a>)</span><input type="radio" value="7618" name="oldid" id="mw-oldid-7618" /><input type="radio" value="7618" name="diff" id="mw-diff-7618" /> <a href="/index.php?title=Boreas&amp;oldid=7618" title="Boreas" class="mw-changeslist-date">08:55, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,684 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,684 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Suggested_Roles" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7617&amp;undo=7618" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7617" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7617&amp;oldid=7616" title="Boreas">prev</a>)</span><input type="radio" value="7617" name="oldid" id="mw-oldid-7617" /><input type="radio" value="7617" name="diff" id="mw-diff-7617" /> <a href="/index.php?title=Boreas&amp;oldid=7617" title="Boreas" class="mw-changeslist-date">08:55, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,684 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,684 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Suggested_Roles" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7616&amp;undo=7617" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7616" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7616&amp;oldid=7615" title="Boreas">prev</a>)</span><input type="radio" value="7616" name="oldid" id="mw-oldid-7616" /><input type="radio" value="7616" name="diff" id="mw-diff-7616" /> <a href="/index.php?title=Boreas&amp;oldid=7616" title="Boreas" class="mw-changeslist-date">08:54, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,641 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,641 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Availability" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7615&amp;undo=7616" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7615" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7615&amp;oldid=7614" title="Boreas">prev</a>)</span><input type="radio" value="7615" name="oldid" id="mw-oldid-7615" /><input type="radio" value="7615" name="diff" id="mw-diff-7615" /> <a href="/index.php?title=Boreas&amp;oldid=7615" title="Boreas" class="mw-changeslist-date">08:53, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,641 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,641 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Availability" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=7614&amp;undo=7615" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=7614" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=7614&amp;oldid=6989" title="Boreas">prev</a>)</span><input type="radio" value="7614" name="oldid" id="mw-oldid-7614" /><input type="radio" value="7614" name="diff" id="mw-diff-7614" /> <a href="/index.php?title=Boreas&amp;oldid=7614" title="Boreas" class="mw-changeslist-date">08:53, 16 October 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Raider480&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Raider480 (page does not exist)">Raider480</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Raider480&amp;action=edit&amp;redlink=1" class="new" title="User talk:Raider480 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Raider480" title="Special:Contributions/Raider480">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,618 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,618 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Combat" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=6989&amp;undo=7614" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=6989" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=6989&amp;oldid=6236" title="Boreas">prev</a>)</span><input type="radio" value="6989" name="oldid" id="mw-oldid-6989" /><input type="radio" value="6989" name="diff" id="mw-diff-6989" /> <a href="/index.php?title=Boreas&amp;oldid=6989" title="Boreas" class="mw-changeslist-date">18:32, 15 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Aerozap&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Aerozap (page does not exist)">Aerozap</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Aerozap&amp;action=edit&amp;redlink=1" class="new" title="User talk:Aerozap (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Aerozap" title="Special:Contributions/Aerozap">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,610 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,610 bytes after change">(+112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Fixed OTAS Shipyard link; added links where applicable; some spelling corrections)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=6236&amp;undo=6989" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=6236" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=6236&amp;oldid=5416" title="Boreas">prev</a>)</span><input type="radio" value="6236" name="oldid" id="mw-oldid-6236" /><input type="radio" value="6236" name="diff" id="mw-diff-6236" /> <a href="/index.php?title=Boreas&amp;oldid=6236" title="Boreas" class="mw-changeslist-date">20:54, 12 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/206.71.170.254" title="Special:Contributions/206.71.170.254" class="mw-userlink mw-anonuserlink">206.71.170.254</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:206.71.170.254&amp;action=edit&amp;redlink=1" class="new" title="User talk:206.71.170.254 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,498 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,498 bytes after change">(+88)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Availability" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=5416&amp;undo=6236" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=5416" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=5416&amp;oldid=4808" title="Boreas">prev</a>)</span><input type="radio" value="5416" name="oldid" id="mw-oldid-5416" /><input type="radio" value="5416" name="diff" id="mw-diff-5416" /> <a href="/index.php?title=Boreas&amp;oldid=5416" title="Boreas" class="mw-changeslist-date">16:53, 15 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,410 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,410 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Availability" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=4808&amp;undo=5416" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=4808" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=4808&amp;oldid=3087" title="Boreas">prev</a>)</span><input type="radio" value="4808" name="oldid" id="mw-oldid-4808" /><input type="radio" value="4808" name="diff" id="mw-diff-4808" /> <a href="/index.php?title=Boreas&amp;oldid=4808" title="Boreas" class="mw-changeslist-date">14:13, 8 January 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Unearthly&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Unearthly (page does not exist)">Unearthly</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Unearthly&amp;action=edit&amp;redlink=1" class="new" title="User talk:Unearthly (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Unearthly" title="Special:Contributions/Unearthly">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,406 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,406 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=3087&amp;undo=4808" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=3087" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=3087&amp;oldid=2101" title="Boreas">prev</a>)</span><input type="radio" value="3087" name="oldid" id="mw-oldid-3087" /><input type="radio" value="3087" name="diff" id="mw-diff-3087" /> <a href="/index.php?title=Boreas&amp;oldid=3087" title="Boreas" class="mw-changeslist-date">00:49, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,408 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,408 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Availability" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=2101&amp;undo=3087" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=2101" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=2101&amp;oldid=1656" title="Boreas">prev</a>)</span><input type="radio" value="2101" name="oldid" id="mw-oldid-2101" /><input type="radio" value="2101" name="diff" id="mw-diff-2101" /> <a href="/index.php?title=Boreas&amp;oldid=2101" title="Boreas" class="mw-changeslist-date">11:46, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,404 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,404 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#See_Also" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=1656&amp;undo=2101" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=1656" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=1656&amp;oldid=780" title="Boreas">prev</a>)</span><input type="radio" value="1656" name="oldid" id="mw-oldid-1656" /><input type="radio" value="1656" name="diff" id="mw-diff-1656" /> <a href="/index.php?title=Boreas&amp;oldid=1656" title="Boreas" class="mw-changeslist-date">00:15, 28 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,397 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,397 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Boreas#Equipment" title="Boreas">→</a>‎<span dir="auto"><span class="autocomment">Equipment: </span> corrected firestorm link</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=780&amp;undo=1656" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=780" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=780&amp;oldid=681" title="Boreas">prev</a>)</span><input type="radio" value="780" name="oldid" id="mw-oldid-780" /><input type="radio" value="780" name="diff" id="mw-diff-780" /> <a href="/index.php?title=Boreas&amp;oldid=780" title="Boreas" class="mw-changeslist-date">20:00, 14 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,398 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,398 bytes after change">(+598)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(datasheet fill, gunslots, missile list in equipment)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=681&amp;undo=780" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=681" title="Boreas">cur</a> | <a href="/index.php?title=Boreas&amp;diff=681&amp;oldid=660" title="Boreas">prev</a>)</span><input type="radio" value="681" name="oldid" id="mw-oldid-681" /><input type="radio" value="681" name="diff" id="mw-diff-681" /> <a href="/index.php?title=Boreas&amp;oldid=681" title="Boreas" class="mw-changeslist-date">21:45, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,800 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,800 bytes after change">(+54)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(some additional color from cache)</span> (<span class="mw-history-undo"><a href="/index.php?title=Boreas&amp;action=edit&amp;undoafter=660&amp;undo=681" title="Boreas">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Boreas&amp;diff=16227&amp;oldid=660" title="Boreas">cur</a> | prev)</span><input type="radio" value="660" name="oldid" id="mw-oldid-660" /><input type="radio" value="660" name="diff" id="mw-diff-660" /> <a href="/index.php?title=Boreas&amp;oldid=660" title="Boreas" class="mw-changeslist-date">00:10, 2 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,746 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,746 bytes after change">(+3,746)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore from cache)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Boreas">http://x3wiki.com/index.php/Boreas</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Boreas" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Boreas&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Boreas&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Boreas&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Boreas&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Boreas&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Boreas" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Boreas" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Boreas&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Boreas&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":73});});</script></body></html>
