<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Ore" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Ore","wgTitle":"Ore","wgCurRevisionId":16424,"wgRevisionId":0,"wgArticleId":226,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Ore","wgRelevantArticleId":226,"wgRequestId":"WYQ@olkfZokAADeIc5UAAAAN","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Ore&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Ore&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Ore&quot; Atom feed" href="/index.php?title=Ore&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Ore rootpage-Ore skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Ore"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Ore" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Ore" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=Ore&amp;dir=prev&amp;action=history" title="Ore" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Ore&amp;offset=20121007013823&amp;action=history" title="Ore" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Ore&amp;offset=&amp;limit=20&amp;action=history" title="Ore" class="mw-numlink">20</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=50&amp;action=history" title="Ore" class="mw-numlink">50</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=100&amp;action=history" title="Ore" class="mw-numlink">100</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=250&amp;action=history" title="Ore" class="mw-numlink">250</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=500&amp;action=history" title="Ore" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Ore" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10911" title="Ore">prev</a>)</span><input type="radio" value="16424" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16424" checked="checked" name="diff" id="mw-diff-16424" /> <a href="/index.php?title=Ore&amp;oldid=16424" title="Ore" class="mw-changeslist-date">19:40, 25 August 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/217.39.106.64" title="Special:Contributions/217.39.106.64" class="mw-userlink mw-anonuserlink">217.39.106.64</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:217.39.106.64&amp;action=edit&amp;redlink=1" class="new" title="User talk:217.39.106.64 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,694 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,694 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Ore#Overview" title="Ore">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10911&amp;undo=16424" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10911" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10911&amp;oldid=10909" title="Ore">prev</a>)</span><input type="radio" value="10911" checked="checked" name="oldid" id="mw-oldid-10911" /><input type="radio" value="10911" name="diff" id="mw-diff-10911" /> <a href="/index.php?title=Ore&amp;oldid=10911" title="Ore" class="mw-changeslist-date">21:37, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,694 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,694 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Wares category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10909&amp;undo=10911" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10909" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10909&amp;oldid=10400" title="Ore">prev</a>)</span><input type="radio" value="10909" name="oldid" id="mw-oldid-10909" /><input type="radio" value="10909" name="diff" id="mw-diff-10909" /> <a href="/index.php?title=Ore&amp;oldid=10909" title="Ore" class="mw-changeslist-date">21:35, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,675 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,675 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Waretable template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10400&amp;undo=10909" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10400" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10400&amp;oldid=10392" title="Ore">prev</a>)</span><input type="radio" value="10400" name="oldid" id="mw-oldid-10400" /><input type="radio" value="10400" name="diff" id="mw-diff-10400" /> <a href="/index.php?title=Ore&amp;oldid=10400" title="Ore" class="mw-changeslist-date">07:35, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,661 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,661 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Wraith Missile Production Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10392&amp;undo=10400" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10392" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10392&amp;oldid=10385" title="Ore">prev</a>)</span><input type="radio" value="10392" name="oldid" id="mw-oldid-10392" /><input type="radio" value="10392" name="diff" id="mw-diff-10392" /> <a href="/index.php?title=Ore&amp;oldid=10392" title="Ore" class="mw-changeslist-date">07:28, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,624 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,624 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Spectre Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10385&amp;undo=10392" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10385" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10385&amp;oldid=10378" title="Ore">prev</a>)</span><input type="radio" value="10385" name="oldid" id="mw-oldid-10385" /><input type="radio" value="10385" name="diff" id="mw-diff-10385" /> <a href="/index.php?title=Ore&amp;oldid=10385" title="Ore" class="mw-changeslist-date">07:24, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,583 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,583 bytes after change">(+45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Poltergeist Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10378&amp;undo=10385" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10378" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10378&amp;oldid=10369" title="Ore">prev</a>)</span><input type="radio" value="10378" name="oldid" id="mw-oldid-10378" /><input type="radio" value="10378" name="diff" id="mw-diff-10378" /> <a href="/index.php?title=Ore&amp;oldid=10378" title="Ore" class="mw-changeslist-date">07:20, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,538 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,538 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phantom Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10369&amp;undo=10378" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10369" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10369&amp;oldid=10353" title="Ore">prev</a>)</span><input type="radio" value="10369" name="oldid" id="mw-oldid-10369" /><input type="radio" value="10369" name="diff" id="mw-diff-10369" /> <a href="/index.php?title=Ore&amp;oldid=10369" title="Ore" class="mw-changeslist-date">07:05, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,497 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,497 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-Matter Mine Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10353&amp;undo=10369" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10353" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10353&amp;oldid=10346" title="Ore">prev</a>)</span><input type="radio" value="10353" name="oldid" id="mw-oldid-10353" /><input type="radio" value="10353" name="diff" id="mw-diff-10353" /> <a href="/index.php?title=Ore&amp;oldid=10353" title="Ore" class="mw-changeslist-date">03:09, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,464 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,464 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ghoul Missile Manufacturing Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10346&amp;undo=10353" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10346" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10346&amp;oldid=10335" title="Ore">prev</a>)</span><input type="radio" value="10346" name="oldid" id="mw-oldid-10346" /><input type="radio" value="10346" name="diff" id="mw-diff-10346" /> <a href="/index.php?title=Ore&amp;oldid=10346" title="Ore" class="mw-changeslist-date">03:00, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,425 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,425 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; EMP Rifle Assembly Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10335&amp;undo=10346" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10335" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10335&amp;oldid=10317" title="Ore">prev</a>)</span><input type="radio" value="10335" name="oldid" id="mw-oldid-10335" /><input type="radio" value="10335" name="diff" id="mw-diff-10335" /> <a href="/index.php?title=Ore&amp;oldid=10335" title="Ore" class="mw-changeslist-date">02:47, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,392 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,392 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Disintegrator Rifles Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10317&amp;undo=10335" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10317" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10317&amp;oldid=10296" title="Ore">prev</a>)</span><input type="radio" value="10317" name="oldid" id="mw-oldid-10317" /><input type="radio" value="10317" name="diff" id="mw-diff-10317" /> <a href="/index.php?title=Ore&amp;oldid=10317" title="Ore" class="mw-changeslist-date">02:31, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,362 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,362 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mobile Drilling System Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10296&amp;undo=10317" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10296" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10296&amp;oldid=10283" title="Ore">prev</a>)</span><input type="radio" value="10296" name="oldid" id="mw-oldid-10296" /><input type="radio" value="10296" name="diff" id="mw-diff-10296" /> <a href="/index.php?title=Ore&amp;oldid=10296" title="Ore" class="mw-changeslist-date">01:38, 8 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,326 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,326 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Cluster Flak Array Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10283&amp;undo=10296" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10283" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10283&amp;oldid=10273" title="Ore">prev</a>)</span><input type="radio" value="10283" name="oldid" id="mw-oldid-10283" /><input type="radio" value="10283" name="diff" id="mw-diff-10283" /> <a href="/index.php?title=Ore&amp;oldid=10283" title="Ore" class="mw-changeslist-date">19:33, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,296 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,296 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tracker Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10273&amp;undo=10283" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10273" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10273&amp;oldid=10261" title="Ore">prev</a>)</span><input type="radio" value="10273" name="oldid" id="mw-oldid-10273" /><input type="radio" value="10273" name="diff" id="mw-diff-10273" /> <a href="/index.php?title=Ore&amp;oldid=10273" title="Ore" class="mw-changeslist-date">19:27, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,270 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,270 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tomahawk Missile Manufacturing Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10261&amp;undo=10273" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10261" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10261&amp;oldid=10253" title="Ore">prev</a>)</span><input type="radio" value="10261" name="oldid" id="mw-oldid-10261" /><input type="radio" value="10261" name="diff" id="mw-diff-10261" /> <a href="/index.php?title=Ore&amp;oldid=10261" title="Ore" class="mw-changeslist-date">19:22, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,228 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,228 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Swarm Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10253&amp;undo=10261" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10253" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10253&amp;oldid=10243" title="Ore">prev</a>)</span><input type="radio" value="10253" name="oldid" id="mw-oldid-10253" /><input type="radio" value="10253" name="diff" id="mw-diff-10253" /> <a href="/index.php?title=Ore&amp;oldid=10253" title="Ore" class="mw-changeslist-date">19:08, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,190 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,190 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; SQUASH Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10243&amp;undo=10253" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10243" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10243&amp;oldid=10238" title="Ore">prev</a>)</span><input type="radio" value="10243" name="oldid" id="mw-oldid-10243" /><input type="radio" value="10243" name="diff" id="mw-diff-10243" /> <a href="/index.php?title=Ore&amp;oldid=10243" title="Ore" class="mw-changeslist-date">19:02, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,165 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,165 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Seeker Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10238&amp;undo=10243" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10238" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10238&amp;oldid=10227" title="Ore">prev</a>)</span><input type="radio" value="10238" name="oldid" id="mw-oldid-10238" /><input type="radio" value="10238" name="diff" id="mw-diff-10238" /> <a href="/index.php?title=Ore&amp;oldid=10238" title="Ore" class="mw-changeslist-date">18:54, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,126 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,126 bytes after change">(+47)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-Matter Warhead Production Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10227&amp;undo=10238" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10227" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10227&amp;oldid=10217" title="Ore">prev</a>)</span><input type="radio" value="10227" name="oldid" id="mw-oldid-10227" /><input type="radio" value="10227" name="diff" id="mw-diff-10227" /> <a href="/index.php?title=Ore&amp;oldid=10227" title="Ore" class="mw-changeslist-date">18:46, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,079 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,079 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Image Recognition Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10217&amp;undo=10227" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10217" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10217&amp;oldid=10202" title="Ore">prev</a>)</span><input type="radio" value="10217" name="oldid" id="mw-oldid-10217" /><input type="radio" value="10217" name="diff" id="mw-diff-10217" /> <a href="/index.php?title=Ore&amp;oldid=10217" title="Ore" class="mw-changeslist-date">18:37, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,037 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,037 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; High Yield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10202&amp;undo=10217" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10202" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10202&amp;oldid=10197" title="Ore">prev</a>)</span><input type="radio" value="10202" name="oldid" id="mw-oldid-10202" /><input type="radio" value="10202" name="diff" id="mw-diff-10202" /> <a href="/index.php?title=Ore&amp;oldid=10202" title="Ore" class="mw-changeslist-date">18:28, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,002 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,002 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Hammer Torpedo Fabrication Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10197&amp;undo=10202" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10197" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10197&amp;oldid=10186" title="Ore">prev</a>)</span><input type="radio" value="10197" name="oldid" id="mw-oldid-10197" /><input type="radio" value="10197" name="diff" id="mw-diff-10197" /> <a href="/index.php?title=Ore&amp;oldid=10197" title="Ore" class="mw-changeslist-date">18:12, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,961 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,961 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Gauss Cannon Ammunition Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10186&amp;undo=10197" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10186" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10186&amp;oldid=10180" title="Ore">prev</a>)</span><input type="radio" value="10186" name="oldid" id="mw-oldid-10186" /><input type="radio" value="10186" name="diff" id="mw-diff-10186" /> <a href="/index.php?title=Ore&amp;oldid=10186" title="Ore" class="mw-changeslist-date">18:07, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,926 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,926 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Flail Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10180&amp;undo=10186" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10180" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10180&amp;oldid=10171" title="Ore">prev</a>)</span><input type="radio" value="10180" name="oldid" id="mw-oldid-10180" /><input type="radio" value="10180" name="diff" id="mw-diff-10180" /> <a href="/index.php?title=Ore&amp;oldid=10180" title="Ore" class="mw-changeslist-date">18:01, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,887 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,887 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Energy Bolt Chaingun Ammunition Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10171&amp;undo=10180" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10171" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10171&amp;oldid=10164" title="Ore">prev</a>)</span><input type="radio" value="10171" name="oldid" id="mw-oldid-10171" /><input type="radio" value="10171" name="diff" id="mw-diff-10171" /> <a href="/index.php?title=Ore&amp;oldid=10171" title="Ore" class="mw-changeslist-date">17:57, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,844 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,844 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Dumbfire Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10164&amp;undo=10171" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10164" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10164&amp;oldid=10159" title="Ore">prev</a>)</span><input type="radio" value="10164" name="oldid" id="mw-oldid-10164" /><input type="radio" value="10164" name="diff" id="mw-diff-10164" /> <a href="/index.php?title=Ore&amp;oldid=10164" title="Ore" class="mw-changeslist-date">08:45, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,803 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,803 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Cyclone Missile Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10159&amp;undo=10164" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10159" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10159&amp;oldid=10154" title="Ore">prev</a>)</span><input type="radio" value="10159" name="oldid" id="mw-oldid-10159" /><input type="radio" value="10159" name="diff" id="mw-diff-10159" /> <a href="/index.php?title=Ore&amp;oldid=10159" title="Ore" class="mw-changeslist-date">08:26, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,774 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,774 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ammunition Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10154&amp;undo=10159" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10154" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10154&amp;oldid=10148" title="Ore">prev</a>)</span><input type="radio" value="10154" name="oldid" id="mw-oldid-10154" /><input type="radio" value="10154" name="diff" id="mw-diff-10154" /> <a href="/index.php?title=Ore&amp;oldid=10154" title="Ore" class="mw-changeslist-date">08:23, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,750 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,750 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tractor Beam Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10148&amp;undo=10154" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10148" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10148&amp;oldid=10140" title="Ore">prev</a>)</span><input type="radio" value="10148" name="oldid" id="mw-oldid-10148" /><input type="radio" value="10148" name="diff" id="mw-diff-10148" /> <a href="/index.php?title=Ore&amp;oldid=10148" title="Ore" class="mw-changeslist-date">08:20, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,724 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,724 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Starburst Shockwave Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10140&amp;undo=10148" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10140" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10140&amp;oldid=10125" title="Ore">prev</a>)</span><input type="radio" value="10140" name="oldid" id="mw-oldid-10140" /><input type="radio" value="10140" name="diff" id="mw-diff-10140" /> <a href="/index.php?title=Ore&amp;oldid=10140" title="Ore" class="mw-changeslist-date">08:12, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,686 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,686 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Shield Production Facility 1MJ)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10125&amp;undo=10140" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10125" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10125&amp;oldid=10119" title="Ore">prev</a>)</span><input type="radio" value="10125" name="oldid" id="mw-oldid-10125" /><input type="radio" value="10125" name="diff" id="mw-diff-10125" /> <a href="/index.php?title=Ore&amp;oldid=10125" title="Ore" class="mw-changeslist-date">07:06, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,650 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,650 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Point Singularity Projector Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10119&amp;undo=10125" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10119" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10119&amp;oldid=10111" title="Ore">prev</a>)</span><input type="radio" value="10119" name="oldid" id="mw-oldid-10119" /><input type="radio" value="10119" name="diff" id="mw-diff-10119" /> <a href="/index.php?title=Ore&amp;oldid=10119" title="Ore" class="mw-changeslist-date">07:03, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,611 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,611 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Plasma Burst Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10111&amp;undo=10119" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10111" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10111&amp;oldid=10106" title="Ore">prev</a>)</span><input type="radio" value="10111" name="oldid" id="mw-oldid-10111" /><input type="radio" value="10111" name="diff" id="mw-diff-10111" /> <a href="/index.php?title=Ore&amp;oldid=10111" title="Ore" class="mw-changeslist-date">06:56, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,577 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,577 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Photon Pulse Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10106&amp;undo=10111" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10106" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10106&amp;oldid=10098" title="Ore">prev</a>)</span><input type="radio" value="10106" name="oldid" id="mw-oldid-10106" /><input type="radio" value="10106" name="diff" id="mw-diff-10106" /> <a href="/index.php?title=Ore&amp;oldid=10106" title="Ore" class="mw-changeslist-date">06:51, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,546 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,546 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phased Shockwave Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10098&amp;undo=10106" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10098" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10098&amp;oldid=10090" title="Ore">prev</a>)</span><input type="radio" value="10098" name="oldid" id="mw-oldid-10098" /><input type="radio" value="10098" name="diff" id="mw-diff-10098" /> <a href="/index.php?title=Ore&amp;oldid=10098" title="Ore" class="mw-changeslist-date">06:46, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,508 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,508 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phased Repeater Gun Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10090&amp;undo=10098" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10090" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10090&amp;oldid=10079" title="Ore">prev</a>)</span><input type="radio" value="10090" name="oldid" id="mw-oldid-10090" /><input type="radio" value="10090" name="diff" id="mw-diff-10090" /> <a href="/index.php?title=Ore&amp;oldid=10090" title="Ore" class="mw-changeslist-date">06:42, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,477 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,477 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Particle Accelerator Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10079&amp;undo=10090" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10079" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10079&amp;oldid=10071" title="Ore">prev</a>)</span><input type="radio" value="10079" name="oldid" id="mw-oldid-10079" /><input type="radio" value="10079" name="diff" id="mw-diff-10079" /> <a href="/index.php?title=Ore&amp;oldid=10079" title="Ore" class="mw-changeslist-date">06:33, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,438 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,438 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10071&amp;undo=10079" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10071" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10071&amp;oldid=10065" title="Ore">prev</a>)</span><input type="radio" value="10071" name="oldid" id="mw-oldid-10071" /><input type="radio" value="10071" name="diff" id="mw-diff-10071" /> <a href="/index.php?title=Ore&amp;oldid=10071" title="Ore" class="mw-changeslist-date">06:26, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,410 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,410 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10065&amp;undo=10071" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10065" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10065&amp;oldid=10059" title="Ore">prev</a>)</span><input type="radio" value="10065" name="oldid" id="mw-oldid-10065" /><input type="radio" value="10065" name="diff" id="mw-diff-10065" /> <a href="/index.php?title=Ore&amp;oldid=10065" title="Ore" class="mw-changeslist-date">06:17, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,372 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,372 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Matter/Anti-matter Launcher Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10059&amp;undo=10065" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10059" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10059&amp;oldid=10044" title="Ore">prev</a>)</span><input type="radio" value="10059" name="oldid" id="mw-oldid-10059" /><input type="radio" value="10059" name="diff" id="mw-diff-10059" /> <a href="/index.php?title=Ore&amp;oldid=10059" title="Ore" class="mw-changeslist-date">06:06, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,333 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,333 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mass Driver Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10044&amp;undo=10059" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10044" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10044&amp;oldid=10035" title="Ore">prev</a>)</span><input type="radio" value="10044" name="oldid" id="mw-oldid-10044" /><input type="radio" value="10044" name="diff" id="mw-diff-10044" /> <a href="/index.php?title=Ore&amp;oldid=10044" title="Ore" class="mw-changeslist-date">04:40, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,310 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,310 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Light Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10035&amp;undo=10044" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10035" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10035&amp;oldid=10026" title="Ore">prev</a>)</span><input type="radio" value="10035" name="oldid" id="mw-oldid-10035" /><input type="radio" value="10035" name="diff" id="mw-diff-10035" /> <a href="/index.php?title=Ore&amp;oldid=10035" title="Ore" class="mw-changeslist-date">04:26, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,283 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,283 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Light Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10026&amp;undo=10035" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10026" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10026&amp;oldid=10019" title="Ore">prev</a>)</span><input type="radio" value="10026" name="oldid" id="mw-oldid-10026" /><input type="radio" value="10026" name="diff" id="mw-diff-10026" /> <a href="/index.php?title=Ore&amp;oldid=10026" title="Ore" class="mw-changeslist-date">04:20, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,246 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,246 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Lasertower Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10019&amp;undo=10026" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10019" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10019&amp;oldid=10015" title="Ore">prev</a>)</span><input type="radio" value="10019" name="oldid" id="mw-oldid-10019" /><input type="radio" value="10019" name="diff" id="mw-diff-10019" /> <a href="/index.php?title=Ore&amp;oldid=10019" title="Ore" class="mw-changeslist-date">04:14, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,222 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,222 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ion Shard Railgun Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10015&amp;undo=10019" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10015" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10015&amp;oldid=10010" title="Ore">prev</a>)</span><input type="radio" value="10015" name="oldid" id="mw-oldid-10015" /><input type="radio" value="10015" name="diff" id="mw-diff-10015" /> <a href="/index.php?title=Ore&amp;oldid=10015" title="Ore" class="mw-changeslist-date">04:11, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,193 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,193 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ion Pulse Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10010&amp;undo=10015" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10010" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10010&amp;oldid=10002" title="Ore">prev</a>)</span><input type="radio" value="10010" name="oldid" id="mw-oldid-10010" /><input type="radio" value="10010" name="diff" id="mw-diff-10010" /> <a href="/index.php?title=Ore&amp;oldid=10010" title="Ore" class="mw-changeslist-date">04:08, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,162 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,162 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ion Disruptor Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=10002&amp;undo=10010" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=10002" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=10002&amp;oldid=9996" title="Ore">prev</a>)</span><input type="radio" value="10002" name="oldid" id="mw-oldid-10002" /><input type="radio" value="10002" name="diff" id="mw-diff-10002" /> <a href="/index.php?title=Ore&amp;oldid=10002" title="Ore" class="mw-changeslist-date">03:48, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,137 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,137 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ion Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=9996&amp;undo=10002" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=9996" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=9996&amp;oldid=9988" title="Ore">prev</a>)</span><input type="radio" value="9996" name="oldid" id="mw-oldid-9996" /><input type="radio" value="9996" name="diff" id="mw-diff-9996" /> <a href="/index.php?title=Ore&amp;oldid=9996" title="Ore" class="mw-changeslist-date">03:43, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,115 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,115 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Incendiary Bomb Launcher Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=9988&amp;undo=9996" title="Ore">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Ore&amp;diff=16424&amp;oldid=9988" title="Ore">cur</a> | <a href="/index.php?title=Ore&amp;diff=9988&amp;oldid=9983" title="Ore">prev</a>)</span><input type="radio" value="9988" name="oldid" id="mw-oldid-9988" /><input type="radio" value="9988" name="diff" id="mw-diff-9988" /> <a href="/index.php?title=Ore&amp;oldid=9988" title="Ore" class="mw-changeslist-date">03:38, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,079 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,079 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Impulse Ray Emitter Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Ore&amp;action=edit&amp;undoafter=9983&amp;undo=9988" title="Ore">undo</a></span>)</li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form>(newest | <a href="/index.php?title=Ore&amp;dir=prev&amp;action=history" title="Ore" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Ore&amp;offset=20121007013823&amp;action=history" title="Ore" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Ore&amp;offset=&amp;limit=20&amp;action=history" title="Ore" class="mw-numlink">20</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=50&amp;action=history" title="Ore" class="mw-numlink">50</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=100&amp;action=history" title="Ore" class="mw-numlink">100</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=250&amp;action=history" title="Ore" class="mw-numlink">250</a> | <a href="/index.php?title=Ore&amp;offset=&amp;limit=500&amp;action=history" title="Ore" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Ore">http://x3wiki.com/index.php/Ore</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Ore" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Ore&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Ore&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Ore&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Ore&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Ore&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Ore" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Ore" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Ore&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Ore&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":188});});</script></body></html>
