<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Hornet Missile" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Hornet_Missile","wgTitle":"Hornet Missile","wgCurRevisionId":14165,"wgRevisionId":0,"wgArticleId":171,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Hornet_Missile","wgRelevantArticleId":171,"wgRequestId":"WTCIhVkfZokAAFSnTiAAAAAc","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Hornet_Missile&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Hornet_Missile&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Hornet Missile&quot; Atom feed" href="/index.php?title=Hornet_Missile&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Hornet_Missile rootpage-Hornet_Missile skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Hornet Missile"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Hornet+Missile" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Hornet_Missile" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Hornet_Missile" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14164" title="Hornet Missile">prev</a>)</span><input type="radio" value="14165" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14165" checked="checked" name="diff" id="mw-diff-14165" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14165" title="Hornet Missile" class="mw-changeslist-date">04:56, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,363 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,363 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Overview" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14164&amp;undo=14165" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14164" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14164&amp;oldid=14163" title="Hornet Missile">prev</a>)</span><input type="radio" value="14164" checked="checked" name="oldid" id="mw-oldid-14164" /><input type="radio" value="14164" name="diff" id="mw-diff-14164" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14164" title="Hornet Missile" class="mw-changeslist-date">04:55, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,355 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,355 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14163&amp;undo=14164" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14163" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14163&amp;oldid=14162" title="Hornet Missile">prev</a>)</span><input type="radio" value="14163" name="oldid" id="mw-oldid-14163" /><input type="radio" value="14163" name="diff" id="mw-diff-14163" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14163" title="Hornet Missile" class="mw-changeslist-date">04:52, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,359 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,359 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14162&amp;undo=14163" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14162" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14162&amp;oldid=14161" title="Hornet Missile">prev</a>)</span><input type="radio" value="14162" name="oldid" id="mw-oldid-14162" /><input type="radio" value="14162" name="diff" id="mw-diff-14162" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14162" title="Hornet Missile" class="mw-changeslist-date">04:50, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,321 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,321 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14161&amp;undo=14162" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14161" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14161&amp;oldid=14160" title="Hornet Missile">prev</a>)</span><input type="radio" value="14161" name="oldid" id="mw-oldid-14161" /><input type="radio" value="14161" name="diff" id="mw-diff-14161" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14161" title="Hornet Missile" class="mw-changeslist-date">04:49, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,304 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,304 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14160&amp;undo=14161" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14160" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14160&amp;oldid=14153" title="Hornet Missile">prev</a>)</span><input type="radio" value="14160" name="oldid" id="mw-oldid-14160" /><input type="radio" value="14160" name="diff" id="mw-diff-14160" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14160" title="Hornet Missile" class="mw-changeslist-date">04:47, 8 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,267 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,267 bytes after change">(+52)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14153&amp;undo=14160" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14153" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14153&amp;oldid=14085" title="Hornet Missile">prev</a>)</span><input type="radio" value="14153" name="oldid" id="mw-oldid-14153" /><input type="radio" value="14153" name="diff" id="mw-diff-14153" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14153" title="Hornet Missile" class="mw-changeslist-date">11:38, 7 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,215 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,215 bytes after change">(+229)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14085&amp;undo=14153" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14085" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14085&amp;oldid=14064" title="Hornet Missile">prev</a>)</span><input type="radio" value="14085" name="oldid" id="mw-oldid-14085" /><input type="radio" value="14085" name="diff" id="mw-diff-14085" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14085" title="Hornet Missile" class="mw-changeslist-date">01:36, 21 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,986 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,986 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14064&amp;undo=14085" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14064" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14064&amp;oldid=14063" title="Hornet Missile">prev</a>)</span><input type="radio" value="14064" name="oldid" id="mw-oldid-14064" /><input type="radio" value="14064" name="diff" id="mw-diff-14064" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14064" title="Hornet Missile" class="mw-changeslist-date">22:58, 19 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,942 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,942 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=14063&amp;undo=14064" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=14063" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=14063&amp;oldid=13750" title="Hornet Missile">prev</a>)</span><input type="radio" value="14063" name="oldid" id="mw-oldid-14063" /><input type="radio" value="14063" name="diff" id="mw-diff-14063" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=14063" title="Hornet Missile" class="mw-changeslist-date">22:58, 19 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,941 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,941 bytes after change">(+171)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=13750&amp;undo=14063" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=13750" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=13750&amp;oldid=12844" title="Hornet Missile">prev</a>)</span><input type="radio" value="13750" name="oldid" id="mw-oldid-13750" /><input type="radio" value="13750" name="diff" id="mw-diff-13750" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=13750" title="Hornet Missile" class="mw-changeslist-date">19:50, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,770 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,770 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=12844&amp;undo=13750" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=12844" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=12844&amp;oldid=12843" title="Hornet Missile">prev</a>)</span><input type="radio" value="12844" name="oldid" id="mw-oldid-12844" /><input type="radio" value="12844" name="diff" id="mw-diff-12844" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=12844" title="Hornet Missile" class="mw-changeslist-date">22:43, 14 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,751 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,751 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary: </span> typo</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=12843&amp;undo=12844" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=12843" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=12843&amp;oldid=12155" title="Hornet Missile">prev</a>)</span><input type="radio" value="12843" name="oldid" id="mw-oldid-12843" /><input type="radio" value="12843" name="diff" id="mw-diff-12843" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=12843" title="Hornet Missile" class="mw-changeslist-date">22:40, 14 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,752 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,752 bytes after change">(+108)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added AP data. Edited commentary for grammar. Removed third paragraph, as it reiterated what the first already said)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=12155&amp;undo=12843" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=12155" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=12155&amp;oldid=12154" title="Hornet Missile">prev</a>)</span><input type="radio" value="12155" name="oldid" id="mw-oldid-12155" /><input type="radio" value="12155" name="diff" id="mw-diff-12155" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=12155" title="Hornet Missile" class="mw-changeslist-date">02:04, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,644 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,644 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=12154&amp;undo=12155" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=12154" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=12154&amp;oldid=11839" title="Hornet Missile">prev</a>)</span><input type="radio" value="12154" name="oldid" id="mw-oldid-12154" /><input type="radio" value="12154" name="diff" id="mw-diff-12154" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=12154" title="Hornet Missile" class="mw-changeslist-date">02:01, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,643 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,643 bytes after change">(+488)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=11839&amp;undo=12154" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=11839" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=11839&amp;oldid=11436" title="Hornet Missile">prev</a>)</span><input type="radio" value="11839" name="oldid" id="mw-oldid-11839" /><input type="radio" value="11839" name="diff" id="mw-diff-11839" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=11839" title="Hornet Missile" class="mw-changeslist-date">20:48, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,155 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,155 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=11436&amp;undo=11839" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=11436" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=11436&amp;oldid=11435" title="Hornet Missile">prev</a>)</span><input type="radio" value="11436" name="oldid" id="mw-oldid-11436" /><input type="radio" value="11436" name="diff" id="mw-diff-11436" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=11436" title="Hornet Missile" class="mw-changeslist-date">19:36, 23 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,153 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,153 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=11435&amp;undo=11436" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=11435" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=11435&amp;oldid=8326" title="Hornet Missile">prev</a>)</span><input type="radio" value="11435" name="oldid" id="mw-oldid-11435" /><input type="radio" value="11435" name="diff" id="mw-diff-11435" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=11435" title="Hornet Missile" class="mw-changeslist-date">19:35, 23 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,134 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,134 bytes after change">(+83)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=8326&amp;undo=11435" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=8326" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=8326&amp;oldid=7919" title="Hornet Missile">prev</a>)</span><input type="radio" value="8326" name="oldid" id="mw-oldid-8326" /><input type="radio" value="8326" name="diff" id="mw-diff-8326" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=8326" title="Hornet Missile" class="mw-changeslist-date">00:12, 21 January 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/174.60.54.189" title="Special:Contributions/174.60.54.189" class="mw-userlink mw-anonuserlink">174.60.54.189</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:174.60.54.189&amp;action=edit&amp;redlink=1" class="new" title="User talk:174.60.54.189 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,051 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,051 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=7919&amp;undo=8326" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=7919" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=7919&amp;oldid=5762" title="Hornet Missile">prev</a>)</span><input type="radio" value="7919" name="oldid" id="mw-oldid-7919" /><input type="radio" value="7919" name="diff" id="mw-diff-7919" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=7919" title="Hornet Missile" class="mw-changeslist-date">05:55, 16 November 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,050 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,050 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(default to IR)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=5762&amp;undo=7919" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=5762" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=5762&amp;oldid=5240" title="Hornet Missile">prev</a>)</span><input type="radio" value="5762" name="oldid" id="mw-oldid-5762" /><input type="radio" value="5762" name="diff" id="mw-diff-5762" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=5762" title="Hornet Missile" class="mw-changeslist-date">00:49, 17 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,033 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,033 bytes after change">(+326)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added categories and note on mining use)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=5240&amp;undo=5762" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=5240" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=5240&amp;oldid=5238" title="Hornet Missile">prev</a>)</span><input type="radio" value="5240" name="oldid" id="mw-oldid-5240" /><input type="radio" value="5240" name="diff" id="mw-diff-5240" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=5240" title="Hornet Missile" class="mw-changeslist-date">03:43, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,707 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,707 bytes after change">(-17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(conformed to standard. seeker is targeted, guidance is not stated, but assumed as standard/image recognition)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=5238&amp;undo=5240" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=5238" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=5238&amp;oldid=3887" title="Hornet Missile">prev</a>)</span><input type="radio" value="5238" name="oldid" id="mw-oldid-5238" /><input type="radio" value="5238" name="diff" id="mw-diff-5238" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=5238" title="Hornet Missile" class="mw-changeslist-date">03:32, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,724 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,724 bytes after change">(+539)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated with encyclopedia info)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=3887&amp;undo=5238" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=3887" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=3887&amp;oldid=3886" title="Hornet Missile">prev</a>)</span><input type="radio" value="3887" name="oldid" id="mw-oldid-3887" /><input type="radio" value="3887" name="diff" id="mw-diff-3887" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=3887" title="Hornet Missile" class="mw-changeslist-date">02:42, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,185 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,185 bytes after change">(+205)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Overview" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=3886&amp;undo=3887" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=3886" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=3886&amp;oldid=3885" title="Hornet Missile">prev</a>)</span><input type="radio" value="3886" name="oldid" id="mw-oldid-3886" /><input type="radio" value="3886" name="diff" id="mw-diff-3886" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=3886" title="Hornet Missile" class="mw-changeslist-date">02:40, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(980 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="980 bytes after change">(-42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=3885&amp;undo=3886" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=3885" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=3885&amp;oldid=3884" title="Hornet Missile">prev</a>)</span><input type="radio" value="3885" name="oldid" id="mw-oldid-3885" /><input type="radio" value="3885" name="diff" id="mw-diff-3885" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=3885" title="Hornet Missile" class="mw-changeslist-date">02:38, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,022 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,022 bytes after change">(+296)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary: </span>  Moved from Overview section</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=3884&amp;undo=3885" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=3884" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=3884&amp;oldid=3154" title="Hornet Missile">prev</a>)</span><input type="radio" value="3884" name="oldid" id="mw-oldid-3884" /><input type="radio" value="3884" name="diff" id="mw-diff-3884" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=3884" title="Hornet Missile" class="mw-changeslist-date">02:38, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(726 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="726 bytes after change">(-302)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Overview" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=3154&amp;undo=3884" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=3154" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=3154&amp;oldid=2372" title="Hornet Missile">prev</a>)</span><input type="radio" value="3154" name="oldid" id="mw-oldid-3154" /><input type="radio" value="3154" name="diff" id="mw-diff-3154" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=3154" title="Hornet Missile" class="mw-changeslist-date">15:34, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Justadude41123" title="User:Justadude41123" class="mw-userlink">Justadude41123</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Justadude41123&amp;action=edit&amp;redlink=1" class="new" title="User talk:Justadude41123 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Justadude41123" title="Special:Contributions/Justadude41123">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,028 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,028 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Overview" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=2372&amp;undo=3154" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=2372" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=2372&amp;oldid=1402" title="Hornet Missile">prev</a>)</span><input type="radio" value="2372" name="oldid" id="mw-oldid-2372" /><input type="radio" value="2372" name="diff" id="mw-diff-2372" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=2372" title="Hornet Missile" class="mw-changeslist-date">21:02, 7 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,027 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,027 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(aoe)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1402&amp;undo=2372" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1402" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1402&amp;oldid=1401" title="Hornet Missile">prev</a>)</span><input type="radio" value="1402" name="oldid" id="mw-oldid-1402" /><input type="radio" value="1402" name="diff" id="mw-diff-1402" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1402" title="Hornet Missile" class="mw-changeslist-date">20:59, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,022 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,022 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(remember to preview before submitting :P)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1401&amp;undo=1402" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1401" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1401&amp;oldid=1379" title="Hornet Missile">prev</a>)</span><input type="radio" value="1401" name="oldid" id="mw-oldid-1401" /><input type="radio" value="1401" name="diff" id="mw-diff-1401" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1401" title="Hornet Missile" class="mw-changeslist-date">20:59, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,022 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,022 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(no x-universe games article, but new x-universe article.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1379&amp;undo=1401" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1379" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1379&amp;oldid=1378" title="Hornet Missile">prev</a>)</span><input type="radio" value="1379" name="oldid" id="mw-oldid-1379" /><input type="radio" value="1379" name="diff" id="mw-diff-1379" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1379" title="Hornet Missile" class="mw-changeslist-date">19:26, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,022 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,022 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1378&amp;undo=1379" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1378" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1378&amp;oldid=1377" title="Hornet Missile">prev</a>)</span><input type="radio" value="1378" name="oldid" id="mw-oldid-1378" /><input type="radio" value="1378" name="diff" id="mw-diff-1378" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1378" title="Hornet Missile" class="mw-changeslist-date">19:24, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,007 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,007 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated the links)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1377&amp;undo=1378" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1377" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1377&amp;oldid=1375" title="Hornet Missile">prev</a>)</span><input type="radio" value="1377" name="oldid" id="mw-oldid-1377" /><input type="radio" value="1377" name="diff" id="mw-diff-1377" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1377" title="Hornet Missile" class="mw-changeslist-date">19:21, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(976 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="976 bytes after change">(+20)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(linked some words)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=1375&amp;undo=1377" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=1375" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=1375&amp;oldid=865" title="Hornet Missile">prev</a>)</span><input type="radio" value="1375" name="oldid" id="mw-oldid-1375" /><input type="radio" value="1375" name="diff" id="mw-diff-1375" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=1375" title="Hornet Missile" class="mw-changeslist-date">19:11, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(956 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="956 bytes after change">(+215)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Hornet_Missile#Commentary" title="Hornet Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=865&amp;undo=1375" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=865" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=865&amp;oldid=617" title="Hornet Missile">prev</a>)</span><input type="radio" value="865" name="oldid" id="mw-oldid-865" /><input type="radio" value="865" name="diff" id="mw-diff-865" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=865" title="Hornet Missile" class="mw-changeslist-date">21:08, 22 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(741 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="741 bytes after change">(+59)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(infobox data)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=617&amp;undo=865" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=617" title="Hornet Missile">cur</a> | <a href="/index.php?title=Hornet_Missile&amp;diff=617&amp;oldid=474" title="Hornet Missile">prev</a>)</span><input type="radio" value="617" name="oldid" id="mw-oldid-617" /><input type="radio" value="617" name="diff" id="mw-diff-617" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=617" title="Hornet Missile" class="mw-changeslist-date">23:22, 29 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(682 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="682 bytes after change">(+277)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added standard form)</span> (<span class="mw-history-undo"><a href="/index.php?title=Hornet_Missile&amp;action=edit&amp;undoafter=474&amp;undo=617" title="Hornet Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Hornet_Missile&amp;diff=14165&amp;oldid=474" title="Hornet Missile">cur</a> | prev)</span><input type="radio" value="474" name="oldid" id="mw-oldid-474" /><input type="radio" value="474" name="diff" id="mw-diff-474" /> <a href="/index.php?title=Hornet_Missile&amp;oldid=474" title="Hornet Missile" class="mw-changeslist-date">23:25, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(405 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="405 bytes after change">(+405)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore from cache)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Hornet_Missile">http://www.x3wiki.com/index.php/Hornet_Missile</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Hornet_Missile" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Hornet_Missile&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Hornet_Missile&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Hornet_Missile&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Hornet+Missile&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Hornet+Missile&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Hornet_Missile" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Hornet_Missile" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Hornet_Missile&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Hornet_Missile&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":134});});</script></body></html>
