<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Races" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Races&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Races&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Races&quot; Atom feed" href="/index.php?title=Races&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Races","wgTitle":"Races","wgCurRevisionId":16469,"wgRevisionId":0,"wgArticleId":8,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Races","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Races skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Races"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Races" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Races" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=Races&amp;dir=prev&amp;action=history" title="Races" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Races&amp;offset=20100802183651&amp;action=history" title="Races" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Races&amp;offset=&amp;limit=20&amp;action=history" title="Races" class="mw-numlink">20</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=50&amp;action=history" title="Races" class="mw-numlink">50</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=100&amp;action=history" title="Races" class="mw-numlink">100</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=250&amp;action=history" title="Races" class="mw-numlink">250</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=500&amp;action=history" title="Races" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Races" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Races&amp;diff=16469&amp;oldid=16468" title="Races">prev</a>)</span><input type="radio" value="16469" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16469" checked="checked" name="diff" id="mw-diff-16469" /> <a href="/index.php?title=Races&amp;oldid=16469" title="Races" class="mw-changeslist-date">10:13, 7 September 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/65.191.15.184" title="Special:Contributions/65.191.15.184" class="mw-userlink">65.191.15.184</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:65.191.15.184&amp;action=edit&amp;redlink=1" class="new" title="User talk:65.191.15.184 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,573 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,573 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Paranid" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Paranid</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=16468&amp;undo=16469" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=16468" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=16468&amp;oldid=14145" title="Races">prev</a>)</span><input type="radio" value="16468" checked="checked" name="oldid" id="mw-oldid-16468" /><input type="radio" value="16468" name="diff" id="mw-diff-16468" /> <a href="/index.php?title=Races&amp;oldid=16468" title="Races" class="mw-changeslist-date">10:04, 7 September 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/65.191.15.184" title="Special:Contributions/65.191.15.184" class="mw-userlink">65.191.15.184</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:65.191.15.184&amp;action=edit&amp;redlink=1" class="new" title="User talk:65.191.15.184 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,573 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,573 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terran" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terran</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=14145&amp;undo=16468" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=14145" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=14145&amp;oldid=13813" title="Races">prev</a>)</span><input type="radio" value="14145" name="oldid" id="mw-oldid-14145" /><input type="radio" value="14145" name="diff" id="mw-diff-14145" /> <a href="/index.php?title=Races&amp;oldid=14145" title="Races" class="mw-changeslist-date">21:31, 4 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,573 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,573 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Paranid" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Paranid</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=13813&amp;undo=14145" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=13813" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=13813&amp;oldid=13352" title="Races">prev</a>)</span><input type="radio" value="13813" name="oldid" id="mw-oldid-13813" /><input type="radio" value="13813" name="diff" id="mw-diff-13813" /> <a href="/index.php?title=Races&amp;oldid=13813" title="Races" class="mw-changeslist-date">18:18, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,563 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,563 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=13352&amp;undo=13813" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=13352" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=13352&amp;oldid=11951" title="Races">prev</a>)</span><input type="radio" value="13352" name="oldid" id="mw-oldid-13352" /><input type="radio" value="13352" name="diff" id="mw-diff-13352" /> <a href="/index.php?title=Races&amp;oldid=13352" title="Races" class="mw-changeslist-date">10:48, 1 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,553 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,553 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Adding Trading Template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=11951&amp;undo=13352" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=11951" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=11951&amp;oldid=6469" title="Races">prev</a>)</span><input type="radio" value="11951" name="oldid" id="mw-oldid-11951" /><input type="radio" value="11951" name="diff" id="mw-diff-11951" /> <a href="/index.php?title=Races&amp;oldid=11951" title="Races" class="mw-changeslist-date">14:24, 17 April 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,540 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,540 bytes after change">(+187)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Teladi" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Teladi</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6469&amp;undo=11951" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6469" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6469&amp;oldid=6219" title="Races">prev</a>)</span><input type="radio" value="6469" name="oldid" id="mw-oldid-6469" /><input type="radio" value="6469" name="diff" id="mw-diff-6469" /> <a href="/index.php?title=Races&amp;oldid=6469" title="Races" class="mw-changeslist-date">06:22, 2 July 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/194.239.204.61" title="Special:Contributions/194.239.204.61" class="mw-userlink">194.239.204.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:194.239.204.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:194.239.204.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,353 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,353 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Strongarms" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Strongarms</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6219&amp;undo=6469" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6219" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6219&amp;oldid=6183" title="Races">prev</a>)</span><input type="radio" value="6219" name="oldid" id="mw-oldid-6219" /><input type="radio" value="6219" name="diff" id="mw-diff-6219" /> <a href="/index.php?title=Races&amp;oldid=6219" title="Races" class="mw-changeslist-date">00:14, 12 May 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,351 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,351 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 6183 by <a href="/index.php/Special:Contributions/221.203.79.101" title="Special:Contributions/221.203.79.101">221.203.79.101</a> (<a href="/index.php?title=User_talk:221.203.79.101&amp;action=edit&amp;redlink=1" class="new" title="User talk:221.203.79.101 (page does not exist)">talk</a>)vandal)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6183&amp;undo=6219" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6183" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6183&amp;oldid=6165" title="Races">prev</a>)</span><input type="radio" value="6183" name="oldid" id="mw-oldid-6183" /><input type="radio" value="6183" name="diff" id="mw-diff-6183" /> <a href="/index.php?title=Races&amp;oldid=6183" title="Races" class="mw-changeslist-date">10:00, 11 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/221.203.79.101" title="Special:Contributions/221.203.79.101" class="mw-userlink">221.203.79.101</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:221.203.79.101&amp;action=edit&amp;redlink=1" class="new" title="User talk:221.203.79.101 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,323 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,323 bytes after change">(-28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Strongarms" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Strongarms</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6165&amp;undo=6183" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6165" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6165&amp;oldid=6147" title="Races">prev</a>)</span><input type="radio" value="6165" name="oldid" id="mw-oldid-6165" /><input type="radio" value="6165" name="diff" id="mw-diff-6165" /> <a href="/index.php?title=Races&amp;oldid=6165" title="Races" class="mw-changeslist-date">23:47, 10 May 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,351 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,351 bytes after change">(+422)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore last good edit)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6147&amp;undo=6165" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6147" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6147&amp;oldid=6097" title="Races">prev</a>)</span><input type="radio" value="6147" name="oldid" id="mw-oldid-6147" /><input type="radio" value="6147" name="diff" id="mw-diff-6147" /> <a href="/index.php?title=Races&amp;oldid=6147" title="Races" class="mw-changeslist-date">17:33, 10 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/213.0.89.54" title="Special:Contributions/213.0.89.54" class="mw-userlink">213.0.89.54</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:213.0.89.54&amp;action=edit&amp;redlink=1" class="new" title="User talk:213.0.89.54 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,929 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,929 bytes after change">(-130)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terracorp" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terracorp</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6097&amp;undo=6147" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6097" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6097&amp;oldid=6090" title="Races">prev</a>)</span><input type="radio" value="6097" name="oldid" id="mw-oldid-6097" /><input type="radio" value="6097" name="diff" id="mw-diff-6097" /> <a href="/index.php?title=Races&amp;oldid=6097" title="Races" class="mw-changeslist-date">00:05, 10 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/84.73.125.222" title="Special:Contributions/84.73.125.222" class="mw-userlink">84.73.125.222</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:84.73.125.222&amp;action=edit&amp;redlink=1" class="new" title="User talk:84.73.125.222 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,059 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,059 bytes after change">(-292)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Aldrin" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Aldrin</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=6090&amp;undo=6097" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=6090" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=6090&amp;oldid=5869" title="Races">prev</a>)</span><input type="radio" value="6090" name="oldid" id="mw-oldid-6090" /><input type="radio" value="6090" name="diff" id="mw-diff-6090" /> <a href="/index.php?title=Races&amp;oldid=6090" title="Races" class="mw-changeslist-date">17:43, 9 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/108.11.164.242" title="Special:Contributions/108.11.164.242" class="mw-userlink">108.11.164.242</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:108.11.164.242&amp;action=edit&amp;redlink=1" class="new" title="User talk:108.11.164.242 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,351 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,351 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Yaki" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Yaki: </span> ~ cleanup</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5869&amp;undo=6090" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5869" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5869&amp;oldid=5868" title="Races">prev</a>)</span><input type="radio" value="5869" name="oldid" id="mw-oldid-5869" /><input type="radio" value="5869" name="diff" id="mw-diff-5869" /> <a href="/index.php?title=Races&amp;oldid=5869" title="Races" class="mw-changeslist-date">14:40, 28 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,351 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,351 bytes after change">(+139)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(adjusted factions section weighting)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5868&amp;undo=5869" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5868" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5868&amp;oldid=5776" title="Races">prev</a>)</span><input type="radio" value="5868" name="oldid" id="mw-oldid-5868" /><input type="radio" value="5868" name="diff" id="mw-diff-5868" /> <a href="/index.php?title=Races&amp;oldid=5868" title="Races" class="mw-changeslist-date">14:35, 28 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,212 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,212 bytes after change">(-24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Species" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Species: </span> altered sectional weights to readd grouping lines</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5776&amp;undo=5868" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5776" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5776&amp;oldid=5624" title="Races">prev</a>)</span><input type="radio" value="5776" name="oldid" id="mw-oldid-5776" /><input type="radio" value="5776" name="diff" id="mw-diff-5776" /> <a href="/index.php?title=Races&amp;oldid=5776" title="Races" class="mw-changeslist-date">01:24, 18 March 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Adam&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Adam (page does not exist)">Adam</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Adam&amp;action=edit&amp;redlink=1" class="new" title="User talk:Adam (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Adam" title="Special:Contributions/Adam">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,236 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,236 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Aldrin" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Aldrin</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5624&amp;undo=5776" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5624" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5624&amp;oldid=5623" title="Races">prev</a>)</span><input type="radio" value="5624" name="oldid" id="mw-oldid-5624" /><input type="radio" value="5624" name="diff" id="mw-diff-5624" /> <a href="/index.php?title=Races&amp;oldid=5624" title="Races" class="mw-changeslist-date">17:00, 28 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,236 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,236 bytes after change">(-229)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Errant page editing event)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5623&amp;undo=5624" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5623" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5623&amp;oldid=5622" title="Races">prev</a>)</span><input type="radio" value="5623" name="oldid" id="mw-oldid-5623" /><input type="radio" value="5623" name="diff" id="mw-diff-5623" /> <a href="/index.php?title=Races&amp;oldid=5623" title="Races" class="mw-changeslist-date">16:52, 28 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/81.152.8.54" title="Special:Contributions/81.152.8.54" class="mw-userlink">81.152.8.54</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:81.152.8.54&amp;action=edit&amp;redlink=1" class="new" title="User talk:81.152.8.54 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,465 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,465 bytes after change">(-83)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Removed sections about weapons; this article is &#039;padding&#039; concerning backstory and such technical information belongs elsewhere.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5622&amp;undo=5623" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5622" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5622&amp;oldid=5621" title="Races">prev</a>)</span><input type="radio" value="5622" name="oldid" id="mw-oldid-5622" /><input type="radio" value="5622" name="diff" id="mw-diff-5622" /> <a href="/index.php?title=Races&amp;oldid=5622" title="Races" class="mw-changeslist-date">15:02, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,548 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,548 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(tested anti spam measures-  rexde500)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5621&amp;undo=5622" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5621" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5621&amp;oldid=5620" title="Races">prev</a>)</span><input type="radio" value="5621" name="oldid" id="mw-oldid-5621" /><input type="radio" value="5621" name="diff" id="mw-diff-5621" /> <a href="/index.php?title=Races&amp;oldid=5621" title="Races" class="mw-changeslist-date">15:01, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,547 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,547 bytes after change">(-10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5620&amp;undo=5621" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5620" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5620&amp;oldid=5619" title="Races">prev</a>)</span><input type="radio" value="5620" name="oldid" id="mw-oldid-5620" /><input type="radio" value="5620" name="diff" id="mw-diff-5620" /> <a href="/index.php?title=Races&amp;oldid=5620" title="Races" class="mw-changeslist-date">15:01, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,557 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,557 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5619&amp;undo=5620" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5619" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5619&amp;oldid=5618" title="Races">prev</a>)</span><input type="radio" value="5619" name="oldid" id="mw-oldid-5619" /><input type="radio" value="5619" name="diff" id="mw-diff-5619" /> <a href="/index.php?title=Races&amp;oldid=5619" title="Races" class="mw-changeslist-date">15:00, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,558 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,558 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5618&amp;undo=5619" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5618" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5618&amp;oldid=5617" title="Races">prev</a>)</span><input type="radio" value="5618" name="oldid" id="mw-oldid-5618" /><input type="radio" value="5618" name="diff" id="mw-diff-5618" /> <a href="/index.php?title=Races&amp;oldid=5618" title="Races" class="mw-changeslist-date">14:56, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,547 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,547 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5617&amp;undo=5618" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5617" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5617&amp;oldid=5616" title="Races">prev</a>)</span><input type="radio" value="5617" name="oldid" id="mw-oldid-5617" /><input type="radio" value="5617" name="diff" id="mw-diff-5617" /> <a href="/index.php?title=Races&amp;oldid=5617" title="Races" class="mw-changeslist-date">14:56, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,551 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,551 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5616&amp;undo=5617" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5616" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5616&amp;oldid=5615" title="Races">prev</a>)</span><input type="radio" value="5616" name="oldid" id="mw-oldid-5616" /><input type="radio" value="5616" name="diff" id="mw-diff-5616" /> <a href="/index.php?title=Races&amp;oldid=5616" title="Races" class="mw-changeslist-date">14:54, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,547 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,547 bytes after change">(-5)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5615&amp;undo=5616" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5615" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5615&amp;oldid=5607" title="Races">prev</a>)</span><input type="radio" value="5615" name="oldid" id="mw-oldid-5615" /><input type="radio" value="5615" name="diff" id="mw-diff-5615" /> <a href="/index.php?title=Races&amp;oldid=5615" title="Races" class="mw-changeslist-date">14:54, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,552 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,552 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5607&amp;undo=5615" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5607" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5607&amp;oldid=5606" title="Races">prev</a>)</span><input type="radio" value="5607" name="oldid" id="mw-oldid-5607" /><input type="radio" value="5607" name="diff" id="mw-diff-5607" /> <a href="/index.php?title=Races&amp;oldid=5607" title="Races" class="mw-changeslist-date">14:43, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,548 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,548 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5606&amp;undo=5607" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5606" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5606&amp;oldid=5605" title="Races">prev</a>)</span><input type="radio" value="5606" name="oldid" id="mw-oldid-5606" /><input type="radio" value="5606" name="diff" id="mw-diff-5606" /> <a href="/index.php?title=Races&amp;oldid=5606" title="Races" class="mw-changeslist-date">14:43, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:TestTest&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:TestTest (page does not exist)">TestTest</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:TestTest&amp;action=edit&amp;redlink=1" class="new" title="User talk:TestTest (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/TestTest" title="Special:Contributions/TestTest">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,549 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,549 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5605&amp;undo=5606" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5605" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5605&amp;oldid=5604" title="Races">prev</a>)</span><input type="radio" value="5605" name="oldid" id="mw-oldid-5605" /><input type="radio" value="5605" name="diff" id="mw-diff-5605" /> <a href="/index.php?title=Races&amp;oldid=5605" title="Races" class="mw-changeslist-date">13:59, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,548 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,548 bytes after change">(+187)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Aldrin" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Aldrin</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5604&amp;undo=5605" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5604" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5604&amp;oldid=5603" title="Races">prev</a>)</span><input type="radio" value="5604" name="oldid" id="mw-oldid-5604" /><input type="radio" value="5604" name="diff" id="mw-diff-5604" /> <a href="/index.php?title=Races&amp;oldid=5604" title="Races" class="mw-changeslist-date">13:58, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,361 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,361 bytes after change">(+61)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Paranid" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Paranid</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5603&amp;undo=5604" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5603" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5603&amp;oldid=5602" title="Races">prev</a>)</span><input type="radio" value="5603" name="oldid" id="mw-oldid-5603" /><input type="radio" value="5603" name="diff" id="mw-diff-5603" /> <a href="/index.php?title=Races&amp;oldid=5603" title="Races" class="mw-changeslist-date">13:58, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,300 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,300 bytes after change">(+68)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Teladi" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Teladi</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5602&amp;undo=5603" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5602" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5602&amp;oldid=5601" title="Races">prev</a>)</span><input type="radio" value="5602" name="oldid" id="mw-oldid-5602" /><input type="radio" value="5602" name="diff" id="mw-diff-5602" /> <a href="/index.php?title=Races&amp;oldid=5602" title="Races" class="mw-changeslist-date">13:57, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,232 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,232 bytes after change">(+79)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Split" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Split</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5601&amp;undo=5602" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5601" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5601&amp;oldid=5600" title="Races">prev</a>)</span><input type="radio" value="5601" name="oldid" id="mw-oldid-5601" /><input type="radio" value="5601" name="diff" id="mw-diff-5601" /> <a href="/index.php?title=Races&amp;oldid=5601" title="Races" class="mw-changeslist-date">13:56, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,153 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,153 bytes after change">(+220)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terran" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terran</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5600&amp;undo=5601" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5600" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5600&amp;oldid=5330" title="Races">prev</a>)</span><input type="radio" value="5600" name="oldid" id="mw-oldid-5600" /><input type="radio" value="5600" name="diff" id="mw-diff-5600" /> <a href="/index.php?title=Races&amp;oldid=5600" title="Races" class="mw-changeslist-date">13:53, 27 February 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/71.237.249.227" title="Special:Contributions/71.237.249.227" class="mw-userlink">71.237.249.227</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:71.237.249.227&amp;action=edit&amp;redlink=1" class="new" title="User talk:71.237.249.227 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,933 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,933 bytes after change">(+120)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Boron" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Boron</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5330&amp;undo=5600" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5330" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5330&amp;oldid=5329" title="Races">prev</a>)</span><input type="radio" value="5330" name="oldid" id="mw-oldid-5330" /><input type="radio" value="5330" name="diff" id="mw-diff-5330" /> <a href="/index.php?title=Races&amp;oldid=5330" title="Races" class="mw-changeslist-date">08:31, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,813 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,813 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#NMMC" title="Races">→</a>‎<span dir="auto"><span class="autocomment">NMMC</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=5329&amp;undo=5330" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=5329" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=5329&amp;oldid=4783" title="Races">prev</a>)</span><input type="radio" value="5329" name="oldid" id="mw-oldid-5329" /><input type="radio" value="5329" name="diff" id="mw-diff-5329" /> <a href="/index.php?title=Races&amp;oldid=5329" title="Races" class="mw-changeslist-date">08:30, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,808 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,808 bytes after change">(-4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Goner" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Goner: </span>  Minor corrections</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4783&amp;undo=5329" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4783" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4783&amp;oldid=4409" title="Races">prev</a>)</span><input type="radio" value="4783" name="oldid" id="mw-oldid-4783" /><input type="radio" value="4783" name="diff" id="mw-diff-4783" /> <a href="/index.php?title=Races&amp;oldid=4783" title="Races" class="mw-changeslist-date">10:30, 5 January 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,812 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,812 bytes after change">(+2,266)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(General additions and header editing)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4409&amp;undo=4783" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4409" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4409&amp;oldid=4314" title="Races">prev</a>)</span><input type="radio" value="4409" name="oldid" id="mw-oldid-4409" /><input type="radio" value="4409" name="diff" id="mw-diff-4409" /> <a href="/index.php?title=Races&amp;oldid=4409" title="Races" class="mw-changeslist-date">08:53, 27 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,546 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,546 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Duke.27s" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Duke&#039;s: </span> Added amusing link. :D</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4314&amp;undo=4409" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4314" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4314&amp;oldid=4270" title="Races">prev</a>)</span><input type="radio" value="4314" name="oldid" id="mw-oldid-4314" /><input type="radio" value="4314" name="diff" id="mw-diff-4314" /> <a href="/index.php?title=Races&amp;oldid=4314" title="Races" class="mw-changeslist-date">17:05, 19 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,533 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,533 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Profit_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Profit Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4270&amp;undo=4314" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4270" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4270&amp;oldid=4269" title="Races">prev</a>)</span><input type="radio" value="4270" name="oldid" id="mw-oldid-4270" /><input type="radio" value="4270" name="diff" id="mw-diff-4270" /> <a href="/index.php?title=Races&amp;oldid=4270" title="Races" class="mw-changeslist-date">15:55, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Justadude41123" title="User:Justadude41123" class="mw-userlink">Justadude41123</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Justadude41123&amp;action=edit&amp;redlink=1" class="new" title="User talk:Justadude41123 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Justadude41123" title="Special:Contributions/Justadude41123">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,533 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,533 bytes after change">(+585)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Profit_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Profit Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4269&amp;undo=4270" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4269" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4269&amp;oldid=4268" title="Races">prev</a>)</span><input type="radio" value="4269" name="oldid" id="mw-oldid-4269" /><input type="radio" value="4269" name="diff" id="mw-diff-4269" /> <a href="/index.php?title=Races&amp;oldid=4269" title="Races" class="mw-changeslist-date">15:49, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Justadude41123" title="User:Justadude41123" class="mw-userlink">Justadude41123</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Justadude41123&amp;action=edit&amp;redlink=1" class="new" title="User talk:Justadude41123 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Justadude41123" title="Special:Contributions/Justadude41123">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,948 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,948 bytes after change">(+343)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Foundation_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Foundation Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4268&amp;undo=4269" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4268" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4268&amp;oldid=4267" title="Races">prev</a>)</span><input type="radio" value="4268" name="oldid" id="mw-oldid-4268" /><input type="radio" value="4268" name="diff" id="mw-diff-4268" /> <a href="/index.php?title=Races&amp;oldid=4268" title="Races" class="mw-changeslist-date">15:42, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/72.91.227.61" title="Special:Contributions/72.91.227.61" class="mw-userlink">72.91.227.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:72.91.227.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:72.91.227.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,605 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,605 bytes after change">(-466)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Foundation_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Foundation Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4267&amp;undo=4268" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4267" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4267&amp;oldid=4266" title="Races">prev</a>)</span><input type="radio" value="4267" name="oldid" id="mw-oldid-4267" /><input type="radio" value="4267" name="diff" id="mw-diff-4267" /> <a href="/index.php?title=Races&amp;oldid=4267" title="Races" class="mw-changeslist-date">15:42, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/72.91.227.61" title="Special:Contributions/72.91.227.61" class="mw-userlink">72.91.227.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:72.91.227.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:72.91.227.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,071 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,071 bytes after change">(+466)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Foundation_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Foundation Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4266&amp;undo=4267" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4266" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4266&amp;oldid=4265" title="Races">prev</a>)</span><input type="radio" value="4266" name="oldid" id="mw-oldid-4266" /><input type="radio" value="4266" name="diff" id="mw-diff-4266" /> <a href="/index.php?title=Races&amp;oldid=4266" title="Races" class="mw-changeslist-date">15:41, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/72.91.227.61" title="Special:Contributions/72.91.227.61" class="mw-userlink">72.91.227.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:72.91.227.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:72.91.227.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,605 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,605 bytes after change">(+467)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Foundation_Guild" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Foundation Guild</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=4265&amp;undo=4266" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=4265" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=4265&amp;oldid=2795" title="Races">prev</a>)</span><input type="radio" value="4265" name="oldid" id="mw-oldid-4265" /><input type="radio" value="4265" name="diff" id="mw-diff-4265" /> <a href="/index.php?title=Races&amp;oldid=4265" title="Races" class="mw-changeslist-date">15:29, 18 November 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/72.91.227.61" title="Special:Contributions/72.91.227.61" class="mw-userlink">72.91.227.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:72.91.227.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:72.91.227.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,138 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,138 bytes after change">(+388)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Yaki" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Yaki</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=2795&amp;undo=4265" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=2795" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=2795&amp;oldid=1680" title="Races">prev</a>)</span><input type="radio" value="2795" name="oldid" id="mw-oldid-2795" /><input type="radio" value="2795" name="diff" id="mw-diff-2795" /> <a href="/index.php?title=Races&amp;oldid=2795" title="Races" class="mw-changeslist-date">19:24, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,750 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,750 bytes after change">(+109)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Community_of_Planets" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Community of Planets: </span> stub description</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=1680&amp;undo=2795" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=1680" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=1680&amp;oldid=1679" title="Races">prev</a>)</span><input type="radio" value="1680" name="oldid" id="mw-oldid-1680" /><input type="radio" value="1680" name="diff" id="mw-diff-1680" /> <a href="/index.php?title=Races&amp;oldid=1680" title="Races" class="mw-changeslist-date">17:51, 27 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,641 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,641 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terran" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terran: </span> corrected gunne ref</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=1679&amp;undo=1680" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=1679" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=1679&amp;oldid=1321" title="Races">prev</a>)</span><input type="radio" value="1679" name="oldid" id="mw-oldid-1679" /><input type="radio" value="1679" name="diff" id="mw-diff-1679" /> <a href="/index.php?title=Races&amp;oldid=1679" title="Races" class="mw-changeslist-date">17:45, 27 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,642 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,642 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terran" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terran: </span> link x-universe</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=1321&amp;undo=1679" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=1321" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=1321&amp;oldid=959" title="Races">prev</a>)</span><input type="radio" value="1321" name="oldid" id="mw-oldid-1321" /><input type="radio" value="1321" name="diff" id="mw-diff-1321" /> <a href="/index.php?title=Races&amp;oldid=1321" title="Races" class="mw-changeslist-date">10:24, 22 September 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,638 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,638 bytes after change">(+147)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Terran" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Terran</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=959&amp;undo=1321" title="Races">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Races&amp;diff=16469&amp;oldid=959" title="Races">cur</a> | <a href="/index.php?title=Races&amp;diff=959&amp;oldid=953" title="Races">prev</a>)</span><input type="radio" value="959" name="oldid" id="mw-oldid-959" /><input type="radio" value="959" name="diff" id="mw-diff-959" /> <a href="/index.php?title=Races&amp;oldid=959" title="Races" class="mw-changeslist-date">13:36, 2 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,491 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,491 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Races#Duke.27s" title="Races">→</a>‎<span dir="auto"><span class="autocomment">Duke&#039;s: </span> coordinates for unknown sector</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Races&amp;action=edit&amp;undoafter=953&amp;undo=959" title="Races">undo</a></span>)</li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form>(newest | <a href="/index.php?title=Races&amp;dir=prev&amp;action=history" title="Races" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Races&amp;offset=20100802183651&amp;action=history" title="Races" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Races&amp;offset=&amp;limit=20&amp;action=history" title="Races" class="mw-numlink">20</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=50&amp;action=history" title="Races" class="mw-numlink">50</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=100&amp;action=history" title="Races" class="mw-numlink">100</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=250&amp;action=history" title="Races" class="mw-numlink">250</a> | <a href="/index.php?title=Races&amp;offset=&amp;limit=500&amp;action=history" title="Races" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a href="http://www.x3wiki.com/index.php/Races">http://www.x3wiki.com/index.php/Races</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Races" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Races" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Races&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Races&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Races&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Races&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Races" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Races" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Races&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Races&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.472 secs. --></body></html>