<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "TL" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"TL","wgTitle":"TL","wgCurRevisionId":16960,"wgRevisionId":0,"wgArticleId":7,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"TL","wgRelevantArticleId":7,"wgRequestId":"WZaQI1kfZokAABNfiKQAAAAK","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=TL&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=TL&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;TL&quot; Atom feed" href="/index.php?title=TL&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-TL rootpage-TL skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "TL"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=TL" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="TL" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="TL" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=TL&amp;diff=16960&amp;oldid=16959" title="TL">prev</a>)</span><input type="radio" value="16960" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16960" checked="checked" name="diff" id="mw-diff-16960" /> <a href="/index.php?title=TL&amp;oldid=16960" title="TL" class="mw-changeslist-date">08:12, 13 May 2017</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/184.167.193.36" title="Special:Contributions/184.167.193.36" class="mw-userlink mw-anonuserlink">184.167.193.36</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:184.167.193.36&amp;action=edit&amp;redlink=1" class="new" title="User talk:184.167.193.36 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,187 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,187 bytes after change">(-11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_List" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=16959&amp;undo=16960" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=16959" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=16959&amp;oldid=13016" title="TL">prev</a>)</span><input type="radio" value="16959" checked="checked" name="oldid" id="mw-oldid-16959" /><input type="radio" value="16959" name="diff" id="mw-diff-16959" /> <a href="/index.php?title=TL&amp;oldid=16959" title="TL" class="mw-changeslist-date">08:11, 13 May 2017</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/184.167.193.36" title="Special:Contributions/184.167.193.36" class="mw-userlink mw-anonuserlink">184.167.193.36</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:184.167.193.36&amp;action=edit&amp;redlink=1" class="new" title="User talk:184.167.193.36 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,198 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,198 bytes after change">(+163)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_List" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=13016&amp;undo=16959" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=13016" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=13016&amp;oldid=12619" title="TL">prev</a>)</span><input type="radio" value="13016" name="oldid" id="mw-oldid-13016" /><input type="radio" value="13016" name="diff" id="mw-diff-13016" /> <a href="/index.php?title=TL&amp;oldid=13016" title="TL" class="mw-changeslist-date">23:04, 2 July 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,035 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,035 bytes after change">(-24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_List" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=12619&amp;undo=13016" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=12619" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=12619&amp;oldid=12594" title="TL">prev</a>)</span><input type="radio" value="12619" name="oldid" id="mw-oldid-12619" /><input type="radio" value="12619" name="diff" id="mw-diff-12619" /> <a href="/index.php?title=TL&amp;oldid=12619" title="TL" class="mw-changeslist-date">12:05, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,059 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,059 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(consistent header)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=12594&amp;undo=12619" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=12594" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=12594&amp;oldid=12591" title="TL">prev</a>)</span><input type="radio" value="12594" name="oldid" id="mw-oldid-12594" /><input type="radio" value="12594" name="diff" id="mw-diff-12594" /> <a href="/index.php?title=TL&amp;oldid=12594" title="TL" class="mw-changeslist-date">11:41, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,048 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,048 bytes after change">(-294)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(remove redundant list and replace with common TL template)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=12591&amp;undo=12594" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=12591" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=12591&amp;oldid=10859" title="TL">prev</a>)</span><input type="radio" value="12591" name="oldid" id="mw-oldid-12591" /><input type="radio" value="12591" name="diff" id="mw-diff-12591" /> <a href="/index.php?title=TL&amp;oldid=12591" title="TL" class="mw-changeslist-date">11:33, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,342 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,342 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(consistent table css)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=10859&amp;undo=12591" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=10859" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=10859&amp;oldid=9597" title="TL">prev</a>)</span><input type="radio" value="10859" name="oldid" id="mw-oldid-10859" /><input type="radio" value="10859" name="diff" id="mw-diff-10859" /> <a href="/index.php?title=TL&amp;oldid=10859" title="TL" class="mw-changeslist-date">18:53, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,304 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,304 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9597&amp;undo=10859" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9597" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9597&amp;oldid=9596" title="TL">prev</a>)</span><input type="radio" value="9597" name="oldid" id="mw-oldid-9597" /><input type="radio" value="9597" name="diff" id="mw-diff-9597" /> <a href="/index.php?title=TL&amp;oldid=9597" title="TL" class="mw-changeslist-date">19:41, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,294 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,294 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9596&amp;undo=9597" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9596" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9596&amp;oldid=9595" title="TL">prev</a>)</span><input type="radio" value="9596" name="oldid" id="mw-oldid-9596" /><input type="radio" value="9596" name="diff" id="mw-diff-9596" /> <a href="/index.php?title=TL&amp;oldid=9596" title="TL" class="mw-changeslist-date">19:40, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,289 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,289 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9595&amp;undo=9596" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9595" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9595&amp;oldid=9594" title="TL">prev</a>)</span><input type="radio" value="9595" name="oldid" id="mw-oldid-9595" /><input type="radio" value="9595" name="diff" id="mw-diff-9595" /> <a href="/index.php?title=TL&amp;oldid=9595" title="TL" class="mw-changeslist-date">19:36, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,285 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,285 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9594&amp;undo=9595" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9594" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9594&amp;oldid=9593" title="TL">prev</a>)</span><input type="radio" value="9594" name="oldid" id="mw-oldid-9594" /><input type="radio" value="9594" name="diff" id="mw-diff-9594" /> <a href="/index.php?title=TL&amp;oldid=9594" title="TL" class="mw-changeslist-date">19:35, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,283 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,283 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9593&amp;undo=9594" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9593" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9593&amp;oldid=9592" title="TL">prev</a>)</span><input type="radio" value="9593" name="oldid" id="mw-oldid-9593" /><input type="radio" value="9593" name="diff" id="mw-diff-9593" /> <a href="/index.php?title=TL&amp;oldid=9593" title="TL" class="mw-changeslist-date">19:35, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,282 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,282 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9592&amp;undo=9593" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9592" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9592&amp;oldid=9591" title="TL">prev</a>)</span><input type="radio" value="9592" name="oldid" id="mw-oldid-9592" /><input type="radio" value="9592" name="diff" id="mw-diff-9592" /> <a href="/index.php?title=TL&amp;oldid=9592" title="TL" class="mw-changeslist-date">19:32, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,276 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,276 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9591&amp;undo=9592" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9591" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9591&amp;oldid=9568" title="TL">prev</a>)</span><input type="radio" value="9591" name="oldid" id="mw-oldid-9591" /><input type="radio" value="9591" name="diff" id="mw-diff-9591" /> <a href="/index.php?title=TL&amp;oldid=9591" title="TL" class="mw-changeslist-date">19:25, 13 September 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Btims&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Btims (page does not exist)">Btims</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Btims&amp;action=edit&amp;redlink=1" class="new" title="User talk:Btims (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Btims" title="Special:Contributions/Btims">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,269 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,269 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9568&amp;undo=9591" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9568" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9568&amp;oldid=9233" title="TL">prev</a>)</span><input type="radio" value="9568" name="oldid" id="mw-oldid-9568" /><input type="radio" value="9568" name="diff" id="mw-diff-9568" /> <a href="/index.php?title=TL&amp;oldid=9568" title="TL" class="mw-changeslist-date">01:49, 15 August 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:ImmoralFibre&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:ImmoralFibre (page does not exist)">ImmoralFibre</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ImmoralFibre&amp;action=edit&amp;redlink=1" class="new" title="User talk:ImmoralFibre (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ImmoralFibre" title="Special:Contributions/ImmoralFibre">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,267 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,267 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(The Ryu is massive.)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9233&amp;undo=9568" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9233" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9233&amp;oldid=9232" title="TL">prev</a>)</span><input type="radio" value="9233" name="oldid" id="mw-oldid-9233" /><input type="radio" value="9233" name="diff" id="mw-diff-9233" /> <a href="/index.php?title=TL&amp;oldid=9233" title="TL" class="mw-changeslist-date">22:06, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,259 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,259 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9232&amp;undo=9233" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9232" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9232&amp;oldid=9230" title="TL">prev</a>)</span><input type="radio" value="9232" name="oldid" id="mw-oldid-9232" /><input type="radio" value="9232" name="diff" id="mw-diff-9232" /> <a href="/index.php?title=TL&amp;oldid=9232" title="TL" class="mw-changeslist-date">22:05, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,259 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,259 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9230&amp;undo=9232" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9230" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9230&amp;oldid=9186" title="TL">prev</a>)</span><input type="radio" value="9230" name="oldid" id="mw-oldid-9230" /><input type="radio" value="9230" name="diff" id="mw-diff-9230" /> <a href="/index.php?title=TL&amp;oldid=9230" title="TL" class="mw-changeslist-date">22:03, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,241 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,241 bytes after change">(+110)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/TL#Sortable_list" title="TL">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=9186&amp;undo=9230" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=9186" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=9186&amp;oldid=6567" title="TL">prev</a>)</span><input type="radio" value="9186" name="oldid" id="mw-oldid-9186" /><input type="radio" value="9186" name="diff" id="mw-diff-9186" /> <a href="/index.php?title=TL&amp;oldid=9186" title="TL" class="mw-changeslist-date">19:09, 16 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,131 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,131 bytes after change">(+1,384)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=6567&amp;undo=9186" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=6567" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=6567&amp;oldid=2911" title="TL">prev</a>)</span><input type="radio" value="6567" name="oldid" id="mw-oldid-6567" /><input type="radio" value="6567" name="diff" id="mw-diff-6567" /> <a href="/index.php?title=TL&amp;oldid=6567" title="TL" class="mw-changeslist-date">06:56, 13 July 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/67.2.40.158" title="Special:Contributions/67.2.40.158" class="mw-userlink mw-anonuserlink">67.2.40.158</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:67.2.40.158&amp;action=edit&amp;redlink=1" class="new" title="User talk:67.2.40.158 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(747 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="747 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2911&amp;undo=6567" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2911" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2911&amp;oldid=2135" title="TL">prev</a>)</span><input type="radio" value="2911" name="oldid" id="mw-oldid-2911" /><input type="radio" value="2911" name="diff" id="mw-diff-2911" /> <a href="/index.php?title=TL&amp;oldid=2911" title="TL" class="mw-changeslist-date">20:21, 15 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(714 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="714 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected cap ship link)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2135&amp;undo=2911" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2135" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2135&amp;oldid=2043" title="TL">prev</a>)</span><input type="radio" value="2135" name="oldid" id="mw-oldid-2135" /><input type="radio" value="2135" name="diff" id="mw-diff-2135" /> <a href="/index.php?title=TL&amp;oldid=2135" title="TL" class="mw-changeslist-date">13:29, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(700 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="700 bytes after change">(-66)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2043&amp;undo=2135" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2043" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2043&amp;oldid=2042" title="TL">prev</a>)</span><input type="radio" value="2043" name="oldid" id="mw-oldid-2043" /><input type="radio" value="2043" name="diff" id="mw-diff-2043" /> <a href="/index.php?title=TL&amp;oldid=2043" title="TL" class="mw-changeslist-date">09:43, 5 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(766 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="766 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2042&amp;undo=2043" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2042" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2042&amp;oldid=2041" title="TL">prev</a>)</span><input type="radio" value="2042" name="oldid" id="mw-oldid-2042" /><input type="radio" value="2042" name="diff" id="mw-diff-2042" /> <a href="/index.php?title=TL&amp;oldid=2042" title="TL" class="mw-changeslist-date">09:42, 5 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(759 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="759 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2041&amp;undo=2042" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2041" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2041&amp;oldid=2040" title="TL">prev</a>)</span><input type="radio" value="2041" name="oldid" id="mw-oldid-2041" /><input type="radio" value="2041" name="diff" id="mw-diff-2041" /> <a href="/index.php?title=TL&amp;oldid=2041" title="TL" class="mw-changeslist-date">09:42, 5 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(759 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="759 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=2040&amp;undo=2041" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=2040" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=2040&amp;oldid=1189" title="TL">prev</a>)</span><input type="radio" value="2040" name="oldid" id="mw-oldid-2040" /><input type="radio" value="2040" name="diff" id="mw-diff-2040" /> <a href="/index.php?title=TL&amp;oldid=2040" title="TL" class="mw-changeslist-date">09:41, 5 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(759 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="759 bytes after change">(+50)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=1189&amp;undo=2040" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=1189" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=1189&amp;oldid=1188" title="TL">prev</a>)</span><input type="radio" value="1189" name="oldid" id="mw-oldid-1189" /><input type="radio" value="1189" name="diff" id="mw-diff-1189" /> <a href="/index.php?title=TL&amp;oldid=1189" title="TL" class="mw-changeslist-date">10:12, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(709 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="709 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=1188&amp;undo=1189" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=1188" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=1188&amp;oldid=699" title="TL">prev</a>)</span><input type="radio" value="1188" name="oldid" id="mw-oldid-1188" /><input type="radio" value="1188" name="diff" id="mw-diff-1188" /> <a href="/index.php?title=TL&amp;oldid=1188" title="TL" class="mw-changeslist-date">10:09, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(686 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="686 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=699&amp;undo=1188" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=699" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=699&amp;oldid=693" title="TL">prev</a>)</span><input type="radio" value="699" name="oldid" id="mw-oldid-699" /><input type="radio" value="699" name="diff" id="mw-diff-699" /> <a href="/index.php?title=TL&amp;oldid=699" title="TL" class="mw-changeslist-date">23:41, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(668 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="668 bytes after change">(+124)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(more commentary from cache description)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=693&amp;undo=699" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=693" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=693&amp;oldid=689" title="TL">prev</a>)</span><input type="radio" value="693" name="oldid" id="mw-oldid-693" /><input type="radio" value="693" name="diff" id="mw-diff-693" /> <a href="/index.php?title=TL&amp;oldid=693" title="TL" class="mw-changeslist-date">23:16, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(544 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="544 bytes after change">(+227)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore ship list from cache)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=689&amp;undo=693" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=689" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=689&amp;oldid=364" title="TL">prev</a>)</span><input type="radio" value="689" name="oldid" id="mw-oldid-689" /><input type="radio" value="689" name="diff" id="mw-diff-689" /> <a href="/index.php?title=TL&amp;oldid=689" title="TL" class="mw-changeslist-date">23:03, 6 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(317 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="317 bytes after change">(+166)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(appended cached doc description, cache refers to older document for cargo, description is as added.)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=364&amp;undo=689" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=364" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=364&amp;oldid=319" title="TL">prev</a>)</span><input type="radio" value="364" name="oldid" id="mw-oldid-364" /><input type="radio" value="364" name="diff" id="mw-diff-364" /> <a href="/index.php?title=TL&amp;oldid=364" title="TL" class="mw-changeslist-date">20:03, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(151 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="151 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(category)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=319&amp;undo=364" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=319" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=319&amp;oldid=38" title="TL">prev</a>)</span><input type="radio" value="319" name="oldid" id="mw-oldid-319" /><input type="radio" value="319" name="diff" id="mw-diff-319" /> <a href="/index.php?title=TL&amp;oldid=319" title="TL" class="mw-changeslist-date">01:50, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(135 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="135 bytes after change">(+52)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(rewrote to home for TL class ships, link to cargo class article)</span> (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=38&amp;undo=319" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=38" title="TL">cur</a> | <a href="/index.php?title=TL&amp;diff=38&amp;oldid=37" title="TL">prev</a>)</span><input type="radio" value="38" name="oldid" id="mw-oldid-38" /><input type="radio" value="38" name="diff" id="mw-diff-38" /> <a href="/index.php?title=TL&amp;oldid=38" title="TL" class="mw-changeslist-date">17:05, 29 April 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(83 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="83 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=TL&amp;action=edit&amp;undoafter=37&amp;undo=38" title="TL">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=TL&amp;diff=16960&amp;oldid=37" title="TL">cur</a> | prev)</span><input type="radio" value="37" name="oldid" id="mw-oldid-37" /><input type="radio" value="37" name="diff" id="mw-diff-37" /> <a href="/index.php?title=TL&amp;oldid=37" title="TL" class="mw-changeslist-date">17:05, 29 April 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.211.17.11" title="Special:Contributions/87.211.17.11" class="mw-userlink mw-anonuserlink">87.211.17.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.211.17.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.211.17.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(39 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="39 bytes after change">(+39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &#039;The Argon are a race in the X universe.&#039;)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/TL">http://www.x3wiki.com/index.php/TL</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/TL" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:TL&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=TL&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=TL&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=TL&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=TL&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/TL" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/TL" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=TL&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=TL&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":93});});</script></body></html>
