<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<title>Revision history of "Help:Contents" - X3 Wiki</title>
<meta charset="UTF-8" />
<meta name="generator" content="MediaWiki 1.19.1" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Help:Contents&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Help:Contents&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Help:Contents&quot; Atom feed" href="/index.php?title=Help:Contents&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(fa),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}a.new,#quickbar a.new{color:#ba0000}

/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:c88e2bcd56513749bec09a7e29cb3ffa */
</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"Help","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":12,"wgPageName":"Help:Contents","wgTitle":"Contents","wgCurRevisionId":11544,"wgArticleId":10,"wgIsArticle":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgRelevantPageName":"Help:Contents","wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function($){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"externaldiff":0,"externaleditor":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"highlightbroken":1,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"quickbar":5,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"showjumplinks":1,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"watchcreations":0,"watchdefault":0,"watchdeletion":
0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"variant":"en","language":"en","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false});;},{},{});mw.loader.implement("user.tokens",function($){mw.user.tokens.set({"editToken":"+\\","watchToken":false});;},{},{});

/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:74a832f2292f1f4d40d425d223444e78 */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-12 ns-subject page-Help_Contents skin-monobook action-history">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=419115078139333";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="globalWrapper">
<div id="column-content"><div id="content">
	<a id="top"></a>
	<div id="siteNotice">
	<script type='text/javascript'>
<!--//<![CDATA[
   document.MAX_ct0 ='';
   var m3_u = (location.protocol=='https:'?'https://cas.criteo.com/delivery/ajs.php?':'http://cas.criteo.com/delivery/ajs.php?');
   var m3_r = Math.floor(Math.random()*99999999999);
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("zoneid=55244");document.write("&amp;nodis=1");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if ((typeof(document.MAX_ct0) != 'undefined') && (document.MAX_ct0.substring(0,4) == 'http')) {
       document.write ("&amp;ct0=" + escape(document.MAX_ct0));
   }
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'></scr"+"ipt>");
//]]>--></script>
	<br /><div class="fb-like" data-href="http://www.facebook.com/pages/X3-wiki/177021675675938" data-send="true" data-width="450" data-show-faces="false"></div>
	
	<!-- centralNotice loads here --><div id="localNotice" lang="en" dir="ltr"><p>Please support us by liking us on facebook!
</p></div></div>
	<h1 id="firstHeading" class="firstHeading"><span dir="auto">Revision history of "Help:Contents"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Help%3AContents" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>
		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Help:Contents" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input name="year" size="4" value="" id="year" maxlength="4" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input name="deleted" type="checkbox" value="1" id="mw-show-deleted-only" />&#160;<label for="mw-show-deleted-only">Deleted only</label>
<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Help:Contents" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=7933" title="Help:Contents">prev</a>) </span><input type="radio" value="11544" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="11544" checked="checked" name="diff" id="mw-diff-11544" /> <a href="/index.php?title=Help:Contents&amp;oldid=11544" title="Help:Contents">18:05, 30 January 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="5,392 bytes after change">(+293)</span>‎ . .  <span class="comment" dir="auto">(instructions on linking.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=7933&amp;undo=11544" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=7933" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=7933&amp;oldid=7932" title="Help:Contents">prev</a>) </span><input type="radio" value="7933" checked="checked" name="oldid" id="mw-oldid-7933" /><input type="radio" value="7933" name="diff" id="mw-diff-7933" /> <a href="/index.php?title=Help:Contents&amp;oldid=7933" title="Help:Contents">00:22, 17 November 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> . . <span dir="ltr" class="mw-plusminus-neg" title="5,099 bytes after change">(-21)</span>‎ . .  <span class="comment" dir="auto">(oops)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=7932&amp;undo=7933" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=7932" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=7932&amp;oldid=7197" title="Help:Contents">prev</a>) </span><input type="radio" value="7932" name="oldid" id="mw-oldid-7932" /><input type="radio" value="7932" name="diff" id="mw-diff-7932" /> <a href="/index.php?title=Help:Contents&amp;oldid=7932" title="Help:Contents">00:20, 17 November 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> . . <strong dir="ltr" class="mw-plusminus-pos" title="5,120 bytes after change">(+4,226)</strong>‎ . .  <span class="comment" dir="auto">(revert to last good, very sneaky vandals)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=7197&amp;undo=7932" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=7197" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=7197&amp;oldid=6106" title="Help:Contents">prev</a>) </span><input type="radio" value="7197" name="oldid" id="mw-oldid-7197" /><input type="radio" value="7197" name="diff" id="mw-diff-7197" /> <a href="/index.php?title=Help:Contents&amp;oldid=7197" title="Help:Contents">20:58, 11 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/146.243.4.157" title="Special:Contributions/146.243.4.157" class="mw-userlink">146.243.4.157</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:146.243.4.157&amp;action=edit&amp;redlink=1" class="new" title="User talk:146.243.4.157 (page does not exist)">Talk</a>)</span></span>‎ . . <strong dir="ltr" class="mw-plusminus-neg" title="894 bytes after change">(-2,700)</strong>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#Picking_new_page_names" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">Picking new page names</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=6106&amp;undo=7197" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=6106" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=6106&amp;oldid=4349" title="Help:Contents">prev</a>) </span><input type="radio" value="6106" name="oldid" id="mw-oldid-6106" /><input type="radio" value="6106" name="diff" id="mw-diff-6106" /> <a href="/index.php?title=Help:Contents&amp;oldid=6106" title="Help:Contents">04:19, 10 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/187.33.192.178" title="Special:Contributions/187.33.192.178" class="mw-userlink">187.33.192.178</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:187.33.192.178&amp;action=edit&amp;redlink=1" class="new" title="User talk:187.33.192.178 (page does not exist)">Talk</a>)</span></span>‎ . . <strong dir="ltr" class="mw-plusminus-neg" title="3,594 bytes after change">(-1,484)</strong>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#Templates" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">Templates</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4349&amp;undo=6106" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4349" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4349&amp;oldid=4344" title="Help:Contents">prev</a>) </span><input type="radio" value="4349" name="oldid" id="mw-oldid-4349" /><input type="radio" value="4349" name="diff" id="mw-diff-4349" /> <a href="/index.php?title=Help:Contents&amp;oldid=4349" title="Help:Contents">14:19, 23 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="5,078 bytes after change">(+87)</span>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#General_HTML_information" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">General HTML information: </span> color palette</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4344&amp;undo=4349" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4344" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4344&amp;oldid=4332" title="Help:Contents">prev</a>) </span><input type="radio" value="4344" name="oldid" id="mw-oldid-4344" /><input type="radio" value="4344" name="diff" id="mw-diff-4344" /> <a href="/index.php?title=Help:Contents&amp;oldid=4344" title="Help:Contents">14:01, 23 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> . . <span dir="ltr" class="mw-plusminus-pos" title="4,991 bytes after change">(+203)</span>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#Templates" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">Templates: </span> spaces warning</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4332&amp;undo=4344" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4332" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4332&amp;oldid=4319" title="Help:Contents">prev</a>) </span><input type="radio" value="4332" name="oldid" id="mw-oldid-4332" /><input type="radio" value="4332" name="diff" id="mw-diff-4332" /> <a href="/index.php?title=Help:Contents&amp;oldid=4332" title="Help:Contents">13:41, 23 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="4,788 bytes after change">(+271)</span>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#Templates" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">Templates: </span> adv templates</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4319&amp;undo=4332" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4319" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4319&amp;oldid=4316" title="Help:Contents">prev</a>) </span><input type="radio" value="4319" name="oldid" id="mw-oldid-4319" /><input type="radio" value="4319" name="diff" id="mw-diff-4319" /> <a href="/index.php?title=Help:Contents&amp;oldid=4319" title="Help:Contents">16:39, 22 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="4,517 bytes after change">(+372)</span>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#General_HTML_information" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">General HTML information: </span> css link</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4316&amp;undo=4319" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4316" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4316&amp;oldid=4060" title="Help:Contents">prev</a>) </span><input type="radio" value="4316" name="oldid" id="mw-oldid-4316" /><input type="radio" value="4316" name="diff" id="mw-diff-4316" /> <a href="/index.php?title=Help:Contents&amp;oldid=4316" title="Help:Contents">16:21, 22 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="4,145 bytes after change">(+159)</span>‎ . .  <span class="comment" dir="auto">(links to a html tutorial page)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=4060&amp;undo=4316" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=4060" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=4060&amp;oldid=3962" title="Help:Contents">prev</a>) </span><input type="radio" value="4060" name="oldid" id="mw-oldid-4060" /><input type="radio" value="4060" name="diff" id="mw-diff-4060" /> <a href="/index.php?title=Help:Contents&amp;oldid=4060" title="Help:Contents">13:59, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="3,986 bytes after change">(+452)</span>‎ . .  <span class="comment" dir="auto">(new page names)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=3962&amp;undo=4060" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=3962" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=3962&amp;oldid=3815" title="Help:Contents">prev</a>) </span><input type="radio" value="3962" name="oldid" id="mw-oldid-3962" /><input type="radio" value="3962" name="diff" id="mw-diff-3962" /> <a href="/index.php?title=Help:Contents&amp;oldid=3962" title="Help:Contents">18:59, 4 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> . . <span dir="ltr" class="mw-plusminus-pos" title="3,534 bytes after change">(+89)</span>‎ . .  <span class="comment" dir="auto">(list out contents of editing cheat sheet)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=3815&amp;undo=3962" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=3815" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=3815&amp;oldid=3814" title="Help:Contents">prev</a>) </span><input type="radio" value="3815" name="oldid" id="mw-oldid-3815" /><input type="radio" value="3815" name="diff" id="mw-diff-3815" /> <a href="/index.php?title=Help:Contents&amp;oldid=3815" title="Help:Contents">13:56, 27 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/216.30.171.130" title="Special:Contributions/216.30.171.130" class="mw-userlink">216.30.171.130</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:216.30.171.130&amp;action=edit&amp;redlink=1" class="new" title="User talk:216.30.171.130 (page does not exist)">Talk</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-neg" title="3,445 bytes after change">(-129)</span>‎ . .  <span class="comment" dir="auto">(removed collapsed table test, not functioning.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=3814&amp;undo=3815" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=3814" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=3814&amp;oldid=553" title="Help:Contents">prev</a>) </span><input type="radio" value="3814" name="oldid" id="mw-oldid-3814" /><input type="radio" value="3814" name="diff" id="mw-diff-3814" /> <a href="/index.php?title=Help:Contents&amp;oldid=3814" title="Help:Contents">13:55, 27 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/216.30.171.130" title="Special:Contributions/216.30.171.130" class="mw-userlink">216.30.171.130</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:216.30.171.130&amp;action=edit&amp;redlink=1" class="new" title="User talk:216.30.171.130 (page does not exist)">Talk</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="3,574 bytes after change">(+129)</span>‎ . .  <span class="comment" dir="auto">(collapsed table test, might be useful for spoiler concealment)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=553&amp;undo=3814" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=553" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=553&amp;oldid=552" title="Help:Contents">prev</a>) </span><input type="radio" value="553" name="oldid" id="mw-oldid-553" /><input type="radio" value="553" name="diff" id="mw-diff-553" /> <a href="/index.php?title=Help:Contents&amp;oldid=553" title="Help:Contents">15:48, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="3,445 bytes after change">(+30)</span>‎ . .  <span class="comment" dir="auto">(corrected shield links)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=552&amp;undo=553" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=552" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=552&amp;oldid=551" title="Help:Contents">prev</a>) </span><input type="radio" value="552" name="oldid" id="mw-oldid-552" /><input type="radio" value="552" name="diff" id="mw-diff-552" /> <a href="/index.php?title=Help:Contents&amp;oldid=552" title="Help:Contents">15:47, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="3,415 bytes after change">(+167)</span>‎ . .  <span class="comment" dir="auto">(<a href="/index.php/Help:Contents#Some_basic_commands" title="Help:Contents">→</a>‎<span dir="auto"><span class="autocomment">Some basic commands: </span> added link alias info</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=551&amp;undo=552" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=551" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=551&amp;oldid=546" title="Help:Contents">prev</a>) </span><input type="radio" value="551" name="oldid" id="mw-oldid-551" /><input type="radio" value="551" name="diff" id="mw-diff-551" /> <a href="/index.php?title=Help:Contents&amp;oldid=551" title="Help:Contents">15:44, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="3,248 bytes after change">(+24)</span>‎ . .  <span class="comment" dir="auto">(corrected ST cargo class link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=546&amp;undo=551" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=546" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=546&amp;oldid=542" title="Help:Contents">prev</a>) </span><input type="radio" value="546" name="oldid" id="mw-oldid-546" /><input type="radio" value="546" name="diff" id="mw-diff-546" /> <a href="/index.php?title=Help:Contents&amp;oldid=546" title="Help:Contents">15:36, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <strong dir="ltr" class="mw-plusminus-pos" title="3,224 bytes after change">(+688)</strong>‎ . .  <span class="comment" dir="auto">(category element fleshed out templates a little.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=542&amp;undo=546" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=542" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=542&amp;oldid=541" title="Help:Contents">prev</a>) </span><input type="radio" value="542" name="oldid" id="mw-oldid-542" /><input type="radio" value="542" name="diff" id="mw-diff-542" /> <a href="/index.php?title=Help:Contents&amp;oldid=542" title="Help:Contents">15:06, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <strong dir="ltr" class="mw-plusminus-pos" title="2,536 bytes after change">(+978)</strong>‎ . .  <span class="comment" dir="auto">(template addition.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=541&amp;undo=542" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=541" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=541&amp;oldid=528" title="Help:Contents">prev</a>) </span><input type="radio" value="541" name="oldid" id="mw-oldid-541" /><input type="radio" value="541" name="diff" id="mw-diff-541" /> <a href="/index.php?title=Help:Contents&amp;oldid=541" title="Help:Contents">14:54, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,558 bytes after change">(+153)</span>‎ . .  <span class="comment" dir="auto">(link to wiki help article on wikitables)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=528&amp;undo=541" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=528" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=528&amp;oldid=86" title="Help:Contents">prev</a>) </span><input type="radio" value="528" name="oldid" id="mw-oldid-528" /><input type="radio" value="528" name="diff" id="mw-diff-528" /> <a href="/index.php?title=Help:Contents&amp;oldid=528" title="Help:Contents">13:53, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,405 bytes after change">(+25)</span>‎ . .  <span class="comment" dir="auto">(anchor for cheat sheet)</span> (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=86&amp;undo=528" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=86" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=86&amp;oldid=50" title="Help:Contents">prev</a>) </span><input type="radio" value="86" name="oldid" id="mw-oldid-86" /><input type="radio" value="86" name="diff" id="mw-diff-86" /> <a href="/index.php?title=Help:Contents&amp;oldid=86" title="Help:Contents">15:29, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,380 bytes after change">(+104)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=50&amp;undo=86" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=50" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=50&amp;oldid=49" title="Help:Contents">prev</a>) </span><input type="radio" value="50" name="oldid" id="mw-oldid-50" /><input type="radio" value="50" name="diff" id="mw-diff-50" /> <a href="/index.php?title=Help:Contents&amp;oldid=50" title="Help:Contents">14:01, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,276 bytes after change">(+16)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=49&amp;undo=50" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=49" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=49&amp;oldid=48" title="Help:Contents">prev</a>) </span><input type="radio" value="49" name="oldid" id="mw-oldid-49" /><input type="radio" value="49" name="diff" id="mw-diff-49" /> <a href="/index.php?title=Help:Contents&amp;oldid=49" title="Help:Contents">14:00, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-neg" title="1,260 bytes after change">(-1)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=48&amp;undo=49" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=48" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=48&amp;oldid=47" title="Help:Contents">prev</a>) </span><input type="radio" value="48" name="oldid" id="mw-oldid-48" /><input type="radio" value="48" name="diff" id="mw-diff-48" /> <a href="/index.php?title=Help:Contents&amp;oldid=48" title="Help:Contents">13:59, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,261 bytes after change">(+5)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=47&amp;undo=48" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=47" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=47&amp;oldid=46" title="Help:Contents">prev</a>) </span><input type="radio" value="47" name="oldid" id="mw-oldid-47" /><input type="radio" value="47" name="diff" id="mw-diff-47" /> <a href="/index.php?title=Help:Contents&amp;oldid=47" title="Help:Contents">13:58, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,256 bytes after change">(+18)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=46&amp;undo=47" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=46" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=46&amp;oldid=45" title="Help:Contents">prev</a>) </span><input type="radio" value="46" name="oldid" id="mw-oldid-46" /><input type="radio" value="46" name="diff" id="mw-diff-46" /> <a href="/index.php?title=Help:Contents&amp;oldid=46" title="Help:Contents">13:58, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-neg" title="1,238 bytes after change">(-13)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=45&amp;undo=46" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=45" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=45&amp;oldid=44" title="Help:Contents">prev</a>) </span><input type="radio" value="45" name="oldid" id="mw-oldid-45" /><input type="radio" value="45" name="diff" id="mw-diff-45" /> <a href="/index.php?title=Help:Contents&amp;oldid=45" title="Help:Contents">13:57, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,251 bytes after change">(+7)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=44&amp;undo=45" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=44" title="Help:Contents">cur</a> | <a href="/index.php?title=Help:Contents&amp;diff=44&amp;oldid=43" title="Help:Contents">prev</a>) </span><input type="radio" value="44" name="oldid" id="mw-oldid-44" /><input type="radio" value="44" name="diff" id="mw-diff-44" /> <a href="/index.php?title=Help:Contents&amp;oldid=44" title="Help:Contents">13:57, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <span dir="ltr" class="mw-plusminus-pos" title="1,244 bytes after change">(+18)</span>‎ . .  (<span class="mw-history-undo"><a href="/index.php?title=Help:Contents&amp;action=edit&amp;undoafter=43&amp;undo=44" title="Help:Contents">undo</a></span>) </li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Help:Contents&amp;diff=11544&amp;oldid=43" title="Help:Contents">cur</a> | prev) </span><input type="radio" value="43" name="oldid" id="mw-oldid-43" /><input type="radio" value="43" name="diff" id="mw-diff-43" /> <a href="/index.php?title=Help:Contents&amp;oldid=43" title="Help:Contents">13:56, 1 May 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ . . <strong dir="ltr" class="mw-plusminus-pos" title="1,226 bytes after change">(+1,226)</strong>‎ . .  <span class="comment" dir="auto">(Created page with &#039;Some basic commands:  Text: hi   text with link to other page <a href="/index.php?title=Hi&amp;action=edit&amp;redlink=1" class="new" title="Hi (page does not exist)">hi</a> If the page doesnt excist when you click on the link it will ask you if you want to make it.  Best thing for …&#039;)</span> </li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Help:Contents">http://x3wiki.com/index.php/Help:Contents</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<div id="p-cactions" class="portlet">
		<h5>Views</h5>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-help" class="selected"><a href="/index.php/Help:Contents" primary="1" context="subject" title="View the help page [c]" accesskey="c">Help page</a></li>
				<li id="ca-talk"><a href="/index.php/Help_talk:Contents" primary="1" context="talk" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Help:Contents&amp;action=edit" primary="1" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Help:Contents&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal">
		<h5>Personal tools</h5>
		<div class="pBody">
			<ul>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Help%3AContents&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in / create account</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation">
		<h5>Navigation</h5>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="/index.php/Help:Contents" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>
	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict">
		<h5>X3 Terran Conflict</h5>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>
	<div class="generated-sidebar portlet" id="p-Links">
		<h5>Links</h5>
		<div class='pBody'>
			<ul>
				<li id="n-Buy-X3-Albion-Prelude.21"><a href="http://www.gamersgate.co.uk/DD-X3AP/x3-albion-prelude-expansion-pack?caff=4628051%7C" rel="nofollow">Buy X3 Albion Prelude!</a></li>
				<li id="n-MMOServerstatus-.5BEN.5D"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMOServerstatus [EN]</a></li>
			</ul>
		</div>
	</div>
	<div id="p-search" class="portlet">
		<h5><label for="searchInput">Search</label></h5>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb">
		<h5>Toolbox</h5>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Help:Contents" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Help:Contents" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Help:Contents&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li><li><a href='http://installatron.com/apps/mediawiki' target='_blank' title='Installatron enables webmasters to instantly install and upgrade MediaWiki and other web applications.'>Powered by Installatron</a></li>
	</ul>
</div>
</div>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.page.ready"], null, true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.304 secs. --></body></html>