<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Rastar Oil" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Rastar_Oil&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Rastar_Oil&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Rastar Oil&quot; Atom feed" href="/index.php?title=Rastar_Oil&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Rastar_Oil","wgTitle":"Rastar Oil","wgCurRevisionId":15575,"wgRevisionId":0,"wgArticleId":1053,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Rastar_Oil","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Rastar_Oil skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Rastar Oil"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Rastar+Oil" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Rastar_Oil" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2014" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Rastar_Oil" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10903" title="Rastar Oil">prev</a>)</span><input type="radio" value="15575" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="15575" checked="checked" name="diff" id="mw-diff-15575" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=15575" title="Rastar Oil" class="mw-changeslist-date">08:07, 4 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">Talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,034 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,034 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(add a Split navbox)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10903&amp;undo=15575" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10903" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10903&amp;oldid=10336" title="Rastar Oil">prev</a>)</span><input type="radio" value="10903" checked="checked" name="oldid" id="mw-oldid-10903" /><input type="radio" value="10903" name="diff" id="mw-diff-10903" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10903" title="Rastar Oil" class="mw-changeslist-date">14:34, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,016 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,016 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added Waretable template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10336&amp;undo=10903" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10336" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10336&amp;oldid=10327" title="Rastar Oil">prev</a>)</span><input type="radio" value="10336" name="oldid" id="mw-oldid-10336" /><input type="radio" value="10336" name="diff" id="mw-diff-10336" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10336" title="Rastar Oil" class="mw-changeslist-date">19:47, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,002 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,002 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Disintegrator Rifles Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10327&amp;undo=10336" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10327" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10327&amp;oldid=10322" title="Rastar Oil">prev</a>)</span><input type="radio" value="10327" name="oldid" id="mw-oldid-10327" /><input type="radio" value="10327" name="diff" id="mw-diff-10327" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10327" title="Rastar Oil" class="mw-changeslist-date">19:42, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,972 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,972 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Rehabilitation Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10322&amp;undo=10327" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10322" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10322&amp;oldid=10299" title="Rastar Oil">prev</a>)</span><input type="radio" value="10322" name="oldid" id="mw-oldid-10322" /><input type="radio" value="10322" name="diff" id="mw-diff-10322" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10322" title="Rastar Oil" class="mw-changeslist-date">19:35, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,943 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,943 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mobile Drilling System Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10299&amp;undo=10322" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10299" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10299&amp;oldid=10287" title="Rastar Oil">prev</a>)</span><input type="radio" value="10299" name="oldid" id="mw-oldid-10299" /><input type="radio" value="10299" name="diff" id="mw-diff-10299" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10299" title="Rastar Oil" class="mw-changeslist-date">18:39, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,901 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,901 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Cluster Flak Array Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10287&amp;undo=10299" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10287" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10287&amp;oldid=10277" title="Rastar Oil">prev</a>)</span><input type="radio" value="10287" name="oldid" id="mw-oldid-10287" /><input type="radio" value="10287" name="diff" id="mw-diff-10287" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10287" title="Rastar Oil" class="mw-changeslist-date">12:35, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,865 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,865 bytes after change">(+32)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tracker Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10277&amp;undo=10287" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10277" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10277&amp;oldid=10266" title="Rastar Oil">prev</a>)</span><input type="radio" value="10277" name="oldid" id="mw-oldid-10277" /><input type="radio" value="10277" name="diff" id="mw-diff-10277" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10277" title="Rastar Oil" class="mw-changeslist-date">12:29, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,833 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,833 bytes after change">(+48)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Tomahawk Missile Manufacturing Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10266&amp;undo=10277" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10266" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10266&amp;oldid=10255" title="Rastar Oil">prev</a>)</span><input type="radio" value="10266" name="oldid" id="mw-oldid-10266" /><input type="radio" value="10266" name="diff" id="mw-diff-10266" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10266" title="Rastar Oil" class="mw-changeslist-date">12:23, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,785 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,785 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Swarm Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10255&amp;undo=10266" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10255" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10255&amp;oldid=10232" title="Rastar Oil">prev</a>)</span><input type="radio" value="10255" name="oldid" id="mw-oldid-10255" /><input type="radio" value="10255" name="diff" id="mw-diff-10255" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10255" title="Rastar Oil" class="mw-changeslist-date">12:09, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,741 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,741 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; SQUASH Mine Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10232&amp;undo=10255" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10232" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10232&amp;oldid=10222" title="Rastar Oil">prev</a>)</span><input type="radio" value="10232" name="oldid" id="mw-oldid-10232" /><input type="radio" value="10232" name="diff" id="mw-diff-10232" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10232" title="Rastar Oil" class="mw-changeslist-date">11:49, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,710 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,710 bytes after change">(+48)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Image Recognition Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10222&amp;undo=10232" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10222" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10222&amp;oldid=10208" title="Rastar Oil">prev</a>)</span><input type="radio" value="10222" name="oldid" id="mw-oldid-10222" /><input type="radio" value="10222" name="diff" id="mw-diff-10222" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10222" title="Rastar Oil" class="mw-changeslist-date">11:38, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,662 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,662 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; High Yield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10208&amp;undo=10222" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10208" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10208&amp;oldid=10191" title="Rastar Oil">prev</a>)</span><input type="radio" value="10208" name="oldid" id="mw-oldid-10208" /><input type="radio" value="10208" name="diff" id="mw-diff-10208" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10208" title="Rastar Oil" class="mw-changeslist-date">11:30, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,621 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,621 bytes after change">(+47)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Hammer Torpedo Fabrication Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10191&amp;undo=10208" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10191" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10191&amp;oldid=10176" title="Rastar Oil">prev</a>)</span><input type="radio" value="10191" name="oldid" id="mw-oldid-10191" /><input type="radio" value="10191" name="diff" id="mw-diff-10191" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10191" title="Rastar Oil" class="mw-changeslist-date">11:09, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,574 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,574 bytes after change">(+45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Flail Missile Production Facility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10176&amp;undo=10191" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10176" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10176&amp;oldid=10160" title="Rastar Oil">prev</a>)</span><input type="radio" value="10176" name="oldid" id="mw-oldid-10176" /><input type="radio" value="10176" name="diff" id="mw-diff-10176" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10176" title="Rastar Oil" class="mw-changeslist-date">10:59, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,529 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,529 bytes after change">(+47)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Dumbfire Missile Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10160&amp;undo=10176" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10160" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10160&amp;oldid=10143" title="Rastar Oil">prev</a>)</span><input type="radio" value="10160" name="oldid" id="mw-oldid-10160" /><input type="radio" value="10160" name="diff" id="mw-diff-10160" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10160" title="Rastar Oil" class="mw-changeslist-date">01:27, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,482 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,482 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ammunition Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10143&amp;undo=10160" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10143" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10143&amp;oldid=10135" title="Rastar Oil">prev</a>)</span><input type="radio" value="10143" name="oldid" id="mw-oldid-10143" /><input type="radio" value="10143" name="diff" id="mw-diff-10143" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10143" title="Rastar Oil" class="mw-changeslist-date">01:13, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,452 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,452 bytes after change">(+42)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Shield Production Facility 1MJ)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10135&amp;undo=10143" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10135" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10135&amp;oldid=10114" title="Rastar Oil">prev</a>)</span><input type="radio" value="10135" name="oldid" id="mw-oldid-10135" /><input type="radio" value="10135" name="diff" id="mw-diff-10135" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10135" title="Rastar Oil" class="mw-changeslist-date">00:39, 7 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,410 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,410 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Satellite Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10114&amp;undo=10135" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10114" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10114&amp;oldid=10101" title="Rastar Oil">prev</a>)</span><input type="radio" value="10114" name="oldid" id="mw-oldid-10114" /><input type="radio" value="10114" name="diff" id="mw-diff-10114" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10114" title="Rastar Oil" class="mw-changeslist-date">23:57, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,381 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,381 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Photon Pulse Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10101&amp;undo=10114" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10101" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10101&amp;oldid=10093" title="Rastar Oil">prev</a>)</span><input type="radio" value="10101" name="oldid" id="mw-oldid-10101" /><input type="radio" value="10101" name="diff" id="mw-diff-10101" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10101" title="Rastar Oil" class="mw-changeslist-date">23:47, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,344 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,344 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Phased Repeater Gun Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10093&amp;undo=10101" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10093" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10093&amp;oldid=10084" title="Rastar Oil">prev</a>)</span><input type="radio" value="10093" name="oldid" id="mw-oldid-10093" /><input type="radio" value="10093" name="diff" id="mw-diff-10093" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10093" title="Rastar Oil" class="mw-changeslist-date">23:43, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,307 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,307 bytes after change">(+45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Particle Accelerator Cannon Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10084&amp;undo=10093" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10084" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10084&amp;oldid=10061" title="Rastar Oil">prev</a>)</span><input type="radio" value="10084" name="oldid" id="mw-oldid-10084" /><input type="radio" value="10084" name="diff" id="mw-diff-10084" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10084" title="Rastar Oil" class="mw-changeslist-date">23:35, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,262 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,262 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Medium Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10061&amp;undo=10084" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10061" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10061&amp;oldid=10038" title="Rastar Oil">prev</a>)</span><input type="radio" value="10061" name="oldid" id="mw-oldid-10061" /><input type="radio" value="10061" name="diff" id="mw-diff-10061" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10061" title="Rastar Oil" class="mw-changeslist-date">23:08, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,228 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,228 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Mass Driver Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10038&amp;undo=10061" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10038" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10038&amp;oldid=10029" title="Rastar Oil">prev</a>)</span><input type="radio" value="10038" name="oldid" id="mw-oldid-10038" /><input type="radio" value="10038" name="diff" id="mw-diff-10038" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10038" title="Rastar Oil" class="mw-changeslist-date">21:27, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,199 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,199 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Light Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10029&amp;undo=10038" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10029" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10029&amp;oldid=10020" title="Rastar Oil">prev</a>)</span><input type="radio" value="10029" name="oldid" id="mw-oldid-10029" /><input type="radio" value="10029" name="diff" id="mw-diff-10029" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10029" title="Rastar Oil" class="mw-changeslist-date">21:21, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,156 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,156 bytes after change">(+30)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Lasertower Factory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=10020&amp;undo=10029" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=10020" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=10020&amp;oldid=9991" title="Rastar Oil">prev</a>)</span><input type="radio" value="10020" name="oldid" id="mw-oldid-10020" /><input type="radio" value="10020" name="diff" id="mw-diff-10020" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=10020" title="Rastar Oil" class="mw-changeslist-date">21:15, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,126 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,126 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Ion Shard Railgun Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9991&amp;undo=10020" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9991" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9991&amp;oldid=9959" title="Rastar Oil">prev</a>)</span><input type="radio" value="9991" name="oldid" id="mw-oldid-9991" /><input type="radio" value="9991" name="diff" id="mw-diff-9991" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9991" title="Rastar Oil" class="mw-changeslist-date">20:39, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,097 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,097 bytes after change">(+37)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Impulse Ray Emitter Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9959&amp;undo=9991" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9959" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9959&amp;oldid=9945" title="Rastar Oil">prev</a>)</span><input type="radio" value="9959" name="oldid" id="mw-oldid-9959" /><input type="radio" value="9959" name="diff" id="mw-diff-9959" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9959" title="Rastar Oil" class="mw-changeslist-date">13:24, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,060 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,060 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; High Energy Plasma Thrower Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9945&amp;undo=9959" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9945" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9945&amp;oldid=9936" title="Rastar Oil">prev</a>)</span><input type="radio" value="9945" name="oldid" id="mw-oldid-9945" /><input type="radio" value="9945" name="diff" id="mw-diff-9945" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9945" title="Rastar Oil" class="mw-changeslist-date">13:06, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,016 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,016 bytes after change">(+33)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Heavy Weapons Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9936&amp;undo=9945" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9936" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9936&amp;oldid=9903" title="Rastar Oil">prev</a>)</span><input type="radio" value="9936" name="oldid" id="mw-oldid-9936" /><input type="radio" value="9936" name="diff" id="mw-diff-9936" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9936" title="Rastar Oil" class="mw-changeslist-date">12:59, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(983 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="983 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Heavy Shield Production Complex)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9903&amp;undo=9936" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9903" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9903&amp;oldid=9887" title="Rastar Oil">prev</a>)</span><input type="radio" value="9903" name="oldid" id="mw-oldid-9903" /><input type="radio" value="9903" name="diff" id="mw-diff-9903" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9903" title="Rastar Oil" class="mw-changeslist-date">12:16, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(940 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="940 bytes after change">(+46)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Concussion Impulse Generator Forge)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9887&amp;undo=9903" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9887" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9887&amp;oldid=9776" title="Rastar Oil">prev</a>)</span><input type="radio" value="9887" name="oldid" id="mw-oldid-9887" /><input type="radio" value="9887" name="diff" id="mw-diff-9887" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9887" title="Rastar Oil" class="mw-changeslist-date">10:54, 6 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(894 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="894 bytes after change">(-43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Secondary Resource&#039; Space Jewellery)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9776&amp;undo=9887" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9776" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9776&amp;oldid=9726" title="Rastar Oil">prev</a>)</span><input type="radio" value="9776" name="oldid" id="mw-oldid-9776" /><input type="radio" value="9776" name="diff" id="mw-diff-9776" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9776" title="Rastar Oil" class="mw-changeslist-date">17:30, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(937 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="937 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(changed &#039;Sold by&#039; to &#039;Produced by&#039;)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9726&amp;undo=9776" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9726" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9726&amp;oldid=9717" title="Rastar Oil">prev</a>)</span><input type="radio" value="9726" name="oldid" id="mw-oldid-9726" /><input type="radio" value="9726" name="diff" id="mw-diff-9726" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9726" title="Rastar Oil" class="mw-changeslist-date">15:22, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(933 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="933 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Quantum Tube Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9717&amp;undo=9726" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9717" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9717&amp;oldid=9709" title="Rastar Oil">prev</a>)</span><input type="radio" value="9717" name="oldid" id="mw-oldid-9717" /><input type="radio" value="9717" name="diff" id="mw-diff-9717" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9717" title="Rastar Oil" class="mw-changeslist-date">15:17, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(905 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="905 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Low-yield Sidearms Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9709&amp;undo=9717" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9709" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9709&amp;oldid=9703" title="Rastar Oil">prev</a>)</span><input type="radio" value="9709" name="oldid" id="mw-oldid-9709" /><input type="radio" value="9709" name="diff" id="mw-diff-9709" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9709" title="Rastar Oil" class="mw-changeslist-date">15:13, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(871 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="871 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Crystal Fab)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9703&amp;undo=9709" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9703" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9703&amp;oldid=9697" title="Rastar Oil">prev</a>)</span><input type="radio" value="9703" name="oldid" id="mw-oldid-9703" /><input type="radio" value="9703" name="diff" id="mw-diff-9703" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9703" title="Rastar Oil" class="mw-changeslist-date">15:11, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(848 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="848 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Computer Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9697&amp;undo=9703" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9697" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9697&amp;oldid=9651" title="Rastar Oil">prev</a>)</span><input type="radio" value="9697" name="oldid" id="mw-oldid-9697" /><input type="radio" value="9697" name="diff" id="mw-diff-9697" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9697" title="Rastar Oil" class="mw-changeslist-date">15:06, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(822 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="822 bytes after change">(-40)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Primary Resource&#039; Chip Plant)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9651&amp;undo=9697" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9651" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9651&amp;oldid=9640" title="Rastar Oil">prev</a>)</span><input type="radio" value="9651" name="oldid" id="mw-oldid-9651" /><input type="radio" value="9651" name="diff" id="mw-diff-9651" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9651" title="Rastar Oil" class="mw-changeslist-date">14:27, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(862 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="862 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=9640&amp;undo=9651" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=9640" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=9640&amp;oldid=7389" title="Rastar Oil">prev</a>)</span><input type="radio" value="9640" name="oldid" id="mw-oldid-9640" /><input type="radio" value="9640" name="diff" id="mw-diff-9640" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=9640" title="Rastar Oil" class="mw-changeslist-date">14:19, 5 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(863 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="863 bytes after change">(+339)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Sold by&#039; Rastar Refinery)</span> (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=7389&amp;undo=9640" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=7389" title="Rastar Oil">cur</a> | <a href="/index.php?title=Rastar_Oil&amp;diff=7389&amp;oldid=4252" title="Rastar Oil">prev</a>)</span><input type="radio" value="7389" name="oldid" id="mw-oldid-7389" /><input type="radio" value="7389" name="diff" id="mw-diff-7389" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=7389" title="Rastar Oil" class="mw-changeslist-date">17:12, 18 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/195.58.83.110" title="Special:Contributions/195.58.83.110" class="mw-userlink">195.58.83.110</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:195.58.83.110&amp;action=edit&amp;redlink=1" class="new" title="User talk:195.58.83.110 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(524 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="524 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Rastar_Oil&amp;action=edit&amp;undoafter=4252&amp;undo=7389" title="Rastar Oil">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Rastar_Oil&amp;diff=15575&amp;oldid=4252" title="Rastar Oil">cur</a> | prev)</span><input type="radio" value="4252" name="oldid" id="mw-oldid-4252" /><input type="radio" value="4252" name="diff" id="mw-diff-4252" /> <a href="/index.php?title=Rastar_Oil&amp;oldid=4252" title="Rastar Oil" class="mw-changeslist-date">14:28, 17 November 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/75.102.168.166" title="Special:Contributions/75.102.168.166" class="mw-userlink">75.102.168.166</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:75.102.168.166&amp;action=edit&amp;redlink=1" class="new" title="User talk:75.102.168.166 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(523 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="523 bytes after change">(+523)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &quot;{{Infobox open}} {{Infobox ware |ware= Rastar Oil |cargoclass=M |volume=6 |minprice=252 |aveprice=484 |maxprice=716 }} {{Infobox close}} ==Overview== Rastar is an oil produced fr...&quot;)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Rastar_Oil">http://x3wiki.com/index.php/Rastar_Oil</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Rastar_Oil" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Rastar_Oil&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Rastar_Oil&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Rastar_Oil&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-anonuserpage"><a href="/index.php/User:207.241.237.233" class="new" title="The user page for the IP address you are editing as [.]" accesskey=".">207.241.237.233</a></li>
				<li id="pt-anontalk"><a href="/index.php/User_talk:207.241.237.233" class="new" title="Discussion about edits from this IP address [n]" accesskey="n">Talk for this IP address</a></li>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Rastar+Oil&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-anonlogin"><a href="/index.php?title=Special:UserLogin&amp;returnto=Rastar+Oil&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Buy-X3-Albion-Prelude.21"><a href="http://www.gamersgate.co.uk/DD-X3AP/x3-albion-prelude-expansion-pack?caff=4628051%7C" rel="nofollow">Buy X3 Albion Prelude!</a></li>
				<li id="n-MMOServerstatus-.5BEN.5D"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMOServerstatus [EN]</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Rastar_Oil" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Rastar_Oil" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Rastar_Oil&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Rastar_Oil&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.405 secs. --></body></html>