<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "M1" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"M1","wgTitle":"M1","wgCurRevisionId":14184,"wgRevisionId":0,"wgArticleId":70,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"M1","wgRelevantArticleId":70,"wgRequestId":"WkUGiFkfZokAAAopE0IAAAAC","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=M1&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=M1&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;M1&quot; Atom feed" href="/index.php?title=M1&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-M1 rootpage-M1 skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "M1"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=M1" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="M1" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="M1" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=M1&amp;diff=14184&amp;oldid=14013" title="M1">prev</a>)</span><input type="radio" value="14184" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14184" checked="checked" name="diff" id="mw-diff-14184" /> <a href="/index.php?title=M1&amp;oldid=14184" title="M1" class="mw-changeslist-date">20:22, 11 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,218 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,218 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_List" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=14013&amp;undo=14184" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=14013" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=14013&amp;oldid=14012" title="M1">prev</a>)</span><input type="radio" value="14013" checked="checked" name="oldid" id="mw-oldid-14013" /><input type="radio" value="14013" name="diff" id="mw-diff-14013" /> <a href="/index.php?title=M1&amp;oldid=14013" title="M1" class="mw-changeslist-date">11:45, 27 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,216 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,216 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_List" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=14012&amp;undo=14013" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=14012" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=14012&amp;oldid=13998" title="M1">prev</a>)</span><input type="radio" value="14012" name="oldid" id="mw-oldid-14012" /><input type="radio" value="14012" name="diff" id="mw-diff-14012" /> <a href="/index.php?title=M1&amp;oldid=14012" title="M1" class="mw-changeslist-date">11:44, 27 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,214 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,214 bytes after change">(-157)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_List" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=13998&amp;undo=14012" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=13998" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=13998&amp;oldid=13046" title="M1">prev</a>)</span><input type="radio" value="13998" name="oldid" id="mw-oldid-13998" /><input type="radio" value="13998" name="diff" id="mw-diff-13998" /> <a href="/index.php?title=M1&amp;oldid=13998" title="M1" class="mw-changeslist-date">07:10, 24 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,371 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,371 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=13046&amp;undo=13998" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=13046" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=13046&amp;oldid=13004" title="M1">prev</a>)</span><input type="radio" value="13046" name="oldid" id="mw-oldid-13046" /><input type="radio" value="13046" name="diff" id="mw-diff-13046" /> <a href="/index.php?title=M1&amp;oldid=13046" title="M1" class="mw-changeslist-date">02:44, 15 July 2013</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,371 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,371 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Modified text, added missing prices for Woden and Odin)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=13004&amp;undo=13046" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=13004" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=13004&amp;oldid=12606" title="M1">prev</a>)</span><input type="radio" value="13004" name="oldid" id="mw-oldid-13004" /><input type="radio" value="13004" name="diff" id="mw-diff-13004" /> <a href="/index.php?title=M1&amp;oldid=13004" title="M1" class="mw-changeslist-date">21:58, 2 July 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,352 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,352 bytes after change">(-24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_List" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable List</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=12606&amp;undo=13004" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=12606" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=12606&amp;oldid=12605" title="M1">prev</a>)</span><input type="radio" value="12606" name="oldid" id="mw-oldid-12606" /><input type="radio" value="12606" name="diff" id="mw-diff-12606" /> <a href="/index.php?title=M1&amp;oldid=12606" title="M1" class="mw-changeslist-date">10:54, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,376 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,376 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(order list alphabetically by race)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=12605&amp;undo=12606" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=12605" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=12605&amp;oldid=12604" title="M1">prev</a>)</span><input type="radio" value="12605" name="oldid" id="mw-oldid-12605" /><input type="radio" value="12605" name="diff" id="mw-diff-12605" /> <a href="/index.php?title=M1&amp;oldid=12605" title="M1" class="mw-changeslist-date">10:49, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,375 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,375 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(using M1 template. Not removing list because it right now has some additional info (boardable vs not) that template doesn&#039;t yet have)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=12604&amp;undo=12605" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=12604" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=12604&amp;oldid=10967" title="M1">prev</a>)</span><input type="radio" value="12604" name="oldid" id="mw-oldid-12604" /><input type="radio" value="12604" name="diff" id="mw-diff-12604" /> <a href="/index.php?title=M1&amp;oldid=12604" title="M1" class="mw-changeslist-date">10:48, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,352 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,352 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(consistent table css and header)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=10967&amp;undo=12604" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=10967" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=10967&amp;oldid=10962" title="M1">prev</a>)</span><input type="radio" value="10967" name="oldid" id="mw-oldid-10967" /><input type="radio" value="10967" name="diff" id="mw-diff-10967" /> <a href="/index.php?title=M1&amp;oldid=10967" title="M1" class="mw-changeslist-date">23:08, 5 November 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Kran31&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Kran31 (page does not exist)">Kran31</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Kran31&amp;action=edit&amp;redlink=1" class="new" title="User talk:Kran31 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Kran31" title="Special:Contributions/Kran31">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,337 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,337 bytes after change">(-142)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=10962&amp;undo=10967" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=10962" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=10962&amp;oldid=10961" title="M1">prev</a>)</span><input type="radio" value="10962" name="oldid" id="mw-oldid-10962" /><input type="radio" value="10962" name="diff" id="mw-diff-10962" /> <a href="/index.php?title=M1&amp;oldid=10962" title="M1" class="mw-changeslist-date">12:57, 5 November 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Soft&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Soft (page does not exist)">Soft</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Soft&amp;action=edit&amp;redlink=1" class="new" title="User talk:Soft (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Soft" title="Special:Contributions/Soft">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,479 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,479 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Acquiring" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Acquiring</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=10961&amp;undo=10962" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=10961" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=10961&amp;oldid=10960" title="M1">prev</a>)</span><input type="radio" value="10961" name="oldid" id="mw-oldid-10961" /><input type="radio" value="10961" name="diff" id="mw-diff-10961" /> <a href="/index.php?title=M1&amp;oldid=10961" title="M1" class="mw-changeslist-date">12:57, 5 November 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Soft&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Soft (page does not exist)">Soft</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Soft&amp;action=edit&amp;redlink=1" class="new" title="User talk:Soft (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Soft" title="Special:Contributions/Soft">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,480 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,480 bytes after change">(+73)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Acquiring" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Acquiring</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=10960&amp;undo=10961" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=10960" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=10960&amp;oldid=10860" title="M1">prev</a>)</span><input type="radio" value="10960" name="oldid" id="mw-oldid-10960" /><input type="radio" value="10960" name="diff" id="mw-diff-10960" /> <a href="/index.php?title=M1&amp;oldid=10960" title="M1" class="mw-changeslist-date">12:56, 5 November 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Soft&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Soft (page does not exist)">Soft</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Soft&amp;action=edit&amp;redlink=1" class="new" title="User talk:Soft (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Soft" title="Special:Contributions/Soft">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,407 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,407 bytes after change">(+72)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=10860&amp;undo=10960" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=10860" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=10860&amp;oldid=9617" title="M1">prev</a>)</span><input type="radio" value="10860" name="oldid" id="mw-oldid-10860" /><input type="radio" value="10860" name="diff" id="mw-diff-10860" /> <a href="/index.php?title=M1&amp;oldid=10860" title="M1" class="mw-changeslist-date">17:53, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,335 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,335 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9617&amp;undo=10860" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9617" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9617&amp;oldid=9491" title="M1">prev</a>)</span><input type="radio" value="9617" name="oldid" id="mw-oldid-9617" /><input type="radio" value="9617" name="diff" id="mw-diff-9617" /> <a href="/index.php?title=M1&amp;oldid=9617" title="M1" class="mw-changeslist-date">21:01, 2 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,325 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,325 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fixed #deca entry)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9491&amp;undo=9617" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9491" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9491&amp;oldid=9374" title="M1">prev</a>)</span><input type="radio" value="9491" name="oldid" id="mw-oldid-9491" /><input type="radio" value="9491" name="diff" id="mw-diff-9491" /> <a href="/index.php?title=M1&amp;oldid=9491" title="M1" class="mw-changeslist-date">17:17, 24 July 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Heyjustarooni (page does not exist)">Heyjustarooni</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Heyjustarooni&amp;action=edit&amp;redlink=1" class="new" title="User talk:Heyjustarooni (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Heyjustarooni" title="Special:Contributions/Heyjustarooni">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,320 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,320 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(edited hull spec for Odin to match X3AP 2.1 targeted info panel)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9374&amp;undo=9491" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9374" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9374&amp;oldid=9247" title="M1">prev</a>)</span><input type="radio" value="9374" name="oldid" id="mw-oldid-9374" /><input type="radio" value="9374" name="diff" id="mw-diff-9374" /> <a href="/index.php?title=M1&amp;oldid=9374" title="M1" class="mw-changeslist-date">16:35, 8 July 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Maxitg&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Maxitg (page does not exist)">Maxitg</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Maxitg&amp;action=edit&amp;redlink=1" class="new" title="User talk:Maxitg (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Maxitg" title="Special:Contributions/Maxitg">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,318 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,318 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9247&amp;undo=9374" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9247" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9247&amp;oldid=9221" title="M1">prev</a>)</span><input type="radio" value="9247" name="oldid" id="mw-oldid-9247" /><input type="radio" value="9247" name="diff" id="mw-diff-9247" /> <a href="/index.php?title=M1&amp;oldid=9247" title="M1" class="mw-changeslist-date">23:46, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,289 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,289 bytes after change">(+248)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9221&amp;undo=9247" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9221" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9221&amp;oldid=9214" title="M1">prev</a>)</span><input type="radio" value="9221" name="oldid" id="mw-oldid-9221" /><input type="radio" value="9221" name="diff" id="mw-diff-9221" /> <a href="/index.php?title=M1&amp;oldid=9221" title="M1" class="mw-changeslist-date">18:41, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,041 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,041 bytes after change">(+85)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9214&amp;undo=9221" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9214" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9214&amp;oldid=9200" title="M1">prev</a>)</span><input type="radio" value="9214" name="oldid" id="mw-oldid-9214" /><input type="radio" value="9214" name="diff" id="mw-diff-9214" /> <a href="/index.php?title=M1&amp;oldid=9214" title="M1" class="mw-changeslist-date">17:42, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,956 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,956 bytes after change">(+336)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9200&amp;undo=9214" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9200" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9200&amp;oldid=9163" title="M1">prev</a>)</span><input type="radio" value="9200" name="oldid" id="mw-oldid-9200" /><input type="radio" value="9200" name="diff" id="mw-diff-9200" /> <a href="/index.php?title=M1&amp;oldid=9200" title="M1" class="mw-changeslist-date">02:34, 20 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,620 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,620 bytes after change">(-160)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9163&amp;undo=9200" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9163" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9163&amp;oldid=9160" title="M1">prev</a>)</span><input type="radio" value="9163" name="oldid" id="mw-oldid-9163" /><input type="radio" value="9163" name="diff" id="mw-diff-9163" /> <a href="/index.php?title=M1&amp;oldid=9163" title="M1" class="mw-changeslist-date">17:06, 13 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,780 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,780 bytes after change">(-51)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9160&amp;undo=9163" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9160" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9160&amp;oldid=9159" title="M1">prev</a>)</span><input type="radio" value="9160" name="oldid" id="mw-oldid-9160" /><input type="radio" value="9160" name="diff" id="mw-diff-9160" /> <a href="/index.php?title=M1&amp;oldid=9160" title="M1" class="mw-changeslist-date">16:34, 12 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,831 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,831 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9159&amp;undo=9160" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9159" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9159&amp;oldid=9158" title="M1">prev</a>)</span><input type="radio" value="9159" name="oldid" id="mw-oldid-9159" /><input type="radio" value="9159" name="diff" id="mw-diff-9159" /> <a href="/index.php?title=M1&amp;oldid=9159" title="M1" class="mw-changeslist-date">16:31, 12 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,829 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,829 bytes after change">(+404)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9158&amp;undo=9159" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9158" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9158&amp;oldid=9157" title="M1">prev</a>)</span><input type="radio" value="9158" name="oldid" id="mw-oldid-9158" /><input type="radio" value="9158" name="diff" id="mw-diff-9158" /> <a href="/index.php?title=M1&amp;oldid=9158" title="M1" class="mw-changeslist-date">15:27, 12 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,425 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,425 bytes after change">(+349)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9157&amp;undo=9158" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9157" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9157&amp;oldid=9156" title="M1">prev</a>)</span><input type="radio" value="9157" name="oldid" id="mw-oldid-9157" /><input type="radio" value="9157" name="diff" id="mw-diff-9157" /> <a href="/index.php?title=M1&amp;oldid=9157" title="M1" class="mw-changeslist-date">14:47, 12 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,076 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,076 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Sortable_list" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Sortable list</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=9156&amp;undo=9157" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=9156" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=9156&amp;oldid=7383" title="M1">prev</a>)</span><input type="radio" value="9156" name="oldid" id="mw-oldid-9156" /><input type="radio" value="9156" name="diff" id="mw-diff-9156" /> <a href="/index.php?title=M1&amp;oldid=9156" title="M1" class="mw-changeslist-date">14:46, 12 May 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Thedataking&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Thedataking (page does not exist)">Thedataking</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Thedataking&amp;action=edit&amp;redlink=1" class="new" title="User talk:Thedataking (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Thedataking" title="Special:Contributions/Thedataking">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,076 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,076 bytes after change">(+1,809)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=7383&amp;undo=9156" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=7383" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=7383&amp;oldid=6390" title="M1">prev</a>)</span><input type="radio" value="7383" name="oldid" id="mw-oldid-7383" /><input type="radio" value="7383" name="diff" id="mw-diff-7383" /> <a href="/index.php?title=M1&amp;oldid=7383" title="M1" class="mw-changeslist-date">06:44, 18 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,267 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,267 bytes after change">(+121)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Acquiring" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Acquiring: </span> added Colossus Hauler, Woden, MRS to &quot;Does not spawn&quot;</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=6390&amp;undo=7383" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=6390" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=6390&amp;oldid=3020" title="M1">prev</a>)</span><input type="radio" value="6390" name="oldid" id="mw-oldid-6390" /><input type="radio" value="6390" name="diff" id="mw-diff-6390" /> <a href="/index.php?title=M1&amp;oldid=6390" title="M1" class="mw-changeslist-date">21:53, 4 June 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/91.154.215.232" title="Special:Contributions/91.154.215.232" class="mw-userlink mw-anonuserlink">91.154.215.232</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:91.154.215.232&amp;action=edit&amp;redlink=1" class="new" title="User talk:91.154.215.232 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,146 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,146 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=3020&amp;undo=6390" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=3020" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=3020&amp;oldid=2912" title="M1">prev</a>)</span><input type="radio" value="3020" name="oldid" id="mw-oldid-3020" /><input type="radio" value="3020" name="diff" id="mw-diff-3020" /> <a href="/index.php?title=M1&amp;oldid=3020" title="M1" class="mw-changeslist-date">21:51, 16 October 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,117 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,117 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Hoshi -&gt; purchaseable)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2912&amp;undo=3020" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2912" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2912&amp;oldid=2642" title="M1">prev</a>)</span><input type="radio" value="2912" name="oldid" id="mw-oldid-2912" /><input type="radio" value="2912" name="diff" id="mw-diff-2912" /> <a href="/index.php?title=M1&amp;oldid=2912" title="M1" class="mw-changeslist-date">19:21, 15 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,116 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,116 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected cap ship link)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2642&amp;undo=2912" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2642" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2642&amp;oldid=2641" title="M1">prev</a>)</span><input type="radio" value="2642" name="oldid" id="mw-oldid-2642" /><input type="radio" value="2642" name="diff" id="mw-diff-2642" /> <a href="/index.php?title=M1&amp;oldid=2642" title="M1" class="mw-changeslist-date">01:49, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,115 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,115 bytes after change">(-22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/M1#Orbital_Weapon_Platforms" title="M1">→</a>‎<span dir="auto"><span class="autocomment">Orbital Weapon Platforms: </span> removed guardian, listed on non-vanilla page.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2641&amp;undo=2642" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2641" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2641&amp;oldid=2636" title="M1">prev</a>)</span><input type="radio" value="2641" name="oldid" id="mw-oldid-2641" /><input type="radio" value="2641" name="diff" id="mw-diff-2641" /> <a href="/index.php?title=M1&amp;oldid=2641" title="M1" class="mw-changeslist-date">01:29, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,137 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,137 bytes after change">(+248)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(owp readded. until owp splits off anyway.)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2636&amp;undo=2641" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2636" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2636&amp;oldid=2116" title="M1">prev</a>)</span><input type="radio" value="2636" name="oldid" id="mw-oldid-2636" /><input type="radio" value="2636" name="diff" id="mw-diff-2636" /> <a href="/index.php?title=M1&amp;oldid=2636" title="M1" class="mw-changeslist-date">00:32, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(889 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="889 bytes after change">(+92)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(list tablized)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2116&amp;undo=2636" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2116" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2116&amp;oldid=2115" title="M1">prev</a>)</span><input type="radio" value="2116" name="oldid" id="mw-oldid-2116" /><input type="radio" value="2116" name="diff" id="mw-diff-2116" /> <a href="/index.php?title=M1&amp;oldid=2116" title="M1" class="mw-changeslist-date">11:34, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(797 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="797 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2115&amp;undo=2116" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2115" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2115&amp;oldid=2114" title="M1">prev</a>)</span><input type="radio" value="2115" name="oldid" id="mw-oldid-2115" /><input type="radio" value="2115" name="diff" id="mw-diff-2115" /> <a href="/index.php?title=M1&amp;oldid=2115" title="M1" class="mw-changeslist-date">11:33, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(784 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="784 bytes after change">(+167)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2114&amp;undo=2115" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2114" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2114&amp;oldid=2113" title="M1">prev</a>)</span><input type="radio" value="2114" name="oldid" id="mw-oldid-2114" /><input type="radio" value="2114" name="diff" id="mw-diff-2114" /> <a href="/index.php?title=M1&amp;oldid=2114" title="M1" class="mw-changeslist-date">11:31, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(617 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="617 bytes after change">(-21)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2113&amp;undo=2114" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2113" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2113&amp;oldid=2105" title="M1">prev</a>)</span><input type="radio" value="2113" name="oldid" id="mw-oldid-2113" /><input type="radio" value="2113" name="diff" id="mw-diff-2113" /> <a href="/index.php?title=M1&amp;oldid=2113" title="M1" class="mw-changeslist-date">11:31, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(638 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="638 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=2105&amp;undo=2113" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=2105" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=2105&amp;oldid=807" title="M1">prev</a>)</span><input type="radio" value="2105" name="oldid" id="mw-oldid-2105" /><input type="radio" value="2105" name="diff" id="mw-diff-2105" /> <a href="/index.php?title=M1&amp;oldid=2105" title="M1" class="mw-changeslist-date">11:06, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(638 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="638 bytes after change">(+109)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Multiple edits; see discussion)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=807&amp;undo=2105" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=807" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=807&amp;oldid=565" title="M1">prev</a>)</span><input type="radio" value="807" name="oldid" id="mw-oldid-807" /><input type="radio" value="807" name="diff" id="mw-diff-807" /> <a href="/index.php?title=M1&amp;oldid=807" title="M1" class="mw-changeslist-date">20:23, 15 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(529 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="529 bytes after change">(+162)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(copied list of ships from m1 category page.)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=565&amp;undo=807" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=565" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=565&amp;oldid=524" title="M1">prev</a>)</span><input type="radio" value="565" name="oldid" id="mw-oldid-565" /><input type="radio" value="565" name="diff" id="mw-diff-565" /> <a href="/index.php?title=M1&amp;oldid=565" title="M1" class="mw-changeslist-date">18:47, 28 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(367 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="367 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added zeus anchor)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=524&amp;undo=565" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=524" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=524&amp;oldid=513" title="M1">prev</a>)</span><input type="radio" value="524" name="oldid" id="mw-oldid-524" /><input type="radio" value="524" name="diff" id="mw-diff-524" /> <a href="/index.php?title=M1&amp;oldid=524" title="M1" class="mw-changeslist-date">02:18, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(357 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="357 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(J anchor)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=513&amp;undo=524" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=513" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=513&amp;oldid=471" title="M1">prev</a>)</span><input type="radio" value="513" name="oldid" id="mw-oldid-513" /><input type="radio" value="513" name="diff" id="mw-diff-513" /> <a href="/index.php?title=M1&amp;oldid=513" title="M1" class="mw-changeslist-date">01:54, 25 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(344 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="344 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(needed anchor)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=471&amp;undo=513" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=471" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=471&amp;oldid=325" title="M1">prev</a>)</span><input type="radio" value="471" name="oldid" id="mw-oldid-471" /><input type="radio" value="471" name="diff" id="mw-diff-471" /> <a href="/index.php?title=M1&amp;oldid=471" title="M1" class="mw-changeslist-date">22:19, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(333 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="333 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added galleon)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=325&amp;undo=471" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=325" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=325&amp;oldid=296" title="M1">prev</a>)</span><input type="radio" value="325" name="oldid" id="mw-oldid-325" /><input type="radio" value="325" name="diff" id="mw-diff-325" /> <a href="/index.php?title=M1&amp;oldid=325" title="M1" class="mw-changeslist-date">18:37, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(320 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="320 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(category)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=296&amp;undo=325" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=296" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=296&amp;oldid=267" title="M1">prev</a>)</span><input type="radio" value="296" name="oldid" id="mw-oldid-296" /><input type="radio" value="296" name="diff" id="mw-diff-296" /> <a href="/index.php?title=M1&amp;oldid=296" title="M1" class="mw-changeslist-date">23:14, 23 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(304 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="304 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(add colossus)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=267&amp;undo=296" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=267" title="M1">cur</a> | <a href="/index.php?title=M1&amp;diff=267&amp;oldid=216" title="M1">prev</a>)</span><input type="radio" value="267" name="oldid" id="mw-oldid-267" /><input type="radio" value="267" name="diff" id="mw-diff-267" /> <a href="/index.php?title=M1&amp;oldid=267" title="M1" class="mw-changeslist-date">22:06, 23 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(290 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="290 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added condor)</span> (<span class="mw-history-undo"><a href="/index.php?title=M1&amp;action=edit&amp;undoafter=216&amp;undo=267" title="M1">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=M1&amp;diff=14184&amp;oldid=216" title="M1">cur</a> | prev)</span><input type="radio" value="216" name="oldid" id="mw-oldid-216" /><input type="radio" value="216" name="diff" id="mw-diff-216" /> <a href="/index.php?title=M1&amp;oldid=216" title="M1" class="mw-changeslist-date">19:26, 23 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(264 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="264 bytes after change">(+264)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(new fab based on other m class pages)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/M1">http://www.x3wiki.com/index.php/M1</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/M1" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:M1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=M1&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=M1&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=M1&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=M1&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/M1" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/M1" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=M1&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=M1&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":89});});</script></body></html>
