<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Missiles" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Missiles","wgTitle":"Missiles","wgCurRevisionId":14668,"wgRevisionId":0,"wgArticleId":25,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Missiles","wgRelevantArticleId":25,"wgRequestId":"WXYMOVkfZokAABV@G4QAAAAN","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Missiles&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Missiles&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Missiles&quot; Atom feed" href="/index.php?title=Missiles&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Missiles rootpage-Missiles skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Missiles"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Missiles" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Missiles" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=Missiles&amp;dir=prev&amp;action=history" title="Missiles" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Missiles&amp;offset=20100921020443&amp;action=history" title="Missiles" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Missiles&amp;offset=&amp;limit=20&amp;action=history" title="Missiles" class="mw-numlink">20</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=50&amp;action=history" title="Missiles" class="mw-numlink">50</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=100&amp;action=history" title="Missiles" class="mw-numlink">100</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=250&amp;action=history" title="Missiles" class="mw-numlink">250</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=500&amp;action=history" title="Missiles" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Missiles" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=14103" title="Missiles">prev</a>)</span><input type="radio" value="14668" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14668" checked="checked" name="diff" id="mw-diff-14668" /> <a href="/index.php?title=Missiles&amp;oldid=14668" title="Missiles" class="mw-changeslist-date">12:19, 25 February 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,083 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="8,083 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Note" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Note: </span> Typpo</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=14103&amp;undo=14668" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=14103" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=14103&amp;oldid=14048" title="Missiles">prev</a>)</span><input type="radio" value="14103" checked="checked" name="oldid" id="mw-oldid-14103" /><input type="radio" value="14103" name="diff" id="mw-diff-14103" /> <a href="/index.php?title=Missiles&amp;oldid=14103" title="Missiles" class="mw-changeslist-date">11:25, 24 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,084 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,084 bytes after change">(+38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=14048&amp;undo=14103" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=14048" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=14048&amp;oldid=14000" title="Missiles">prev</a>)</span><input type="radio" value="14048" name="oldid" id="mw-oldid-14048" /><input type="radio" value="14048" name="diff" id="mw-diff-14048" /> <a href="/index.php?title=Missiles&amp;oldid=14048" title="Missiles" class="mw-changeslist-date">02:11, 13 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,046 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,046 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> Thunderbolt produced only by Split</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=14000&amp;undo=14048" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=14000" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=14000&amp;oldid=13895" title="Missiles">prev</a>)</span><input type="radio" value="14000" name="oldid" id="mw-oldid-14000" /><input type="radio" value="14000" name="diff" id="mw-diff-14000" /> <a href="/index.php?title=Missiles&amp;oldid=14000" title="Missiles" class="mw-changeslist-date">15:57, 24 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,035 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,035 bytes after change">(+142)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> Use footnote for Medusa-compatible missiles</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13895&amp;undo=14000" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13895" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13895&amp;oldid=13775" title="Missiles">prev</a>)</span><input type="radio" value="13895" name="oldid" id="mw-oldid-13895" /><input type="radio" value="13895" name="diff" id="mw-diff-13895" /> <a href="/index.php?title=Missiles&amp;oldid=13895" title="Missiles" class="mw-changeslist-date">23:16, 15 September 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Wraith_Magus&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Wraith Magus (page does not exist)">Wraith Magus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Wraith_Magus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Wraith Magus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Wraith_Magus" title="Special:Contributions/Wraith Magus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,893 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,893 bytes after change">(+958)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(link to combat)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13775&amp;undo=13895" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13775" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13775&amp;oldid=13740" title="Missiles">prev</a>)</span><input type="radio" value="13775" name="oldid" id="mw-oldid-13775" /><input type="radio" value="13775" name="diff" id="mw-diff-13775" /> <a href="/index.php?title=Missiles&amp;oldid=13775" title="Missiles" class="mw-changeslist-date">21:26, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,935 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,935 bytes after change">(+71)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(See also section)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13740&amp;undo=13775" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13740" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13740&amp;oldid=13703" title="Missiles">prev</a>)</span><input type="radio" value="13740" name="oldid" id="mw-oldid-13740" /><input type="radio" value="13740" name="diff" id="mw-diff-13740" /> <a href="/index.php?title=Missiles&amp;oldid=13740" title="Missiles" class="mw-changeslist-date">19:48, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,864 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,864 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Missile navbox)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13703&amp;undo=13740" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13703" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13703&amp;oldid=13446" title="Missiles">prev</a>)</span><input type="radio" value="13703" name="oldid" id="mw-oldid-13703" /><input type="radio" value="13703" name="diff" id="mw-diff-13703" /> <a href="/index.php?title=Missiles&amp;oldid=13703" title="Missiles" class="mw-changeslist-date">17:51, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,845 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,845 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Overview" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Overview: </span>  Bolding &quot;Standard Guidance&quot;</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13446&amp;undo=13703" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13446" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13446&amp;oldid=13262" title="Missiles">prev</a>)</span><input type="radio" value="13446" name="oldid" id="mw-oldid-13446" /><input type="radio" value="13446" name="diff" id="mw-diff-13446" /> <a href="/index.php?title=Missiles&amp;oldid=13446" title="Missiles" class="mw-changeslist-date">03:44, 10 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,839 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,839 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(See also: Weapons)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=13262&amp;undo=13446" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=13262" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=13262&amp;oldid=12543" title="Missiles">prev</a>)</span><input type="radio" value="13262" name="oldid" id="mw-oldid-13262" /><input type="radio" value="13262" name="diff" id="mw-diff-13262" /> <a href="/index.php?title=Missiles&amp;oldid=13262" title="Missiles" class="mw-changeslist-date">04:44, 30 July 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sorvolge&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sorvolge (page does not exist)">Sorvolge</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sorvolge&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sorvolge (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sorvolge" title="Special:Contributions/Sorvolge">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,817 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,817 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12543&amp;undo=13262" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12543" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12543&amp;oldid=12541" title="Missiles">prev</a>)</span><input type="radio" value="12543" name="oldid" id="mw-oldid-12543" /><input type="radio" value="12543" name="diff" id="mw-diff-12543" /> <a href="/index.php?title=Missiles&amp;oldid=12543" title="Missiles" class="mw-changeslist-date">10:32, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,819 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,819 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12541&amp;undo=12543" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12541" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12541&amp;oldid=12540" title="Missiles">prev</a>)</span><input type="radio" value="12541" name="oldid" id="mw-oldid-12541" /><input type="radio" value="12541" name="diff" id="mw-diff-12541" /> <a href="/index.php?title=Missiles&amp;oldid=12541" title="Missiles" class="mw-changeslist-date">10:29, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,813 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,813 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12540&amp;undo=12541" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12540" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12540&amp;oldid=12348" title="Missiles">prev</a>)</span><input type="radio" value="12540" name="oldid" id="mw-oldid-12540" /><input type="radio" value="12540" name="diff" id="mw-diff-12540" /> <a href="/index.php?title=Missiles&amp;oldid=12540" title="Missiles" class="mw-changeslist-date">10:28, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,808 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,808 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12348&amp;undo=12540" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12348" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12348&amp;oldid=12132" title="Missiles">prev</a>)</span><input type="radio" value="12348" name="oldid" id="mw-oldid-12348" /><input type="radio" value="12348" name="diff" id="mw-diff-12348" /> <a href="/index.php?title=Missiles&amp;oldid=12348" title="Missiles" class="mw-changeslist-date">00:06, 2 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,802 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,802 bytes after change">(+1,719)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> Added Producing races and weapon availability columns</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12132&amp;undo=12348" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12132" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12132&amp;oldid=12131" title="Missiles">prev</a>)</span><input type="radio" value="12132" name="oldid" id="mw-oldid-12132" /><input type="radio" value="12132" name="diff" id="mw-diff-12132" /> <a href="/index.php?title=Missiles&amp;oldid=12132" title="Missiles" class="mw-changeslist-date">23:17, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,083 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,083 bytes after change">(-8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=12131&amp;undo=12132" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=12131" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=12131&amp;oldid=11821" title="Missiles">prev</a>)</span><input type="radio" value="12131" name="oldid" id="mw-oldid-12131" /><input type="radio" value="12131" name="diff" id="mw-diff-12131" /> <a href="/index.php?title=Missiles&amp;oldid=12131" title="Missiles" class="mw-changeslist-date">23:16, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,091 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,091 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=11821&amp;undo=12131" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=11821" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=11821&amp;oldid=11742" title="Missiles">prev</a>)</span><input type="radio" value="11821" name="oldid" id="mw-oldid-11821" /><input type="radio" value="11821" name="diff" id="mw-diff-11821" /> <a href="/index.php?title=Missiles&amp;oldid=11821" title="Missiles" class="mw-changeslist-date">07:59, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,073 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,073 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=11742&amp;undo=11821" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=11742" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=11742&amp;oldid=11741" title="Missiles">prev</a>)</span><input type="radio" value="11742" name="oldid" id="mw-oldid-11742" /><input type="radio" value="11742" name="diff" id="mw-diff-11742" /> <a href="/index.php?title=Missiles&amp;oldid=11742" title="Missiles" class="mw-changeslist-date">00:22, 20 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,071 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,071 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> corrected label to match intro.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=11741&amp;undo=11742" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=11741" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=11741&amp;oldid=11740" title="Missiles">prev</a>)</span><input type="radio" value="11741" name="oldid" id="mw-oldid-11741" /><input type="radio" value="11741" name="diff" id="mw-diff-11741" /> <a href="/index.php?title=Missiles&amp;oldid=11741" title="Missiles" class="mw-changeslist-date">00:21, 20 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,069 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,069 bytes after change">(-3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> corrrected ghoul to impact per missile page.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=11740&amp;undo=11741" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=11740" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=11740&amp;oldid=11601" title="Missiles">prev</a>)</span><input type="radio" value="11740" name="oldid" id="mw-oldid-11740" /><input type="radio" value="11740" name="diff" id="mw-diff-11740" /> <a href="/index.php?title=Missiles&amp;oldid=11740" title="Missiles" class="mw-changeslist-date">00:18, 20 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,072 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,072 bytes after change">(+221)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> merged seeker columns, retooled proximity y/n to fusing noted synaptic on aurora, that still synaptic or did they reprogram that?</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=11601&amp;undo=11740" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=11601" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=11601&amp;oldid=8356" title="Missiles">prev</a>)</span><input type="radio" value="11601" name="oldid" id="mw-oldid-11601" /><input type="radio" value="11601" name="diff" id="mw-diff-11601" /> <a href="/index.php?title=Missiles&amp;oldid=11601" title="Missiles" class="mw-changeslist-date">03:59, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,851 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,851 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=8356&amp;undo=11601" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=8356" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=8356&amp;oldid=8349" title="Missiles">prev</a>)</span><input type="radio" value="8356" name="oldid" id="mw-oldid-8356" /><input type="radio" value="8356" name="diff" id="mw-diff-8356" /> <a href="/index.php?title=Missiles&amp;oldid=8356" title="Missiles" class="mw-changeslist-date">17:23, 22 January 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Vwcd&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Vwcd (page does not exist)">Vwcd</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Vwcd&amp;action=edit&amp;redlink=1" class="new" title="User talk:Vwcd (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Vwcd" title="Special:Contributions/Vwcd">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,848 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,848 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=8349&amp;undo=8356" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=8349" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=8349&amp;oldid=6169" title="Missiles">prev</a>)</span><input type="radio" value="8349" name="oldid" id="mw-oldid-8349" /><input type="radio" value="8349" name="diff" id="mw-diff-8349" /> <a href="/index.php?title=Missiles&amp;oldid=8349" title="Missiles" class="mw-changeslist-date">23:12, 21 January 2012</a>‎ <span class='history-user'><a href="/index.php/User:Pairoftwos" title="User:Pairoftwos" class="mw-userlink">Pairoftwos</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Pairoftwos&amp;action=edit&amp;redlink=1" class="new" title="User talk:Pairoftwos (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Pairoftwos" title="Special:Contributions/Pairoftwos">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,848 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,848 bytes after change">(-149)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Removed &quot;Yield x Warheads&quot; info from the Damage column (sorting issues). Edited Swarming note to match the style of the other lines. Added note about warhead behavior. Need to edit &quot;properties&quot; info at top for easier reading at some point.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=6169&amp;undo=8349" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=6169" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=6169&amp;oldid=6146" title="Missiles">prev</a>)</span><input type="radio" value="6169" name="oldid" id="mw-oldid-6169" /><input type="radio" value="6169" name="diff" id="mw-diff-6169" /> <a href="/index.php?title=Missiles&amp;oldid=6169" title="Missiles" class="mw-changeslist-date">14:57, 11 May 2011</a>‎ <span class='history-user'><a href="/index.php/User:Anarchistica" title="User:Anarchistica" class="mw-userlink">Anarchistica</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Anarchistica&amp;action=edit&amp;redlink=1" class="new" title="User talk:Anarchistica (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Anarchistica" title="Special:Contributions/Anarchistica">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,997 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,997 bytes after change">(+4,954)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo spam)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=6146&amp;undo=6169" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=6146" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=6146&amp;oldid=4576" title="Missiles">prev</a>)</span><input type="radio" value="6146" name="oldid" id="mw-oldid-6146" /><input type="radio" value="6146" name="diff" id="mw-diff-6146" /> <a href="/index.php?title=Missiles&amp;oldid=6146" title="Missiles" class="mw-changeslist-date">00:28, 11 May 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/173.15.232.34" title="Special:Contributions/173.15.232.34" class="mw-userlink mw-anonuserlink">173.15.232.34</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:173.15.232.34&amp;action=edit&amp;redlink=1" class="new" title="User talk:173.15.232.34 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="43 bytes after change">(-4,954)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(ABxlWKglbdqboLOR)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=4576&amp;undo=6146" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=4576" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=4576&amp;oldid=3929" title="Missiles">prev</a>)</span><input type="radio" value="4576" name="oldid" id="mw-oldid-4576" /><input type="radio" value="4576" name="diff" id="mw-diff-4576" /> <a href="/index.php?title=Missiles&amp;oldid=4576" title="Missiles" class="mw-changeslist-date">03:36, 2 December 2010</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,997 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,997 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles: </span> Wildfire is not dumbfire</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=3929&amp;undo=4576" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=3929" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=3929&amp;oldid=3855" title="Missiles">prev</a>)</span><input type="radio" value="3929" name="oldid" id="mw-oldid-3929" /><input type="radio" value="3929" name="diff" id="mw-diff-3929" /> <a href="/index.php?title=Missiles&amp;oldid=3929" title="Missiles" class="mw-changeslist-date">11:49, 4 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,998 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,998 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=3855&amp;undo=3929" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=3855" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=3855&amp;oldid=2386" title="Missiles">prev</a>)</span><input type="radio" value="3855" name="oldid" id="mw-oldid-3855" /><input type="radio" value="3855" name="diff" id="mw-diff-3855" /> <a href="/index.php?title=Missiles&amp;oldid=3855" title="Missiles" class="mw-changeslist-date">23:46, 30 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,997 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,997 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Overview" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=2386&amp;undo=3855" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=2386" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=2386&amp;oldid=1849" title="Missiles">prev</a>)</span><input type="radio" value="2386" name="oldid" id="mw-oldid-2386" /><input type="radio" value="2386" name="diff" id="mw-diff-2386" /> <a href="/index.php?title=Missiles&amp;oldid=2386" title="Missiles" class="mw-changeslist-date">21:27, 7 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,956 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,956 bytes after change">(+831)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(trying to standardize notations, at least in description)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1849&amp;undo=2386" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1849" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1849&amp;oldid=1762" title="Missiles">prev</a>)</span><input type="radio" value="1849" name="oldid" id="mw-oldid-1849" /><input type="radio" value="1849" name="diff" id="mw-diff-1849" /> <a href="/index.php?title=Missiles&amp;oldid=1849" title="Missiles" class="mw-changeslist-date">01:28, 2 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,125 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,125 bytes after change">(-12)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fix boarding pods link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1762&amp;undo=1849" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1762" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1762&amp;oldid=1166" title="Missiles">prev</a>)</span><input type="radio" value="1762" name="oldid" id="mw-oldid-1762" /><input type="radio" value="1762" name="diff" id="mw-diff-1762" /> <a href="/index.php?title=Missiles&amp;oldid=1762" title="Missiles" class="mw-changeslist-date">23:43, 29 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,137 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,137 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected boarding pod link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1166&amp;undo=1762" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1166" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1166&amp;oldid=1165" title="Missiles">prev</a>)</span><input type="radio" value="1166" name="oldid" id="mw-oldid-1166" /><input type="radio" value="1166" name="diff" id="mw-diff-1166" /> <a href="/index.php?title=Missiles&amp;oldid=1166" title="Missiles" class="mw-changeslist-date">07:41, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,124 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,124 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1165&amp;undo=1166" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1165" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1165&amp;oldid=1164" title="Missiles">prev</a>)</span><input type="radio" value="1165" name="oldid" id="mw-oldid-1165" /><input type="radio" value="1165" name="diff" id="mw-diff-1165" /> <a href="/index.php?title=Missiles&amp;oldid=1165" title="Missiles" class="mw-changeslist-date">07:39, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,119 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,119 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1164&amp;undo=1165" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1164" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1164&amp;oldid=1163" title="Missiles">prev</a>)</span><input type="radio" value="1164" name="oldid" id="mw-oldid-1164" /><input type="radio" value="1164" name="diff" id="mw-diff-1164" /> <a href="/index.php?title=Missiles&amp;oldid=1164" title="Missiles" class="mw-changeslist-date">07:29, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,078 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,078 bytes after change">(-31)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1163&amp;undo=1164" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1163" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1163&amp;oldid=1144" title="Missiles">prev</a>)</span><input type="radio" value="1163" name="oldid" id="mw-oldid-1163" /><input type="radio" value="1163" name="diff" id="mw-diff-1163" /> <a href="/index.php?title=Missiles&amp;oldid=1163" title="Missiles" class="mw-changeslist-date">07:14, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,109 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,109 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1144&amp;undo=1163" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1144" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1144&amp;oldid=1143" title="Missiles">prev</a>)</span><input type="radio" value="1144" name="oldid" id="mw-oldid-1144" /><input type="radio" value="1144" name="diff" id="mw-diff-1144" /> <a href="/index.php?title=Missiles&amp;oldid=1144" title="Missiles" class="mw-changeslist-date">05:24, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,100 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,100 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1143&amp;undo=1144" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1143" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1143&amp;oldid=1142" title="Missiles">prev</a>)</span><input type="radio" value="1143" name="oldid" id="mw-oldid-1143" /><input type="radio" value="1143" name="diff" id="mw-diff-1143" /> <a href="/index.php?title=Missiles&amp;oldid=1143" title="Missiles" class="mw-changeslist-date">05:24, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,100 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,100 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1142&amp;undo=1143" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1142" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1142&amp;oldid=1141" title="Missiles">prev</a>)</span><input type="radio" value="1142" name="oldid" id="mw-oldid-1142" /><input type="radio" value="1142" name="diff" id="mw-diff-1142" /> <a href="/index.php?title=Missiles&amp;oldid=1142" title="Missiles" class="mw-changeslist-date">05:18, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,100 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,100 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1141&amp;undo=1142" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1141" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1141&amp;oldid=1140" title="Missiles">prev</a>)</span><input type="radio" value="1141" name="oldid" id="mw-oldid-1141" /><input type="radio" value="1141" name="diff" id="mw-diff-1141" /> <a href="/index.php?title=Missiles&amp;oldid=1141" title="Missiles" class="mw-changeslist-date">05:16, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,098 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,098 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1140&amp;undo=1141" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1140" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1140&amp;oldid=1131" title="Missiles">prev</a>)</span><input type="radio" value="1140" name="oldid" id="mw-oldid-1140" /><input type="radio" value="1140" name="diff" id="mw-diff-1140" /> <a href="/index.php?title=Missiles&amp;oldid=1140" title="Missiles" class="mw-changeslist-date">05:15, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,089 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,089 bytes after change">(+64)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1131&amp;undo=1140" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1131" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1131&amp;oldid=1130" title="Missiles">prev</a>)</span><input type="radio" value="1131" name="oldid" id="mw-oldid-1131" /><input type="radio" value="1131" name="diff" id="mw-diff-1131" /> <a href="/index.php?title=Missiles&amp;oldid=1131" title="Missiles" class="mw-changeslist-date">04:50, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,025 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,025 bytes after change">(+267)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1130&amp;undo=1131" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1130" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1130&amp;oldid=1129" title="Missiles">prev</a>)</span><input type="radio" value="1130" name="oldid" id="mw-oldid-1130" /><input type="radio" value="1130" name="diff" id="mw-diff-1130" /> <a href="/index.php?title=Missiles&amp;oldid=1130" title="Missiles" class="mw-changeslist-date">04:39, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,758 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,758 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1129&amp;undo=1130" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1129" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1129&amp;oldid=1128" title="Missiles">prev</a>)</span><input type="radio" value="1129" name="oldid" id="mw-oldid-1129" /><input type="radio" value="1129" name="diff" id="mw-diff-1129" /> <a href="/index.php?title=Missiles&amp;oldid=1129" title="Missiles" class="mw-changeslist-date">04:38, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,757 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,757 bytes after change">(+123)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1128&amp;undo=1129" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1128" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1128&amp;oldid=1127" title="Missiles">prev</a>)</span><input type="radio" value="1128" name="oldid" id="mw-oldid-1128" /><input type="radio" value="1128" name="diff" id="mw-diff-1128" /> <a href="/index.php?title=Missiles&amp;oldid=1128" title="Missiles" class="mw-changeslist-date">04:26, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,634 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,634 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1127&amp;undo=1128" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1127" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1127&amp;oldid=1126" title="Missiles">prev</a>)</span><input type="radio" value="1127" name="oldid" id="mw-oldid-1127" /><input type="radio" value="1127" name="diff" id="mw-diff-1127" /> <a href="/index.php?title=Missiles&amp;oldid=1127" title="Missiles" class="mw-changeslist-date">04:26, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,635 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,635 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1126&amp;undo=1127" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1126" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1126&amp;oldid=1125" title="Missiles">prev</a>)</span><input type="radio" value="1126" name="oldid" id="mw-oldid-1126" /><input type="radio" value="1126" name="diff" id="mw-diff-1126" /> <a href="/index.php?title=Missiles&amp;oldid=1126" title="Missiles" class="mw-changeslist-date">04:22, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,634 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,634 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1125&amp;undo=1126" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1125" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1125&amp;oldid=1124" title="Missiles">prev</a>)</span><input type="radio" value="1125" name="oldid" id="mw-oldid-1125" /><input type="radio" value="1125" name="diff" id="mw-diff-1125" /> <a href="/index.php?title=Missiles&amp;oldid=1125" title="Missiles" class="mw-changeslist-date">04:15, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,628 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,628 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1124&amp;undo=1125" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1124" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1124&amp;oldid=1123" title="Missiles">prev</a>)</span><input type="radio" value="1124" name="oldid" id="mw-oldid-1124" /><input type="radio" value="1124" name="diff" id="mw-diff-1124" /> <a href="/index.php?title=Missiles&amp;oldid=1124" title="Missiles" class="mw-changeslist-date">04:14, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,612 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,612 bytes after change">(+214)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Missiles#Table_of_Missiles" title="Missiles">→</a>‎<span dir="auto"><span class="autocomment">Table of Missiles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1123&amp;undo=1124" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1123" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1123&amp;oldid=1122" title="Missiles">prev</a>)</span><input type="radio" value="1123" name="oldid" id="mw-oldid-1123" /><input type="radio" value="1123" name="diff" id="mw-diff-1123" /> <a href="/index.php?title=Missiles&amp;oldid=1123" title="Missiles" class="mw-changeslist-date">04:05, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,398 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,398 bytes after change">(-3)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1122&amp;undo=1123" title="Missiles">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Missiles&amp;diff=14668&amp;oldid=1122" title="Missiles">cur</a> | <a href="/index.php?title=Missiles&amp;diff=1122&amp;oldid=1121" title="Missiles">prev</a>)</span><input type="radio" value="1122" name="oldid" id="mw-oldid-1122" /><input type="radio" value="1122" name="diff" id="mw-diff-1122" /> <a href="/index.php?title=Missiles&amp;oldid=1122" title="Missiles" class="mw-changeslist-date">04:04, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,401 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,401 bytes after change">(+31)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Missiles&amp;action=edit&amp;undoafter=1121&amp;undo=1122" title="Missiles">undo</a></span>)</li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form>(newest | <a href="/index.php?title=Missiles&amp;dir=prev&amp;action=history" title="Missiles" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Missiles&amp;offset=20100921020443&amp;action=history" title="Missiles" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Missiles&amp;offset=&amp;limit=20&amp;action=history" title="Missiles" class="mw-numlink">20</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=50&amp;action=history" title="Missiles" class="mw-numlink">50</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=100&amp;action=history" title="Missiles" class="mw-numlink">100</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=250&amp;action=history" title="Missiles" class="mw-numlink">250</a> | <a href="/index.php?title=Missiles&amp;offset=&amp;limit=500&amp;action=history" title="Missiles" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Missiles">http://x3wiki.com/index.php/Missiles</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Missiles" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Missiles" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Missiles&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Missiles&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Missiles&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Missiles&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Missiles" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Missiles" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Missiles&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Missiles&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":105});});</script></body></html>
