<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Headquarters" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Headquarters","wgTitle":"Headquarters","wgCurRevisionId":16319,"wgRevisionId":0,"wgArticleId":2121,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Headquarters","wgRelevantArticleId":2121,"wgRequestId":"WX09jlkfZokAAE1cYbUAAAAH","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Headquarters&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Headquarters&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Headquarters&quot; Atom feed" href="/index.php?title=Headquarters&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Headquarters rootpage-Headquarters skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Headquarters"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Headquarters" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Headquarters" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Headquarters" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=16170" title="Headquarters">prev</a>)</span><input type="radio" value="16319" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16319" checked="checked" name="diff" id="mw-diff-16319" /> <a href="/index.php?title=Headquarters&amp;oldid=16319" title="Headquarters" class="mw-changeslist-date">08:50, 15 July 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/186.136.111.144" title="Special:Contributions/186.136.111.144" class="mw-userlink mw-anonuserlink">186.136.111.144</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:186.136.111.144&amp;action=edit&amp;redlink=1" class="new" title="User talk:186.136.111.144 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(44,192 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="44,192 bytes after change">(+656)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added information about the Terran PHQ)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=16170&amp;undo=16319" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=16170" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=16170&amp;oldid=16169" title="Headquarters">prev</a>)</span><input type="radio" value="16170" checked="checked" name="oldid" id="mw-oldid-16170" /><input type="radio" value="16170" name="diff" id="mw-diff-16170" /> <a href="/index.php?title=Headquarters&amp;oldid=16170" title="Headquarters" class="mw-changeslist-date">00:51, 28 March 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:ShadowPhantom&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:ShadowPhantom (page does not exist)">ShadowPhantom</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ShadowPhantom&amp;action=edit&amp;redlink=1" class="new" title="User talk:ShadowPhantom (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ShadowPhantom" title="Special:Contributions/ShadowPhantom">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,536 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,536 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=16169&amp;undo=16170" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=16169" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=16169&amp;oldid=16165" title="Headquarters">prev</a>)</span><input type="radio" value="16169" name="oldid" id="mw-oldid-16169" /><input type="radio" value="16169" name="diff" id="mw-diff-16169" /> <a href="/index.php?title=Headquarters&amp;oldid=16169" title="Headquarters" class="mw-changeslist-date">00:45, 28 March 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:ShadowPhantom&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:ShadowPhantom (page does not exist)">ShadowPhantom</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ShadowPhantom&amp;action=edit&amp;redlink=1" class="new" title="User talk:ShadowPhantom (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ShadowPhantom" title="Special:Contributions/ShadowPhantom">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,534 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="43,534 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Fleet_Storage" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Fleet Storage</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=16165&amp;undo=16169" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=16165" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=16165&amp;oldid=13942" title="Headquarters">prev</a>)</span><input type="radio" value="16165" name="oldid" id="mw-oldid-16165" /><input type="radio" value="16165" name="diff" id="mw-diff-16165" /> <a href="/index.php?title=Headquarters&amp;oldid=16165" title="Headquarters" class="mw-changeslist-date">16:33, 26 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,535 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="43,535 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains: </span> re-order legend in column order</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=13942&amp;undo=16165" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=13942" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=13942&amp;oldid=12166" title="Headquarters">prev</a>)</span><input type="radio" value="13942" name="oldid" id="mw-oldid-13942" /><input type="radio" value="13942" name="diff" id="mw-diff-13942" /> <a href="/index.php?title=Headquarters&amp;oldid=13942" title="Headquarters" class="mw-changeslist-date">09:16, 7 October 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Lyonus&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Lyonus (page does not exist)">Lyonus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Lyonus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Lyonus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Lyonus" title="Special:Contributions/Lyonus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,536 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,536 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fixed typo and added clarity)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12166&amp;undo=13942" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12166" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12166&amp;oldid=12111" title="Headquarters">prev</a>)</span><input type="radio" value="12166" name="oldid" id="mw-oldid-12166" /><input type="radio" value="12166" name="diff" id="mw-diff-12166" /> <a href="/index.php?title=Headquarters&amp;oldid=12166" title="Headquarters" class="mw-changeslist-date">15:09, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,493 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,493 bytes after change">(+336)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added Data sorting for time and numbers)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12111&amp;undo=12166" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12111" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12111&amp;oldid=12110" title="Headquarters">prev</a>)</span><input type="radio" value="12111" name="oldid" id="mw-oldid-12111" /><input type="radio" value="12111" name="diff" id="mw-diff-12111" /> <a href="/index.php?title=Headquarters&amp;oldid=12111" title="Headquarters" class="mw-changeslist-date">01:41, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,157 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="43,157 bytes after change">(-297)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains: </span>  Fixed some formatting issues and table errors</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12110&amp;undo=12111" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12110" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12110&amp;oldid=12109" title="Headquarters">prev</a>)</span><input type="radio" value="12110" name="oldid" id="mw-oldid-12110" /><input type="radio" value="12110" name="diff" id="mw-diff-12110" /> <a href="/index.php?title=Headquarters&amp;oldid=12110" title="Headquarters" class="mw-changeslist-date">01:31, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,454 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,454 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12109&amp;undo=12110" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12109" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12109&amp;oldid=12108" title="Headquarters">prev</a>)</span><input type="radio" value="12109" name="oldid" id="mw-oldid-12109" /><input type="radio" value="12109" name="diff" id="mw-diff-12109" /> <a href="/index.php?title=Headquarters&amp;oldid=12109" title="Headquarters" class="mw-changeslist-date">01:30, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,448 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="43,448 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Introduction" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Introduction</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12108&amp;undo=12109" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12108" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12108&amp;oldid=12107" title="Headquarters">prev</a>)</span><input type="radio" value="12108" name="oldid" id="mw-oldid-12108" /><input type="radio" value="12108" name="diff" id="mw-diff-12108" /> <a href="/index.php?title=Headquarters&amp;oldid=12108" title="Headquarters" class="mw-changeslist-date">01:29, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,449 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,449 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production.2C_Recycling_and_Reverse_Engineering" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production, Recycling and Reverse Engineering</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12107&amp;undo=12108" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12107" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12107&amp;oldid=12106" title="Headquarters">prev</a>)</span><input type="radio" value="12107" name="oldid" id="mw-oldid-12107" /><input type="radio" value="12107" name="diff" id="mw-diff-12107" /> <a href="/index.php?title=Headquarters&amp;oldid=12107" title="Headquarters" class="mw-changeslist-date">01:28, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,447 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,447 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production.2C_Recycling_and_Reverse_Engineering" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production, Recycling and Reverse Engineering: </span> Moved box to the right side</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12106&amp;undo=12107" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12106" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12106&amp;oldid=12105" title="Headquarters">prev</a>)</span><input type="radio" value="12106" name="oldid" id="mw-oldid-12106" /><input type="radio" value="12106" name="diff" id="mw-diff-12106" /> <a href="/index.php?title=Headquarters&amp;oldid=12106" title="Headquarters" class="mw-changeslist-date">01:27, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,428 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="43,428 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production.2C_Recycling_and_Reverse_Engineering" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production, Recycling and Reverse Engineering</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12105&amp;undo=12106" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12105" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12105&amp;oldid=12104" title="Headquarters">prev</a>)</span><input type="radio" value="12105" name="oldid" id="mw-oldid-12105" /><input type="radio" value="12105" name="diff" id="mw-diff-12105" /> <a href="/index.php?title=Headquarters&amp;oldid=12105" title="Headquarters" class="mw-changeslist-date">01:26, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(43,426 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="43,426 bytes after change">(+1,808)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added Fleet Storage)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12104&amp;undo=12105" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12104" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12104&amp;oldid=12103" title="Headquarters">prev</a>)</span><input type="radio" value="12104" name="oldid" id="mw-oldid-12104" /><input type="radio" value="12104" name="diff" id="mw-diff-12104" /> <a href="/index.php?title=Headquarters&amp;oldid=12104" title="Headquarters" class="mw-changeslist-date">01:08, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(41,618 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="41,618 bytes after change">(-37,497)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12103&amp;undo=12104" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12103" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12103&amp;oldid=12102" title="Headquarters">prev</a>)</span><input type="radio" value="12103" name="oldid" id="mw-oldid-12103" /><input type="radio" value="12103" name="diff" id="mw-diff-12103" /> <a href="/index.php?title=Headquarters&amp;oldid=12103" title="Headquarters" class="mw-changeslist-date">00:50, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(79,115 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="79,115 bytes after change">(+77,193)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12102&amp;undo=12103" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12102" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12102&amp;oldid=12101" title="Headquarters">prev</a>)</span><input type="radio" value="12102" name="oldid" id="mw-oldid-12102" /><input type="radio" value="12102" name="diff" id="mw-diff-12102" /> <a href="/index.php?title=Headquarters&amp;oldid=12102" title="Headquarters" class="mw-changeslist-date">23:12, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,922 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="1,922 bytes after change">(-16,412)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12101&amp;undo=12102" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12101" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12101&amp;oldid=12100" title="Headquarters">prev</a>)</span><input type="radio" value="12101" name="oldid" id="mw-oldid-12101" /><input type="radio" value="12101" name="diff" id="mw-diff-12101" /> <a href="/index.php?title=Headquarters&amp;oldid=12101" title="Headquarters" class="mw-changeslist-date">22:52, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(18,334 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="18,334 bytes after change">(+105)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12100&amp;undo=12101" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12100" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12100&amp;oldid=12099" title="Headquarters">prev</a>)</span><input type="radio" value="12100" name="oldid" id="mw-oldid-12100" /><input type="radio" value="12100" name="diff" id="mw-diff-12100" /> <a href="/index.php?title=Headquarters&amp;oldid=12100" title="Headquarters" class="mw-changeslist-date">22:49, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(18,229 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="18,229 bytes after change">(+62)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Decomposition_and_Production" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Decomposition and Production</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12099&amp;undo=12100" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12099" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12099&amp;oldid=12098" title="Headquarters">prev</a>)</span><input type="radio" value="12099" name="oldid" id="mw-oldid-12099" /><input type="radio" value="12099" name="diff" id="mw-diff-12099" /> <a href="/index.php?title=Headquarters&amp;oldid=12099" title="Headquarters" class="mw-changeslist-date">22:46, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(18,167 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="18,167 bytes after change">(+278)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Decomposition_and_Production" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Decomposition and Production</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12098&amp;undo=12099" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12098" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12098&amp;oldid=12097" title="Headquarters">prev</a>)</span><input type="radio" value="12098" name="oldid" id="mw-oldid-12098" /><input type="radio" value="12098" name="diff" id="mw-diff-12098" /> <a href="/index.php?title=Headquarters&amp;oldid=12098" title="Headquarters" class="mw-changeslist-date">22:38, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(17,889 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="17,889 bytes after change">(-171,260)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Headquarters#Production_Costs_.2F_Gains" title="Headquarters">→</a>‎<span dir="auto"><span class="autocomment">Production Costs / Gains</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12097&amp;undo=12098" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12097" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12097&amp;oldid=12096" title="Headquarters">prev</a>)</span><input type="radio" value="12097" name="oldid" id="mw-oldid-12097" /><input type="radio" value="12097" name="diff" id="mw-diff-12097" /> <a href="/index.php?title=Headquarters&amp;oldid=12097" title="Headquarters" class="mw-changeslist-date">22:17, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(189,149 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="189,149 bytes after change">(-69,511)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12096&amp;undo=12097" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12096" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12096&amp;oldid=12090" title="Headquarters">prev</a>)</span><input type="radio" value="12096" name="oldid" id="mw-oldid-12096" /><input type="radio" value="12096" name="diff" id="mw-diff-12096" /> <a href="/index.php?title=Headquarters&amp;oldid=12096" title="Headquarters" class="mw-changeslist-date">22:12, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(258,660 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="258,660 bytes after change">(+257,764)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added table)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12090&amp;undo=12096" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12090" title="Headquarters">cur</a> | <a href="/index.php?title=Headquarters&amp;diff=12090&amp;oldid=12068" title="Headquarters">prev</a>)</span><input type="radio" value="12090" name="oldid" id="mw-oldid-12090" /><input type="radio" value="12090" name="diff" id="mw-diff-12090" /> <a href="/index.php?title=Headquarters&amp;oldid=12090" title="Headquarters" class="mw-changeslist-date">21:36, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(896 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="896 bytes after change">(+888)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added Basics)</span> (<span class="mw-history-undo"><a href="/index.php?title=Headquarters&amp;action=edit&amp;undoafter=12068&amp;undo=12090" title="Headquarters">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Headquarters&amp;diff=16319&amp;oldid=12068" title="Headquarters">cur</a> | prev)</span><input type="radio" value="12068" name="oldid" id="mw-oldid-12068" /><input type="radio" value="12068" name="diff" id="mw-diff-12068" /> <a href="/index.php?title=Headquarters&amp;oldid=12068" title="Headquarters" class="mw-changeslist-date">19:16, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Created page with &quot;{{stub}}&quot;)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://x3wiki.com/index.php/Headquarters">http://x3wiki.com/index.php/Headquarters</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Headquarters" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Headquarters&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Headquarters&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Headquarters&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Headquarters&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Headquarters&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Headquarters" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Headquarters" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Headquarters&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Headquarters&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":84});});</script></body></html>
