<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Remote Guided Warhead" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Remote_Guided_Warhead","wgTitle":"Remote Guided Warhead","wgCurRevisionId":14277,"wgRevisionId":0,"wgArticleId":40,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Remote_Guided_Warhead","wgRelevantArticleId":40,"wgRequestId":"Wi0KXlkfZokAAAXdM4QAAAAQ","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Remote_Guided_Warhead&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Remote_Guided_Warhead&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Remote Guided Warhead&quot; Atom feed" href="/index.php?title=Remote_Guided_Warhead&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Remote_Guided_Warhead rootpage-Remote_Guided_Warhead skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Remote Guided Warhead"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Remote+Guided+Warhead" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Remote_Guided_Warhead" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Remote_Guided_Warhead" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14179" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14277" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14277" checked="checked" name="diff" id="mw-diff-14277" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14277" title="Remote Guided Warhead" class="mw-changeslist-date">14:26, 29 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,119 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,119 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Add Not Purchasable category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=14179&amp;undo=14277" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14179" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14179&amp;oldid=14094" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14179" checked="checked" name="oldid" id="mw-oldid-14179" /><input type="radio" value="14179" name="diff" id="mw-diff-14179" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14179" title="Remote Guided Warhead" class="mw-changeslist-date">09:13, 11 January 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,090 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,090 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=14094&amp;undo=14179" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14094" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14094&amp;oldid=14065" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14094" name="oldid" id="mw-oldid-14094" /><input type="radio" value="14094" name="diff" id="mw-diff-14094" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14094" title="Remote Guided Warhead" class="mw-changeslist-date">22:27, 22 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,090 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,090 bytes after change">(-21)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=14065&amp;undo=14094" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14065" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14065&amp;oldid=14062" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14065" name="oldid" id="mw-oldid-14065" /><input type="radio" value="14065" name="diff" id="mw-diff-14065" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14065" title="Remote Guided Warhead" class="mw-changeslist-date">22:01, 19 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,111 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,111 bytes after change">(+162)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=14062&amp;undo=14065" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14062" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14062&amp;oldid=14018" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14062" name="oldid" id="mw-oldid-14062" /><input type="radio" value="14062" name="diff" id="mw-diff-14062" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14062" title="Remote Guided Warhead" class="mw-changeslist-date">21:53, 19 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,949 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,949 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=14018&amp;undo=14062" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=14018" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14018&amp;oldid=13768" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="14018" name="oldid" id="mw-oldid-14018" /><input type="radio" value="14018" name="diff" id="mw-diff-14018" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=14018" title="Remote Guided Warhead" class="mw-changeslist-date">22:32, 28 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,949 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,949 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=13768&amp;undo=14018" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=13768" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=13768&amp;oldid=12874" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="13768" name="oldid" id="mw-oldid-13768" /><input type="radio" value="13768" name="diff" id="mw-diff-13768" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=13768" title="Remote Guided Warhead" class="mw-changeslist-date">18:53, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,949 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,949 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12874&amp;undo=13768" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12874" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12874&amp;oldid=12364" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12874" name="oldid" id="mw-oldid-12874" /><input type="radio" value="12874" name="diff" id="mw-diff-12874" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12874" title="Remote Guided Warhead" class="mw-changeslist-date">00:06, 26 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,930 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,930 bytes after change">(-17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12364&amp;undo=12874" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12364" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12364&amp;oldid=12322" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12364" name="oldid" id="mw-oldid-12364" /><input type="radio" value="12364" name="diff" id="mw-diff-12364" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12364" title="Remote Guided Warhead" class="mw-changeslist-date">00:14, 2 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,947 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,947 bytes after change">(+220)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview: </span> Encyclopedia Entry</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12322&amp;undo=12364" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12322" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12322&amp;oldid=12320" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12322" name="oldid" id="mw-oldid-12322" /><input type="radio" value="12322" name="diff" id="mw-diff-12322" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12322" title="Remote Guided Warhead" class="mw-changeslist-date">21:21, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,727 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,727 bytes after change">(+115)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12320&amp;undo=12322" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12320" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12320&amp;oldid=12319" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12320" name="oldid" id="mw-oldid-12320" /><input type="radio" value="12320" name="diff" id="mw-diff-12320" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12320" title="Remote Guided Warhead" class="mw-changeslist-date">21:20, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,612 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,612 bytes after change">(-91)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12319&amp;undo=12320" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12319" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12319&amp;oldid=12317" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12319" name="oldid" id="mw-oldid-12319" /><input type="radio" value="12319" name="diff" id="mw-diff-12319" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12319" title="Remote Guided Warhead" class="mw-changeslist-date">21:19, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,703 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,703 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12317&amp;undo=12319" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12317" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12317&amp;oldid=12314" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12317" name="oldid" id="mw-oldid-12317" /><input type="radio" value="12317" name="diff" id="mw-diff-12317" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12317" title="Remote Guided Warhead" class="mw-changeslist-date">21:18, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,696 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,696 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=12314&amp;undo=12317" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=12314" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=12314&amp;oldid=11949" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="12314" name="oldid" id="mw-oldid-12314" /><input type="radio" value="12314" name="diff" id="mw-diff-12314" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=12314" title="Remote Guided Warhead" class="mw-changeslist-date">21:17, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,679 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,679 bytes after change">(+91)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11949&amp;undo=12314" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11949" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11949&amp;oldid=11941" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11949" name="oldid" id="mw-oldid-11949" /><input type="radio" value="11949" name="diff" id="mw-diff-11949" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11949" title="Remote Guided Warhead" class="mw-changeslist-date">20:21, 17 April 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,588 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,588 bytes after change">(+29)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11941&amp;undo=11949" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11941" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11941&amp;oldid=11940" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11941" name="oldid" id="mw-oldid-11941" /><input type="radio" value="11941" name="diff" id="mw-diff-11941" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11941" title="Remote Guided Warhead" class="mw-changeslist-date">01:01, 16 April 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,559 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,559 bytes after change">(+80)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11940&amp;undo=11941" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11940" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11940&amp;oldid=11833" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11940" name="oldid" id="mw-oldid-11940" /><input type="radio" value="11940" name="diff" id="mw-diff-11940" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11940" title="Remote Guided Warhead" class="mw-changeslist-date">00:58, 16 April 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,479 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,479 bytes after change">(+155)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11833&amp;undo=11940" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11833" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11833&amp;oldid=11826" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11833" name="oldid" id="mw-oldid-11833" /><input type="radio" value="11833" name="diff" id="mw-diff-11833" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11833" title="Remote Guided Warhead" class="mw-changeslist-date">08:12, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,324 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,324 bytes after change">(-112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11826&amp;undo=11833" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11826" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11826&amp;oldid=11824" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11826" name="oldid" id="mw-oldid-11826" /><input type="radio" value="11826" name="diff" id="mw-diff-11826" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11826" title="Remote Guided Warhead" class="mw-changeslist-date">07:42, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,436 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,436 bytes after change">(+32)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=11824&amp;undo=11826" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=11824" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=11824&amp;oldid=7896" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="11824" name="oldid" id="mw-oldid-11824" /><input type="radio" value="11824" name="diff" id="mw-diff-11824" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=11824" title="Remote Guided Warhead" class="mw-changeslist-date">07:36, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,404 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,404 bytes after change">(+295)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=7896&amp;undo=11824" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=7896" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=7896&amp;oldid=3917" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="7896" name="oldid" id="mw-oldid-7896" /><input type="radio" value="7896" name="diff" id="mw-diff-7896" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=7896" title="Remote Guided Warhead" class="mw-changeslist-date">04:31, 16 November 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,109 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,109 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(case sensitive)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=3917&amp;undo=7896" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=3917" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=3917&amp;oldid=3916" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="3917" name="oldid" id="mw-oldid-3917" /><input type="radio" value="3917" name="diff" id="mw-diff-3917" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=3917" title="Remote Guided Warhead" class="mw-changeslist-date">15:26, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,109 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,109 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=3916&amp;undo=3917" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=3916" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=3916&amp;oldid=3915" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="3916" name="oldid" id="mw-oldid-3916" /><input type="radio" value="3916" name="diff" id="mw-diff-3916" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=3916" title="Remote Guided Warhead" class="mw-changeslist-date">15:26, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,102 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,102 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=3915&amp;undo=3916" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=3915" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=3915&amp;oldid=3914" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="3915" name="oldid" id="mw-oldid-3915" /><input type="radio" value="3915" name="diff" id="mw-diff-3915" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=3915" title="Remote Guided Warhead" class="mw-changeslist-date">15:25, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,102 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,102 bytes after change">(+112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=3914&amp;undo=3915" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=3914" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=3914&amp;oldid=2397" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="3914" name="oldid" id="mw-oldid-3914" /><input type="radio" value="3914" name="diff" id="mw-diff-3914" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=3914" title="Remote Guided Warhead" class="mw-changeslist-date">15:23, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(990 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="990 bytes after change">(-90)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=2397&amp;undo=3914" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=2397" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=2397&amp;oldid=1444" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="2397" name="oldid" id="mw-oldid-2397" /><input type="radio" value="2397" name="diff" id="mw-diff-2397" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=2397" title="Remote Guided Warhead" class="mw-changeslist-date">20:40, 7 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,080 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,080 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(based on commentary, changed guidance to Image recognition)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=1444&amp;undo=2397" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=1444" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=1444&amp;oldid=1430" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="1444" name="oldid" id="mw-oldid-1444" /><input type="radio" value="1444" name="diff" id="mw-diff-1444" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=1444" title="Remote Guided Warhead" class="mw-changeslist-date">01:40, 24 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,057 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,057 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(missile data fill)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=1430&amp;undo=1444" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=1430" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=1430&amp;oldid=1429" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="1430" name="oldid" id="mw-oldid-1430" /><input type="radio" value="1430" name="diff" id="mw-diff-1430" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=1430" title="Remote Guided Warhead" class="mw-changeslist-date">21:35, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,034 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,034 bytes after change">(+280)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Overview" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=1429&amp;undo=1430" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=1429" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=1429&amp;oldid=800" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="1429" name="oldid" id="mw-oldid-1429" /><input type="radio" value="1429" name="diff" id="mw-diff-1429" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=1429" title="Remote Guided Warhead" class="mw-changeslist-date">21:33, 23 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(754 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="754 bytes after change">(+266)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Remote_Guided_Warhead#Commentary" title="Remote Guided Warhead">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=800&amp;undo=1429" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=800" title="Remote Guided Warhead">cur</a> | <a href="/index.php?title=Remote_Guided_Warhead&amp;diff=800&amp;oldid=156" title="Remote Guided Warhead">prev</a>)</span><input type="radio" value="800" name="oldid" id="mw-oldid-800" /><input type="radio" value="800" name="diff" id="mw-diff-800" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=800" title="Remote Guided Warhead" class="mw-changeslist-date">20:14, 14 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(488 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="488 bytes after change">(+298)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(standard form)</span> (<span class="mw-history-undo"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit&amp;undoafter=156&amp;undo=800" title="Remote Guided Warhead">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Remote_Guided_Warhead&amp;diff=14277&amp;oldid=156" title="Remote Guided Warhead">cur</a> | prev)</span><input type="radio" value="156" name="oldid" id="mw-oldid-156" /><input type="radio" value="156" name="diff" id="mw-diff-156" /> <a href="/index.php?title=Remote_Guided_Warhead&amp;oldid=156" title="Remote Guided Warhead" class="mw-changeslist-date">00:12, 23 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(190 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="190 bytes after change">(+190)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(copy from cache)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Remote_Guided_Warhead">http://www.x3wiki.com/index.php/Remote_Guided_Warhead</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Remote_Guided_Warhead" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Remote_Guided_Warhead&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Remote+Guided+Warhead&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Remote+Guided+Warhead&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Remote_Guided_Warhead" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Remote_Guided_Warhead" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Remote_Guided_Warhead&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Remote_Guided_Warhead&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":79});});</script></body></html>
