<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Typhoon Missile" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Typhoon_Missile","wgTitle":"Typhoon Missile","wgCurRevisionId":14338,"wgRevisionId":0,"wgArticleId":307,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Typhoon_Missile","wgRelevantArticleId":307,"wgRequestId":"WTCITlkfZokAAFP3e5AAAAAL","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Typhoon_Missile&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Typhoon_Missile&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Typhoon Missile&quot; Atom feed" href="/index.php?title=Typhoon_Missile&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Typhoon_Missile rootpage-Typhoon_Missile skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Typhoon Missile"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Typhoon+Missile" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Typhoon_Missile" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2017" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Typhoon_Missile" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=14071" title="Typhoon Missile">prev</a>)</span><input type="radio" value="14338" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14338" checked="checked" name="diff" id="mw-diff-14338" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=14338" title="Typhoon Missile" class="mw-changeslist-date">10:45, 18 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,583 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,583 bytes after change">(+179)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=14071&amp;undo=14338" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=14071" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=14071&amp;oldid=14068" title="Typhoon Missile">prev</a>)</span><input type="radio" value="14071" checked="checked" name="oldid" id="mw-oldid-14071" /><input type="radio" value="14071" name="diff" id="mw-diff-14071" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=14071" title="Typhoon Missile" class="mw-changeslist-date">00:48, 20 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,404 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,404 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=14068&amp;undo=14071" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=14068" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=14068&amp;oldid=14067" title="Typhoon Missile">prev</a>)</span><input type="radio" value="14068" name="oldid" id="mw-oldid-14068" /><input type="radio" value="14068" name="diff" id="mw-diff-14068" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=14068" title="Typhoon Missile" class="mw-changeslist-date">00:43, 20 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,400 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,400 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=14067&amp;undo=14068" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=14067" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=14067&amp;oldid=13751" title="Typhoon Missile">prev</a>)</span><input type="radio" value="14067" name="oldid" id="mw-oldid-14067" /><input type="radio" value="14067" name="diff" id="mw-diff-14067" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=14067" title="Typhoon Missile" class="mw-changeslist-date">00:43, 20 December 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,392 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,392 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=13751&amp;undo=14067" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=13751" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=13751&amp;oldid=11953" title="Typhoon Missile">prev</a>)</span><input type="radio" value="13751" name="oldid" id="mw-oldid-13751" /><input type="radio" value="13751" name="diff" id="mw-diff-13751" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=13751" title="Typhoon Missile" class="mw-changeslist-date">19:51, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,365 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,365 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11953&amp;undo=13751" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11953" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11953&amp;oldid=11847" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11953" name="oldid" id="mw-oldid-11953" /><input type="radio" value="11953" name="diff" id="mw-diff-11953" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11953" title="Typhoon Missile" class="mw-changeslist-date">21:27, 17 April 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,346 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,346 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11847&amp;undo=11953" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11847" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11847&amp;oldid=11846" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11847" name="oldid" id="mw-oldid-11847" /><input type="radio" value="11847" name="diff" id="mw-diff-11847" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11847" title="Typhoon Missile" class="mw-changeslist-date">04:08, 27 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,346 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,346 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11846&amp;undo=11847" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11846" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11846&amp;oldid=11845" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11846" name="oldid" id="mw-oldid-11846" /><input type="radio" value="11846" name="diff" id="mw-diff-11846" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11846" title="Typhoon Missile" class="mw-changeslist-date">04:02, 27 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,305 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,305 bytes after change">(+73)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11845&amp;undo=11846" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11845" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11845&amp;oldid=11844" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11845" name="oldid" id="mw-oldid-11845" /><input type="radio" value="11845" name="diff" id="mw-diff-11845" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11845" title="Typhoon Missile" class="mw-changeslist-date">03:59, 27 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,232 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,232 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11844&amp;undo=11845" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11844" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11844&amp;oldid=11843" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11844" name="oldid" id="mw-oldid-11844" /><input type="radio" value="11844" name="diff" id="mw-diff-11844" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11844" title="Typhoon Missile" class="mw-changeslist-date">03:57, 27 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,204 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,204 bytes after change">(+287)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11843&amp;undo=11844" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11843" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11843&amp;oldid=11735" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11843" name="oldid" id="mw-oldid-11843" /><input type="radio" value="11843" name="diff" id="mw-diff-11843" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11843" title="Typhoon Missile" class="mw-changeslist-date">03:51, 27 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,917 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,917 bytes after change">(+45)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11735&amp;undo=11843" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11735" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11735&amp;oldid=11732" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11735" name="oldid" id="mw-oldid-11735" /><input type="radio" value="11735" name="diff" id="mw-diff-11735" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11735" title="Typhoon Missile" class="mw-changeslist-date">01:19, 18 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,872 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,872 bytes after change">(+335)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11732&amp;undo=11735" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11732" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11732&amp;oldid=11604" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11732" name="oldid" id="mw-oldid-11732" /><input type="radio" value="11732" name="diff" id="mw-diff-11732" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11732" title="Typhoon Missile" class="mw-changeslist-date">08:15, 15 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,537 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,537 bytes after change">(+72)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11604&amp;undo=11732" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11604" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11604&amp;oldid=11603" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11604" name="oldid" id="mw-oldid-11604" /><input type="radio" value="11604" name="diff" id="mw-diff-11604" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11604" title="Typhoon Missile" class="mw-changeslist-date">04:10, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,465 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,465 bytes after change">(+101)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=11603&amp;undo=11604" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=11603" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=11603&amp;oldid=7886" title="Typhoon Missile">prev</a>)</span><input type="radio" value="11603" name="oldid" id="mw-oldid-11603" /><input type="radio" value="11603" name="diff" id="mw-diff-11603" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=11603" title="Typhoon Missile" class="mw-changeslist-date">04:08, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,364 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,364 bytes after change">(+192)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=7886&amp;undo=11603" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=7886" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=7886&amp;oldid=7796" title="Typhoon Missile">prev</a>)</span><input type="radio" value="7886" name="oldid" id="mw-oldid-7886" /><input type="radio" value="7886" name="diff" id="mw-diff-7886" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=7886" title="Typhoon Missile" class="mw-changeslist-date">05:14, 16 November 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,172 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,172 bytes after change">(-40)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(case sensitive)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=7796&amp;undo=7886" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=7796" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=7796&amp;oldid=7795" title="Typhoon Missile">prev</a>)</span><input type="radio" value="7796" name="oldid" id="mw-oldid-7796" /><input type="radio" value="7796" name="diff" id="mw-diff-7796" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=7796" title="Typhoon Missile" class="mw-changeslist-date">06:48, 31 October 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.247.160.198" title="Special:Contributions/70.247.160.198" class="mw-userlink mw-anonuserlink">70.247.160.198</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.247.160.198&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.247.160.198 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,212 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,212 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=7795&amp;undo=7796" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=7795" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=7795&amp;oldid=5766" title="Typhoon Missile">prev</a>)</span><input type="radio" value="7795" name="oldid" id="mw-oldid-7795" /><input type="radio" value="7795" name="diff" id="mw-diff-7795" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=7795" title="Typhoon Missile" class="mw-changeslist-date">06:48, 31 October 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.247.160.198" title="Special:Contributions/70.247.160.198" class="mw-userlink mw-anonuserlink">70.247.160.198</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.247.160.198&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.247.160.198 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,213 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,213 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=5766&amp;undo=7795" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=5766" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=5766&amp;oldid=5241" title="Typhoon Missile">prev</a>)</span><input type="radio" value="5766" name="oldid" id="mw-oldid-5766" /><input type="radio" value="5766" name="diff" id="mw-diff-5766" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=5766" title="Typhoon Missile" class="mw-changeslist-date">00:55, 17 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,203 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,203 bytes after change">(+134)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added categories)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=5241&amp;undo=5766" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=5241" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=5241&amp;oldid=3947" title="Typhoon Missile">prev</a>)</span><input type="radio" value="5241" name="oldid" id="mw-oldid-5241" /><input type="radio" value="5241" name="diff" id="mw-diff-5241" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=5241" title="Typhoon Missile" class="mw-changeslist-date">03:49, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,069 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,069 bytes after change">(+436)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(overwrote ave price 80856 with encyclopedia 33692, verification? updated with encyclopedia info. verified lower bound.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=3947&amp;undo=5241" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=3947" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=3947&amp;oldid=3908" title="Typhoon Missile">prev</a>)</span><input type="radio" value="3947" name="oldid" id="mw-oldid-3947" /><input type="radio" value="3947" name="diff" id="mw-diff-3947" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=3947" title="Typhoon Missile" class="mw-changeslist-date">12:19, 4 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(633 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="633 bytes after change">(+152)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Commentary" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=3908&amp;undo=3947" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=3908" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=3908&amp;oldid=2374" title="Typhoon Missile">prev</a>)</span><input type="radio" value="3908" name="oldid" id="mw-oldid-3908" /><input type="radio" value="3908" name="diff" id="mw-diff-3908" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=3908" title="Typhoon Missile" class="mw-changeslist-date">03:37, 1 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(481 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="481 bytes after change">(+166)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Typhoon_Missile#Overview" title="Typhoon Missile">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=2374&amp;undo=3908" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=2374" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=2374&amp;oldid=1197" title="Typhoon Missile">prev</a>)</span><input type="radio" value="2374" name="oldid" id="mw-oldid-2374" /><input type="radio" value="2374" name="diff" id="mw-diff-2374" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=2374" title="Typhoon Missile" class="mw-changeslist-date">21:03, 7 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(315 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="315 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(aoe)</span> (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=1197&amp;undo=2374" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=1197" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=1197&amp;oldid=1133" title="Typhoon Missile">prev</a>)</span><input type="radio" value="1197" name="oldid" id="mw-oldid-1197" /><input type="radio" value="1197" name="diff" id="mw-diff-1197" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=1197" title="Typhoon Missile" class="mw-changeslist-date">10:54, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(310 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="310 bytes after change">(-8)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=1133&amp;undo=1197" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=1133" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=1133&amp;oldid=1132" title="Typhoon Missile">prev</a>)</span><input type="radio" value="1133" name="oldid" id="mw-oldid-1133" /><input type="radio" value="1133" name="diff" id="mw-diff-1133" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=1133" title="Typhoon Missile" class="mw-changeslist-date">05:00, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(318 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="318 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=1132&amp;undo=1133" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=1132" title="Typhoon Missile">cur</a> | <a href="/index.php?title=Typhoon_Missile&amp;diff=1132&amp;oldid=857" title="Typhoon Missile">prev</a>)</span><input type="radio" value="1132" name="oldid" id="mw-oldid-1132" /><input type="radio" value="1132" name="diff" id="mw-diff-1132" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=1132" title="Typhoon Missile" class="mw-changeslist-date">05:00, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/70.65.251.68" title="Special:Contributions/70.65.251.68" class="mw-userlink mw-anonuserlink">70.65.251.68</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:70.65.251.68&amp;action=edit&amp;redlink=1" class="new" title="User talk:70.65.251.68 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(318 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="318 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Typhoon_Missile&amp;action=edit&amp;undoafter=857&amp;undo=1132" title="Typhoon Missile">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Typhoon_Missile&amp;diff=14338&amp;oldid=857" title="Typhoon Missile">cur</a> | prev)</span><input type="radio" value="857" name="oldid" id="mw-oldid-857" /><input type="radio" value="857" name="diff" id="mw-diff-857" /> <a href="/index.php?title=Typhoon_Missile&amp;oldid=857" title="Typhoon Missile" class="mw-changeslist-date">20:57, 22 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(309 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="309 bytes after change">(+309)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(start)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Typhoon_Missile">http://www.x3wiki.com/index.php/Typhoon_Missile</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Typhoon_Missile" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Typhoon_Missile&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Typhoon_Missile&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Typhoon_Missile&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Typhoon+Missile&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Typhoon+Missile&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Typhoon_Missile" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Typhoon_Missile" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Typhoon_Missile&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Typhoon_Missile&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":81});});</script></body></html>
