<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Elite" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Elite&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Elite&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Elite&quot; Atom feed" href="/index.php?title=Elite&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Elite","wgTitle":"Elite","wgCurRevisionId":13657,"wgRevisionId":0,"wgArticleId":191,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Elite","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Elite skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Elite"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Elite" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Elite" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Elite" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=12723" title="Elite">prev</a>)</span><input type="radio" value="13657" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="13657" checked="checked" name="diff" id="mw-diff-13657" /> <a href="/index.php?title=Elite&amp;oldid=13657" title="Elite" class="mw-changeslist-date">08:38, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,716 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,716 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=12723&amp;undo=13657" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=12723" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=12723&amp;oldid=12705" title="Elite">prev</a>)</span><input type="radio" value="12723" checked="checked" name="oldid" id="mw-oldid-12723" /><input type="radio" value="12723" name="diff" id="mw-diff-12723" /> <a href="/index.php?title=Elite&amp;oldid=12723" title="Elite" class="mw-changeslist-date">06:26, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,699 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,699 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(reintroduce related reference)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=12705&amp;undo=12723" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=12705" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=12705&amp;oldid=11585" title="Elite">prev</a>)</span><input type="radio" value="12705" name="oldid" id="mw-oldid-12705" /><input type="radio" value="12705" name="diff" id="mw-diff-12705" /> <a href="/index.php?title=Elite&amp;oldid=12705" title="Elite" class="mw-changeslist-date">06:13, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,674 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,674 bytes after change">(-41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#See_Also" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> remove unrelated specific reference</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11585&amp;undo=12705" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11585" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11585&amp;oldid=11584" title="Elite">prev</a>)</span><input type="radio" value="11585" name="oldid" id="mw-oldid-11585" /><input type="radio" value="11585" name="diff" id="mw-diff-11585" /> <a href="/index.php?title=Elite&amp;oldid=11585" title="Elite" class="mw-changeslist-date">02:04, 11 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,715 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,715 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11584&amp;undo=11585" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11584" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11584&amp;oldid=11578" title="Elite">prev</a>)</span><input type="radio" value="11584" name="oldid" id="mw-oldid-11584" /><input type="radio" value="11584" name="diff" id="mw-diff-11584" /> <a href="/index.php?title=Elite&amp;oldid=11584" title="Elite" class="mw-changeslist-date">02:03, 11 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,713 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,713 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11578&amp;undo=11584" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11578" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11578&amp;oldid=11567" title="Elite">prev</a>)</span><input type="radio" value="11578" name="oldid" id="mw-oldid-11578" /><input type="radio" value="11578" name="diff" id="mw-diff-11578" /> <a href="/index.php?title=Elite&amp;oldid=11578" title="Elite" class="mw-changeslist-date">02:06, 7 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,700 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,700 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11567&amp;undo=11578" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11567" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11567&amp;oldid=11380" title="Elite">prev</a>)</span><input type="radio" value="11567" name="oldid" id="mw-oldid-11567" /><input type="radio" value="11567" name="diff" id="mw-diff-11567" /> <a href="/index.php?title=Elite&amp;oldid=11567" title="Elite" class="mw-changeslist-date">22:37, 6 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,687 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,687 bytes after change">(+12)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11380&amp;undo=11567" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11380" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11380&amp;oldid=11379" title="Elite">prev</a>)</span><input type="radio" value="11380" name="oldid" id="mw-oldid-11380" /><input type="radio" value="11380" name="diff" id="mw-diff-11380" /> <a href="/index.php?title=Elite&amp;oldid=11380" title="Elite" class="mw-changeslist-date">10:03, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,675 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,675 bytes after change">(+200)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Enhanced_Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Enhanced Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11379&amp;undo=11380" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11379" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11379&amp;oldid=11378" title="Elite">prev</a>)</span><input type="radio" value="11379" name="oldid" id="mw-oldid-11379" /><input type="radio" value="11379" name="diff" id="mw-diff-11379" /> <a href="/index.php?title=Elite&amp;oldid=11379" title="Elite" class="mw-changeslist-date">10:01, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,475 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,475 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Combat" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11378&amp;undo=11379" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11378" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11378&amp;oldid=11377" title="Elite">prev</a>)</span><input type="radio" value="11378" name="oldid" id="mw-oldid-11378" /><input type="radio" value="11378" name="diff" id="mw-diff-11378" /> <a href="/index.php?title=Elite&amp;oldid=11378" title="Elite" class="mw-changeslist-date">10:00, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,470 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,470 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Combat" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11377&amp;undo=11378" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11377" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11377&amp;oldid=11376" title="Elite">prev</a>)</span><input type="radio" value="11377" name="oldid" id="mw-oldid-11377" /><input type="radio" value="11377" name="diff" id="mw-diff-11377" /> <a href="/index.php?title=Elite&amp;oldid=11377" title="Elite" class="mw-changeslist-date">10:00, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,466 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,466 bytes after change">(+161)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Combat" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11376&amp;undo=11377" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11376" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11376&amp;oldid=11375" title="Elite">prev</a>)</span><input type="radio" value="11376" name="oldid" id="mw-oldid-11376" /><input type="radio" value="11376" name="diff" id="mw-diff-11376" /> <a href="/index.php?title=Elite&amp;oldid=11376" title="Elite" class="mw-changeslist-date">09:58, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,305 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,305 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11375&amp;undo=11376" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11375" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11375&amp;oldid=11374" title="Elite">prev</a>)</span><input type="radio" value="11375" name="oldid" id="mw-oldid-11375" /><input type="radio" value="11375" name="diff" id="mw-diff-11375" /> <a href="/index.php?title=Elite&amp;oldid=11375" title="Elite" class="mw-changeslist-date">09:58, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,297 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,297 bytes after change">(+320)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11374&amp;undo=11375" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11374" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11374&amp;oldid=11373" title="Elite">prev</a>)</span><input type="radio" value="11374" name="oldid" id="mw-oldid-11374" /><input type="radio" value="11374" name="diff" id="mw-diff-11374" /> <a href="/index.php?title=Elite&amp;oldid=11374" title="Elite" class="mw-changeslist-date">09:54, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,977 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,977 bytes after change">(+390)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Pirate_Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Pirate Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11373&amp;undo=11374" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11373" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11373&amp;oldid=11372" title="Elite">prev</a>)</span><input type="radio" value="11373" name="oldid" id="mw-oldid-11373" /><input type="radio" value="11373" name="diff" id="mw-diff-11373" /> <a href="/index.php?title=Elite&amp;oldid=11373" title="Elite" class="mw-changeslist-date">09:51, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,587 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,587 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=11372&amp;undo=11373" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=11372" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=11372&amp;oldid=10646" title="Elite">prev</a>)</span><input type="radio" value="11372" name="oldid" id="mw-oldid-11372" /><input type="radio" value="11372" name="diff" id="mw-diff-11372" /> <a href="/index.php?title=Elite&amp;oldid=11372" title="Elite" class="mw-changeslist-date">09:50, 14 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,552 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,552 bytes after change">(+311)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Elite" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Elite</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=10646&amp;undo=11372" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=10646" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=10646&amp;oldid=10471" title="Elite">prev</a>)</span><input type="radio" value="10646" name="oldid" id="mw-oldid-10646" /><input type="radio" value="10646" name="diff" id="mw-diff-10646" /> <a href="/index.php?title=Elite&amp;oldid=10646" title="Elite" class="mw-changeslist-date">18:53, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,241 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,241 bytes after change">(-193)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M4+ template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=10471&amp;undo=10646" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=10471" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=10471&amp;oldid=10470" title="Elite">prev</a>)</span><input type="radio" value="10471" name="oldid" id="mw-oldid-10471" /><input type="radio" value="10471" name="diff" id="mw-diff-10471" /> <a href="/index.php?title=Elite&amp;oldid=10471" title="Elite" class="mw-changeslist-date">22:57, 14 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,434 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,434 bytes after change">(+522)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; Enhanced Elite missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=10470&amp;undo=10471" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=10470" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=10470&amp;oldid=10469" title="Elite">prev</a>)</span><input type="radio" value="10470" name="oldid" id="mw-oldid-10470" /><input type="radio" value="10470" name="diff" id="mw-diff-10470" /> <a href="/index.php?title=Elite&amp;oldid=10470" title="Elite" class="mw-changeslist-date">22:53, 14 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,912 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,912 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=10469&amp;undo=10470" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=10469" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=10469&amp;oldid=9616" title="Elite">prev</a>)</span><input type="radio" value="10469" name="oldid" id="mw-oldid-10469" /><input type="radio" value="10469" name="diff" id="mw-diff-10469" /> <a href="/index.php?title=Elite&amp;oldid=10469" title="Elite" class="mw-changeslist-date">22:53, 14 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,913 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,913 bytes after change">(+313)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=9616&amp;undo=10469" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=9616" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=9616&amp;oldid=8657" title="Elite">prev</a>)</span><input type="radio" value="9616" name="oldid" id="mw-oldid-9616" /><input type="radio" value="9616" name="diff" id="mw-diff-9616" /> <a href="/index.php?title=Elite&amp;oldid=9616" title="Elite" class="mw-changeslist-date">14:13, 2 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,600 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,600 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=8657&amp;undo=9616" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=8657" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=8657&amp;oldid=8649" title="Elite">prev</a>)</span><input type="radio" value="8657" name="oldid" id="mw-oldid-8657" /><input type="radio" value="8657" name="diff" id="mw-diff-8657" /> <a href="/index.php?title=Elite&amp;oldid=8657" title="Elite" class="mw-changeslist-date">13:41, 18 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,576 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,576 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=8649&amp;undo=8657" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=8649" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=8649&amp;oldid=8423" title="Elite">prev</a>)</span><input type="radio" value="8649" name="oldid" id="mw-oldid-8649" /><input type="radio" value="8649" name="diff" id="mw-diff-8649" /> <a href="/index.php?title=Elite&amp;oldid=8649" title="Elite" class="mw-changeslist-date">22:55, 17 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,575 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,575 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=8423&amp;undo=8649" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=8423" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=8423&amp;oldid=8224" title="Elite">prev</a>)</span><input type="radio" value="8423" name="oldid" id="mw-oldid-8423" /><input type="radio" value="8423" name="diff" id="mw-diff-8423" /> <a href="/index.php?title=Elite&amp;oldid=8423" title="Elite" class="mw-changeslist-date">18:33, 3 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/62.107.32.49" title="Special:Contributions/62.107.32.49" class="mw-userlink">62.107.32.49</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:62.107.32.49&amp;action=edit&amp;redlink=1" class="new" title="User talk:62.107.32.49 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,575 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,575 bytes after change">(+302)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Combat" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=8224&amp;undo=8423" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=8224" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=8224&amp;oldid=7749" title="Elite">prev</a>)</span><input type="radio" value="8224" name="oldid" id="mw-oldid-8224" /><input type="radio" value="8224" name="diff" id="mw-diff-8224" /> <a href="/index.php?title=Elite&amp;oldid=8224" title="Elite" class="mw-changeslist-date">11:33, 29 December 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/80.247.240.240" title="Special:Contributions/80.247.240.240" class="mw-userlink">80.247.240.240</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:80.247.240.240&amp;action=edit&amp;redlink=1" class="new" title="User talk:80.247.240.240 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,273 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,273 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=7749&amp;undo=8224" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=7749" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=7749&amp;oldid=7073" title="Elite">prev</a>)</span><input type="radio" value="7749" name="oldid" id="mw-oldid-7749" /><input type="radio" value="7749" name="diff" id="mw-diff-7749" /> <a href="/index.php?title=Elite&amp;oldid=7749" title="Elite" class="mw-changeslist-date">21:19, 28 October 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,271 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,271 bytes after change">(+687)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(cleanup; added data, category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=7073&amp;undo=7749" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=7073" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=7073&amp;oldid=6819" title="Elite">prev</a>)</span><input type="radio" value="7073" name="oldid" id="mw-oldid-7073" /><input type="radio" value="7073" name="diff" id="mw-diff-7073" /> <a href="/index.php?title=Elite&amp;oldid=7073" title="Elite" class="mw-changeslist-date">17:04, 20 August 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/87.57.70.242" title="Special:Contributions/87.57.70.242" class="mw-userlink">87.57.70.242</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:87.57.70.242&amp;action=edit&amp;redlink=1" class="new" title="User talk:87.57.70.242 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,584 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,584 bytes after change">(+195)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Suggested_Roles" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=6819&amp;undo=7073" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=6819" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=6819&amp;oldid=6593" title="Elite">prev</a>)</span><input type="radio" value="6819" name="oldid" id="mw-oldid-6819" /><input type="radio" value="6819" name="diff" id="mw-diff-6819" /> <a href="/index.php?title=Elite&amp;oldid=6819" title="Elite" class="mw-changeslist-date">19:26, 7 August 2011</a>‎ <span class='history-user'><a href="/index.php/User:Nepo11" title="User:Nepo11" class="mw-userlink">Nepo11</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Nepo11" title="User talk:Nepo11">Talk</a> | <a href="/index.php/Special:Contributions/Nepo11" title="Special:Contributions/Nepo11">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,389 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,389 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added some missing values)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=6593&amp;undo=6819" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=6593" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=6593&amp;oldid=4526" title="Elite">prev</a>)</span><input type="radio" value="6593" name="oldid" id="mw-oldid-6593" /><input type="radio" value="6593" name="diff" id="mw-diff-6593" /> <a href="/index.php?title=Elite&amp;oldid=6593" title="Elite" class="mw-changeslist-date">12:11, 15 July 2011</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,367 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,367 bytes after change">(+118)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Suggested_Roles" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4526&amp;undo=6593" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4526" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4526&amp;oldid=4501" title="Elite">prev</a>)</span><input type="radio" value="4526" name="oldid" id="mw-oldid-4526" /><input type="radio" value="4526" name="diff" id="mw-diff-4526" /> <a href="/index.php?title=Elite&amp;oldid=4526" title="Elite" class="mw-changeslist-date">14:59, 29 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,249 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,249 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(pirate guns)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4501&amp;undo=4526" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4501" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4501&amp;oldid=4500" title="Elite">prev</a>)</span><input type="radio" value="4501" name="oldid" id="mw-oldid-4501" /><input type="radio" value="4501" name="diff" id="mw-diff-4501" /> <a href="/index.php?title=Elite&amp;oldid=4501" title="Elite" class="mw-changeslist-date">13:48, 29 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,239 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,239 bytes after change">(+40)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#See_Also" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4500&amp;undo=4501" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4500" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4500&amp;oldid=4107" title="Elite">prev</a>)</span><input type="radio" value="4500" name="oldid" id="mw-oldid-4500" /><input type="radio" value="4500" name="diff" id="mw-diff-4500" /> <a href="/index.php?title=Elite&amp;oldid=4500" title="Elite" class="mw-changeslist-date">13:47, 29 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,199 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,199 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Variants" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Variants</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4107&amp;undo=4500" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4107" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4107&amp;oldid=4106" title="Elite">prev</a>)</span><input type="radio" value="4107" name="oldid" id="mw-oldid-4107" /><input type="radio" value="4107" name="diff" id="mw-diff-4107" /> <a href="/index.php?title=Elite&amp;oldid=4107" title="Elite" class="mw-changeslist-date">18:49, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,163 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,163 bytes after change">(-23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#See_Also" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4106&amp;undo=4107" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4106" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4106&amp;oldid=4105" title="Elite">prev</a>)</span><input type="radio" value="4106" name="oldid" id="mw-oldid-4106" /><input type="radio" value="4106" name="diff" id="mw-diff-4106" /> <a href="/index.php?title=Elite&amp;oldid=4106" title="Elite" class="mw-changeslist-date">18:49, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,186 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,186 bytes after change">(+184)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#See_Also" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4105&amp;undo=4106" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4105" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4105&amp;oldid=4104" title="Elite">prev</a>)</span><input type="radio" value="4105" name="oldid" id="mw-oldid-4105" /><input type="radio" value="4105" name="diff" id="mw-diff-4105" /> <a href="/index.php?title=Elite&amp;oldid=4105" title="Elite" class="mw-changeslist-date">18:48, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,002 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,002 bytes after change">(+206)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Combat" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=4104&amp;undo=4105" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=4104" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=4104&amp;oldid=2781" title="Elite">prev</a>)</span><input type="radio" value="4104" name="oldid" id="mw-oldid-4104" /><input type="radio" value="4104" name="diff" id="mw-diff-4104" /> <a href="/index.php?title=Elite&amp;oldid=4104" title="Elite" class="mw-changeslist-date">18:47, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,796 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,796 bytes after change">(+56)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Overview" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=2781&amp;undo=4104" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=2781" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=2781&amp;oldid=2764" title="Elite">prev</a>)</span><input type="radio" value="2781" name="oldid" id="mw-oldid-2781" /><input type="radio" value="2781" name="diff" id="mw-diff-2781" /> <a href="/index.php?title=Elite&amp;oldid=2781" title="Elite" class="mw-changeslist-date">18:48, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,740 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,740 bytes after change">(+46)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Availability" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Availability: </span> ownerless ship</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=2764&amp;undo=2781" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=2764" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=2764&amp;oldid=2678" title="Elite">prev</a>)</span><input type="radio" value="2764" name="oldid" id="mw-oldid-2764" /><input type="radio" value="2764" name="diff" id="mw-diff-2764" /> <a href="/index.php?title=Elite&amp;oldid=2764" title="Elite" class="mw-changeslist-date">18:22, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,694 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,694 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(rejigged Argonshipcategory)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=2678&amp;undo=2764" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=2678" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=2678&amp;oldid=2002" title="Elite">prev</a>)</span><input type="radio" value="2678" name="oldid" id="mw-oldid-2678" /><input type="radio" value="2678" name="diff" id="mw-diff-2678" /> <a href="/index.php?title=Elite&amp;oldid=2678" title="Elite" class="mw-changeslist-date">09:54, 12 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">Talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,690 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,690 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=2002&amp;undo=2678" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=2002" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=2002&amp;oldid=1502" title="Elite">prev</a>)</span><input type="radio" value="2002" name="oldid" id="mw-oldid-2002" /><input type="radio" value="2002" name="diff" id="mw-diff-2002" /> <a href="/index.php?title=Elite&amp;oldid=2002" title="Elite" class="mw-changeslist-date">17:01, 4 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,672 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,672 bytes after change">(+913)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(pirate infobox and section)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=1502&amp;undo=2002" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=1502" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=1502&amp;oldid=1501" title="Elite">prev</a>)</span><input type="radio" value="1502" name="oldid" id="mw-oldid-1502" /><input type="radio" value="1502" name="diff" id="mw-diff-1502" /> <a href="/index.php?title=Elite&amp;oldid=1502" title="Elite" class="mw-changeslist-date">14:55, 24 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,759 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,759 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(priceblock rep)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=1501&amp;undo=1502" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=1501" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=1501&amp;oldid=757" title="Elite">prev</a>)</span><input type="radio" value="1501" name="oldid" id="mw-oldid-1501" /><input type="radio" value="1501" name="diff" id="mw-diff-1501" /> <a href="/index.php?title=Elite&amp;oldid=1501" title="Elite" class="mw-changeslist-date">14:54, 24 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,743 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,743 bytes after change">(+48)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Elite#Background" title="Elite">→</a>‎<span dir="auto"><span class="autocomment">Background: </span> variants section</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=757&amp;undo=1501" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=757" title="Elite">cur</a> | <a href="/index.php?title=Elite&amp;diff=757&amp;oldid=522" title="Elite">prev</a>)</span><input type="radio" value="757" name="oldid" id="mw-oldid-757" /><input type="radio" value="757" name="diff" id="mw-diff-757" /> <a href="/index.php?title=Elite&amp;oldid=757" title="Elite" class="mw-changeslist-date">13:12, 13 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,695 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,695 bytes after change">(+1,285)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(unformatted numbers so templates can do their thing, added elite enhanced info.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Elite&amp;action=edit&amp;undoafter=522&amp;undo=757" title="Elite">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Elite&amp;diff=13657&amp;oldid=522" title="Elite">cur</a> | prev)</span><input type="radio" value="522" name="oldid" id="mw-oldid-522" /><input type="radio" value="522" name="diff" id="mw-diff-522" /> <a href="/index.php?title=Elite&amp;oldid=522" title="Elite" class="mw-changeslist-date">20:12, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,410 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,410 bytes after change">(+1,410)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(recover from cache)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Elite">http://x3wiki.com/index.php/Elite</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Elite" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Elite" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Elite&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Elite&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Elite&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Elite&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Elite" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Elite" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Elite&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Elite&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.409 secs. --></body></html>