<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Q" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Q&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Q&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Q&quot; Atom feed" href="/index.php?title=Q&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://www.x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Q","wgTitle":"Q","wgCurRevisionId":14385,"wgRevisionId":0,"wgArticleId":115,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Q","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Q skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Q"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Q" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Q" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2014" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Q" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11799" title="Q">prev</a>)</span><input type="radio" value="14385" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14385" checked="checked" name="diff" id="mw-diff-14385" /> <a href="/index.php?title=Q&amp;oldid=14385" title="Q" class="mw-changeslist-date">23:36, 19 February 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,905 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,905 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=11799&amp;undo=14385" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11799" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=11799&amp;oldid=11777" title="Q">prev</a>)</span><input type="radio" value="11799" checked="checked" name="oldid" id="mw-oldid-11799" /><input type="radio" value="11799" name="diff" id="mw-diff-11799" /> <a href="/index.php?title=Q&amp;oldid=11799" title="Q" class="mw-changeslist-date">22:26, 23 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,891 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,891 bytes after change">(+224)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=11777&amp;undo=11799" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11777" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=11777&amp;oldid=11776" title="Q">prev</a>)</span><input type="radio" value="11777" name="oldid" id="mw-oldid-11777" /><input type="radio" value="11777" name="diff" id="mw-diff-11777" /> <a href="/index.php?title=Q&amp;oldid=11777" title="Q" class="mw-changeslist-date">00:26, 22 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,667 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,667 bytes after change">(+7)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=11776&amp;undo=11777" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11776" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=11776&amp;oldid=11617" title="Q">prev</a>)</span><input type="radio" value="11776" name="oldid" id="mw-oldid-11776" /><input type="radio" value="11776" name="diff" id="mw-diff-11776" /> <a href="/index.php?title=Q&amp;oldid=11776" title="Q" class="mw-changeslist-date">00:25, 22 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,660 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,660 bytes after change">(+159)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=11617&amp;undo=11776" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11617" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=11617&amp;oldid=11020" title="Q">prev</a>)</span><input type="radio" value="11617" name="oldid" id="mw-oldid-11617" /><input type="radio" value="11617" name="diff" id="mw-diff-11617" /> <a href="/index.php?title=Q&amp;oldid=11617" title="Q" class="mw-changeslist-date">01:52, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,501 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,501 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=11020&amp;undo=11617" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=11020" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=11020&amp;oldid=10841" title="Q">prev</a>)</span><input type="radio" value="11020" name="oldid" id="mw-oldid-11020" /><input type="radio" value="11020" name="diff" id="mw-diff-11020" /> <a href="/index.php?title=Q&amp;oldid=11020" title="Q" class="mw-changeslist-date">19:37, 16 November 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,487 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,487 bytes after change">(+413)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added in-game description)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=10841&amp;undo=11020" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=10841" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=10841&amp;oldid=10767" title="Q">prev</a>)</span><input type="radio" value="10841" name="oldid" id="mw-oldid-10841" /><input type="radio" value="10841" name="diff" id="mw-diff-10841" /> <a href="/index.php?title=Q&amp;oldid=10841" title="Q" class="mw-changeslist-date">11:45, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,074 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,074 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=10767&amp;undo=10841" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=10767" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=10767&amp;oldid=8446" title="Q">prev</a>)</span><input type="radio" value="10767" name="oldid" id="mw-oldid-10767" /><input type="radio" value="10767" name="diff" id="mw-diff-10767" /> <a href="/index.php?title=Q&amp;oldid=10767" title="Q" class="mw-changeslist-date">16:27, 16 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,050 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,050 bytes after change">(-334)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M7 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=8446&amp;undo=10767" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=8446" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=8446&amp;oldid=8153" title="Q">prev</a>)</span><input type="radio" value="8446" name="oldid" id="mw-oldid-8446" /><input type="radio" value="8446" name="diff" id="mw-diff-8446" /> <a href="/index.php?title=Q&amp;oldid=8446" title="Q" class="mw-changeslist-date">18:51, 6 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,384 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,384 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=8153&amp;undo=8446" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=8153" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=8153&amp;oldid=7449" title="Q">prev</a>)</span><input type="radio" value="8153" name="oldid" id="mw-oldid-8153" /><input type="radio" value="8153" name="diff" id="mw-diff-8153" /> <a href="/index.php?title=Q&amp;oldid=8153" title="Q" class="mw-changeslist-date">15:05, 19 December 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Skybon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Skybon (page does not exist)">Skybon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skybon&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skybon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skybon" title="Special:Contributions/Skybon">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,384 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,384 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(moved <a href="/index.php/Xenon_Q" class="mw-redirect" title="Xenon Q">Xenon Q</a> to <a href="/index.php/Q" title="Q">Q</a>: &#039;Xenon&#039; is not part of the name)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=7449&amp;undo=8153" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=7449" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=7449&amp;oldid=5591" title="Q">prev</a>)</span><input type="radio" value="7449" name="oldid" id="mw-oldid-7449" /><input type="radio" value="7449" name="diff" id="mw-diff-7449" /> <a href="/index.php?title=Q&amp;oldid=7449" title="Q" class="mw-changeslist-date">11:33, 21 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.151.73.100" title="Special:Contributions/78.151.73.100" class="mw-userlink">78.151.73.100</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.151.73.100&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.151.73.100 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,384 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,384 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Availability" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=5591&amp;undo=7449" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=5591" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=5591&amp;oldid=5161" title="Q">prev</a>)</span><input type="radio" value="5591" name="oldid" id="mw-oldid-5591" /><input type="radio" value="5591" name="diff" id="mw-diff-5591" /> <a href="/index.php?title=Q&amp;oldid=5591" title="Q" class="mw-changeslist-date">01:37, 24 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:MagicSquid" title="User:MagicSquid" class="mw-userlink">MagicSquid</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:MagicSquid&amp;action=edit&amp;redlink=1" class="new" title="User talk:MagicSquid (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/MagicSquid" title="Special:Contributions/MagicSquid">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,376 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,376 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Corrected # of guns, added laser weapon reload rate, steering, acceleration rates.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=5161&amp;undo=5591" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=5161" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=5161&amp;oldid=5142" title="Q">prev</a>)</span><input type="radio" value="5161" name="oldid" id="mw-oldid-5161" /><input type="radio" value="5161" name="diff" id="mw-diff-5161" /> <a href="/index.php?title=Q&amp;oldid=5161" title="Q" class="mw-changeslist-date">13:03, 9 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Master_of_the_Blade" title="User:Master of the Blade" class="mw-userlink">Master of the Blade</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Master_of_the_Blade&amp;action=edit&amp;redlink=1" class="new" title="User talk:Master of the Blade (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Master_of_the_Blade" title="Special:Contributions/Master of the Blade">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,365 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,365 bytes after change">(+182)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Physical_Characteristics" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=5142&amp;undo=5161" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=5142" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=5142&amp;oldid=4697" title="Q">prev</a>)</span><input type="radio" value="5142" name="oldid" id="mw-oldid-5142" /><input type="radio" value="5142" name="diff" id="mw-diff-5142" /> <a href="/index.php?title=Q&amp;oldid=5142" title="Q" class="mw-changeslist-date">17:10, 8 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,183 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,183 bytes after change">(+53)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Overview" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4697&amp;undo=5142" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4697" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4697&amp;oldid=4695" title="Q">prev</a>)</span><input type="radio" value="4697" name="oldid" id="mw-oldid-4697" /><input type="radio" value="4697" name="diff" id="mw-diff-4697" /> <a href="/index.php?title=Q&amp;oldid=4697" title="Q" class="mw-changeslist-date">18:38, 28 December 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,130 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,130 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Headquarters_Production_Info" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Headquarters Production Info: </span> corrected materials links</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4695&amp;undo=4697" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4695" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4695&amp;oldid=4382" title="Q">prev</a>)</span><input type="radio" value="4695" name="oldid" id="mw-oldid-4695" /><input type="radio" value="4695" name="diff" id="mw-diff-4695" /> <a href="/index.php?title=Q&amp;oldid=4695" title="Q" class="mw-changeslist-date">15:20, 28 December 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/72.91.227.61" title="Special:Contributions/72.91.227.61" class="mw-userlink">72.91.227.61</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:72.91.227.61&amp;action=edit&amp;redlink=1" class="new" title="User talk:72.91.227.61 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,121 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,121 bytes after change">(+667)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added HQ Production info)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4382&amp;undo=4695" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4382" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4382&amp;oldid=4381" title="Q">prev</a>)</span><input type="radio" value="4382" name="oldid" id="mw-oldid-4382" /><input type="radio" value="4382" name="diff" id="mw-diff-4382" /> <a href="/index.php?title=Q&amp;oldid=4382" title="Q" class="mw-changeslist-date">07:35, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,454 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,454 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#See_Also" title="Q">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4381&amp;undo=4382" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4381" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4381&amp;oldid=4380" title="Q">prev</a>)</span><input type="radio" value="4381" name="oldid" id="mw-oldid-4381" /><input type="radio" value="4381" name="diff" id="mw-diff-4381" /> <a href="/index.php?title=Q&amp;oldid=4381" title="Q" class="mw-changeslist-date">07:34, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,428 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,428 bytes after change">(+316)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Background" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Background</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4380&amp;undo=4381" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4380" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4380&amp;oldid=4379" title="Q">prev</a>)</span><input type="radio" value="4380" name="oldid" id="mw-oldid-4380" /><input type="radio" value="4380" name="diff" id="mw-diff-4380" /> <a href="/index.php?title=Q&amp;oldid=4380" title="Q" class="mw-changeslist-date">07:29, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,112 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,112 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Overview" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4379&amp;undo=4380" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4379" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4379&amp;oldid=4373" title="Q">prev</a>)</span><input type="radio" value="4379" name="oldid" id="mw-oldid-4379" /><input type="radio" value="4379" name="diff" id="mw-diff-4379" /> <a href="/index.php?title=Q&amp;oldid=4379" title="Q" class="mw-changeslist-date">07:28, 26 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,112 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,112 bytes after change">(-331)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Overview" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Overview: </span> Reduced length of Overview section; all information retained.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4373&amp;undo=4379" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4373" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4373&amp;oldid=4365" title="Q">prev</a>)</span><input type="radio" value="4373" name="oldid" id="mw-oldid-4373" /><input type="radio" value="4373" name="diff" id="mw-diff-4373" /> <a href="/index.php?title=Q&amp;oldid=4373" title="Q" class="mw-changeslist-date">14:19, 24 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,443 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,443 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Overview" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Overview: </span> typos</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4365&amp;undo=4373" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4365" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4365&amp;oldid=4224" title="Q">prev</a>)</span><input type="radio" value="4365" name="oldid" id="mw-oldid-4365" /><input type="radio" value="4365" name="diff" id="mw-diff-4365" /> <a href="/index.php?title=Q&amp;oldid=4365" title="Q" class="mw-changeslist-date">12:51, 24 November 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,440 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,440 bytes after change">(+457)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Chat about the Q being dreaded because it&#039;s the most commonly encountered enemy m7.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=4224&amp;undo=4365" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=4224" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=4224&amp;oldid=3489" title="Q">prev</a>)</span><input type="radio" value="4224" name="oldid" id="mw-oldid-4224" /><input type="radio" value="4224" name="diff" id="mw-diff-4224" /> <a href="/index.php?title=Q&amp;oldid=4224" title="Q" class="mw-changeslist-date">20:42, 13 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,983 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,983 bytes after change">(+299)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#See_Also" title="Q">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3489&amp;undo=4224" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3489" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3489&amp;oldid=3488" title="Q">prev</a>)</span><input type="radio" value="3489" name="oldid" id="mw-oldid-3489" /><input type="radio" value="3489" name="diff" id="mw-diff-3489" /> <a href="/index.php?title=Q&amp;oldid=3489" title="Q" class="mw-changeslist-date">13:34, 21 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,684 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,684 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Availability" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Availability: </span> rephrase capturing</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3488&amp;undo=3489" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3488" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3488&amp;oldid=3255" title="Q">prev</a>)</span><input type="radio" value="3488" name="oldid" id="mw-oldid-3488" /><input type="radio" value="3488" name="diff" id="mw-diff-3488" /> <a href="/index.php?title=Q&amp;oldid=3488" title="Q" class="mw-changeslist-date">13:21, 21 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,640 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,640 bytes after change">(-72)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span> didn&#039;t see any terran guns, Ks mount terran guns for sure, added turret aspect to weapons notation.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3255&amp;undo=3488" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3255" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3255&amp;oldid=3252" title="Q">prev</a>)</span><input type="radio" value="3255" name="oldid" id="mw-oldid-3255" /><input type="radio" value="3255" name="diff" id="mw-diff-3255" /> <a href="/index.php?title=Q&amp;oldid=3255" title="Q" class="mw-changeslist-date">13:18, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,712 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,712 bytes after change">(+1,404)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(changed infobox template, added gunslots, added missiles.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3252&amp;undo=3255" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3252" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3252&amp;oldid=3251" title="Q">prev</a>)</span><input type="radio" value="3252" name="oldid" id="mw-oldid-3252" /><input type="radio" value="3252" name="diff" id="mw-diff-3252" /> <a href="/index.php?title=Q&amp;oldid=3252" title="Q" class="mw-changeslist-date">13:01, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,308 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,308 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3251&amp;undo=3252" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3251" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3251&amp;oldid=3250" title="Q">prev</a>)</span><input type="radio" value="3251" name="oldid" id="mw-oldid-3251" /><input type="radio" value="3251" name="diff" id="mw-diff-3251" /> <a href="/index.php?title=Q&amp;oldid=3251" title="Q" class="mw-changeslist-date">13:00, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,304 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,304 bytes after change">(+192)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Combat" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3250&amp;undo=3251" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3250" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3250&amp;oldid=3249" title="Q">prev</a>)</span><input type="radio" value="3250" name="oldid" id="mw-oldid-3250" /><input type="radio" value="3250" name="diff" id="mw-diff-3250" /> <a href="/index.php?title=Q&amp;oldid=3250" title="Q" class="mw-changeslist-date">12:58, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,112 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,112 bytes after change">(+175)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Physical_Characteristics" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3249&amp;undo=3250" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3249" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3249&amp;oldid=3248" title="Q">prev</a>)</span><input type="radio" value="3249" name="oldid" id="mw-oldid-3249" /><input type="radio" value="3249" name="diff" id="mw-diff-3249" /> <a href="/index.php?title=Q&amp;oldid=3249" title="Q" class="mw-changeslist-date">12:56, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,937 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,937 bytes after change">(+5)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Overview" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=3248&amp;undo=3249" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=3248" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=3248&amp;oldid=510" title="Q">prev</a>)</span><input type="radio" value="3248" name="oldid" id="mw-oldid-3248" /><input type="radio" value="3248" name="diff" id="mw-diff-3248" /> <a href="/index.php?title=Q&amp;oldid=3248" title="Q" class="mw-changeslist-date">12:56, 19 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,932 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,932 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Q#Availability" title="Q">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=510&amp;undo=3248" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=510" title="Q">cur</a> | <a href="/index.php?title=Q&amp;diff=510&amp;oldid=307" title="Q">prev</a>)</span><input type="radio" value="510" name="oldid" id="mw-oldid-510" /><input type="radio" value="510" name="diff" id="mw-diff-510" /> <a href="/index.php?title=Q&amp;oldid=510" title="Q" class="mw-changeslist-date">19:50, 24 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,918 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,918 bytes after change">(+16)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Q&amp;action=edit&amp;undoafter=307&amp;undo=510" title="Q">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Q&amp;diff=14385&amp;oldid=307" title="Q">cur</a> | prev)</span><input type="radio" value="307" name="oldid" id="mw-oldid-307" /><input type="radio" value="307" name="diff" id="mw-diff-307" /> <a href="/index.php?title=Q&amp;oldid=307" title="Q" class="mw-changeslist-date">18:07, 23 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,902 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,902 bytes after change">(+1,902)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(restore from cache)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://www.x3wiki.com/index.php/Q">http://www.x3wiki.com/index.php/Q</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Q" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Q&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Q&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Q&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-anonuserpage"><a href="/index.php/User:174.129.228.67" class="new" title="The user page for the IP address you are editing as [.]" accesskey=".">174.129.228.67</a></li>
				<li id="pt-anontalk"><a href="/index.php/User_talk:174.129.228.67" class="new" title="Discussion about edits from this IP address [n]" accesskey="n">Talk for this IP address</a></li>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Q&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-anonlogin"><a href="/index.php?title=Special:UserLogin&amp;returnto=Q&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Buy-X3-Albion-Prelude.21"><a href="http://www.gamersgate.co.uk/DD-X3AP/x3-albion-prelude-expansion-pack?caff=4628051%7C" rel="nofollow">Buy X3 Albion Prelude!</a></li>
				<li id="n-MMOServerstatus-.5BEN.5D"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMOServerstatus [EN]</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Q" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Q" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Q&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Q&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.377 secs. --></body></html>