<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Photon Pulse Cannon" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Photon_Pulse_Cannon","wgTitle":"Photon Pulse Cannon","wgCurRevisionId":15940,"wgRevisionId":0,"wgArticleId":326,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Photon_Pulse_Cannon","wgRelevantArticleId":326,"wgRequestId":"WlTT2lkfZokAAF3JSMEAAAAH","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Photon Pulse Cannon&quot; Atom feed" href="/index.php?title=Photon_Pulse_Cannon&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Photon_Pulse_Cannon rootpage-Photon_Pulse_Cannon skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Photon Pulse Cannon"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Photon+Pulse+Cannon" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Photon_Pulse_Cannon" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Photon_Pulse_Cannon" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15939" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15940" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="15940" checked="checked" name="diff" id="mw-diff-15940" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15940" title="Photon Pulse Cannon" class="mw-changeslist-date">17:37, 10 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,640 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,640 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships: </span> add Goner</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15939&amp;undo=15940" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15939" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15939&amp;oldid=15865" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15939" checked="checked" name="oldid" id="mw-oldid-15939" /><input type="radio" value="15939" name="diff" id="mw-diff-15939" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15939" title="Photon Pulse Cannon" class="mw-changeslist-date">17:36, 10 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,634 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,634 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks: </span> add Paranid shipyard</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15865&amp;undo=15939" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15865" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15865&amp;oldid=15864" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15865" name="oldid" id="mw-oldid-15865" /><input type="radio" value="15865" name="diff" id="mw-diff-15865" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15865" title="Photon Pulse Cannon" class="mw-changeslist-date">11:00, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,609 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,609 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks: </span> add a new sector</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15864&amp;undo=15865" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15864" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15864&amp;oldid=15863" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15864" name="oldid" id="mw-oldid-15864" /><input type="radio" value="15864" name="diff" id="mw-diff-15864" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15864" title="Photon Pulse Cannon" class="mw-changeslist-date">10:59, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,584 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,584 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15863&amp;undo=15864" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15863" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15863&amp;oldid=15627" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15863" name="oldid" id="mw-oldid-15863" /><input type="radio" value="15863" name="diff" id="mw-diff-15863" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15863" title="Photon Pulse Cannon" class="mw-changeslist-date">10:58, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,583 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,583 bytes after change">(+180)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks: </span> update with some new sectors</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15627&amp;undo=15863" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15627" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15627&amp;oldid=15589" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15627" name="oldid" id="mw-oldid-15627" /><input type="radio" value="15627" name="diff" id="mw-diff-15627" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15627" title="Photon Pulse Cannon" class="mw-changeslist-date">10:17, 5 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,403 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,403 bytes after change">(+116)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks: </span> add few sectors</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15589&amp;undo=15627" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15589" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15589&amp;oldid=15588" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15589" name="oldid" id="mw-oldid-15589" /><input type="radio" value="15589" name="diff" id="mw-diff-15589" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15589" title="Photon Pulse Cannon" class="mw-changeslist-date">16:02, 4 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,287 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,287 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15588&amp;undo=15589" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15588" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15588&amp;oldid=15587" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15588" name="oldid" id="mw-oldid-15588" /><input type="radio" value="15588" name="diff" id="mw-diff-15588" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15588" title="Photon Pulse Cannon" class="mw-changeslist-date">16:01, 4 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,286 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,286 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15587&amp;undo=15588" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15587" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15587&amp;oldid=15586" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15587" name="oldid" id="mw-oldid-15587" /><input type="radio" value="15587" name="diff" id="mw-diff-15587" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15587" title="Photon Pulse Cannon" class="mw-changeslist-date">15:58, 4 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,268 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,268 bytes after change">(+370)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Available_at_Known_Docks" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Available at Known Docks: </span> add factory</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=15586&amp;undo=15587" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=15586" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15586&amp;oldid=14016" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="15586" name="oldid" id="mw-oldid-15586" /><input type="radio" value="15586" name="diff" id="mw-diff-15586" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=15586" title="Photon Pulse Cannon" class="mw-changeslist-date">15:44, 4 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,898 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,898 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships: </span> add links</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=14016&amp;undo=15586" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=14016" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=14016&amp;oldid=11510" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="14016" name="oldid" id="mw-oldid-14016" /><input type="radio" value="14016" name="diff" id="mw-diff-14016" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=14016" title="Photon Pulse Cannon" class="mw-changeslist-date">20:24, 27 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Barashkafromro&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Barashkafromro (page does not exist)">Barashkafromro</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Barashkafromro&amp;action=edit&amp;redlink=1" class="new" title="User talk:Barashkafromro (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Barashkafromro" title="Special:Contributions/Barashkafromro">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,875 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,875 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=11510&amp;undo=14016" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=11510" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=11510&amp;oldid=10865" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="11510" name="oldid" id="mw-oldid-11510" /><input type="radio" value="11510" name="diff" id="mw-diff-11510" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=11510" title="Photon Pulse Cannon" class="mw-changeslist-date">00:21, 8 January 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,875 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,875 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=10865&amp;undo=11510" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=10865" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=10865&amp;oldid=10449" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="10865" name="oldid" id="mw-oldid-10865" /><input type="radio" value="10865" name="diff" id="mw-diff-10865" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=10865" title="Photon Pulse Cannon" class="mw-changeslist-date">17:55, 17 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,875 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,875 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=10449&amp;undo=10865" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=10449" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=10449&amp;oldid=7499" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="10449" name="oldid" id="mw-oldid-10449" /><input type="radio" value="10449" name="diff" id="mw-diff-10449" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=10449" title="Photon Pulse Cannon" class="mw-changeslist-date">18:43, 12 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,865 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,865 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added links to frigate, destroyer and carrier)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=7499&amp;undo=10449" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=7499" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=7499&amp;oldid=7498" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="7499" name="oldid" id="mw-oldid-7499" /><input type="radio" value="7499" name="diff" id="mw-diff-7499" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=7499" title="Photon Pulse Cannon" class="mw-changeslist-date">12:20, 28 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.121.193.251" title="Special:Contributions/212.121.193.251" class="mw-userlink mw-anonuserlink">212.121.193.251</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.121.193.251&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.121.193.251 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,843 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,843 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=7498&amp;undo=7499" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=7498" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=7498&amp;oldid=2914" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="7498" name="oldid" id="mw-oldid-7498" /><input type="radio" value="7498" name="diff" id="mw-diff-7498" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=7498" title="Photon Pulse Cannon" class="mw-changeslist-date">12:20, 28 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.121.193.253" title="Special:Contributions/212.121.193.253" class="mw-userlink mw-anonuserlink">212.121.193.253</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.121.193.253&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.121.193.253 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,835 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,835 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=2914&amp;undo=7498" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=2914" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=2914&amp;oldid=2790" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="2914" name="oldid" id="mw-oldid-2914" /><input type="radio" value="2914" name="diff" id="mw-diff-2914" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=2914" title="Photon Pulse Cannon" class="mw-changeslist-date">19:23, 15 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,820 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,820 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(corrected capital ships link, moved link to first occurance of phrase)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=2790&amp;undo=2914" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=2790" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=2790&amp;oldid=2657" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="2790" name="oldid" id="mw-oldid-2790" /><input type="radio" value="2790" name="diff" id="mw-diff-2790" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=2790" title="Photon Pulse Cannon" class="mw-changeslist-date">01:05, 13 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,806 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,806 bytes after change">(+88)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Known_Compatible_Ships" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Known Compatible Ships: </span> truelight seeker</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=2657&amp;undo=2790" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=2657" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=2657&amp;oldid=2308" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="2657" name="oldid" id="mw-oldid-2657" /><input type="radio" value="2657" name="diff" id="mw-diff-2657" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=2657" title="Photon Pulse Cannon" class="mw-changeslist-date">17:23, 10 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink mw-anonuserlink">94.195.170.31</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,718 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,718 bytes after change">(+118)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=2308&amp;undo=2657" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=2308" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=2308&amp;oldid=2305" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="2308" name="oldid" id="mw-oldid-2308" /><input type="radio" value="2308" name="diff" id="mw-diff-2308" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=2308" title="Photon Pulse Cannon" class="mw-changeslist-date">22:24, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,600 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,600 bytes after change">(+627)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Commentary" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Commentary</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=2305&amp;undo=2308" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=2305" title="Photon Pulse Cannon">cur</a> | <a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=2305&amp;oldid=908" title="Photon Pulse Cannon">prev</a>)</span><input type="radio" value="2305" name="oldid" id="mw-oldid-2305" /><input type="radio" value="2305" name="diff" id="mw-diff-2305" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=2305" title="Photon Pulse Cannon" class="mw-changeslist-date">22:18, 6 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(973 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="973 bytes after change">(+85)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Photon_Pulse_Cannon#Overview" title="Photon Pulse Cannon">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit&amp;undoafter=908&amp;undo=2305" title="Photon Pulse Cannon">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Photon_Pulse_Cannon&amp;diff=15940&amp;oldid=908" title="Photon Pulse Cannon">cur</a> | prev)</span><input type="radio" value="908" name="oldid" id="mw-oldid-908" /><input type="radio" value="908" name="diff" id="mw-diff-908" /> <a href="/index.php?title=Photon_Pulse_Cannon&amp;oldid=908" title="Photon Pulse Cannon" class="mw-changeslist-date">18:45, 31 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(888 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="888 bytes after change">(+888)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(start)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Photon_Pulse_Cannon">http://www.x3wiki.com/index.php/Photon_Pulse_Cannon</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Photon_Pulse_Cannon" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Photon_Pulse_Cannon" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Photon+Pulse+Cannon&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Photon+Pulse+Cannon&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Photon_Pulse_Cannon" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Photon_Pulse_Cannon" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Photon_Pulse_Cannon&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Photon_Pulse_Cannon&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":64});});</script></body></html>
