<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Raijin" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Raijin","wgTitle":"Raijin","wgCurRevisionId":16359,"wgRevisionId":0,"wgArticleId":374,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Raijin","wgRelevantArticleId":374,"wgRequestId":"WmiJoVkfZokAAGq9c5EAAAAQ","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Raijin&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Raijin&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Raijin&quot; Atom feed" href="/index.php?title=Raijin&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Raijin rootpage-Raijin skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Raijin"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Raijin" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Raijin" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Raijin" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=16108" title="Raijin">prev</a>)</span><input type="radio" value="16359" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16359" checked="checked" name="diff" id="mw-diff-16359" /> <a href="/index.php?title=Raijin&amp;oldid=16359" title="Raijin" class="mw-changeslist-date">10:27, 27 July 2014</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/149.172.210.55" title="Special:Contributions/149.172.210.55" class="mw-userlink mw-anonuserlink">149.172.210.55</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:149.172.210.55&amp;action=edit&amp;redlink=1" class="new" title="User talk:149.172.210.55 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,156 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,156 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Availability" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=16108&amp;undo=16359" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=16108" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=16108&amp;oldid=12710" title="Raijin">prev</a>)</span><input type="radio" value="16108" checked="checked" name="oldid" id="mw-oldid-16108" /><input type="radio" value="16108" name="diff" id="mw-diff-16108" /> <a href="/index.php?title=Raijin&amp;oldid=16108" title="Raijin" class="mw-changeslist-date">15:41, 18 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,156 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,156 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> Add Yaki Navbox</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=12710&amp;undo=16108" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=12710" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=12710&amp;oldid=11642" title="Raijin">prev</a>)</span><input type="radio" value="12710" name="oldid" id="mw-oldid-12710" /><input type="radio" value="12710" name="diff" id="mw-diff-12710" /> <a href="/index.php?title=Raijin&amp;oldid=12710" title="Raijin" class="mw-changeslist-date">12:16, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,139 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,139 bytes after change">(-39)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> no need for special mention, no direct relation other than race and can just click on race link to see all ships</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=11642&amp;undo=12710" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=11642" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=11642&amp;oldid=11630" title="Raijin">prev</a>)</span><input type="radio" value="11642" name="oldid" id="mw-oldid-11642" /><input type="radio" value="11642" name="diff" id="mw-diff-11642" /> <a href="/index.php?title=Raijin&amp;oldid=11642" title="Raijin" class="mw-changeslist-date">00:36, 15 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,178 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,178 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Apparently the combat was correct but the person who did the data for the Raijin had the incorrect weapon listed. The PBE has been properly attributed to the Raijin and the Combat section properly fixed to say PBE.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=11630&amp;undo=11642" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=11630" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=11630&amp;oldid=11629" title="Raijin">prev</a>)</span><input type="radio" value="11630" name="oldid" id="mw-oldid-11630" /><input type="radio" value="11630" name="diff" id="mw-diff-11630" /> <a href="/index.php?title=Raijin&amp;oldid=11630" title="Raijin" class="mw-changeslist-date">08:34, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,178 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,178 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(I think he meant PBG, as the pulsed beam emitter isn&#039;t on the weapons list.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=11629&amp;undo=11630" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=11629" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=11629&amp;oldid=11025" title="Raijin">prev</a>)</span><input type="radio" value="11629" name="oldid" id="mw-oldid-11629" /><input type="radio" value="11629" name="diff" id="mw-diff-11629" /> <a href="/index.php?title=Raijin&amp;oldid=11629" title="Raijin" class="mw-changeslist-date">08:33, 13 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,178 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,178 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=11025&amp;undo=11629" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=11025" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=11025&amp;oldid=10602" title="Raijin">prev</a>)</span><input type="radio" value="11025" name="oldid" id="mw-oldid-11025" /><input type="radio" value="11025" name="diff" id="mw-diff-11025" /> <a href="/index.php?title=Raijin&amp;oldid=11025" title="Raijin" class="mw-changeslist-date">01:50, 17 November 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,142 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,142 bytes after change">(+69)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Background" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Background: </span> Add in game description</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=10602&amp;undo=11025" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=10602" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=10602&amp;oldid=10467" title="Raijin">prev</a>)</span><input type="radio" value="10602" name="oldid" id="mw-oldid-10602" /><input type="radio" value="10602" name="diff" id="mw-diff-10602" /> <a href="/index.php?title=Raijin&amp;oldid=10602" title="Raijin" class="mw-changeslist-date">23:40, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,073 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,073 bytes after change">(-319)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M4 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=10467&amp;undo=10602" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=10467" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=10467&amp;oldid=9279" title="Raijin">prev</a>)</span><input type="radio" value="10467" name="oldid" id="mw-oldid-10467" /><input type="radio" value="10467" name="diff" id="mw-diff-10467" /> <a href="/index.php?title=Raijin&amp;oldid=10467" title="Raijin" class="mw-changeslist-date">03:58, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,392 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,392 bytes after change">(+327)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=9279&amp;undo=10467" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=9279" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=9279&amp;oldid=8807" title="Raijin">prev</a>)</span><input type="radio" value="9279" name="oldid" id="mw-oldid-9279" /><input type="radio" value="9279" name="diff" id="mw-diff-9279" /> <a href="/index.php?title=Raijin&amp;oldid=9279" title="Raijin" class="mw-changeslist-date">07:14, 7 June 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/124.181.30.149" title="Special:Contributions/124.181.30.149" class="mw-userlink mw-anonuserlink">124.181.30.149</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:124.181.30.149&amp;action=edit&amp;redlink=1" class="new" title="User talk:124.181.30.149 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,065 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,065 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=8807&amp;undo=9279" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=8807" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=8807&amp;oldid=7031" title="Raijin">prev</a>)</span><input type="radio" value="8807" name="oldid" id="mw-oldid-8807" /><input type="radio" value="8807" name="diff" id="mw-diff-8807" /> <a href="/index.php?title=Raijin&amp;oldid=8807" title="Raijin" class="mw-changeslist-date">01:31, 29 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,055 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,055 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> this is why switching xenon (letter) to (letter) sucks</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=7031&amp;undo=8807" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=7031" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=7031&amp;oldid=6824" title="Raijin">prev</a>)</span><input type="radio" value="7031" name="oldid" id="mw-oldid-7031" /><input type="radio" value="7031" name="diff" id="mw-diff-7031" /> <a href="/index.php?title=Raijin&amp;oldid=7031" title="Raijin" class="mw-changeslist-date">19:50, 17 August 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Aerozap&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Aerozap (page does not exist)">Aerozap</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Aerozap&amp;action=edit&amp;redlink=1" class="new" title="User talk:Aerozap (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Aerozap" title="Special:Contributions/Aerozap">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,053 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,053 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added Eurus to See Also)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=6824&amp;undo=7031" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=6824" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=6824&amp;oldid=6493" title="Raijin">prev</a>)</span><input type="radio" value="6824" name="oldid" id="mw-oldid-6824" /><input type="radio" value="6824" name="diff" id="mw-diff-6824" /> <a href="/index.php?title=Raijin&amp;oldid=6824" title="Raijin" class="mw-changeslist-date">01:43, 8 August 2011</a>‎ <span class='history-user'><a href="/index.php/User:Nepo11" title="User:Nepo11" class="mw-userlink">Nepo11</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Nepo11" title="User talk:Nepo11">talk</a> | <a href="/index.php/Special:Contributions/Nepo11" title="Special:Contributions/Nepo11">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,030 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,030 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added some missing values)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=6493&amp;undo=6824" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=6493" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=6493&amp;oldid=6492" title="Raijin">prev</a>)</span><input type="radio" value="6493" name="oldid" id="mw-oldid-6493" /><input type="radio" value="6493" name="diff" id="mw-diff-6493" /> <a href="/index.php?title=Raijin&amp;oldid=6493" title="Raijin" class="mw-changeslist-date">06:01, 7 July 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Chumley67&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Chumley67 (page does not exist)">Chumley67</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Chumley67&amp;action=edit&amp;redlink=1" class="new" title="User talk:Chumley67 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Chumley67" title="Special:Contributions/Chumley67">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,003 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,003 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=6492&amp;undo=6493" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=6492" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=6492&amp;oldid=6491" title="Raijin">prev</a>)</span><input type="radio" value="6492" name="oldid" id="mw-oldid-6492" /><input type="radio" value="6492" name="diff" id="mw-diff-6492" /> <a href="/index.php?title=Raijin&amp;oldid=6492" title="Raijin" class="mw-changeslist-date">05:59, 7 July 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Chumley67&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Chumley67 (page does not exist)">Chumley67</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Chumley67&amp;action=edit&amp;redlink=1" class="new" title="User talk:Chumley67 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Chumley67" title="Special:Contributions/Chumley67">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,002 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,002 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated Raijin Raider)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=6491&amp;undo=6492" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=6491" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=6491&amp;oldid=6490" title="Raijin">prev</a>)</span><input type="radio" value="6491" name="oldid" id="mw-oldid-6491" /><input type="radio" value="6491" name="diff" id="mw-diff-6491" /> <a href="/index.php?title=Raijin&amp;oldid=6491" title="Raijin" class="mw-changeslist-date">05:57, 7 July 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Chumley67&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Chumley67 (page does not exist)">Chumley67</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Chumley67&amp;action=edit&amp;redlink=1" class="new" title="User talk:Chumley67 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Chumley67" title="Special:Contributions/Chumley67">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,996 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,996 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=6490&amp;undo=6491" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=6490" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=6490&amp;oldid=5308" title="Raijin">prev</a>)</span><input type="radio" value="6490" name="oldid" id="mw-oldid-6490" /><input type="radio" value="6490" name="diff" id="mw-diff-6490" /> <a href="/index.php?title=Raijin&amp;oldid=6490" title="Raijin" class="mw-changeslist-date">05:56, 7 July 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Chumley67&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Chumley67 (page does not exist)">Chumley67</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Chumley67&amp;action=edit&amp;redlink=1" class="new" title="User talk:Chumley67 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Chumley67" title="Special:Contributions/Chumley67">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,994 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,994 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=5308&amp;undo=6490" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=5308" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=5308&amp;oldid=4542" title="Raijin">prev</a>)</span><input type="radio" value="5308" name="oldid" id="mw-oldid-5308" /><input type="radio" value="5308" name="diff" id="mw-diff-5308" /> <a href="/index.php?title=Raijin&amp;oldid=5308" title="Raijin" class="mw-changeslist-date">03:24, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Unearthly&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Unearthly (page does not exist)">Unearthly</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Unearthly&amp;action=edit&amp;redlink=1" class="new" title="User talk:Unearthly (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Unearthly" title="Special:Contributions/Unearthly">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,986 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,986 bytes after change">(+48)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Bank triggered the spam filter.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4542&amp;undo=5308" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4542" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4542&amp;oldid=4541" title="Raijin">prev</a>)</span><input type="radio" value="4542" name="oldid" id="mw-oldid-4542" /><input type="radio" value="4542" name="diff" id="mw-diff-4542" /> <a href="/index.php?title=Raijin&amp;oldid=4542" title="Raijin" class="mw-changeslist-date">21:38, 29 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,938 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,938 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4541&amp;undo=4542" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4541" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4541&amp;oldid=4103" title="Raijin">prev</a>)</span><input type="radio" value="4541" name="oldid" id="mw-oldid-4541" /><input type="radio" value="4541" name="diff" id="mw-diff-4541" /> <a href="/index.php?title=Raijin&amp;oldid=4541" title="Raijin" class="mw-changeslist-date">21:37, 29 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,894 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,894 bytes after change">(+36)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Variants" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Variants</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4103&amp;undo=4541" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4103" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4103&amp;oldid=4044" title="Raijin">prev</a>)</span><input type="radio" value="4103" name="oldid" id="mw-oldid-4103" /><input type="radio" value="4103" name="diff" id="mw-diff-4103" /> <a href="/index.php?title=Raijin&amp;oldid=4103" title="Raijin" class="mw-changeslist-date">00:42, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,858 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,858 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4044&amp;undo=4103" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4044" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4044&amp;oldid=4043" title="Raijin">prev</a>)</span><input type="radio" value="4044" name="oldid" id="mw-oldid-4044" /><input type="radio" value="4044" name="diff" id="mw-diff-4044" /> <a href="/index.php?title=Raijin&amp;oldid=4044" title="Raijin" class="mw-changeslist-date">16:41, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,836 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,836 bytes after change">(+259)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#See_Also" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4043&amp;undo=4044" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4043" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4043&amp;oldid=4042" title="Raijin">prev</a>)</span><input type="radio" value="4043" name="oldid" id="mw-oldid-4043" /><input type="radio" value="4043" name="diff" id="mw-diff-4043" /> <a href="/index.php?title=Raijin&amp;oldid=4043" title="Raijin" class="mw-changeslist-date">16:41, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,577 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,577 bytes after change">(+122)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Availability" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4042&amp;undo=4043" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4042" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4042&amp;oldid=4041" title="Raijin">prev</a>)</span><input type="radio" value="4042" name="oldid" id="mw-oldid-4042" /><input type="radio" value="4042" name="diff" id="mw-diff-4042" /> <a href="/index.php?title=Raijin&amp;oldid=4042" title="Raijin" class="mw-changeslist-date">16:40, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,455 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,455 bytes after change">(+163)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Combat" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4041&amp;undo=4042" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4041" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4041&amp;oldid=4040" title="Raijin">prev</a>)</span><input type="radio" value="4041" name="oldid" id="mw-oldid-4041" /><input type="radio" value="4041" name="diff" id="mw-diff-4041" /> <a href="/index.php?title=Raijin&amp;oldid=4041" title="Raijin" class="mw-changeslist-date">16:38, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,292 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,292 bytes after change">(+74)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Overview" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=4040&amp;undo=4041" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=4040" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=4040&amp;oldid=1732" title="Raijin">prev</a>)</span><input type="radio" value="4040" name="oldid" id="mw-oldid-4040" /><input type="radio" value="4040" name="diff" id="mw-diff-4040" /> <a href="/index.php?title=Raijin&amp;oldid=4040" title="Raijin" class="mw-changeslist-date">16:38, 9 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,218 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,218 bytes after change">(+50)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Physical_Characteristics" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=1732&amp;undo=4040" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=1732" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=1732&amp;oldid=1035" title="Raijin">prev</a>)</span><input type="radio" value="1732" name="oldid" id="mw-oldid-1732" /><input type="radio" value="1732" name="diff" id="mw-diff-1732" /> <a href="/index.php?title=Raijin&amp;oldid=1732" title="Raijin" class="mw-changeslist-date">19:21, 28 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,168 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,168 bytes after change">(+69)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Raijin#Background" title="Raijin">→</a>‎<span dir="auto"><span class="autocomment">Background: </span> variants section</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=1035&amp;undo=1732" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=1035" title="Raijin">cur</a> | <a href="/index.php?title=Raijin&amp;diff=1035&amp;oldid=1034" title="Raijin">prev</a>)</span><input type="radio" value="1035" name="oldid" id="mw-oldid-1035" /><input type="radio" value="1035" name="diff" id="mw-diff-1035" /> <a href="/index.php?title=Raijin&amp;oldid=1035" title="Raijin" class="mw-changeslist-date">21:11, 12 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,099 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,099 bytes after change">(+1,277)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(variant infoboxes)</span> (<span class="mw-history-undo"><a href="/index.php?title=Raijin&amp;action=edit&amp;undoafter=1034&amp;undo=1035" title="Raijin">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Raijin&amp;diff=16359&amp;oldid=1034" title="Raijin">cur</a> | prev)</span><input type="radio" value="1034" name="oldid" id="mw-oldid-1034" /><input type="radio" value="1034" name="diff" id="mw-diff-1034" /> <a href="/index.php?title=Raijin&amp;oldid=1034" title="Raijin" class="mw-changeslist-date">21:08, 12 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(822 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="822 bytes after change">(+822)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(start)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Raijin">http://www.x3wiki.com/index.php/Raijin</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Raijin" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Raijin&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Raijin&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Raijin&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Raijin&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Raijin&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Raijin" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Raijin" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Raijin&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Raijin&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":67});});</script></body></html>
