<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Federal Argon Shipyard" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Federal_Argon_Shipyard","wgTitle":"Federal Argon Shipyard","wgCurRevisionId":16511,"wgRevisionId":0,"wgArticleId":1321,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Federal_Argon_Shipyard","wgRelevantArticleId":1321,"wgRequestId":"WlL4a1kfZokAAFjMcvoAAAAD","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Federal Argon Shipyard&quot; Atom feed" href="/index.php?title=Federal_Argon_Shipyard&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Federal_Argon_Shipyard rootpage-Federal_Argon_Shipyard skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Federal Argon Shipyard"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Federal+Argon+Shipyard" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Federal_Argon_Shipyard" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Federal_Argon_Shipyard" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16510" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16511" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16511" checked="checked" name="diff" id="mw-diff-16511" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16511" title="Federal Argon Shipyard" class="mw-changeslist-date">20:50, 24 September 2014</a>‎ <span class='history-user'><a href="/index.php/User:Fyhlen" title="User:Fyhlen" class="mw-userlink">Fyhlen</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Fyhlen&amp;action=edit&amp;redlink=1" class="new" title="User talk:Fyhlen (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Fyhlen" title="Special:Contributions/Fyhlen">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(11,621 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="11,621 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> Corrected Light of Heart info.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=16510&amp;undo=16511" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16510" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16510&amp;oldid=16146" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16510" checked="checked" name="oldid" id="mw-oldid-16510" /><input type="radio" value="16510" name="diff" id="mw-diff-16510" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16510" title="Federal Argon Shipyard" class="mw-changeslist-date">20:46, 24 September 2014</a>‎ <span class='history-user'><a href="/index.php/User:Fyhlen" title="User:Fyhlen" class="mw-userlink">Fyhlen</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Fyhlen&amp;action=edit&amp;redlink=1" class="new" title="User talk:Fyhlen (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Fyhlen" title="Special:Contributions/Fyhlen">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(11,621 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="11,621 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=16146&amp;undo=16510" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16146" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16146&amp;oldid=16071" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16146" name="oldid" id="mw-oldid-16146" /><input type="radio" value="16146" name="diff" id="mw-diff-16146" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16146" title="Federal Argon Shipyard" class="mw-changeslist-date">11:34, 26 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(11,621 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="11,621 bytes after change">(+1,160)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> use a template for the station entry presentation (left align) + add ST Size column</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=16071&amp;undo=16146" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16071" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16071&amp;oldid=16070" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16071" name="oldid" id="mw-oldid-16071" /><input type="radio" value="16071" name="diff" id="mw-diff-16071" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16071" title="Federal Argon Shipyard" class="mw-changeslist-date">10:25, 16 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,461 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="10,461 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> fix table with review of Legend&#039;s Home</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=16070&amp;undo=16071" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16070" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16070&amp;oldid=16034" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16070" name="oldid" id="mw-oldid-16070" /><input type="radio" value="16070" name="diff" id="mw-diff-16070" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16070" title="Federal Argon Shipyard" class="mw-changeslist-date">10:17, 16 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,461 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="10,461 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> fix table with Cloudbase South East</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=16034&amp;undo=16070" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=16034" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16034&amp;oldid=15956" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="16034" name="oldid" id="mw-oldid-16034" /><input type="radio" value="16034" name="diff" id="mw-diff-16034" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=16034" title="Federal Argon Shipyard" class="mw-changeslist-date">03:05, 15 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Fyhlen" title="User:Fyhlen" class="mw-userlink">Fyhlen</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Fyhlen&amp;action=edit&amp;redlink=1" class="new" title="User talk:Fyhlen (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Fyhlen" title="Special:Contributions/Fyhlen">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,461 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="10,461 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15956&amp;undo=16034" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15956" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15956&amp;oldid=15911" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15956" name="oldid" id="mw-oldid-15956" /><input type="radio" value="15956" name="diff" id="mw-diff-15956" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15956" title="Federal Argon Shipyard" class="mw-changeslist-date">07:14, 13 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Fyhlen" title="User:Fyhlen" class="mw-userlink">Fyhlen</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Fyhlen&amp;action=edit&amp;redlink=1" class="new" title="User talk:Fyhlen (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Fyhlen" title="Special:Contributions/Fyhlen">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,463 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="10,463 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15911&amp;undo=15956" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15911" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15911&amp;oldid=15872" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15911" name="oldid" id="mw-oldid-15911" /><input type="radio" value="15911" name="diff" id="mw-diff-15911" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15911" title="Federal Argon Shipyard" class="mw-changeslist-date">14:56, 10 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,462 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="10,462 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(See Also)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15872&amp;undo=15911" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15872" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15872&amp;oldid=15871" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15872" name="oldid" id="mw-oldid-15872" /><input type="radio" value="15872" name="diff" id="mw-diff-15872" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15872" title="Federal Argon Shipyard" class="mw-changeslist-date">16:09, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,449 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="10,449 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> price Mercury Hauler</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15871&amp;undo=15872" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15871" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15871&amp;oldid=15870" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15871" name="oldid" id="mw-oldid-15871" /><input type="radio" value="15871" name="diff" id="mw-diff-15871" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15871" title="Federal Argon Shipyard" class="mw-changeslist-date">16:08, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,443 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="10,443 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> price of Phantom</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15870&amp;undo=15871" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15870" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15870&amp;oldid=15656" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15870" name="oldid" id="mw-oldid-15870" /><input type="radio" value="15870" name="diff" id="mw-diff-15870" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15870" title="Federal Argon Shipyard" class="mw-changeslist-date">16:07, 7 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(10,435 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="10,435 bytes after change">(+1,014)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> Use the template ShipSyAvail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15656&amp;undo=15870" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15656" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15656&amp;oldid=15378" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15656" name="oldid" id="mw-oldid-15656" /><input type="radio" value="15656" name="diff" id="mw-diff-15656" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15656" title="Federal Argon Shipyard" class="mw-changeslist-date">15:10, 5 March 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,421 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="9,421 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> update with Legend&#039;s Home</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15378&amp;undo=15656" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15378" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15378&amp;oldid=15377" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15378" name="oldid" id="mw-oldid-15378" /><input type="radio" value="15378" name="diff" id="mw-diff-15378" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15378" title="Federal Argon Shipyard" class="mw-changeslist-date">21:45, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,421 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,421 bytes after change">(+100)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> add Griffon Sentinel</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15377&amp;undo=15378" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15377" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15377&amp;oldid=15359" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15377" name="oldid" id="mw-oldid-15377" /><input type="radio" value="15377" name="diff" id="mw-diff-15377" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15377" title="Federal Argon Shipyard" class="mw-changeslist-date">21:37, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,321 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="9,321 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> reorder and update data with Argon Sector M148</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=15359&amp;undo=15377" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=15359" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=15359&amp;oldid=14936" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="15359" name="oldid" id="mw-oldid-15359" /><input type="radio" value="15359" name="diff" id="mw-diff-15359" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=15359" title="Federal Argon Shipyard" class="mw-changeslist-date">19:49, 28 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,321 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,321 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(add a Argon navbox)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=14936&amp;undo=15359" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=14936" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=14936&amp;oldid=14935" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="14936" name="oldid" id="mw-oldid-14936" /><input type="radio" value="14936" name="diff" id="mw-diff-14936" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=14936" title="Federal Argon Shipyard" class="mw-changeslist-date">01:41, 27 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,303 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,303 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update links</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=14935&amp;undo=14936" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=14935" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=14935&amp;oldid=14395" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="14935" name="oldid" id="mw-oldid-14935" /><input type="radio" value="14935" name="diff" id="mw-diff-14935" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=14935" title="Federal Argon Shipyard" class="mw-changeslist-date">01:40, 27 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,288 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="9,288 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update with Omicron Lyrae data</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=14395&amp;undo=14935" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=14395" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=14395&amp;oldid=14390" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="14395" name="oldid" id="mw-oldid-14395" /><input type="radio" value="14395" name="diff" id="mw-diff-14395" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=14395" title="Federal Argon Shipyard" class="mw-changeslist-date">13:35, 20 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,289 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="9,289 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> Change definition of Mercury Tanker/Super Freighter 1/2 to &#039;&#039;/XL as in game</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=14390&amp;undo=14395" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=14390" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=14390&amp;oldid=14387" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="14390" name="oldid" id="mw-oldid-14390" /><input type="radio" value="14390" name="diff" id="mw-diff-14390" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=14390" title="Federal Argon Shipyard" class="mw-changeslist-date">13:19, 20 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,291 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="9,291 bytes after change">(+707)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> Use the template ArgonSyAvail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=14387&amp;undo=14390" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=14387" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=14387&amp;oldid=12956" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="14387" name="oldid" id="mw-oldid-14387" /><input type="radio" value="14387" name="diff" id="mw-diff-14387" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=14387" title="Federal Argon Shipyard" class="mw-changeslist-date">11:53, 20 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,584 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="8,584 bytes after change">(+1,168)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span>  use new ArgonSyAvail template</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=12956&amp;undo=14387" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=12956" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=12956&amp;oldid=12884" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="12956" name="oldid" id="mw-oldid-12956" /><input type="radio" value="12956" name="diff" id="mw-diff-12956" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=12956" title="Federal Argon Shipyard" class="mw-changeslist-date">00:56, 2 July 2013</a>‎ <span class='history-user'><a href="/index.php/User:ZacQuicksilver" title="User:ZacQuicksilver" class="mw-userlink">ZacQuicksilver</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ZacQuicksilver&amp;action=edit&amp;redlink=1" class="new" title="User talk:ZacQuicksilver (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ZacQuicksilver" title="Special:Contributions/ZacQuicksilver">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,416 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,416 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span>  Correected Complex Construction Kit cost</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=12884&amp;undo=12956" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=12884" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=12884&amp;oldid=12882" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="12884" name="oldid" id="mw-oldid-12884" /><input type="radio" value="12884" name="diff" id="mw-diff-12884" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=12884" title="Federal Argon Shipyard" class="mw-changeslist-date">02:51, 27 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:ZacQuicksilver" title="User:ZacQuicksilver" class="mw-userlink">ZacQuicksilver</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ZacQuicksilver&amp;action=edit&amp;redlink=1" class="new" title="User talk:ZacQuicksilver (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ZacQuicksilver" title="Special:Contributions/ZacQuicksilver">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,416 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,416 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span>  Corrected me not putting in prices</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=12882&amp;undo=12884" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=12882" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=12882&amp;oldid=12881" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="12882" name="oldid" id="mw-oldid-12882" /><input type="radio" value="12882" name="diff" id="mw-diff-12882" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=12882" title="Federal Argon Shipyard" class="mw-changeslist-date">09:31, 26 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:ZacQuicksilver" title="User:ZacQuicksilver" class="mw-userlink">ZacQuicksilver</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ZacQuicksilver&amp;action=edit&amp;redlink=1" class="new" title="User talk:ZacQuicksilver (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ZacQuicksilver" title="Special:Contributions/ZacQuicksilver">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,417 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,417 bytes after change">(+153)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span>  Added two more forges available in Omicron Lyrae</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=12881&amp;undo=12882" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=12881" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=12881&amp;oldid=11714" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="12881" name="oldid" id="mw-oldid-12881" /><input type="radio" value="12881" name="diff" id="mw-diff-12881" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=12881" title="Federal Argon Shipyard" class="mw-changeslist-date">09:28, 26 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:ZacQuicksilver" title="User:ZacQuicksilver" class="mw-userlink">ZacQuicksilver</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:ZacQuicksilver&amp;action=edit&amp;redlink=1" class="new" title="User talk:ZacQuicksilver (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/ZacQuicksilver" title="Special:Contributions/ZacQuicksilver">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,264 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,264 bytes after change">(+197)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> Added some factories available in Omicron Lyrae, including some that weren&#039;t on the chart. I think there are more not on the chart.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11714&amp;undo=12881" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11714" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11714&amp;oldid=11713" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11714" name="oldid" id="mw-oldid-11714" /><input type="radio" value="11714" name="diff" id="mw-diff-11714" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11714" title="Federal Argon Shipyard" class="mw-changeslist-date">22:28, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,067 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,067 bytes after change">(+76)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update additional ship avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11713&amp;undo=11714" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11713" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11713&amp;oldid=11712" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11713" name="oldid" id="mw-oldid-11713" /><input type="radio" value="11713" name="diff" id="mw-diff-11713" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11713" title="Federal Argon Shipyard" class="mw-changeslist-date">22:23, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,991 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,991 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update heavy centaur avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11712&amp;undo=11713" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11712" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11712&amp;oldid=11711" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11712" name="oldid" id="mw-oldid-11712" /><input type="radio" value="11712" name="diff" id="mw-diff-11712" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11712" title="Federal Argon Shipyard" class="mw-changeslist-date">22:22, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,990 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,990 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update centaur avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11711&amp;undo=11712" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11711" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11711&amp;oldid=11710" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11711" name="oldid" id="mw-oldid-11711" /><input type="radio" value="11711" name="diff" id="mw-diff-11711" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11711" title="Federal Argon Shipyard" class="mw-changeslist-date">22:21, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,981 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,981 bytes after change">(+9)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update elite avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11710&amp;undo=11711" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11710" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11710&amp;oldid=11709" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11710" name="oldid" id="mw-oldid-11710" /><input type="radio" value="11710" name="diff" id="mw-diff-11710" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11710" title="Federal Argon Shipyard" class="mw-changeslist-date">22:20, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,972 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,972 bytes after change">(+8)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update titan avail, assume standard cap ships everywhere</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=11709&amp;undo=11710" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=11709" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=11709&amp;oldid=5829" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="11709" name="oldid" id="mw-oldid-11709" /><input type="radio" value="11709" name="diff" id="mw-diff-11709" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=11709" title="Federal Argon Shipyard" class="mw-changeslist-date">22:19, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,964 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,964 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Ships" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Ships: </span> update buster avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5829&amp;undo=11709" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5829" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5829&amp;oldid=5570" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5829" name="oldid" id="mw-oldid-5829" /><input type="radio" value="5829" name="diff" id="mw-diff-5829" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5829" title="Federal Argon Shipyard" class="mw-changeslist-date">09:42, 20 March 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Adam&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Adam (page does not exist)">Adam</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Adam&amp;action=edit&amp;redlink=1" class="new" title="User talk:Adam (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Adam" title="Special:Contributions/Adam">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,947 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,947 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5570&amp;undo=5829" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5570" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5570&amp;oldid=5554" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5570" name="oldid" id="mw-oldid-5570" /><input type="radio" value="5570" name="diff" id="mw-diff-5570" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5570" title="Federal Argon Shipyard" class="mw-changeslist-date">21:06, 22 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,923 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,923 bytes after change">(+539)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> updated cattle and cahoona avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5554&amp;undo=5570" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5554" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5554&amp;oldid=5552" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5554" name="oldid" id="mw-oldid-5554" /><input type="radio" value="5554" name="diff" id="mw-diff-5554" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5554" title="Federal Argon Shipyard" class="mw-changeslist-date">22:39, 21 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,384 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,384 bytes after change">(+124)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> updated crystal fab, chip plant, computer plant</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5552&amp;undo=5554" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5552" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5552&amp;oldid=5534" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5552" name="oldid" id="mw-oldid-5552" /><input type="radio" value="5552" name="diff" id="mw-diff-5552" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5552" title="Federal Argon Shipyard" class="mw-changeslist-date">22:11, 21 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,260 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="6,260 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> corrected low-yield sidearms link</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5534&amp;undo=5552" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5534" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5534&amp;oldid=5456" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5534" name="oldid" id="mw-oldid-5534" /><input type="radio" value="5534" name="diff" id="mw-diff-5534" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5534" title="Federal Argon Shipyard" class="mw-changeslist-date">20:54, 21 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,260 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,260 bytes after change">(+963)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated with encyclopedia info)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5456&amp;undo=5534" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5456" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5456&amp;oldid=5386" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5456" name="oldid" id="mw-oldid-5456" /><input type="radio" value="5456" name="diff" id="mw-diff-5456" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5456" title="Federal Argon Shipyard" class="mw-changeslist-date">12:27, 16 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,297 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,297 bytes after change">(+164)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Overview" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5386&amp;undo=5456" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5386" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5386&amp;oldid=5378" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5386" name="oldid" id="mw-oldid-5386" /><input type="radio" value="5386" name="diff" id="mw-diff-5386" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5386" title="Federal Argon Shipyard" class="mw-changeslist-date">22:12, 14 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,133 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,133 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Federal_Argon_Shipyard#Stations" title="Federal Argon Shipyard">→</a>‎<span dir="auto"><span class="autocomment">Stations: </span> updated weapon component factory avail</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5378&amp;undo=5386" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5378" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5378&amp;oldid=5331" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5378" name="oldid" id="mw-oldid-5378" /><input type="radio" value="5378" name="diff" id="mw-diff-5378" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5378" title="Federal Argon Shipyard" class="mw-changeslist-date">21:43, 14 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,120 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,120 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added apostrophe to legend&#039;s home)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5331&amp;undo=5378" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5331" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5331&amp;oldid=5316" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5331" name="oldid" id="mw-oldid-5331" /><input type="radio" value="5331" name="diff" id="mw-diff-5331" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5331" title="Federal Argon Shipyard" class="mw-changeslist-date">14:35, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,119 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,119 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Replaced table header links to sector pages to Shipyard pages)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5316&amp;undo=5331" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5316" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5316&amp;oldid=5303" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5316" name="oldid" id="mw-oldid-5316" /><input type="radio" value="5316" name="diff" id="mw-diff-5316" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5316" title="Federal Argon Shipyard" class="mw-changeslist-date">09:29, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,097 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="5,097 bytes after change">(+5,000)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added sortable table from shipyard page.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5303&amp;undo=5316" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5303" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5303&amp;oldid=5302" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5303" name="oldid" id="mw-oldid-5303" /><input type="radio" value="5303" name="diff" id="mw-diff-5303" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5303" title="Federal Argon Shipyard" class="mw-changeslist-date">01:14, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(97 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="97 bytes after change">(-13)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5302&amp;undo=5303" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5302" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5302&amp;oldid=5298" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5302" name="oldid" id="mw-oldid-5302" /><input type="radio" value="5302" name="diff" id="mw-diff-5302" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5302" title="Federal Argon Shipyard" class="mw-changeslist-date">01:14, 13 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Rexde500" title="User:Rexde500" class="mw-userlink">Rexde500</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Rexde500" title="User talk:Rexde500">talk</a> | <a href="/index.php/Special:Contributions/Rexde500" title="Special:Contributions/Rexde500">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(110 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="110 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5298&amp;undo=5302" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5298" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5298&amp;oldid=5295" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5298" name="oldid" id="mw-oldid-5298" /><input type="radio" value="5298" name="diff" id="mw-diff-5298" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5298" title="Federal Argon Shipyard" class="mw-changeslist-date">20:34, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(97 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="97 bytes after change">(+97)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5295&amp;undo=5298" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5295" title="Federal Argon Shipyard">cur</a> | <a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=5295&amp;oldid=5230" title="Federal Argon Shipyard">prev</a>)</span><input type="radio" value="5295" name="oldid" id="mw-oldid-5295" /><input type="radio" value="5295" name="diff" id="mw-diff-5295" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5295" title="Federal Argon Shipyard" class="mw-changeslist-date">20:31, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(empty)</span> <span dir="ltr" class="mw-plusminus-neg" title="0 bytes after change">(-34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Blanked the page)</span> (<span class="mw-history-undo"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit&amp;undoafter=5230&amp;undo=5295" title="Federal Argon Shipyard">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Federal_Argon_Shipyard&amp;diff=16511&amp;oldid=5230" title="Federal Argon Shipyard">cur</a> | prev)</span><input type="radio" value="5230" name="oldid" id="mw-oldid-5230" /><input type="radio" value="5230" name="diff" id="mw-diff-5230" /> <a href="/index.php?title=Federal_Argon_Shipyard&amp;oldid=5230" title="Federal Argon Shipyard" class="mw-changeslist-date">02:10, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(34 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="34 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(moved <a href="/index.php/Federal_Argon_Shipyard" title="Federal Argon Shipyard">Federal Argon Shipyard</a> to <a href="/index.php/Argon_Prime_Shipyard" class="mw-redirect" title="Argon Prime Shipyard">Argon Prime Shipyard</a>: Each Shipyard will ultimately have its own page)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Federal_Argon_Shipyard">http://www.x3wiki.com/index.php/Federal_Argon_Shipyard</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Federal_Argon_Shipyard" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:Federal_Argon_Shipyard" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Federal+Argon+Shipyard&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Federal+Argon+Shipyard&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Federal_Argon_Shipyard" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Federal_Argon_Shipyard" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Federal_Argon_Shipyard&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Federal_Argon_Shipyard&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":97});});</script></body></html>
