<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Eclipse" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Eclipse","wgTitle":"Eclipse","wgCurRevisionId":16982,"wgRevisionId":0,"wgArticleId":198,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Eclipse","wgRelevantArticleId":198,"wgRequestId":"Wllu5FkfZokAADMcx20AAAAK","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Eclipse&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Eclipse&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Eclipse&quot; Atom feed" href="/index.php?title=Eclipse&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Eclipse rootpage-Eclipse skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Eclipse"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Eclipse" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Eclipse" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=Eclipse&amp;dir=prev&amp;action=history" title="Eclipse" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Eclipse&amp;offset=20101017231443&amp;action=history" title="Eclipse" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Eclipse&amp;offset=&amp;limit=20&amp;action=history" title="Eclipse" class="mw-numlink">20</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=50&amp;action=history" title="Eclipse" class="mw-numlink">50</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=100&amp;action=history" title="Eclipse" class="mw-numlink">100</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=250&amp;action=history" title="Eclipse" class="mw-numlink">250</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=500&amp;action=history" title="Eclipse" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Eclipse" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=16981" title="Eclipse">prev</a>)</span><input type="radio" value="16982" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="16982" checked="checked" name="diff" id="mw-diff-16982" /> <a href="/index.php?title=Eclipse&amp;oldid=16982" title="Eclipse" class="mw-changeslist-date">21:47, 13 June 2017</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/178.9.55.73" title="Special:Contributions/178.9.55.73" class="mw-userlink mw-anonuserlink">178.9.55.73</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:178.9.55.73&amp;action=edit&amp;redlink=1" class="new" title="User talk:178.9.55.73 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,134 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,134 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Eclipse" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Eclipse</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=16981&amp;undo=16982" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=16981" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=16981&amp;oldid=16816" title="Eclipse">prev</a>)</span><input type="radio" value="16981" checked="checked" name="oldid" id="mw-oldid-16981" /><input type="radio" value="16981" name="diff" id="mw-diff-16981" /> <a href="/index.php?title=Eclipse&amp;oldid=16981" title="Eclipse" class="mw-changeslist-date">21:46, 13 June 2017</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/178.9.55.73" title="Special:Contributions/178.9.55.73" class="mw-userlink mw-anonuserlink">178.9.55.73</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:178.9.55.73&amp;action=edit&amp;redlink=1" class="new" title="User talk:178.9.55.73 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,133 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,133 bytes after change">(+78)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Eclipse" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Eclipse</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=16816&amp;undo=16981" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=16816" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=16816&amp;oldid=16815" title="Eclipse">prev</a>)</span><input type="radio" value="16816" name="oldid" id="mw-oldid-16816" /><input type="radio" value="16816" name="diff" id="mw-diff-16816" /> <a href="/index.php?title=Eclipse&amp;oldid=16816" title="Eclipse" class="mw-changeslist-date">18:19, 16 October 2016</a>‎ <span class='history-user'><a href="/index.php?title=User:Eyeseeyou&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Eyeseeyou (page does not exist)">Eyeseeyou</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Eyeseeyou&amp;action=edit&amp;redlink=1" class="new" title="User talk:Eyeseeyou (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Eyeseeyou" title="Special:Contributions/Eyeseeyou">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,055 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,055 bytes after change">(+26)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Filling in missing ship values)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=16815&amp;undo=16816" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=16815" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=16815&amp;oldid=13655" title="Eclipse">prev</a>)</span><input type="radio" value="16815" name="oldid" id="mw-oldid-16815" /><input type="radio" value="16815" name="diff" id="mw-diff-16815" /> <a href="/index.php?title=Eclipse&amp;oldid=16815" title="Eclipse" class="mw-changeslist-date">18:07, 16 October 2016</a>‎ <span class='history-user'><a href="/index.php?title=User:Eyeseeyou&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Eyeseeyou (page does not exist)">Eyeseeyou</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Eyeseeyou&amp;action=edit&amp;redlink=1" class="new" title="User talk:Eyeseeyou (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Eyeseeyou" title="Special:Contributions/Eyeseeyou">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,029 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,029 bytes after change">(+13)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Filling in missing ship values)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=13655&amp;undo=16815" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=13655" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=13655&amp;oldid=11838" title="Eclipse">prev</a>)</span><input type="radio" value="13655" name="oldid" id="mw-oldid-13655" /><input type="radio" value="13655" name="diff" id="mw-diff-13655" /> <a href="/index.php?title=Eclipse&amp;oldid=13655" title="Eclipse" class="mw-changeslist-date">14:38, 9 September 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(9,016 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="9,016 bytes after change">(+17)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11838&amp;undo=13655" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11838" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11838&amp;oldid=11770" title="Eclipse">prev</a>)</span><input type="radio" value="11838" name="oldid" id="mw-oldid-11838" /><input type="radio" value="11838" name="diff" id="mw-diff-11838" /> <a href="/index.php?title=Eclipse&amp;oldid=11838" title="Eclipse" class="mw-changeslist-date">19:07, 25 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,999 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,999 bytes after change">(+296)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11770&amp;undo=11838" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11770" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11770&amp;oldid=11769" title="Eclipse">prev</a>)</span><input type="radio" value="11770" name="oldid" id="mw-oldid-11770" /><input type="radio" value="11770" name="diff" id="mw-diff-11770" /> <a href="/index.php?title=Eclipse&amp;oldid=11770" title="Eclipse" class="mw-changeslist-date">00:52, 21 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,703 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="8,703 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11769&amp;undo=11770" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11769" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11769&amp;oldid=11768" title="Eclipse">prev</a>)</span><input type="radio" value="11769" name="oldid" id="mw-oldid-11769" /><input type="radio" value="11769" name="diff" id="mw-diff-11769" /> <a href="/index.php?title=Eclipse&amp;oldid=11769" title="Eclipse" class="mw-changeslist-date">00:51, 21 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,703 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="8,703 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11768&amp;undo=11769" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11768" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11768&amp;oldid=11347" title="Eclipse">prev</a>)</span><input type="radio" value="11768" name="oldid" id="mw-oldid-11768" /><input type="radio" value="11768" name="diff" id="mw-diff-11768" /> <a href="/index.php?title=Eclipse&amp;oldid=11768" title="Eclipse" class="mw-changeslist-date">00:48, 21 March 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,703 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,703 bytes after change">(+44)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(I found a prototype during one of my games in AP. This thing has 30000 hull strength. That&#039;s unusual compared to other M3s, which basically are doubled from their TC counterparts. I think they improved some stuff for the Prototype in AP.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11347&amp;undo=11768" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11347" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11347&amp;oldid=11252" title="Eclipse">prev</a>)</span><input type="radio" value="11347" name="oldid" id="mw-oldid-11347" /><input type="radio" value="11347" name="diff" id="mw-diff-11347" /> <a href="/index.php?title=Eclipse&amp;oldid=11347" title="Eclipse" class="mw-changeslist-date">13:37, 11 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,659 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,659 bytes after change">(+160)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Eclipse_Prototype" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Eclipse Prototype</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11252&amp;undo=11347" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11252" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11252&amp;oldid=11238" title="Eclipse">prev</a>)</span><input type="radio" value="11252" name="oldid" id="mw-oldid-11252" /><input type="radio" value="11252" name="diff" id="mw-diff-11252" /> <a href="/index.php?title=Eclipse&amp;oldid=11252" title="Eclipse" class="mw-changeslist-date">07:53, 10 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,499 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,499 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added pirate hull value)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=11238&amp;undo=11252" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=11238" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=11238&amp;oldid=10643" title="Eclipse">prev</a>)</span><input type="radio" value="11238" name="oldid" id="mw-oldid-11238" /><input type="radio" value="11238" name="diff" id="mw-diff-11238" /> <a href="/index.php?title=Eclipse&amp;oldid=11238" title="Eclipse" class="mw-changeslist-date">02:40, 8 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Bizbag" title="User:Bizbag" class="mw-userlink">Bizbag</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Bizbag&amp;action=edit&amp;redlink=1" class="new" title="User talk:Bizbag (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Bizbag" title="Special:Contributions/Bizbag">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,495 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="8,495 bytes after change">(+564)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Updated page)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=10643&amp;undo=11238" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=10643" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=10643&amp;oldid=10490" title="Eclipse">prev</a>)</span><input type="radio" value="10643" name="oldid" id="mw-oldid-10643" /><input type="radio" value="10643" name="diff" id="mw-diff-10643" /> <a href="/index.php?title=Eclipse&amp;oldid=10643" title="Eclipse" class="mw-changeslist-date">00:46, 16 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,931 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,931 bytes after change">(-238)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M3+ template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=10490&amp;undo=10643" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=10490" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=10490&amp;oldid=10412" title="Eclipse">prev</a>)</span><input type="radio" value="10490" name="oldid" id="mw-oldid-10490" /><input type="radio" value="10490" name="diff" id="mw-diff-10490" /> <a href="/index.php?title=Eclipse&amp;oldid=10490" title="Eclipse" class="mw-changeslist-date">05:48, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,169 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="8,169 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=10412&amp;undo=10490" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=10412" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=10412&amp;oldid=9323" title="Eclipse">prev</a>)</span><input type="radio" value="10412" name="oldid" id="mw-oldid-10412" /><input type="radio" value="10412" name="diff" id="mw-diff-10412" /> <a href="/index.php?title=Eclipse&amp;oldid=10412" title="Eclipse" class="mw-changeslist-date">05:23, 10 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(8,165 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="8,165 bytes after change">(+503)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added missile compatibility)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=9323&amp;undo=10412" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=9323" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=9323&amp;oldid=9293" title="Eclipse">prev</a>)</span><input type="radio" value="9323" name="oldid" id="mw-oldid-9323" /><input type="radio" value="9323" name="diff" id="mw-diff-9323" /> <a href="/index.php?title=Eclipse&amp;oldid=9323" title="Eclipse" class="mw-changeslist-date">01:31, 13 June 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.144.185.0" title="Special:Contributions/78.144.185.0" class="mw-userlink mw-anonuserlink">78.144.185.0</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.144.185.0&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.144.185.0 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,662 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,662 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles: </span> nonsensical wording fixed</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=9293&amp;undo=9323" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=9293" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=9293&amp;oldid=9280" title="Eclipse">prev</a>)</span><input type="radio" value="9293" name="oldid" id="mw-oldid-9293" /><input type="radio" value="9293" name="diff" id="mw-diff-9293" /> <a href="/index.php?title=Eclipse&amp;oldid=9293" title="Eclipse" class="mw-changeslist-date">07:55, 11 June 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Ironbuket&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Ironbuket (page does not exist)">Ironbuket</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Ironbuket&amp;action=edit&amp;redlink=1" class="new" title="User talk:Ironbuket (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Ironbuket" title="Special:Contributions/Ironbuket">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,660 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,660 bytes after change">(+141)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=9280&amp;undo=9293" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=9280" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=9280&amp;oldid=8981" title="Eclipse">prev</a>)</span><input type="radio" value="9280" name="oldid" id="mw-oldid-9280" /><input type="radio" value="9280" name="diff" id="mw-diff-9280" /> <a href="/index.php?title=Eclipse&amp;oldid=9280" title="Eclipse" class="mw-changeslist-date">11:50, 7 June 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/31.32.254.95" title="Special:Contributions/31.32.254.95" class="mw-userlink mw-anonuserlink">31.32.254.95</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:31.32.254.95&amp;action=edit&amp;redlink=1" class="new" title="User talk:31.32.254.95 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,519 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,519 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Combat" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=8981&amp;undo=9280" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=8981" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=8981&amp;oldid=8588" title="Eclipse">prev</a>)</span><input type="radio" value="8981" name="oldid" id="mw-oldid-8981" /><input type="radio" value="8981" name="diff" id="mw-diff-8981" /> <a href="/index.php?title=Eclipse&amp;oldid=8981" title="Eclipse" class="mw-changeslist-date">23:59, 8 April 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/93.143.213.56" title="Special:Contributions/93.143.213.56" class="mw-userlink mw-anonuserlink">93.143.213.56</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:93.143.213.56&amp;action=edit&amp;redlink=1" class="new" title="User talk:93.143.213.56 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,519 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="7,519 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=8588&amp;undo=8981" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=8588" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=8588&amp;oldid=8427" title="Eclipse">prev</a>)</span><input type="radio" value="8588" name="oldid" id="mw-oldid-8588" /><input type="radio" value="8588" name="diff" id="mw-diff-8588" /> <a href="/index.php?title=Eclipse&amp;oldid=8588" title="Eclipse" class="mw-changeslist-date">08:41, 15 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Sadron&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Sadron (page does not exist)">Sadron</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Sadron&amp;action=edit&amp;redlink=1" class="new" title="User talk:Sadron (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Sadron" title="Special:Contributions/Sadron">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,521 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="7,521 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=8427&amp;undo=8588" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=8427" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=8427&amp;oldid=7306" title="Eclipse">prev</a>)</span><input type="radio" value="8427" name="oldid" id="mw-oldid-8427" /><input type="radio" value="8427" name="diff" id="mw-diff-8427" /> <a href="/index.php?title=Eclipse&amp;oldid=8427" title="Eclipse" class="mw-changeslist-date">00:56, 4 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/62.107.32.49" title="Special:Contributions/62.107.32.49" class="mw-userlink mw-anonuserlink">62.107.32.49</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:62.107.32.49&amp;action=edit&amp;redlink=1" class="new" title="User talk:62.107.32.49 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,521 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,521 bytes after change">(+238)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7306&amp;undo=8427" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7306" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7306&amp;oldid=7298" title="Eclipse">prev</a>)</span><input type="radio" value="7306" name="oldid" id="mw-oldid-7306" /><input type="radio" value="7306" name="diff" id="mw-diff-7306" /> <a href="/index.php?title=Eclipse&amp;oldid=7306" title="Eclipse" class="mw-changeslist-date">14:46, 14 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:MagicSquid" title="User:MagicSquid" class="mw-userlink">MagicSquid</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:MagicSquid&amp;action=edit&amp;redlink=1" class="new" title="User talk:MagicSquid (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/MagicSquid" title="Special:Contributions/MagicSquid">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,283 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,283 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Availability" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Availability: </span> -- Changed &quot;on&quot; to &quot;one&quot;</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7298&amp;undo=7306" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7298" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7298&amp;oldid=7297" title="Eclipse">prev</a>)</span><input type="radio" value="7298" name="oldid" id="mw-oldid-7298" /><input type="radio" value="7298" name="diff" id="mw-diff-7298" /> <a href="/index.php?title=Eclipse&amp;oldid=7298" title="Eclipse" class="mw-changeslist-date">13:03, 14 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:MagicSquid" title="User:MagicSquid" class="mw-userlink">MagicSquid</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:MagicSquid&amp;action=edit&amp;redlink=1" class="new" title="User talk:MagicSquid (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/MagicSquid" title="Special:Contributions/MagicSquid">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,282 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="7,282 bytes after change">(+7,247)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Looks like someone&#039;s been vandalizing the page. This is an edit to restore it to what appears to be one of the last good states.)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7297&amp;undo=7298" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7297" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7297&amp;oldid=7283" title="Eclipse">prev</a>)</span><input type="radio" value="7297" name="oldid" id="mw-oldid-7297" /><input type="radio" value="7297" name="diff" id="mw-diff-7297" /> <a href="/index.php?title=Eclipse&amp;oldid=7297" title="Eclipse" class="mw-changeslist-date">00:46, 14 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/217.172.179.88" title="Special:Contributions/217.172.179.88" class="mw-userlink mw-anonuserlink">217.172.179.88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:217.172.179.88&amp;action=edit&amp;redlink=1" class="new" title="User talk:217.172.179.88 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(35 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="35 bytes after change">(-23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(LRxMRaqAhJSkaOwUsU)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7283&amp;undo=7297" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7283" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7283&amp;oldid=7282" title="Eclipse">prev</a>)</span><input type="radio" value="7283" name="oldid" id="mw-oldid-7283" /><input type="radio" value="7283" name="diff" id="mw-diff-7283" /> <a href="/index.php?title=Eclipse&amp;oldid=7283" title="Eclipse" class="mw-changeslist-date">21:43, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/107.20.251.132" title="Special:Contributions/107.20.251.132" class="mw-userlink mw-anonuserlink">107.20.251.132</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:107.20.251.132&amp;action=edit&amp;redlink=1" class="new" title="User talk:107.20.251.132 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(58 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="58 bytes after change">(+14)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(JnafbmPWEzm)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7282&amp;undo=7283" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7282" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7282&amp;oldid=7277" title="Eclipse">prev</a>)</span><input type="radio" value="7282" name="oldid" id="mw-oldid-7282" /><input type="radio" value="7282" name="diff" id="mw-diff-7282" /> <a href="/index.php?title=Eclipse&amp;oldid=7282" title="Eclipse" class="mw-changeslist-date">21:35, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/109.224.30.146" title="Special:Contributions/109.224.30.146" class="mw-userlink mw-anonuserlink">109.224.30.146</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:109.224.30.146&amp;action=edit&amp;redlink=1" class="new" title="User talk:109.224.30.146 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(44 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="44 bytes after change">(-6,880)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(QPVbErAEIDQCfYfHWg)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7277&amp;undo=7282" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7277" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7277&amp;oldid=7273" title="Eclipse">prev</a>)</span><input type="radio" value="7277" name="oldid" id="mw-oldid-7277" /><input type="radio" value="7277" name="diff" id="mw-diff-7277" /> <a href="/index.php?title=Eclipse&amp;oldid=7277" title="Eclipse" class="mw-changeslist-date">20:41, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.144.176.211" title="Special:Contributions/78.144.176.211" class="mw-userlink mw-anonuserlink">78.144.176.211</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.144.176.211&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.144.176.211 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,924 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,924 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 7273 by <a href="/index.php/Special:Contributions/119.46.111.11" title="Special:Contributions/119.46.111.11">119.46.111.11</a> (<a href="/index.php?title=User_talk:119.46.111.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:119.46.111.11 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7273&amp;undo=7277" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7273" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7273&amp;oldid=7265" title="Eclipse">prev</a>)</span><input type="radio" value="7273" name="oldid" id="mw-oldid-7273" /><input type="radio" value="7273" name="diff" id="mw-diff-7273" /> <a href="/index.php?title=Eclipse&amp;oldid=7273" title="Eclipse" class="mw-changeslist-date">19:54, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/119.46.111.11" title="Special:Contributions/119.46.111.11" class="mw-userlink mw-anonuserlink">119.46.111.11</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:119.46.111.11&amp;action=edit&amp;redlink=1" class="new" title="User talk:119.46.111.11 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,883 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,883 bytes after change">(-41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Variants" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Variants</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7265&amp;undo=7273" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7265" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7265&amp;oldid=7262" title="Eclipse">prev</a>)</span><input type="radio" value="7265" name="oldid" id="mw-oldid-7265" /><input type="radio" value="7265" name="diff" id="mw-diff-7265" /> <a href="/index.php?title=Eclipse&amp;oldid=7265" title="Eclipse" class="mw-changeslist-date">19:27, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.144.176.211" title="Special:Contributions/78.144.176.211" class="mw-userlink mw-anonuserlink">78.144.176.211</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.144.176.211&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.144.176.211 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,924 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,924 bytes after change">(+6,878)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 7262 by <a href="/index.php/Special:Contributions/150.15.96.163" title="Special:Contributions/150.15.96.163">150.15.96.163</a> (<a href="/index.php?title=User_talk:150.15.96.163&amp;action=edit&amp;redlink=1" class="new" title="User talk:150.15.96.163 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7262&amp;undo=7265" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7262" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7262&amp;oldid=7245" title="Eclipse">prev</a>)</span><input type="radio" value="7262" name="oldid" id="mw-oldid-7262" /><input type="radio" value="7262" name="diff" id="mw-diff-7262" /> <a href="/index.php?title=Eclipse&amp;oldid=7262" title="Eclipse" class="mw-changeslist-date">19:16, 13 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/150.15.96.163" title="Special:Contributions/150.15.96.163" class="mw-userlink mw-anonuserlink">150.15.96.163</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:150.15.96.163&amp;action=edit&amp;redlink=1" class="new" title="User talk:150.15.96.163 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(46 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="46 bytes after change">(-6,878)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(TVWhiPvmb)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7245&amp;undo=7262" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7245" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7245&amp;oldid=7243" title="Eclipse">prev</a>)</span><input type="radio" value="7245" name="oldid" id="mw-oldid-7245" /><input type="radio" value="7245" name="diff" id="mw-diff-7245" /> <a href="/index.php?title=Eclipse&amp;oldid=7245" title="Eclipse" class="mw-changeslist-date">23:19, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.145.167.18" title="Special:Contributions/78.145.167.18" class="mw-userlink mw-anonuserlink">78.145.167.18</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.145.167.18&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.145.167.18 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,924 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,924 bytes after change">(+6,870)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 7243 by <a href="/index.php/Special:Contributions/168.87.10.53" title="Special:Contributions/168.87.10.53">168.87.10.53</a> (<a href="/index.php?title=User_talk:168.87.10.53&amp;action=edit&amp;redlink=1" class="new" title="User talk:168.87.10.53 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7243&amp;undo=7245" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7243" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7243&amp;oldid=7239" title="Eclipse">prev</a>)</span><input type="radio" value="7243" name="oldid" id="mw-oldid-7243" /><input type="radio" value="7243" name="diff" id="mw-diff-7243" /> <a href="/index.php?title=Eclipse&amp;oldid=7243" title="Eclipse" class="mw-changeslist-date">23:16, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/168.87.10.53" title="Special:Contributions/168.87.10.53" class="mw-userlink mw-anonuserlink">168.87.10.53</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:168.87.10.53&amp;action=edit&amp;redlink=1" class="new" title="User talk:168.87.10.53 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(54 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="54 bytes after change">(-6,870)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(AaMjuGiMQboWCITcJlb)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7239&amp;undo=7243" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7239" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7239&amp;oldid=7238" title="Eclipse">prev</a>)</span><input type="radio" value="7239" name="oldid" id="mw-oldid-7239" /><input type="radio" value="7239" name="diff" id="mw-diff-7239" /> <a href="/index.php?title=Eclipse&amp;oldid=7239" title="Eclipse" class="mw-changeslist-date">21:08, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.145.167.18" title="Special:Contributions/78.145.167.18" class="mw-userlink mw-anonuserlink">78.145.167.18</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.145.167.18&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.145.167.18 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,924 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,924 bytes after change">(+6,877)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Undo revision 7238 by <a href="/index.php/Special:Contributions/59.124.27.108" title="Special:Contributions/59.124.27.108">59.124.27.108</a> (<a href="/index.php?title=User_talk:59.124.27.108&amp;action=edit&amp;redlink=1" class="new" title="User talk:59.124.27.108 (page does not exist)">talk</a>))</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7238&amp;undo=7239" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7238" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7238&amp;oldid=7235" title="Eclipse">prev</a>)</span><input type="radio" value="7238" name="oldid" id="mw-oldid-7238" /><input type="radio" value="7238" name="diff" id="mw-diff-7238" /> <a href="/index.php?title=Eclipse&amp;oldid=7238" title="Eclipse" class="mw-changeslist-date">20:52, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/59.124.27.108" title="Special:Contributions/59.124.27.108" class="mw-userlink mw-anonuserlink">59.124.27.108</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:59.124.27.108&amp;action=edit&amp;redlink=1" class="new" title="User talk:59.124.27.108 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(47 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="47 bytes after change">(-6,877)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(MdsGklbYUyMFJ)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7235&amp;undo=7238" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7235" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7235&amp;oldid=7214" title="Eclipse">prev</a>)</span><input type="radio" value="7235" name="oldid" id="mw-oldid-7235" /><input type="radio" value="7235" name="diff" id="mw-diff-7235" /> <a href="/index.php?title=Eclipse&amp;oldid=7235" title="Eclipse" class="mw-changeslist-date">19:19, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.145.167.18" title="Special:Contributions/78.145.167.18" class="mw-userlink mw-anonuserlink">78.145.167.18</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.145.167.18&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.145.167.18 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,924 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="6,924 bytes after change">(+6,871)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7214&amp;undo=7235" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7214" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7214&amp;oldid=7211" title="Eclipse">prev</a>)</span><input type="radio" value="7214" name="oldid" id="mw-oldid-7214" /><input type="radio" value="7214" name="diff" id="mw-diff-7214" /> <a href="/index.php?title=Eclipse&amp;oldid=7214" title="Eclipse" class="mw-changeslist-date">10:58, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/89.134.144.121" title="Special:Contributions/89.134.144.121" class="mw-userlink mw-anonuserlink">89.134.144.121</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:89.134.144.121&amp;action=edit&amp;redlink=1" class="new" title="User talk:89.134.144.121 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(53 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="53 bytes after change">(+3)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(GkFsunZbKXgvzVtLH)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7211&amp;undo=7214" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7211" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7211&amp;oldid=7204" title="Eclipse">prev</a>)</span><input type="radio" value="7211" name="oldid" id="mw-oldid-7211" /><input type="radio" value="7211" name="diff" id="mw-diff-7211" /> <a href="/index.php?title=Eclipse&amp;oldid=7211" title="Eclipse" class="mw-changeslist-date">08:25, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/66.201.44.210" title="Special:Contributions/66.201.44.210" class="mw-userlink mw-anonuserlink">66.201.44.210</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:66.201.44.210&amp;action=edit&amp;redlink=1" class="new" title="User talk:66.201.44.210 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(50 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="50 bytes after change">(-6,302)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(hoYjOSOta)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7204&amp;undo=7211" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7204" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7204&amp;oldid=7174" title="Eclipse">prev</a>)</span><input type="radio" value="7204" name="oldid" id="mw-oldid-7204" /><input type="radio" value="7204" name="diff" id="mw-diff-7204" /> <a href="/index.php?title=Eclipse&amp;oldid=7204" title="Eclipse" class="mw-changeslist-date">04:04, 12 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/186.5.65.165" title="Special:Contributions/186.5.65.165" class="mw-userlink mw-anonuserlink">186.5.65.165</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:186.5.65.165&amp;action=edit&amp;redlink=1" class="new" title="User talk:186.5.65.165 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,352 bytes)</span> <strong dir="ltr" class="mw-plusminus-neg" title="6,352 bytes after change">(-619)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Combat" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=7174&amp;undo=7204" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=7174" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=7174&amp;oldid=6836" title="Eclipse">prev</a>)</span><input type="radio" value="7174" name="oldid" id="mw-oldid-7174" /><input type="radio" value="7174" name="diff" id="mw-diff-7174" /> <a href="/index.php?title=Eclipse&amp;oldid=7174" title="Eclipse" class="mw-changeslist-date">18:45, 11 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/122.112.34.22" title="Special:Contributions/122.112.34.22" class="mw-userlink mw-anonuserlink">122.112.34.22</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:122.112.34.22&amp;action=edit&amp;redlink=1" class="new" title="User talk:122.112.34.22 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,971 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,971 bytes after change">(-311)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Suggested_Roles" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=6836&amp;undo=7174" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=6836" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=6836&amp;oldid=6653" title="Eclipse">prev</a>)</span><input type="radio" value="6836" name="oldid" id="mw-oldid-6836" /><input type="radio" value="6836" name="diff" id="mw-diff-6836" /> <a href="/index.php?title=Eclipse&amp;oldid=6836" title="Eclipse" class="mw-changeslist-date">04:03, 8 August 2011</a>‎ <span class='history-user'><a href="/index.php/User:Nepo11" title="User:Nepo11" class="mw-userlink">Nepo11</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Nepo11" title="User talk:Nepo11">talk</a> | <a href="/index.php/Special:Contributions/Nepo11" title="Special:Contributions/Nepo11">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,282 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,282 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Added some missing values)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=6653&amp;undo=6836" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=6653" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=6653&amp;oldid=6652" title="Eclipse">prev</a>)</span><input type="radio" value="6653" name="oldid" id="mw-oldid-6653" /><input type="radio" value="6653" name="diff" id="mw-diff-6653" /> <a href="/index.php?title=Eclipse&amp;oldid=6653" title="Eclipse" class="mw-changeslist-date">10:13, 24 July 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/174.23.221.17" title="Special:Contributions/174.23.221.17" class="mw-userlink mw-anonuserlink">174.23.221.17</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:174.23.221.17&amp;action=edit&amp;redlink=1" class="new" title="User talk:174.23.221.17 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,254 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,254 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=6652&amp;undo=6653" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=6652" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=6652&amp;oldid=5265" title="Eclipse">prev</a>)</span><input type="radio" value="6652" name="oldid" id="mw-oldid-6652" /><input type="radio" value="6652" name="diff" id="mw-diff-6652" /> <a href="/index.php?title=Eclipse&amp;oldid=6652" title="Eclipse" class="mw-changeslist-date">10:11, 24 July 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/174.23.221.17" title="Special:Contributions/174.23.221.17" class="mw-userlink mw-anonuserlink">174.23.221.17</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:174.23.221.17&amp;action=edit&amp;redlink=1" class="new" title="User talk:174.23.221.17 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,248 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,248 bytes after change">(+12)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=5265&amp;undo=6652" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=5265" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=5265&amp;oldid=4081" title="Eclipse">prev</a>)</span><input type="radio" value="5265" name="oldid" id="mw-oldid-5265" /><input type="radio" value="5265" name="diff" id="mw-diff-5265" /> <a href="/index.php?title=Eclipse&amp;oldid=5265" title="Eclipse" class="mw-changeslist-date">04:42, 12 February 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:Unearthly&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Unearthly (page does not exist)">Unearthly</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Unearthly&amp;action=edit&amp;redlink=1" class="new" title="User talk:Unearthly (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Unearthly" title="Special:Contributions/Unearthly">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,236 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,236 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=4081&amp;undo=5265" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=4081" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=4081&amp;oldid=4080" title="Eclipse">prev</a>)</span><input type="radio" value="4081" name="oldid" id="mw-oldid-4081" /><input type="radio" value="4081" name="diff" id="mw-diff-4081" /> <a href="/index.php?title=Eclipse&amp;oldid=4081" title="Eclipse" class="mw-changeslist-date">00:20, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,230 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,230 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Physical_Characteristics" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=4080&amp;undo=4081" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=4080" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=4080&amp;oldid=4079" title="Eclipse">prev</a>)</span><input type="radio" value="4080" name="oldid" id="mw-oldid-4080" /><input type="radio" value="4080" name="diff" id="mw-diff-4080" /> <a href="/index.php?title=Eclipse&amp;oldid=4080" title="Eclipse" class="mw-changeslist-date">00:17, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(7,206 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="7,206 bytes after change">(+268)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Gereral tidying of article)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=4079&amp;undo=4080" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=4079" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=4079&amp;oldid=4078" title="Eclipse">prev</a>)</span><input type="radio" value="4079" name="oldid" id="mw-oldid-4079" /><input type="radio" value="4079" name="diff" id="mw-diff-4079" /> <a href="/index.php?title=Eclipse&amp;oldid=4079" title="Eclipse" class="mw-changeslist-date">00:16, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,938 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,938 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#See_Also" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=4078&amp;undo=4079" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=4078" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=4078&amp;oldid=4077" title="Eclipse">prev</a>)</span><input type="radio" value="4078" name="oldid" id="mw-oldid-4078" /><input type="radio" value="4078" name="diff" id="mw-diff-4078" /> <a href="/index.php?title=Eclipse&amp;oldid=4078" title="Eclipse" class="mw-changeslist-date">00:15, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,914 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,914 bytes after change">(+419)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Combat" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=4077&amp;undo=4078" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=4077" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=4077&amp;oldid=3124" title="Eclipse">prev</a>)</span><input type="radio" value="4077" name="oldid" id="mw-oldid-4077" /><input type="radio" value="4077" name="diff" id="mw-diff-4077" /> <a href="/index.php?title=Eclipse&amp;oldid=4077" title="Eclipse" class="mw-changeslist-date">00:06, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,495 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="6,495 bytes after change">(-249)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#Overview" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=3124&amp;undo=4077" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=3124" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=3124&amp;oldid=3114" title="Eclipse">prev</a>)</span><input type="radio" value="3124" name="oldid" id="mw-oldid-3124" /><input type="radio" value="3124" name="diff" id="mw-diff-3124" /> <a href="/index.php?title=Eclipse&amp;oldid=3124" title="Eclipse" class="mw-changeslist-date">00:27, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,744 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,744 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#See_Also" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=3114&amp;undo=3124" title="Eclipse">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Eclipse&amp;diff=16982&amp;oldid=3114" title="Eclipse">cur</a> | <a href="/index.php?title=Eclipse&amp;diff=3114&amp;oldid=3113" title="Eclipse">prev</a>)</span><input type="radio" value="3114" name="oldid" id="mw-oldid-3114" /><input type="radio" value="3114" name="diff" id="mw-diff-3114" /> <a href="/index.php?title=Eclipse&amp;oldid=3114" title="Eclipse" class="mw-changeslist-date">00:14, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(6,729 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="6,729 bytes after change">(+168)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Eclipse#See_Also" title="Eclipse">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Eclipse&amp;action=edit&amp;undoafter=3113&amp;undo=3114" title="Eclipse">undo</a></span>)</li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form>(newest | <a href="/index.php?title=Eclipse&amp;dir=prev&amp;action=history" title="Eclipse" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=Eclipse&amp;offset=20101017231443&amp;action=history" title="Eclipse" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=Eclipse&amp;offset=&amp;limit=20&amp;action=history" title="Eclipse" class="mw-numlink">20</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=50&amp;action=history" title="Eclipse" class="mw-numlink">50</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=100&amp;action=history" title="Eclipse" class="mw-numlink">100</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=250&amp;action=history" title="Eclipse" class="mw-numlink">250</a> | <a href="/index.php?title=Eclipse&amp;offset=&amp;limit=500&amp;action=history" title="Eclipse" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Eclipse">http://www.x3wiki.com/index.php/Eclipse</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Eclipse" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Eclipse&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Eclipse&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Eclipse&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Eclipse&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Eclipse&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Eclipse" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Eclipse" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Eclipse&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Eclipse&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":111});});</script></body></html>
