<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "To do List" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=To_do_List&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=To_do_List&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;To do List&quot; Atom feed" href="/index.php?title=To_do_List&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"To_do_List","wgTitle":"To do List","wgCurRevisionId":13001,"wgRevisionId":0,"wgArticleId":19,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"To_do_List","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-To_do_List skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "To do List"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=To+do+List" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="To_do_List" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
(newest | <a href="/index.php?title=To_do_List&amp;dir=prev&amp;action=history" title="To do List" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=To_do_List&amp;offset=20100502140727&amp;action=history" title="To do List" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=To_do_List&amp;offset=&amp;limit=20&amp;action=history" title="To do List" class="mw-numlink">20</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=50&amp;action=history" title="To do List" class="mw-numlink">50</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=100&amp;action=history" title="To do List" class="mw-numlink">100</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=250&amp;action=history" title="To do List" class="mw-numlink">250</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=500&amp;action=history" title="To do List" class="mw-numlink">500</a>)<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="To_do_List" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12379" title="To do List">prev</a>)</span><input type="radio" value="13001" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="13001" checked="checked" name="diff" id="mw-diff-13001" /> <a href="/index.php?title=To_do_List&amp;oldid=13001" title="To do List" class="mw-changeslist-date">15:03, 2 July 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Mindstorm555&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Mindstorm555 (page does not exist)">Mindstorm555</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Mindstorm555&amp;action=edit&amp;redlink=1" class="new" title="User talk:Mindstorm555 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Mindstorm555" title="Special:Contributions/Mindstorm555">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,210 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,210 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Admin_TODO" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Admin TODO</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12379&amp;undo=13001" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12379" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12379&amp;oldid=12378" title="To do List">prev</a>)</span><input type="radio" value="12379" checked="checked" name="oldid" id="mw-oldid-12379" /><input type="radio" value="12379" name="diff" id="mw-diff-12379" /> <a href="/index.php?title=To_do_List&amp;oldid=12379" title="To do List" class="mw-changeslist-date">18:42, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,209 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,209 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Details_.28Large-scale.29" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Details (Large-scale)</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12378&amp;undo=12379" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12378" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12378&amp;oldid=12356" title="To do List">prev</a>)</span><input type="radio" value="12378" name="oldid" id="mw-oldid-12378" /><input type="radio" value="12378" name="diff" id="mw-diff-12378" /> <a href="/index.php?title=To_do_List&amp;oldid=12378" title="To do List" class="mw-changeslist-date">18:38, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,205 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,205 bytes after change">(+49)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Finished missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12356&amp;undo=12378" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12356" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12356&amp;oldid=12346" title="To do List">prev</a>)</span><input type="radio" value="12356" name="oldid" id="mw-oldid-12356" /><input type="radio" value="12356" name="diff" id="mw-diff-12356" /> <a href="/index.php?title=To_do_List&amp;oldid=12356" title="To do List" class="mw-changeslist-date">18:02, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,156 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,156 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12346&amp;undo=12356" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12346" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12346&amp;oldid=12345" title="To do List">prev</a>)</span><input type="radio" value="12346" name="oldid" id="mw-oldid-12346" /><input type="radio" value="12346" name="diff" id="mw-diff-12346" /> <a href="/index.php?title=To_do_List&amp;oldid=12346" title="To do List" class="mw-changeslist-date">16:19, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,156 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,156 bytes after change">(+56)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Admin_TODO" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Admin TODO</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12345&amp;undo=12346" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12345" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12345&amp;oldid=12344" title="To do List">prev</a>)</span><input type="radio" value="12345" name="oldid" id="mw-oldid-12345" /><input type="radio" value="12345" name="diff" id="mw-diff-12345" /> <a href="/index.php?title=To_do_List&amp;oldid=12345" title="To do List" class="mw-changeslist-date">16:19, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,100 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,100 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12344&amp;undo=12345" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12344" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12344&amp;oldid=12264" title="To do List">prev</a>)</span><input type="radio" value="12344" name="oldid" id="mw-oldid-12344" /><input type="radio" value="12344" name="diff" id="mw-diff-12344" /> <a href="/index.php?title=To_do_List&amp;oldid=12344" title="To do List" class="mw-changeslist-date">16:18, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,094 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,094 bytes after change">(-18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(set some to done)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12264&amp;undo=12344" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12264" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12264&amp;oldid=12248" title="To do List">prev</a>)</span><input type="radio" value="12264" name="oldid" id="mw-oldid-12264" /><input type="radio" value="12264" name="diff" id="mw-diff-12264" /> <a href="/index.php?title=To_do_List&amp;oldid=12264" title="To do List" class="mw-changeslist-date">13:15, 1 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,112 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,112 bytes after change">(+50)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Categorized TODO page)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12248&amp;undo=12264" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12248" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12248&amp;oldid=12247" title="To do List">prev</a>)</span><input type="radio" value="12248" name="oldid" id="mw-oldid-12248" /><input type="radio" value="12248" name="diff" id="mw-diff-12248" /> <a href="/index.php?title=To_do_List&amp;oldid=12248" title="To do List" class="mw-changeslist-date">13:18, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,062 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="4,062 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12247&amp;undo=12248" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12247" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12247&amp;oldid=12246" title="To do List">prev</a>)</span><input type="radio" value="12247" name="oldid" id="mw-oldid-12247" /><input type="radio" value="12247" name="diff" id="mw-diff-12247" /> <a href="/index.php?title=To_do_List&amp;oldid=12247" title="To do List" class="mw-changeslist-date">13:14, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,062 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,062 bytes after change">(+54)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Completed" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Completed</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12246&amp;undo=12247" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12246" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12246&amp;oldid=12192" title="To do List">prev</a>)</span><input type="radio" value="12246" name="oldid" id="mw-oldid-12246" /><input type="radio" value="12246" name="diff" id="mw-diff-12246" /> <a href="/index.php?title=To_do_List&amp;oldid=12246" title="To do List" class="mw-changeslist-date">13:13, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,008 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,008 bytes after change">(-54)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12192&amp;undo=12246" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12192" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12192&amp;oldid=12145" title="To do List">prev</a>)</span><input type="radio" value="12192" name="oldid" id="mw-oldid-12192" /><input type="radio" value="12192" name="diff" id="mw-diff-12192" /> <a href="/index.php?title=To_do_List&amp;oldid=12192" title="To do List" class="mw-changeslist-date">10:11, 31 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,062 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,062 bytes after change">(+41)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12145&amp;undo=12192" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12145" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12145&amp;oldid=12114" title="To do List">prev</a>)</span><input type="radio" value="12145" name="oldid" id="mw-oldid-12145" /><input type="radio" value="12145" name="diff" id="mw-diff-12145" /> <a href="/index.php?title=To_do_List&amp;oldid=12145" title="To do List" class="mw-changeslist-date">17:16, 30 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,021 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,021 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12114&amp;undo=12145" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12114" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12114&amp;oldid=12113" title="To do List">prev</a>)</span><input type="radio" value="12114" name="oldid" id="mw-oldid-12114" /><input type="radio" value="12114" name="diff" id="mw-diff-12114" /> <a href="/index.php?title=To_do_List&amp;oldid=12114" title="To do List" class="mw-changeslist-date">18:50, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,006 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,006 bytes after change">(+78)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Completed" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Completed</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12113&amp;undo=12114" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12113" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12113&amp;oldid=12063" title="To do List">prev</a>)</span><input type="radio" value="12113" name="oldid" id="mw-oldid-12113" /><input type="radio" value="12113" name="diff" id="mw-diff-12113" /> <a href="/index.php?title=To_do_List&amp;oldid=12113" title="To do List" class="mw-changeslist-date">18:45, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,928 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,928 bytes after change">(+91)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Completed" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Completed</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=12063&amp;undo=12113" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=12063" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=12063&amp;oldid=11708" title="To do List">prev</a>)</span><input type="radio" value="12063" name="oldid" id="mw-oldid-12063" /><input type="radio" value="12063" name="diff" id="mw-diff-12063" /> <a href="/index.php?title=To_do_List&amp;oldid=12063" title="To do List" class="mw-changeslist-date">11:20, 29 May 2013</a>‎ <span class='history-user'><a href="/index.php/User:EterniaLogic" title="User:EterniaLogic" class="mw-userlink">EterniaLogic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:EterniaLogic" title="User talk:EterniaLogic">Talk</a> | <a href="/index.php/Special:Contributions/EterniaLogic" title="Special:Contributions/EterniaLogic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,837 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,837 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=11708&amp;undo=12063" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=11708" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=11708&amp;oldid=11554" title="To do List">prev</a>)</span><input type="radio" value="11708" name="oldid" id="mw-oldid-11708" /><input type="radio" value="11708" name="diff" id="mw-diff-11708" /> <a href="/index.php?title=To_do_List&amp;oldid=11708" title="To do List" class="mw-changeslist-date">16:16, 11 March 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,814 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,814 bytes after change">(+113)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> prep for shipyards</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=11554&amp;undo=11708" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=11554" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=11554&amp;oldid=11545" title="To do List">prev</a>)</span><input type="radio" value="11554" name="oldid" id="mw-oldid-11554" /><input type="radio" value="11554" name="diff" id="mw-diff-11554" /> <a href="/index.php?title=To_do_List&amp;oldid=11554" title="To do List" class="mw-changeslist-date">12:37, 4 February 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Anemone221&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Anemone221 (page does not exist)">Anemone221</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Anemone221&amp;action=edit&amp;redlink=1" class="new" title="User talk:Anemone221 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Anemone221" title="Special:Contributions/Anemone221">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,701 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,701 bytes after change">(+64)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=11545&amp;undo=11554" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=11545" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=11545&amp;oldid=11452" title="To do List">prev</a>)</span><input type="radio" value="11545" name="oldid" id="mw-oldid-11545" /><input type="radio" value="11545" name="diff" id="mw-diff-11545" /> <a href="/index.php?title=To_do_List&amp;oldid=11545" title="To do List" class="mw-changeslist-date">18:13, 30 January 2013</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,637 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,637 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> link marine to do</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=11452&amp;undo=11545" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=11452" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=11452&amp;oldid=8830" title="To do List">prev</a>)</span><input type="radio" value="11452" name="oldid" id="mw-oldid-11452" /><input type="radio" value="11452" name="diff" id="mw-diff-11452" /> <a href="/index.php?title=To_do_List&amp;oldid=11452" title="To do List" class="mw-changeslist-date">19:42, 24 December 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:Limbes&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Limbes (page does not exist)">Limbes</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Limbes&amp;action=edit&amp;redlink=1" class="new" title="User talk:Limbes (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Limbes" title="Special:Contributions/Limbes">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,633 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,633 bytes after change">(+72)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8830&amp;undo=11452" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8830" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8830&amp;oldid=8772" title="To do List">prev</a>)</span><input type="radio" value="8830" name="oldid" id="mw-oldid-8830" /><input type="radio" value="8830" name="diff" id="mw-diff-8830" /> <a href="/index.php?title=To_do_List&amp;oldid=8830" title="To do List" class="mw-changeslist-date">00:28, 10 March 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,561 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,561 bytes after change">(-172)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8772&amp;undo=8830" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8772" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8772&amp;oldid=8771" title="To do List">prev</a>)</span><input type="radio" value="8772" name="oldid" id="mw-oldid-8772" /><input type="radio" value="8772" name="diff" id="mw-diff-8772" /> <a href="/index.php?title=To_do_List&amp;oldid=8772" title="To do List" class="mw-changeslist-date">00:26, 26 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,733 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,733 bytes after change">(+86)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8771&amp;undo=8772" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8771" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8771&amp;oldid=8722" title="To do List">prev</a>)</span><input type="radio" value="8771" name="oldid" id="mw-oldid-8771" /><input type="radio" value="8771" name="diff" id="mw-diff-8771" /> <a href="/index.php?title=To_do_List&amp;oldid=8771" title="To do List" class="mw-changeslist-date">00:26, 26 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,647 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,647 bytes after change">(+55)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8722&amp;undo=8771" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8722" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8722&amp;oldid=8544" title="To do List">prev</a>)</span><input type="radio" value="8722" name="oldid" id="mw-oldid-8722" /><input type="radio" value="8722" name="diff" id="mw-diff-8722" /> <a href="/index.php?title=To_do_List&amp;oldid=8722" title="To do List" class="mw-changeslist-date">13:48, 24 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,592 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,592 bytes after change">(+28)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(universe map)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8544&amp;undo=8722" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8544" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8544&amp;oldid=8543" title="To do List">prev</a>)</span><input type="radio" value="8544" name="oldid" id="mw-oldid-8544" /><input type="radio" value="8544" name="diff" id="mw-diff-8544" /> <a href="/index.php?title=To_do_List&amp;oldid=8544" title="To do List" class="mw-changeslist-date">03:19, 12 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,564 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,564 bytes after change">(+318)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8543&amp;undo=8544" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8543" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8543&amp;oldid=8542" title="To do List">prev</a>)</span><input type="radio" value="8543" name="oldid" id="mw-oldid-8543" /><input type="radio" value="8543" name="diff" id="mw-diff-8543" /> <a href="/index.php?title=To_do_List&amp;oldid=8543" title="To do List" class="mw-changeslist-date">03:11, 12 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,246 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,246 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8542&amp;undo=8543" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8542" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8542&amp;oldid=8540" title="To do List">prev</a>)</span><input type="radio" value="8542" name="oldid" id="mw-oldid-8542" /><input type="radio" value="8542" name="diff" id="mw-diff-8542" /> <a href="/index.php?title=To_do_List&amp;oldid=8542" title="To do List" class="mw-changeslist-date">03:11, 12 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,246 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,246 bytes after change">(+173)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8540&amp;undo=8542" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8540" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8540&amp;oldid=8539" title="To do List">prev</a>)</span><input type="radio" value="8540" name="oldid" id="mw-oldid-8540" /><input type="radio" value="8540" name="diff" id="mw-diff-8540" /> <a href="/index.php?title=To_do_List&amp;oldid=8540" title="To do List" class="mw-changeslist-date">03:05, 12 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,073 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,073 bytes after change">(+144)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8539&amp;undo=8540" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8539" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8539&amp;oldid=8521" title="To do List">prev</a>)</span><input type="radio" value="8539" name="oldid" id="mw-oldid-8539" /><input type="radio" value="8539" name="diff" id="mw-diff-8539" /> <a href="/index.php?title=To_do_List&amp;oldid=8539" title="To do List" class="mw-changeslist-date">02:57, 12 February 2012</a>‎ <span class='history-user'><a href="/index.php?title=User:SaniK&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SaniK (page does not exist)">SaniK</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:SaniK" title="User talk:SaniK">Talk</a> | <a href="/index.php/Special:Contributions/SaniK" title="Special:Contributions/SaniK">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,929 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,929 bytes after change">(+219)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8521&amp;undo=8539" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8521" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8521&amp;oldid=8520" title="To do List">prev</a>)</span><input type="radio" value="8521" name="oldid" id="mw-oldid-8521" /><input type="radio" value="8521" name="diff" id="mw-diff-8521" /> <a href="/index.php?title=To_do_List&amp;oldid=8521" title="To do List" class="mw-changeslist-date">02:58, 11 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,710 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,710 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> link universe map. in case readers didn&#039;t know where to find it.</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=8520&amp;undo=8521" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=8520" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=8520&amp;oldid=7152" title="To do List">prev</a>)</span><input type="radio" value="8520" name="oldid" id="mw-oldid-8520" /><input type="radio" value="8520" name="diff" id="mw-diff-8520" /> <a href="/index.php?title=To_do_List&amp;oldid=8520" title="To do List" class="mw-changeslist-date">02:57, 11 February 2012</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,706 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,706 bytes after change">(+142)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> universe map</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=7152&amp;undo=8520" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=7152" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=7152&amp;oldid=5870" title="To do List">prev</a>)</span><input type="radio" value="7152" name="oldid" id="mw-oldid-7152" /><input type="radio" value="7152" name="diff" id="mw-diff-7152" /> <a href="/index.php?title=To_do_List&amp;oldid=7152" title="To do List" class="mw-changeslist-date">06:52, 6 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/24.128.97.43" title="Special:Contributions/24.128.97.43" class="mw-userlink">24.128.97.43</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:24.128.97.43&amp;action=edit&amp;redlink=1" class="new" title="User talk:24.128.97.43 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,564 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,564 bytes after change">(+163)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span>  added a request for image uploading</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=5870&amp;undo=7152" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=5870" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=5870&amp;oldid=5206" title="To do List">prev</a>)</span><input type="radio" value="5870" name="oldid" id="mw-oldid-5870" /><input type="radio" value="5870" name="diff" id="mw-diff-5870" /> <a href="/index.php?title=To_do_List&amp;oldid=5870" title="To do List" class="mw-changeslist-date">15:01, 28 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,401 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,401 bytes after change">(+515)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(stub section)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=5206&amp;undo=5870" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=5206" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=5206&amp;oldid=4553" title="To do List">prev</a>)</span><input type="radio" value="5206" name="oldid" id="mw-oldid-5206" /><input type="radio" value="5206" name="diff" id="mw-diff-5206" /> <a href="/index.php?title=To_do_List&amp;oldid=5206" title="To do List" class="mw-changeslist-date">01:04, 10 February 2011</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,886 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,886 bytes after change">(+89)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(moved basic wares to complete)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=4553&amp;undo=5206" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=4553" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=4553&amp;oldid=3849" title="To do List">prev</a>)</span><input type="radio" value="4553" name="oldid" id="mw-oldid-4553" /><input type="radio" value="4553" name="diff" id="mw-diff-4553" /> <a href="/index.php?title=To_do_List&amp;oldid=4553" title="To do List" class="mw-changeslist-date">05:27, 1 December 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:EmperorJon&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:EmperorJon (page does not exist)">EmperorJon</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:EmperorJon&amp;action=edit&amp;redlink=1" class="new" title="User talk:EmperorJon (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/EmperorJon" title="Special:Contributions/EmperorJon">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,797 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,797 bytes after change">(+34)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=3849&amp;undo=4553" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=3849" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=3849&amp;oldid=2996" title="To do List">prev</a>)</span><input type="radio" value="3849" name="oldid" id="mw-oldid-3849" /><input type="radio" value="3849" name="diff" id="mw-diff-3849" /> <a href="/index.php?title=To_do_List&amp;oldid=3849" title="To do List" class="mw-changeslist-date">15:49, 30 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,763 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,763 bytes after change">(+54)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=2996&amp;undo=3849" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=2996" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=2996&amp;oldid=2457" title="To do List">prev</a>)</span><input type="radio" value="2996" name="oldid" id="mw-oldid-2996" /><input type="radio" value="2996" name="diff" id="mw-diff-2996" /> <a href="/index.php?title=To_do_List&amp;oldid=2996" title="To do List" class="mw-changeslist-date">18:36, 15 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,709 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,709 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(updated sectors, all sectors have basic form stubs.)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=2457&amp;undo=2996" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=2457" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=2457&amp;oldid=1627" title="To do List">prev</a>)</span><input type="radio" value="2457" name="oldid" id="mw-oldid-2457" /><input type="radio" value="2457" name="diff" id="mw-diff-2457" /> <a href="/index.php?title=To_do_List&amp;oldid=2457" title="To do List" class="mw-changeslist-date">17:07, 7 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,685 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,685 bytes after change">(+55)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(new stuff, moved ship pages to complete)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=1627&amp;undo=2457" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=1627" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=1627&amp;oldid=1292" title="To do List">prev</a>)</span><input type="radio" value="1627" name="oldid" id="mw-oldid-1627" /><input type="radio" value="1627" name="diff" id="mw-diff-1627" /> <a href="/index.php?title=To_do_List&amp;oldid=1627" title="To do List" class="mw-changeslist-date">12:47, 27 September 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/216.30.171.130" title="Special:Contributions/216.30.171.130" class="mw-userlink">216.30.171.130</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:216.30.171.130&amp;action=edit&amp;redlink=1" class="new" title="User talk:216.30.171.130 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,630 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,630 bytes after change">(+49)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> docking</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=1292&amp;undo=1627" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=1292" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=1292&amp;oldid=1093" title="To do List">prev</a>)</span><input type="radio" value="1292" name="oldid" id="mw-oldid-1292" /><input type="radio" value="1292" name="diff" id="mw-diff-1292" /> <a href="/index.php?title=To_do_List&amp;oldid=1292" title="To do List" class="mw-changeslist-date">17:16, 21 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,581 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,581 bytes after change">(+147)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(update completed tasks.)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=1093&amp;undo=1292" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=1093" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=1093&amp;oldid=1092" title="To do List">prev</a>)</span><input type="radio" value="1093" name="oldid" id="mw-oldid-1093" /><input type="radio" value="1093" name="diff" id="mw-diff-1093" /> <a href="/index.php?title=To_do_List&amp;oldid=1093" title="To do List" class="mw-changeslist-date">19:15, 14 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,434 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,434 bytes after change">(+65)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#Completed" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">Completed: </span> added weapon list with advisement</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=1092&amp;undo=1093" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=1092" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=1092&amp;oldid=967" title="To do List">prev</a>)</span><input type="radio" value="1092" name="oldid" id="mw-oldid-1092" /><input type="radio" value="1092" name="diff" id="mw-diff-1092" /> <a href="/index.php?title=To_do_List&amp;oldid=1092" title="To do List" class="mw-changeslist-date">19:14, 14 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,369 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,369 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> updated weapon list todo</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=967&amp;undo=1092" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=967" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=967&amp;oldid=966" title="To do List">prev</a>)</span><input type="radio" value="967" name="oldid" id="mw-oldid-967" /><input type="radio" value="967" name="diff" id="mw-diff-967" /> <a href="/index.php?title=To_do_List&amp;oldid=967" title="To do List" class="mw-changeslist-date">14:04, 2 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,371 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="1,371 bytes after change">(-1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> removed extra line</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=966&amp;undo=967" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=966" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=966&amp;oldid=883" title="To do List">prev</a>)</span><input type="radio" value="966" name="oldid" id="mw-oldid-966" /><input type="radio" value="966" name="diff" id="mw-diff-966" /> <a href="/index.php?title=To_do_List&amp;oldid=966" title="To do List" class="mw-changeslist-date">14:03, 2 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,372 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,372 bytes after change">(+81)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do: </span> weapons update</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=883&amp;undo=966" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=883" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=883&amp;oldid=722" title="To do List">prev</a>)</span><input type="radio" value="883" name="oldid" id="mw-oldid-883" /><input type="radio" value="883" name="diff" id="mw-diff-883" /> <a href="/index.php?title=To_do_List&amp;oldid=883" title="To do List" class="mw-changeslist-date">16:39, 22 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,291 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,291 bytes after change">(+336)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=722&amp;undo=883" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=722" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=722&amp;oldid=604" title="To do List">prev</a>)</span><input type="radio" value="722" name="oldid" id="mw-oldid-722" /><input type="radio" value="722" name="diff" id="mw-diff-722" /> <a href="/index.php?title=To_do_List&amp;oldid=722" title="To do List" class="mw-changeslist-date">15:05, 7 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(955 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="955 bytes after change">(+100)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/To_do_List#To_Do" title="To do List">→</a>‎<span dir="auto"><span class="autocomment">To Do</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=604&amp;undo=722" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=604" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=604&amp;oldid=123" title="To do List">prev</a>)</span><input type="radio" value="604" name="oldid" id="mw-oldid-604" /><input type="radio" value="604" name="diff" id="mw-diff-604" /> <a href="/index.php?title=To_do_List&amp;oldid=604" title="To do List" class="mw-changeslist-date">14:37, 28 June 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(855 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="855 bytes after change">(+32)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(separated the completed items from incomplete. added headers.)</span> (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=123&amp;undo=604" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=123" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=123&amp;oldid=103" title="To do List">prev</a>)</span><input type="radio" value="123" name="oldid" id="mw-oldid-123" /><input type="radio" value="123" name="diff" id="mw-diff-123" /> <a href="/index.php?title=To_do_List&amp;oldid=123" title="To do List" class="mw-changeslist-date">16:26, 3 May 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/212.130.113.35" title="Special:Contributions/212.130.113.35" class="mw-userlink">212.130.113.35</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:212.130.113.35&amp;action=edit&amp;redlink=1" class="new" title="User talk:212.130.113.35 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(823 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="823 bytes after change">(+94)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=103&amp;undo=123" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=103" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=103&amp;oldid=102" title="To do List">prev</a>)</span><input type="radio" value="103" name="oldid" id="mw-oldid-103" /><input type="radio" value="103" name="diff" id="mw-diff-103" /> <a href="/index.php?title=To_do_List&amp;oldid=103" title="To do List" class="mw-changeslist-date">09:08, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(729 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="729 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=102&amp;undo=103" title="To do List">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=To_do_List&amp;diff=13001&amp;oldid=102" title="To do List">cur</a> | <a href="/index.php?title=To_do_List&amp;diff=102&amp;oldid=101" title="To do List">prev</a>)</span><input type="radio" value="102" name="oldid" id="mw-oldid-102" /><input type="radio" value="102" name="diff" id="mw-diff-102" /> <a href="/index.php?title=To_do_List&amp;oldid=102" title="To do List" class="mw-changeslist-date">09:07, 2 May 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Alien_ND&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Alien ND (page does not exist)">Alien ND</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Alien_ND&amp;action=edit&amp;redlink=1" class="new" title="User talk:Alien ND (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Alien_ND" title="Special:Contributions/Alien ND">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(729 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="729 bytes after change">(-97)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=To_do_List&amp;action=edit&amp;undoafter=101&amp;undo=102" title="To do List">undo</a></span>)</li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form>(newest | <a href="/index.php?title=To_do_List&amp;dir=prev&amp;action=history" title="To do List" rel="last" class="mw-lastlink">oldest</a>) View (newer 50  |  <a href="/index.php?title=To_do_List&amp;offset=20100502140727&amp;action=history" title="To do List" rel="next" class="mw-nextlink">older 50</a>) (<a href="/index.php?title=To_do_List&amp;offset=&amp;limit=20&amp;action=history" title="To do List" class="mw-numlink">20</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=50&amp;action=history" title="To do List" class="mw-numlink">50</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=100&amp;action=history" title="To do List" class="mw-numlink">100</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=250&amp;action=history" title="To do List" class="mw-numlink">250</a> | <a href="/index.php?title=To_do_List&amp;offset=&amp;limit=500&amp;action=history" title="To do List" class="mw-numlink">500</a>)</div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/To_do_List">http://x3wiki.com/index.php/To_do_List</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/To_do_List" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk"><a href="/index.php/Talk:To_do_List" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=To_do_List&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=To_do_List&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=To+do+List&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=To+do+List&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/To_do_List" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/To_do_List" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=To_do_List&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=To_do_List&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.459 secs. --></body></html>