<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" /><title>Revision history of "Spitfyre" - X3 Wiki</title>
<meta name="generator" content="MediaWiki 1.22.6" />
<meta name="robots" content="noindex,nofollow" />
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Spitfyre&amp;action=edit" />
<link rel="edit" title="Edit" href="/index.php?title=Spitfyre&amp;action=edit" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)" />
<link rel="EditURI" type="application/rsd+xml" href="http://x3wiki.com/api.php?action=rsd" />
<link rel="alternate" type="application/atom+xml" title="&quot;Spitfyre&quot; Atom feed" href="/index.php?title=Spitfyre&amp;feed=atom&amp;action=history" />
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="stylesheet" href="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.monobook&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<style>a:lang(ar),a:lang(ckb),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: dailystunt_wiki:resourceloader:filter:minify-css:7:bcf2b4205b52540e110d3a777baf7453 */</style>

<script src="http://x3wiki.com/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Spitfyre","wgTitle":"Spitfyre","wgCurRevisionId":14111,"wgRevisionId":0,"wgArticleId":285,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Spitfyre","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function(){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"disablesuggest":0,"editfont":"default","editondblclick":0,"editsection":1,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":0,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"justify":0,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nocache":0,"noconvertlink":0,"norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rememberpassword":0,"rows":25,"searchlimit":20,"showhiddencats":0,"shownumberswatching":1,"showtoc":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"vector-simplesearch":1,"watchcreations":0,"watchdefault":0,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0
,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function(){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: dailystunt_wiki:resourceloader:filter:minify-js:7:68471340157e99d9e2eb390b7623161a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Spitfyre skin-monobook action-history">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
	<div id="siteNotice"><!-- centralNotice loads here --></div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>


	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Revision history of "Spitfyre"</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From X3 Wiki</div>
		<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Spitfyre" title="Special:Log">View logs for this page</a></div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Spitfyre" name="title" />
<input type="hidden" value="history" name="action" />
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2016" name="year" /> <label for="month">From month (and earlier):</label> <select id="month" name="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Go" />
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <b>(cur)</b> = difference with latest revision, <b>(prev)</b> = difference with preceding revision, <b>m</b> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Spitfyre" name="title" />
<input type="hidden" value="historysubmit" name="action" />
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=14007" title="Spitfyre">prev</a>)</span><input type="radio" value="14111" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="14111" checked="checked" name="diff" id="mw-diff-14111" /> <a href="/index.php?title=Spitfyre&amp;oldid=14111" title="Spitfyre" class="mw-changeslist-date">11:55, 30 December 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,862 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,862 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Adding Aldrin Navbox)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=14007&amp;undo=14111" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=14007" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=14007&amp;oldid=12732" title="Spitfyre">prev</a>)</span><input type="radio" value="14007" checked="checked" name="oldid" id="mw-oldid-14007" /><input type="radio" value="14007" name="diff" id="mw-diff-14007" /> <a href="/index.php?title=Spitfyre&amp;oldid=14007" title="Spitfyre" class="mw-changeslist-date">15:43, 24 November 2013</a>‎ <span class='history-user'><a href="/index.php?title=User:Akruppa&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Akruppa (page does not exist)">Akruppa</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Akruppa&amp;action=edit&amp;redlink=1" class="new" title="User talk:Akruppa (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Akruppa" title="Special:Contributions/Akruppa">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,844 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,844 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Rear turret takes EMPC, oddly enough)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=12732&amp;undo=14007" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=12732" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=12732&amp;oldid=12731" title="Spitfyre">prev</a>)</span><input type="radio" value="12732" name="oldid" id="mw-oldid-12732" /><input type="radio" value="12732" name="diff" id="mw-diff-12732" /> <a href="/index.php?title=Spitfyre&amp;oldid=12732" title="Spitfyre" class="mw-changeslist-date">06:32, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,844 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,844 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#See_Also" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> typo</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=12731&amp;undo=12732" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=12731" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=12731&amp;oldid=12730" title="Spitfyre">prev</a>)</span><input type="radio" value="12731" name="oldid" id="mw-oldid-12731" /><input type="radio" value="12731" name="diff" id="mw-diff-12731" /> <a href="/index.php?title=Spitfyre&amp;oldid=12731" title="Spitfyre" class="mw-changeslist-date">06:31, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,843 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,843 bytes after change">(-17)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#See_Also" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> cleanup</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=12730&amp;undo=12731" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=12730" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=12730&amp;oldid=11344" title="Spitfyre">prev</a>)</span><input type="radio" value="12730" name="oldid" id="mw-oldid-12730" /><input type="radio" value="12730" name="diff" id="mw-diff-12730" /> <a href="/index.php?title=Spitfyre&amp;oldid=12730" title="Spitfyre" class="mw-changeslist-date">06:31, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">Talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,860 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,860 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#See_Also" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> link to more directly related ship</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=11344&amp;undo=12730" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=11344" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=11344&amp;oldid=11343" title="Spitfyre">prev</a>)</span><input type="radio" value="11344" name="oldid" id="mw-oldid-11344" /><input type="radio" value="11344" name="diff" id="mw-diff-11344" /> <a href="/index.php?title=Spitfyre&amp;oldid=11344" title="Spitfyre" class="mw-changeslist-date">07:30, 11 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,856 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,856 bytes after change">(+11)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Combat" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=11343&amp;undo=11344" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=11343" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=11343&amp;oldid=11342" title="Spitfyre">prev</a>)</span><input type="radio" value="11343" name="oldid" id="mw-oldid-11343" /><input type="radio" value="11343" name="diff" id="mw-diff-11343" /> <a href="/index.php?title=Spitfyre&amp;oldid=11343" title="Spitfyre" class="mw-changeslist-date">07:30, 11 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,845 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,845 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Combat" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=11342&amp;undo=11343" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=11342" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=11342&amp;oldid=11341" title="Spitfyre">prev</a>)</span><input type="radio" value="11342" name="oldid" id="mw-oldid-11342" /><input type="radio" value="11342" name="diff" id="mw-diff-11342" /> <a href="/index.php?title=Spitfyre&amp;oldid=11342" title="Spitfyre" class="mw-changeslist-date">07:28, 11 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,835 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,835 bytes after change">(+434)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Combat" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=11341&amp;undo=11342" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=11341" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=11341&amp;oldid=10626" title="Spitfyre">prev</a>)</span><input type="radio" value="11341" name="oldid" id="mw-oldid-11341" /><input type="radio" value="11341" name="diff" id="mw-diff-11341" /> <a href="/index.php?title=Spitfyre&amp;oldid=11341" title="Spitfyre" class="mw-changeslist-date">07:23, 11 December 2012</a>‎ <span class='history-user'><a href="/index.php/User:Endemantis" title="User:Endemantis" class="mw-userlink">Endemantis</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Endemantis&amp;action=edit&amp;redlink=1" class="new" title="User talk:Endemantis (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Endemantis" title="Special:Contributions/Endemantis">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,401 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,401 bytes after change">(+10)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Overview" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=10626&amp;undo=11341" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=10626" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=10626&amp;oldid=8633" title="Spitfyre">prev</a>)</span><input type="radio" value="10626" name="oldid" id="mw-oldid-10626" /><input type="radio" value="10626" name="diff" id="mw-diff-10626" /> <a href="/index.php?title=Spitfyre&amp;oldid=10626" title="Spitfyre" class="mw-changeslist-date">18:28, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,391 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,391 bytes after change">(-447)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M3 template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=8633&amp;undo=10626" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=8633" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=8633&amp;oldid=8168" title="Spitfyre">prev</a>)</span><input type="radio" value="8633" name="oldid" id="mw-oldid-8633" /><input type="radio" value="8633" name="diff" id="mw-diff-8633" /> <a href="/index.php?title=Spitfyre&amp;oldid=8633" title="Spitfyre" class="mw-changeslist-date">07:53, 17 February 2012</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/31.198.138.161" title="Special:Contributions/31.198.138.161" class="mw-userlink">31.198.138.161</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:31.198.138.161&amp;action=edit&amp;redlink=1" class="new" title="User talk:31.198.138.161 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,838 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="3,838 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=8168&amp;undo=8633" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=8168" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=8168&amp;oldid=7358" title="Spitfyre">prev</a>)</span><input type="radio" value="8168" name="oldid" id="mw-oldid-8168" /><input type="radio" value="8168" name="diff" id="mw-diff-8168" /> <a href="/index.php?title=Spitfyre&amp;oldid=8168" title="Spitfyre" class="mw-changeslist-date">04:39, 20 December 2011</a>‎ <span class='history-user'><a href="/index.php?title=User:SirDarius&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:SirDarius (page does not exist)">SirDarius</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:SirDarius&amp;action=edit&amp;redlink=1" class="new" title="User talk:SirDarius (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/SirDarius" title="Special:Contributions/SirDarius">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,838 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,838 bytes after change">(+66)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=7358&amp;undo=8168" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=7358" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=7358&amp;oldid=6847" title="Spitfyre">prev</a>)</span><input type="radio" value="7358" name="oldid" id="mw-oldid-7358" /><input type="radio" value="7358" name="diff" id="mw-diff-7358" /> <a href="/index.php?title=Spitfyre&amp;oldid=7358" title="Spitfyre" class="mw-changeslist-date">17:10, 17 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,772 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,772 bytes after change">(+615)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(cleanup; added data, category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=6847&amp;undo=7358" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=6847" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=6847&amp;oldid=4713" title="Spitfyre">prev</a>)</span><input type="radio" value="6847" name="oldid" id="mw-oldid-6847" /><input type="radio" value="6847" name="diff" id="mw-diff-6847" /> <a href="/index.php?title=Spitfyre&amp;oldid=6847" title="Spitfyre" class="mw-changeslist-date">22:34, 7 August 2011</a>‎ <span class='history-user'><a href="/index.php/User:Nepo11" title="User:Nepo11" class="mw-userlink">Nepo11</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Nepo11" title="User talk:Nepo11">Talk</a> | <a href="/index.php/Special:Contributions/Nepo11" title="Special:Contributions/Nepo11">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,157 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,157 bytes after change">(+4)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=4713&amp;undo=6847" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=4713" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=4713&amp;oldid=4647" title="Spitfyre">prev</a>)</span><input type="radio" value="4713" name="oldid" id="mw-oldid-4713" /><input type="radio" value="4713" name="diff" id="mw-diff-4713" /> <a href="/index.php?title=Spitfyre&amp;oldid=4713" title="Spitfyre" class="mw-changeslist-date">19:43, 31 December 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Unearthly&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Unearthly (page does not exist)">Unearthly</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Unearthly&amp;action=edit&amp;redlink=1" class="new" title="User talk:Unearthly (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Unearthly" title="Special:Contributions/Unearthly">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,153 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,153 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=4647&amp;undo=4713" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=4647" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=4647&amp;oldid=4639" title="Spitfyre">prev</a>)</span><input type="radio" value="4647" name="oldid" id="mw-oldid-4647" /><input type="radio" value="4647" name="diff" id="mw-diff-4647" /> <a href="/index.php?title=Spitfyre&amp;oldid=4647" title="Spitfyre" class="mw-changeslist-date">12:57, 20 December 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,138 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,138 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Combat" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span> typo</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=4639&amp;undo=4647" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=4639" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=4639&amp;oldid=3172" title="Spitfyre">prev</a>)</span><input type="radio" value="4639" name="oldid" id="mw-oldid-4639" /><input type="radio" value="4639" name="diff" id="mw-diff-4639" /> <a href="/index.php?title=Spitfyre&amp;oldid=4639" title="Spitfyre" class="mw-changeslist-date">20:03, 17 December 2010</a>‎ <span class='history-user'><a href="/index.php?title=User:Silverado&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Silverado (page does not exist)">Silverado</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Silverado&amp;action=edit&amp;redlink=1" class="new" title="User talk:Silverado (page does not exist)">Talk</a> | <a href="/index.php/Special:Contributions/Silverado" title="Special:Contributions/Silverado">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,137 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,137 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Physical_Characteristics" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Physical Characteristics</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=3172&amp;undo=4639" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=3172" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=3172&amp;oldid=3137" title="Spitfyre">prev</a>)</span><input type="radio" value="3172" name="oldid" id="mw-oldid-3172" /><input type="radio" value="3172" name="diff" id="mw-diff-3172" /> <a href="/index.php?title=Spitfyre&amp;oldid=3172" title="Spitfyre" class="mw-changeslist-date">13:57, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class='minoredit' title='This is a minor edit'>m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,135 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,135 bytes after change">(+68)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(gunslots)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=3137&amp;undo=3172" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=3137" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=3137&amp;oldid=3103" title="Spitfyre">prev</a>)</span><input type="radio" value="3137" name="oldid" id="mw-oldid-3137" /><input type="radio" value="3137" name="diff" id="mw-diff-3137" /> <a href="/index.php?title=Spitfyre&amp;oldid=3137" title="Spitfyre" class="mw-changeslist-date">18:40, 17 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,067 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="3,067 bytes after change">(-2)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=3103&amp;undo=3137" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=3103" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=3103&amp;oldid=3102" title="Spitfyre">prev</a>)</span><input type="radio" value="3103" name="oldid" id="mw-oldid-3103" /><input type="radio" value="3103" name="diff" id="mw-diff-3103" /> <a href="/index.php?title=Spitfyre&amp;oldid=3103" title="Spitfyre" class="mw-changeslist-date">18:05, 17 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,069 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,069 bytes after change">(+331)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#See_Also" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=3102&amp;undo=3103" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=3102" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=3102&amp;oldid=3101" title="Spitfyre">prev</a>)</span><input type="radio" value="3102" name="oldid" id="mw-oldid-3102" /><input type="radio" value="3102" name="diff" id="mw-diff-3102" /> <a href="/index.php?title=Spitfyre&amp;oldid=3102" title="Spitfyre" class="mw-changeslist-date">18:05, 17 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,738 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,738 bytes after change">(-112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Combat" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Combat: </span>  Error correction and abbreviation of limitations</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=3101&amp;undo=3102" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=3101" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=3101&amp;oldid=2897" title="Spitfyre">prev</a>)</span><input type="radio" value="3101" name="oldid" id="mw-oldid-3101" /><input type="radio" value="3101" name="diff" id="mw-diff-3101" /> <a href="/index.php?title=Spitfyre&amp;oldid=3101" title="Spitfyre" class="mw-changeslist-date">18:01, 17 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">Talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,850 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="2,850 bytes after change">(-18)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Spitfyre#Background" title="Spitfyre">→</a>‎<span dir="auto"><span class="autocomment">Background</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2897&amp;undo=3101" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2897" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2897&amp;oldid=2649" title="Spitfyre">prev</a>)</span><input type="radio" value="2897" name="oldid" id="mw-oldid-2897" /><input type="radio" value="2897" name="diff" id="mw-diff-2897" /> <a href="/index.php?title=Spitfyre&amp;oldid=2897" title="Spitfyre" class="mw-changeslist-date">17:52, 14 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,868 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,868 bytes after change">(+18)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2649&amp;undo=2897" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2649" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2649&amp;oldid=2648" title="Spitfyre">prev</a>)</span><input type="radio" value="2649" name="oldid" id="mw-oldid-2649" /><input type="radio" value="2649" name="diff" id="mw-diff-2649" /> <a href="/index.php?title=Spitfyre&amp;oldid=2649" title="Spitfyre" class="mw-changeslist-date">13:12, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,850 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="2,850 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2648&amp;undo=2649" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2648" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2648&amp;oldid=2647" title="Spitfyre">prev</a>)</span><input type="radio" value="2648" name="oldid" id="mw-oldid-2648" /><input type="radio" value="2648" name="diff" id="mw-diff-2648" /> <a href="/index.php?title=Spitfyre&amp;oldid=2648" title="Spitfyre" class="mw-changeslist-date">13:11, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,850 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="2,850 bytes after change">(+862)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2647&amp;undo=2648" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2647" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2647&amp;oldid=2646" title="Spitfyre">prev</a>)</span><input type="radio" value="2647" name="oldid" id="mw-oldid-2647" /><input type="radio" value="2647" name="diff" id="mw-diff-2647" /> <a href="/index.php?title=Spitfyre&amp;oldid=2647" title="Spitfyre" class="mw-changeslist-date">12:24, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,988 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,988 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2646&amp;undo=2647" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2646" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2646&amp;oldid=2645" title="Spitfyre">prev</a>)</span><input type="radio" value="2646" name="oldid" id="mw-oldid-2646" /><input type="radio" value="2646" name="diff" id="mw-diff-2646" /> <a href="/index.php?title=Spitfyre&amp;oldid=2646" title="Spitfyre" class="mw-changeslist-date">12:23, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,963 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,963 bytes after change">(+703)</strong>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=2645&amp;undo=2646" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=2645" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=2645&amp;oldid=829" title="Spitfyre">prev</a>)</span><input type="radio" value="2645" name="oldid" id="mw-oldid-2645" /><input type="radio" value="2645" name="diff" id="mw-diff-2645" /> <a href="/index.php?title=Spitfyre&amp;oldid=2645" title="Spitfyre" class="mw-changeslist-date">12:04, 9 October 2010</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/94.195.170.31" title="Special:Contributions/94.195.170.31" class="mw-userlink">94.195.170.31</a>  <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:94.195.170.31&amp;action=edit&amp;redlink=1" class="new" title="User talk:94.195.170.31 (page does not exist)">Talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,260 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,260 bytes after change">(+150)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=829&amp;undo=2645" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=829" title="Spitfyre">cur</a> | <a href="/index.php?title=Spitfyre&amp;diff=829&amp;oldid=828" title="Spitfyre">prev</a>)</span><input type="radio" value="829" name="oldid" id="mw-oldid-829" /><input type="radio" value="829" name="diff" id="mw-diff-829" /> <a href="/index.php?title=Spitfyre&amp;oldid=829" title="Spitfyre" class="mw-changeslist-date">16:04, 16 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,110 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="1,110 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(guess at gunslots)</span> (<span class="mw-history-undo"><a href="/index.php?title=Spitfyre&amp;action=edit&amp;undoafter=828&amp;undo=829" title="Spitfyre">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Spitfyre&amp;diff=14111&amp;oldid=828" title="Spitfyre">cur</a> | prev)</span><input type="radio" value="828" name="oldid" id="mw-oldid-828" /><input type="radio" value="828" name="diff" id="mw-diff-828" /> <a href="/index.php?title=Spitfyre&amp;oldid=828" title="Spitfyre" class="mw-changeslist-date">16:03, 16 July 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a>  <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">Talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,110 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,110 bytes after change">(+1,110)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(infobox stub)</span></li>
</ul>
<div><input type="submit" value="Compare selected revisions" class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" />
</div></form></div><div class="printfooter">
Retrieved from "<a href="http://x3wiki.com/index.php/Spitfyre">http://x3wiki.com/index.php/Spitfyre</a>"</div>
		<div id='catlinks' class='catlinks catlinks-allhidden'></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Spitfyre" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Spitfyre&amp;action=edit&amp;redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Spitfyre&amp;action=edit" title="You can edit this page. Please use the preview button before saving [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Spitfyre&amp;action=history" rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-createaccount"><a href="/index.php?title=Special:UserLogin&amp;returnto=Spitfyre&amp;returntoquery=action%3Dhistory&amp;type=signup">Create account</a></li>
				<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Spitfyre&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/index.php/Main_Page" style="background-image: url(http://www.x3wiki.com/x3.jpg);" title="Visit the main page"></a>
	</div>
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
				<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
				<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
				<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
				<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
				<li id="n-Races"><a href="/index.php/Races">Races</a></li>
				<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
				<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
				<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
				<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
				<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
				<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
				<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
			</ul>
		</div>
	</div>

	<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Wildstar-trial"><a href="http://www.wildstartrial.com" rel="nofollow">Wildstar trial</a></li>
				<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com" rel="nofollow">MMO Server Status</a></li>
			</ul>
		</div>
	</div>

	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>
		</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Spitfyre" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Spitfyre" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="feedlinks"><a href="/index.php?title=Spitfyre&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
				<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-info"><a href="/index.php?title=Spitfyre&amp;action=info">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
		<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
		<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
	</ul>
</div>
</div>
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.history","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"],null,true);
}</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-265105-19");
pageTracker._trackPageview();
} catch(err) {}
</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script>
<script>if(window.mw){
mw.loader.state({"site":"ready"});
}</script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><!-- Served in 0.320 secs. --></body></html>