<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Chimera" - X3 Wiki</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Chimera","wgTitle":"Chimera","wgCurRevisionId":20851,"wgRevisionId":0,"wgArticleId":360,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Chimera","wgRelevantArticleId":360,"wgRequestId":"WlQ2hlkfZokAABcLwpkAAAAM","wgIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"Geo":{"city":"","country":""},"wgNoticeProject":"wikipedia"});mw.loader.implement("user.options",function($,jQuery,require,module){mw.user.options.set({"variant":"en"});});mw.loader.implement("user.tokens",function ( $, jQuery, require, module ) {
mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});/*@nomin*/;

});mw.loader.load(["mediawiki.action.history","mediawiki.page.startup"]);});</script>
<link rel="stylesheet" href="/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.feedlink%2Chelplink%2CsectionAnchor%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.content.externallinks%7Cmediawiki.skinning.interface%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook"/>
<!--[if IE 6]><link rel="stylesheet" href="/skins/MonoBook/IE60Fixes.css?303" media="screen"/><![endif]--><!--[if IE 7]><link rel="stylesheet" href="/skins/MonoBook/IE70Fixes.css?303" media="screen"/><![endif]-->
<meta name="ResourceLoaderDynamicStyles" content=""/>
<script async="" src="/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook"></script>
<meta name="generator" content="MediaWiki 1.27.1"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="alternate" type="application/x-wiki" title="Edit" href="/index.php?title=Chimera&amp;action=edit"/>
<link rel="edit" title="Edit" href="/index.php?title=Chimera&amp;action=edit"/>
<link rel="shortcut icon" href="/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch_desc.php" title="X3 Wiki (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://www.x3wiki.com/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Chimera&quot; Atom feed" href="/index.php?title=Chimera&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="X3 Wiki Atom feed" href="/index.php?title=Special:RecentChanges&amp;feed=atom"/>
</head>
<body class="mediawiki ltr sitedir-ltr ns-0 ns-subject page-Chimera rootpage-Chimera skin-monobook action-history">
<div id="globalWrapper">
		<div id="column-content">
			<div id="content" class="mw-body" role="main">
				<a id="top"></a>
									<div id="siteNotice"><!-- centralNotice loads here --></div>
				<div class="mw-indicators">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="//meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-7526491584299412",
    enable_page_level_ads: true
  });
</script>

<!-- X3 wiki -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-7526491584299412"
     data-ad-slot="4173455889"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
				<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Chimera"</h1>
				
				<div id="bodyContent" class="mw-body-content">
					<div id="siteSub">From X3 Wiki</div>
					<div id="contentSub"><a href="/index.php?title=Special:Log&amp;page=Chimera" title="Special:Log">View logs for this page</a></div>
										<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

					<!-- start content -->
					<div id="mw-content-text"><form action="/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Browse history</legend>
<input type="hidden" value="Chimera" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2018" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select>&#160;<input type="submit" value="Show"/>
</fieldset></form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>
<form action="/index.php" id="mw-history-compare">
<input type="hidden" value="Chimera" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li><span class="mw-history-histlinks">(cur | <a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=16419" title="Chimera">prev</a>)</span><input type="radio" value="20851" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="20851" checked="checked" name="diff" id="mw-diff-20851" /> <a href="/index.php?title=Chimera&amp;oldid=20851" title="Chimera" class="mw-changeslist-date">10:03, 25 November 2017</a>‎ <span class='history-user'><a href="/index.php?title=User:Halavus&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Halavus (page does not exist)">Halavus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Halavus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Halavus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Halavus" title="Special:Contributions/Halavus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,458 bytes)</span> <span dir="ltr" class="mw-plusminus-null" title="5,458 bytes after change">(0)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(minspeed corrected to 72.8)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=16419&amp;undo=20851" title="&quot;Undo&quot; reverts this edit and opens the edit form in preview mode. It allows adding a reason in the summary.">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=16419" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=16419&amp;oldid=16418" title="Chimera">prev</a>)</span><input type="radio" value="16419" checked="checked" name="oldid" id="mw-oldid-16419" /><input type="radio" value="16419" name="diff" id="mw-diff-16419" /> <a href="/index.php?title=Chimera&amp;oldid=16419" title="Chimera" class="mw-changeslist-date">02:57, 25 August 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,458 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,458 bytes after change">(+63)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Combat" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=16418&amp;undo=16419" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=16418" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=16418&amp;oldid=16417" title="Chimera">prev</a>)</span><input type="radio" value="16418" name="oldid" id="mw-oldid-16418" /><input type="radio" value="16418" name="diff" id="mw-diff-16418" /> <a href="/index.php?title=Chimera&amp;oldid=16418" title="Chimera" class="mw-changeslist-date">02:55, 25 August 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,395 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,395 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Enhanced_Chimera" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Enhanced Chimera</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=16417&amp;undo=16418" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=16417" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=16417&amp;oldid=14624" title="Chimera">prev</a>)</span><input type="radio" value="16417" name="oldid" id="mw-oldid-16417" /><input type="radio" value="16417" name="diff" id="mw-diff-16417" /> <a href="/index.php?title=Chimera&amp;oldid=16417" title="Chimera" class="mw-changeslist-date">02:54, 25 August 2014</a>‎ <span class='history-user'><a href="/index.php?title=User:Osarakman88&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Osarakman88 (page does not exist)">Osarakman88</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Osarakman88&amp;action=edit&amp;redlink=1" class="new" title="User talk:Osarakman88 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Osarakman88" title="Special:Contributions/Osarakman88">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,372 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,372 bytes after change">(+35)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=14624&amp;undo=16417" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=14624" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=14624&amp;oldid=13307" title="Chimera">prev</a>)</span><input type="radio" value="14624" name="oldid" id="mw-oldid-14624" /><input type="radio" value="14624" name="diff" id="mw-diff-14624" /> <a href="/index.php?title=Chimera&amp;oldid=14624" title="Chimera" class="mw-changeslist-date">17:09, 24 February 2014</a>‎ <span class='history-user'><a href="/index.php/User:Knighster35" title="User:Knighster35" class="mw-userlink">Knighster35</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Knighster35" title="User talk:Knighster35">talk</a> | <a href="/index.php/Special:Contributions/Knighster35" title="Special:Contributions/Knighster35">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,337 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,337 bytes after change">(+19)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(add a Split navbox)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=13307&amp;undo=14624" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=13307" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=13307&amp;oldid=12738" title="Chimera">prev</a>)</span><input type="radio" value="13307" name="oldid" id="mw-oldid-13307" /><input type="radio" value="13307" name="diff" id="mw-diff-13307" /> <a href="/index.php?title=Chimera&amp;oldid=13307" title="Chimera" class="mw-changeslist-date">12:21, 1 August 2013</a>‎ <span class='history-user'><a href="/index.php/User:Korlus" title="User:Korlus" class="mw-userlink">Korlus</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Korlus&amp;action=edit&amp;redlink=1" class="new" title="User talk:Korlus (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Korlus" title="Special:Contributions/Korlus">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,318 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,318 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(Correcting link)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=12738&amp;undo=13307" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=12738" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=12738&amp;oldid=12702" title="Chimera">prev</a>)</span><input type="radio" value="12738" name="oldid" id="mw-oldid-12738" /><input type="radio" value="12738" name="diff" id="mw-diff-12738" /> <a href="/index.php?title=Chimera&amp;oldid=12738" title="Chimera" class="mw-changeslist-date">12:38, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,317 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,317 bytes after change">(+22)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(reintroduce related reference)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=12702&amp;undo=12738" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=12702" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=12702&amp;oldid=10637" title="Chimera">prev</a>)</span><input type="radio" value="12702" name="oldid" id="mw-oldid-12702" /><input type="radio" value="12702" name="diff" id="mw-diff-12702" /> <a href="/index.php?title=Chimera&amp;oldid=12702" title="Chimera" class="mw-changeslist-date">12:12, 11 June 2013</a>‎ <span class='history-user'><a href="/index.php/User:Gene" title="User:Gene" class="mw-userlink">Gene</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Gene" title="User talk:Gene">talk</a> | <a href="/index.php/Special:Contributions/Gene" title="Special:Contributions/Gene">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,295 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,295 bytes after change">(-38)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#See_Also" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">See Also: </span> no need for special mention, no direct relation other than race and can just click on race link to see all ships</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=10637&amp;undo=12702" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=10637" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=10637&amp;oldid=10493" title="Chimera">prev</a>)</span><input type="radio" value="10637" name="oldid" id="mw-oldid-10637" /><input type="radio" value="10637" name="diff" id="mw-diff-10637" /> <a href="/index.php?title=Chimera&amp;oldid=10637" title="Chimera" class="mw-changeslist-date">00:43, 16 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,333 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="5,333 bytes after change">(-267)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added M3+ template)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=10493&amp;undo=10637" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=10493" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=10493&amp;oldid=7418" title="Chimera">prev</a>)</span><input type="radio" value="10493" name="oldid" id="mw-oldid-10493" /><input type="radio" value="10493" name="diff" id="mw-diff-10493" /> <a href="/index.php?title=Chimera&amp;oldid=10493" title="Chimera" class="mw-changeslist-date">05:54, 15 October 2012</a>‎ <span class='history-user'><a href="/index.php/User:Skald359" title="User:Skald359" class="mw-userlink">Skald359</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Skald359&amp;action=edit&amp;redlink=1" class="new" title="User talk:Skald359 (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Skald359" title="Special:Contributions/Skald359">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,600 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,600 bytes after change">(+494)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added &#039;Equipment&#039; missiles)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=7418&amp;undo=10493" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=7418" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=7418&amp;oldid=7158" title="Chimera">prev</a>)</span><input type="radio" value="7418" name="oldid" id="mw-oldid-7418" /><input type="radio" value="7418" name="diff" id="mw-diff-7418" /> <a href="/index.php?title=Chimera&amp;oldid=7418" title="Chimera" class="mw-changeslist-date">00:31, 21 September 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(5,106 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="5,106 bytes after change">(+220)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(minor cleanup; added category)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=7158&amp;undo=7418" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=7158" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=7158&amp;oldid=7157" title="Chimera">prev</a>)</span><input type="radio" value="7158" name="oldid" id="mw-oldid-7158" /><input type="radio" value="7158" name="diff" id="mw-diff-7158" /> <a href="/index.php?title=Chimera&amp;oldid=7158" title="Chimera" class="mw-changeslist-date">19:51, 8 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/78.145.166.70" title="Special:Contributions/78.145.166.70" class="mw-userlink mw-anonuserlink">78.145.166.70</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:78.145.166.70&amp;action=edit&amp;redlink=1" class="new" title="User talk:78.145.166.70 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,886 bytes)</span> <span dir="ltr" class="mw-plusminus-neg" title="4,886 bytes after change">(-23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Overview" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=7157&amp;undo=7158" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=7157" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=7157&amp;oldid=6844" title="Chimera">prev</a>)</span><input type="radio" value="7157" name="oldid" id="mw-oldid-7157" /><input type="radio" value="7157" name="diff" id="mw-diff-7157" /> <a href="/index.php?title=Chimera&amp;oldid=7157" title="Chimera" class="mw-changeslist-date">11:11, 8 September 2011</a>‎ <span class='history-user'><a href="/index.php/Special:Contributions/86.12.164.5" title="Special:Contributions/86.12.164.5" class="mw-userlink mw-anonuserlink">86.12.164.5</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:86.12.164.5&amp;action=edit&amp;redlink=1" class="new" title="User talk:86.12.164.5 (page does not exist)">talk</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,909 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,909 bytes after change">(+23)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Overview" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=6844&amp;undo=7157" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=6844" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=6844&amp;oldid=6301" title="Chimera">prev</a>)</span><input type="radio" value="6844" name="oldid" id="mw-oldid-6844" /><input type="radio" value="6844" name="diff" id="mw-diff-6844" /> <a href="/index.php?title=Chimera&amp;oldid=6844" title="Chimera" class="mw-changeslist-date">04:28, 8 August 2011</a>‎ <span class='history-user'><a href="/index.php/User:Nepo11" title="User:Nepo11" class="mw-userlink">Nepo11</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Nepo11" title="User talk:Nepo11">talk</a> | <a href="/index.php/Special:Contributions/Nepo11" title="Special:Contributions/Nepo11">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,886 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,886 bytes after change">(+6)</span>‎ <span class="mw-changeslist-separator">. .</span>  (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=6301&amp;undo=6844" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=6301" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=6301&amp;oldid=6192" title="Chimera">prev</a>)</span><input type="radio" value="6301" name="oldid" id="mw-oldid-6301" /><input type="radio" value="6301" name="diff" id="mw-diff-6301" /> <a href="/index.php?title=Chimera&amp;oldid=6301" title="Chimera" class="mw-changeslist-date">15:28, 18 May 2011</a>‎ <span class='history-user'><a href="/index.php/User:Anarchistica" title="User:Anarchistica" class="mw-userlink">Anarchistica</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:Anarchistica&amp;action=edit&amp;redlink=1" class="new" title="User talk:Anarchistica (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/Anarchistica" title="Special:Contributions/Anarchistica">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,880 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,880 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Availability" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Availability</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=6192&amp;undo=6301" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=6192" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=6192&amp;oldid=5742" title="Chimera">prev</a>)</span><input type="radio" value="6192" name="oldid" id="mw-oldid-6192" /><input type="radio" value="6192" name="diff" id="mw-diff-6192" /> <a href="/index.php?title=Chimera&amp;oldid=6192" title="Chimera" class="mw-changeslist-date">23:12, 11 May 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,879 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,879 bytes after change">(+95)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Combat" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5742&amp;undo=6192" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5742" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5742&amp;oldid=5741" title="Chimera">prev</a>)</span><input type="radio" value="5742" name="oldid" id="mw-oldid-5742" /><input type="radio" value="5742" name="diff" id="mw-diff-5742" /> <a href="/index.php?title=Chimera&amp;oldid=5742" title="Chimera" class="mw-changeslist-date">13:52, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,784 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,784 bytes after change">(+43)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Combat" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5741&amp;undo=5742" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5741" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5741&amp;oldid=5740" title="Chimera">prev</a>)</span><input type="radio" value="5741" name="oldid" id="mw-oldid-5741" /><input type="radio" value="5741" name="diff" id="mw-diff-5741" /> <a href="/index.php?title=Chimera&amp;oldid=5741" title="Chimera" class="mw-changeslist-date">13:52, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,741 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,741 bytes after change">(+2)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Suggested_Roles" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5740&amp;undo=5741" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5740" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5740&amp;oldid=5738" title="Chimera">prev</a>)</span><input type="radio" value="5740" name="oldid" id="mw-oldid-5740" /><input type="radio" value="5740" name="diff" id="mw-diff-5740" /> <a href="/index.php?title=Chimera&amp;oldid=5740" title="Chimera" class="mw-changeslist-date">13:52, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,739 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,739 bytes after change">(+25)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Overview" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5738&amp;undo=5740" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5738" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5738&amp;oldid=5737" title="Chimera">prev</a>)</span><input type="radio" value="5738" name="oldid" id="mw-oldid-5738" /><input type="radio" value="5738" name="diff" id="mw-diff-5738" /> <a href="/index.php?title=Chimera&amp;oldid=5738" title="Chimera" class="mw-changeslist-date">07:02, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,714 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,714 bytes after change">(+1)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(fixed priceblock on Enhanced Chimera)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5737&amp;undo=5738" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5737" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5737&amp;oldid=5736" title="Chimera">prev</a>)</span><input type="radio" value="5737" name="oldid" id="mw-oldid-5737" /><input type="radio" value="5737" name="diff" id="mw-diff-5737" /> <a href="/index.php?title=Chimera&amp;oldid=5737" title="Chimera" class="mw-changeslist-date">07:01, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,713 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="4,713 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(minor adjustment to infobox: priceblock)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=5736&amp;undo=5737" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=5736" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=5736&amp;oldid=4086" title="Chimera">prev</a>)</span><input type="radio" value="5736" name="oldid" id="mw-oldid-5736" /><input type="radio" value="5736" name="diff" id="mw-diff-5736" /> <a href="/index.php?title=Chimera&amp;oldid=5736" title="Chimera" class="mw-changeslist-date">06:58, 16 March 2011</a>‎ <span class='history-user'><a href="/index.php/User:StarSword" title="User:StarSword" class="mw-userlink">StarSword</a> <span class="mw-usertoollinks">(<a href="/index.php?title=User_talk:StarSword&amp;action=edit&amp;redlink=1" class="new" title="User talk:StarSword (page does not exist)">talk</a> | <a href="/index.php/Special:Contributions/StarSword" title="Special:Contributions/StarSword">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(4,698 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="4,698 bytes after change">(+1,512)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(added data)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=4086&amp;undo=5736" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=4086" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=4086&amp;oldid=4085" title="Chimera">prev</a>)</span><input type="radio" value="4086" name="oldid" id="mw-oldid-4086" /><input type="radio" value="4086" name="diff" id="mw-diff-4086" /> <a href="/index.php?title=Chimera&amp;oldid=4086" title="Chimera" class="mw-changeslist-date">00:22, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,186 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,186 bytes after change">(+24)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#See_Also" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=4085&amp;undo=4086" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=4085" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=4085&amp;oldid=3793" title="Chimera">prev</a>)</span><input type="radio" value="4085" name="oldid" id="mw-oldid-4085" /><input type="radio" value="4085" name="diff" id="mw-diff-4085" /> <a href="/index.php?title=Chimera&amp;oldid=4085" title="Chimera" class="mw-changeslist-date">00:21, 10 November 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,162 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="3,162 bytes after change">(+27)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Combat" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3793&amp;undo=4085" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3793" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3793&amp;oldid=3370" title="Chimera">prev</a>)</span><input type="radio" value="3793" name="oldid" id="mw-oldid-3793" /><input type="radio" value="3793" name="diff" id="mw-diff-3793" /> <a href="/index.php?title=Chimera&amp;oldid=3793" title="Chimera" class="mw-changeslist-date">04:47, 27 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(3,135 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="3,135 bytes after change">(+855)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(encyclopedia entry, infobox update)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3370&amp;undo=3793" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3370" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3370&amp;oldid=3127" title="Chimera">prev</a>)</span><input type="radio" value="3370" name="oldid" id="mw-oldid-3370" /><input type="radio" value="3370" name="diff" id="mw-diff-3370" /> <a href="/index.php?title=Chimera&amp;oldid=3370" title="Chimera" class="mw-changeslist-date">20:55, 20 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,280 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,280 bytes after change">(+158)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Combat" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Combat</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3127&amp;undo=3370" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3127" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3127&amp;oldid=3119" title="Chimera">prev</a>)</span><input type="radio" value="3127" name="oldid" id="mw-oldid-3127" /><input type="radio" value="3127" name="diff" id="mw-diff-3127" /> <a href="/index.php?title=Chimera&amp;oldid=3127" title="Chimera" class="mw-changeslist-date">00:28, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,122 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,122 bytes after change">(+15)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#See_Also" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3119&amp;undo=3127" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3119" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3119&amp;oldid=3118" title="Chimera">prev</a>)</span><input type="radio" value="3119" name="oldid" id="mw-oldid-3119" /><input type="radio" value="3119" name="diff" id="mw-diff-3119" /> <a href="/index.php?title=Chimera&amp;oldid=3119" title="Chimera" class="mw-changeslist-date">00:24, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(2,107 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="2,107 bytes after change">(+168)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#See_Also" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">See Also</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3118&amp;undo=3119" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3118" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3118&amp;oldid=3117" title="Chimera">prev</a>)</span><input type="radio" value="3118" name="oldid" id="mw-oldid-3118" /><input type="radio" value="3118" name="diff" id="mw-diff-3118" /> <a href="/index.php?title=Chimera&amp;oldid=3118" title="Chimera" class="mw-changeslist-date">00:24, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,939 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,939 bytes after change">(+112)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Suggested_Roles" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Suggested Roles</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=3117&amp;undo=3118" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=3117" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=3117&amp;oldid=1708" title="Chimera">prev</a>)</span><input type="radio" value="3117" name="oldid" id="mw-oldid-3117" /><input type="radio" value="3117" name="diff" id="mw-diff-3117" /> <a href="/index.php?title=Chimera&amp;oldid=3117" title="Chimera" class="mw-changeslist-date">00:23, 18 October 2010</a>‎ <span class='history-user'><a href="/index.php/User:Spychotic" title="User:Spychotic" class="mw-userlink">Spychotic</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Spychotic" title="User talk:Spychotic">talk</a> | <a href="/index.php/Special:Contributions/Spychotic" title="Special:Contributions/Spychotic">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,827 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,827 bytes after change">(+287)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Overview" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Overview</span></span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=1708&amp;undo=3117" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=1708" title="Chimera">cur</a> | <a href="/index.php?title=Chimera&amp;diff=1708&amp;oldid=1010" title="Chimera">prev</a>)</span><input type="radio" value="1708" name="oldid" id="mw-oldid-1708" /><input type="radio" value="1708" name="diff" id="mw-diff-1708" /> <a href="/index.php?title=Chimera&amp;oldid=1708" title="Chimera" class="mw-changeslist-date">18:40, 28 September 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,540 bytes)</span> <span dir="ltr" class="mw-plusminus-pos" title="1,540 bytes after change">(+51)</span>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(<a href="/index.php/Chimera#Background" title="Chimera">→</a>‎<span dir="auto"><span class="autocomment">Background: </span> variants section</span>)</span> (<span class="mw-history-undo"><a href="/index.php?title=Chimera&amp;action=edit&amp;undoafter=1010&amp;undo=1708" title="Chimera">undo</a></span>)</li>
<li><span class="mw-history-histlinks">(<a href="/index.php?title=Chimera&amp;diff=20851&amp;oldid=1010" title="Chimera">cur</a> | prev)</span><input type="radio" value="1010" name="oldid" id="mw-oldid-1010" /><input type="radio" value="1010" name="diff" id="mw-diff-1010" /> <a href="/index.php?title=Chimera&amp;oldid=1010" title="Chimera" class="mw-changeslist-date">01:03, 7 August 2010</a>‎ <span class='history-user'><a href="/index.php/User:Madned" title="User:Madned" class="mw-userlink">Madned</a> <span class="mw-usertoollinks">(<a href="/index.php/User_talk:Madned" title="User talk:Madned">talk</a> | <a href="/index.php/Special:Contributions/Madned" title="Special:Contributions/Madned">contribs</a>)</span></span>‎ <span class="mw-changeslist-separator">. .</span> <span class="history-size">(1,489 bytes)</span> <strong dir="ltr" class="mw-plusminus-pos" title="1,489 bytes after change">(+1,489)</strong>‎ <span class="mw-changeslist-separator">. .</span>  <span class="comment">(start)</span></li>
</ul>
<div><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div><div class="printfooter">
Retrieved from "<a dir="ltr" href="http://www.x3wiki.com/index.php/Chimera">http://www.x3wiki.com/index.php/Chimera</a>"</div>
					<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>					<!-- end content -->
										<div class="visualClear"></div>
				</div>
			</div>
		</div>
		<div id="column-one">
			<h2>Navigation menu</h2>
					<div id="p-cactions" class="portlet" role="navigation">
			<h3>Views</h3>

			<div class="pBody">
				<ul>
				<li id="ca-nstab-main" class="selected"><a href="/index.php/Chimera" title="View the content page [c]" accesskey="c">Page</a></li>
				<li id="ca-talk" class="new"><a href="/index.php?title=Talk:Chimera&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-edit"><a href="/index.php?title=Chimera&amp;action=edit" title="Edit this page [e]" accesskey="e">Edit</a></li>
				<li id="ca-history" class="selected"><a href="/index.php?title=Chimera&amp;action=history" title="Past revisions of this page [h]" accesskey="h">History</a></li>
				</ul>
							</div>
		</div>
				<div class="portlet" id="p-personal" role="navigation">
				<h3>Personal tools</h3>

				<div class="pBody">
					<ul>
						<li id="pt-anonuserpage">Not logged in</li>							<li id="pt-anontalk"><a href="/index.php/Special:MyTalk" title="Discussion about edits from this IP address [n]" accesskey="n">Talk</a></li>
													<li id="pt-anoncontribs"><a href="/index.php/Special:MyContributions" title="A list of edits made from this IP address [y]" accesskey="y">Contributions</a></li>
													<li id="pt-createaccount"><a href="/index.php?title=Special:CreateAccount&amp;returnto=Chimera&amp;returntoquery=action%3Dhistory" title="You are encouraged to create an account and log in; however, it is not mandatory">Create account</a></li>
													<li id="pt-login"><a href="/index.php?title=Special:UserLogin&amp;returnto=Chimera&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>
											</ul>
				</div>
			</div>
			<div class="portlet" id="p-logo" role="banner">
				<a href="/index.php/Main_Page" class="mw-wiki-logo" title="Visit the main page"></a>
			</div>
				<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
							<ul>
											<li id="n-mainpage-description"><a href="/index.php/Main_Page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
											<li id="n-recentchanges"><a href="/index.php/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
											<li id="n-randompage"><a href="/index.php/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
											<li id="n-help"><a href="https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents" title="The place to find out">Help</a></li>
											<li id="n-To-do-list"><a href="/index.php/To_do_List">To do list</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-X3_Terran_Conflict" role="navigation">
		<h3>X3 Terran Conflict</h3>
		<div class='pBody'>
							<ul>
											<li id="n-Ships"><a href="/index.php/Ships">Ships</a></li>
											<li id="n-Stations"><a href="/index.php/Stations">Stations</a></li>
											<li id="n-Sectors"><a href="/index.php/Sectors">Sectors</a></li>
											<li id="n-Races"><a href="/index.php/Races">Races</a></li>
											<li id="n-Missions"><a href="/index.php/Missions">Missions</a></li>
											<li id="n-Missiles"><a href="/index.php/Missiles">Missiles</a></li>
											<li id="n-Weapons"><a href="/index.php/Weapons">Weapons</a></li>
											<li id="n-Ranks"><a href="/index.php/Ranks">Ranks</a></li>
											<li id="n-Wares"><a href="/index.php/Wares">Wares</a></li>
											<li id="n-Asteroids"><a href="/index.php/Asteroids">Asteroids</a></li>
											<li id="n-Scripts-.26-Mods"><a href="/index.php/Scripts_%26_Mods">Scripts &amp; Mods</a></li>
									</ul>
					</div>
		</div>
		<div class="generated-sidebar portlet" id="p-Links" role="navigation">
		<h3>Links</h3>
		<div class='pBody'>
							<ul>
											<li id="n-MMO-Server-Status"><a href="http://www.mmoserverstatus.com">MMO Server Status</a></li>
											<li id="n-Compare-Everglades-Tours"><a href="http://www.compare-everglades-tours.com">Compare Everglades Tours</a></li>
											<li id="n-Pokemon-GO-Wiki"><a href="http://www.pokemon-go-wiki.com">Pokemon GO Wiki</a></li>
											<li id="n-Harry-Potter-Wizards-Unite-Wiki"><a href="http://harrypotterwizardsunite.wiki">Harry Potter Wizards Unite Wiki</a></li>
									</ul>
					</div>
		</div>
			<div id="p-search" class="portlet" role="search">
			<h3><label for="searchInput">Search</label></h3>

			<div id="searchBody" class="pBody">
				<form action="/index.php" id="searchform">
					<input type='hidden' name="title" value="Special:Search"/>
					<input type="search" name="search" placeholder="Search" title="Search X3 Wiki [f]" accesskey="f" id="searchInput"/>
					<input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchGoButton" class="searchButton"/>&#160;
						<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton"/>
				</form>

							</div>
		</div>
			<div class="portlet" id="p-tb" role="navigation">
			<h3>Tools</h3>

			<div class="pBody">
				<ul>
											<li id="t-whatlinkshere"><a href="/index.php/Special:WhatLinksHere/Chimera" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
											<li id="t-recentchangeslinked"><a href="/index.php/Special:RecentChangesLinked/Chimera" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
											<li id="feedlinks"><a href="/index.php?title=Chimera&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li>
											<li id="t-specialpages"><a href="/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
											<li id="t-info"><a href="/index.php?title=Chimera&amp;action=info" title="More information about this page">Page information</a></li>
									</ul>
							</div>
		</div>
			</div><!-- end of the left (by default at least) column -->
		<div class="visualClear"></div>
					<div id="footer" role="contentinfo">
						<div id="f-poweredbyico">
									<a href="//www.mediawiki.org/"><img src="/resources/assets/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" srcset="/resources/assets/poweredby_mediawiki_132x47.png 1.5x, /resources/assets/poweredby_mediawiki_176x62.png 2x" width="88" height="31"/></a>
							</div>
					<ul id="f-list">
									<li id="privacy"><a href="/index.php/X3_Wiki:Privacy_policy" title="X3 Wiki:Privacy policy">Privacy policy</a></li>
									<li id="about"><a href="/index.php/X3_Wiki:About" title="X3 Wiki:About">About X3 Wiki</a></li>
									<li id="disclaimer"><a href="/index.php/X3_Wiki:General_disclaimer" title="X3 Wiki:General disclaimer">Disclaimers</a></li>
							</ul>
		</div>
		</div>
		<script>(window.RLQ=window.RLQ||[]).push(function(){mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);});</script>
<script src="/index.php?title=Special:BannerController&amp;cache=/cn.js&amp;303"></script><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-265105-19', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="https://analytics.example.com/tracking.js"></script>
<script type="text/javascript" src="//geoiplookup.wikimedia.org/"></script><script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":83});});</script></body></html>
